### ISSUE TITLE
Filters on Reports/Treatments

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1065]
This goes along with a user thread in the CGM in a Cloud group. She was reporting a problem getting the filters to work on treatments screen. In testing... I don't see them work properly either. Depending on what you select, the date-range of results included differs... it almost looks like it is pulling the FIRST of the correct type and then everything after it rather than only pulling events of specified type. 

(Not passing over my url.)

![reports-correctionbolus](https://cloud.githubusercontent.com/assets/9641700/9978026/1513316a-5ed3-11e5-8c64-d6c03de16b85.png)

![reports-pumpsit](https://cloud.githubusercontent.com/assets/9641700/9978029/1a7591e8-5ed3-11e5-80cd-c7f99a7b2548.png)

![reports-bgcheck](https://cloud.githubusercontent.com/assets/9641700/9978030/1c66c3dc-5ed3-11e5-9dde-cc0f3e45d4f6.png)

**Comment by MilosKozak** [comment]
yeah.thx. i'm able to reproduce this bug and will look for a fix

**Comment by oamyoamy** [comment]
The thread in the forum... just in case... since her issue seems a bit different (like the processing never shows anything at all) https://www.facebook.com/groups/cgminthecloud/permalink/821614691293122/

Her thread led me to test though... and see what appears to be a filter issue. Thanks, Milos.

**Comment by oamyoamy** [comment]
Actually... it looks like it pulls ALL info for any DAY in which the specified event occurs. That's why the dates included in the pulls by type seem to differ noticeably. In each screenshot above, the same date range was applied... the "days" that got included were all ones with the correct "type".... but it shows everything on that day.

**Comment by MilosKozak** [comment]
solved by https://github.com/nightscout/cgm-remote-monitor/pull/1082
