### ISSUE TITLE
High Alarm alarms when it shouldn't

### ISSUE THREAD

**Issue by gregwaehner** [nightscout/cgm-remote-monitor#107]
Jason -
Testing the develop branch. On computer (and phone and kindle tablet), I get the high alarm even when I have the control set for no high alarm, and I also added the "mute=true" to the URL. I've been away from computer all day, so I don't know if there was a session timeout or something that led to the high alarm alarming.

But when I hit enter and the URL in the browser, the alarming went away.

Screenshot of alarming included.

![image](https://cloud.githubusercontent.com/assets/7674953/3973848/bfc3c7ba-27ec-11e4-88c7-aa947decede9.png)

- Greg

**Comment by jimsiff** [comment]
Can this be closed now that Dreamsicle is out?

**Comment by denvergail** [comment]
As far as I'm concerned, yes.
