### ISSUE TITLE
Cancel the snooze?

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1081]
Feature request?

It would be nice if there was a way to "cancel" a snooze (to reset the alarms)...  Since someone snoozing an alarms snoozes them all, there are times when you realize you shouldn't have snoozed something.... if you needed someone else to notice and respond to the alarm. I can't figure out a way right now to reset alarms... is there one? If not... 
##

**Comment by stavlor** [comment]
Believe restarting crm will cancel any active snooze not sure though

**Comment by bewest** [comment]
Would like to learn more about this.  What about "generate alarm" or something similar, "flag/SOS/mayday" instead?
