### ISSUE TITLE
TIME_FORMAT 24 not working

### ISSUE THREAD

**Issue by ELUTE** [nightscout/cgm-remote-monitor#1083]
Setting Time format to 24 does not appear to change the time format on the site. 

![screen shot 2015-09-22 at 10 23 33 am](https://cloud.githubusercontent.com/assets/7684327/10021144/817f84dc-6114-11e5-9bb1-78c32245053c.png)

![screen shot 2015-09-22 at 10 27 31 am](https://cloud.githubusercontent.com/assets/7684327/10021159/939e5e2c-6114-11e5-9209-cc7c703558e3.png)

**Comment by MilosKozak** [comment]
24 vs '24' issue. working on fix

**Comment by sulkaharo** [comment]
The preference loader should already automatically convert the prefs to a Number() when the number parsing succeeds.

**Comment by MilosKozak** [comment]
trying to convert it to number everywhere. many things were broken after we optimized for codacy (===). we just didn't know
what line do you mean?

**Comment by sulkaharo** [comment]
See line 58 of settings.js -> when loading values from Mongo, the system should map every number value to a number. This used to work, so it should be possible to compare any numeric value using === without needing to locally convert the value.

**Comment by MilosKozak** [comment]
yeah. this is special for arrays. will do similar for numbers

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/1087

**Comment by sulkaharo** [comment]
Sounds like a regression then -> I specifically fixed and tested this due to CAGE breaking due to the exact same === changes and it did work. :(

**Comment by MilosKozak** [comment]
??? may i help?

**Comment by MilosKozak** [comment]
solved by https://github.com/nightscout/cgm-remote-monitor/pull/1087
