### ISSUE TITLE
Timeline lag on webapp

### ISSUE THREAD

**Issue by JosiahNS** [nightscout/cgm-remote-monitor#1099]
For some reason, the timeline on the website does not advance in real time, leaving the raw number lagging one reading behind--unless I move the timeline slider, refresh the page, or toggle between one of the 3hr, 6hr, 12hr, or 24hr views--then it updates to the current raw number on the website. Pebble raw updates normally for me. The dex dot and raw dot both show up on the website and if I hover the mouse pointer over the dot, it shows the correct/current values, but the raw value listed at the top of the webpage lags one reading behind unless I refresh as described above.

![image](https://cloud.githubusercontent.com/assets/9634825/10106579/8403f8fc-6383-11e5-89a8-1bec69969b22.png)
##

**Comment by Thebassefamily** [comment]
We have this exact same issue. My pebble keeps up but the website (through the iOS app) lags

**Comment by jasoncalabrese** [comment]
Check time on your devices, I've seen something like this when some times aren't in sync

**Comment by Kdisimone** [comment]
@JosiahNS can this issue be closed now?  did you check your time on the devices?

**Comment by PieterGit** [comment]
@JosiahNS 
We are closing issues that are not updated. There has not been much activity with this issue in the last 2 years.
I'm closing this issue for now.
If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
