### ISSUE TITLE
Y axis ticks broken

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1113]
Noticed this after merging #1097 

<img width="116" alt="screen shot 2015-09-27 at 10 24 23 am" src="https://cloud.githubusercontent.com/assets/751143/10124136/057df69c-6502-11e5-900f-59658e3e396e.png">

@MilosKozak

**Comment by MilosKozak** [comment]
Hmmm was working for me. I'm on phone only now

Odesláno z iPhonu
MK

27. 9. 2015 v 19:26, Jason Calabrese <notifications@github.com<mailto:notifications@github.com>>:


Noticed this after merging #1097<https://github.com/nightscout/cgm-remote-monitor/pull/1097>

[https://cloud.githubusercontent.com/assets/751143/10124136/057df69c-6502-11e5-900f-59658e3e396e.png]<https://cloud.githubusercontent.com/assets/751143/10124136/057df69c-6502-11e5-900f-59658e3e396e.png>

@MilosKozak<https://github.com/MilosKozak>

**Comment by jasoncalabrese** [comment]
this fixes it, but maybe there's a better fix

```diff
diff --git a/lib/client/chart.js b/lib/client/chart.js
index 7eaffd1..b29a30c 100644
--- a/lib/client/chart.js
+++ b/lib/client/chart.js
@@ -87,7 +87,7 @@ function init (client, d3, $) {

   chart.yAxis = d3.svg.axis()
     .scale(yScale)
-    .tickFormat(localeFormater.timeFormat('d'))
+    .tickFormat(d3.format('d'))
     .tickValues(tickValues)
     .orient('left');

@@ -99,7 +99,7 @@ function init (client, d3, $) {

   chart.yAxis2 = d3.svg.axis()
     .scale(yScale2)
-    .tickFormat(localeFormater.timeFormat('d'))
+    .tickFormat(d3.format('d'))
     .tickValues(tickValues)
     .orient('right');
```

**Comment by jasoncalabrese** [comment]
While fixing this we should also rename `localeFormater` to `localeFormatter`

**Comment by MilosKozak** [comment]
Do it pls

Odesláno z iPhonu
MK

27. 9. 2015 v 19:54, Jason Calabrese <notifications@github.com<mailto:notifications@github.com>>:


While fixing this we should also rename localeFormater to localeFormatter
