### ISSUE TITLE
BWP Popup / Clarification

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1120]
A discussion in the Facebook group recently highlighted the fact that the way the "recommendations" are shown for 30 min and 1 hr temp basals may obscure the fact that the BWP number shown (when >0) could be the amount of a correction bolus.  The bolus amount isn't shown as an option in the popup, so it looks like temp basal changes are "the" way to address the issue. This might lead someone to wonder, "why shouldn't I just do a bolus." The single bolus amount is there... but when you start looking at the popup info, you have to read between the lines to "get" that.

In the bottom portion, it says "Basal change to account for x.xx:" followed by temp basal suggestions to address the bwp. The phrasing of "basal change to account for x.xx" is the issue... 

I think a single bolus recommendation should be clearly noted in that section.

https://www.facebook.com/groups/cgminthecloud/permalink/822145111240080/
##

**Comment by sulkaharo** [comment]
:+1: Should the bolus info be right at the start?

**Comment by sulkaharo** [comment]
Amy would this be better?

<img width="460" alt="screen shot 2015-09-28 at 08 15 48" src="https://cloud.githubusercontent.com/assets/1001330/10128303/3cf59e9c-65b9-11e5-8c31-6a54406dd4fe.png">
<img width="420" alt="screen shot 2015-09-28 at 08 16 01" src="https://cloud.githubusercontent.com/assets/1001330/10128302/3cf3f970-65b9-11e5-9134-fe085c29497f.png">

**Comment by sulkaharo** [comment]
One more tweak pass

<img width="427" alt="screen shot 2015-09-28 at 08 18 56" src="https://cloud.githubusercontent.com/assets/1001330/10128325/a340651a-65b9-11e5-9009-269304c8e510.png">
<img width="403" alt="screen shot 2015-09-28 at 08 19 08" src="https://cloud.githubusercontent.com/assets/1001330/10128326/a36a6e5a-65b9-11e5-98ad-4483ccbc2e1e.png">

**Comment by oamyoamy** [comment]
Yes - either approach would really help clarify that bolus is an option. Second approach is very clean.

**Comment by sulkaharo** [comment]
Cool, will pr. :)

**Comment by Kdisimone** [comment]
Looks like this issue can be closed.  The change appears to have been made to help with bolus clarification.
<img width="623" alt="screen shot 2018-02-21 at 10 57 50 am" src="https://user-images.githubusercontent.com/12402160/36499464-2999ea2e-16f6-11e8-88c5-bad4435d11ba.png">

**Comment by PieterGit** [comment]
@oamyoamy thanks for reporting. I think this issue has been fixed (see @Kdisimone screenshot above). If not, please reopen the issue, or recreate another issue and link it to this one. I'm closing this issue.
