### ISSUE TITLE
Date problem on treatments / 1 day off

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1128]
This bug is similar to a previous issue in reports (and I thought treatments) that was fixed. General reports no longer demonstrate this bug, but in the LIVE 0.8.1 release, "treatments" are a day off. (Multiple users in CGM in the Cloud group have reported this.)

VERSION NOTE -- this bug does NOT appear in the 0.8.1-beta2 but DOES appear in the final 0.8.1 release and in the current dev branch.

Screenshot of 2-days view of treatments in dev and 0.8.1-beta2 for comparison. 
 
DEV (same error appears in 0.8.1 release) -- days in results are a day off of the query dates:

![dayoff-devor081release](https://cloud.githubusercontent.com/assets/9641700/10150138/bcd3a850-65f2-11e5-9b98-f4731dd448f9.png)

0.8.1-beta2 for comparison (and tracking what may have changed between the beta and final 0.8.1 release) -- days in results match query dates:

![dayoff-081beta2](https://cloud.githubusercontent.com/assets/9641700/10150164/d199938a-65f2-11e5-8ff3-8bfead5c0e51.png)

**Comment by jasoncalabrese** [comment]
I've seen this before also, but haven't looked into the cause yet

**Comment by MilosKozak** [comment]
making notice here
https://github.com/nightscout/cgm-remote-monitor/compare/d38f01298442dcd8d07a2ecfbcef0855e857decf...a0906d04ded492ea5ef3157fb41cfc5f09a15c8e

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/1133
