### ISSUE TITLE
Bigger SHOW button on Nightscout reporting page 

### ISSUE THREAD

**Issue by xpucuto** [nightscout/cgm-remote-monitor#1149]
When i open the reporting page from my phone is very hard to klick on the Show button even when the page is zoomed in. 
I hope you will be able to make it a little bit bigger. 
Thank you :)

**Comment by MilosKozak** [comment]
No problem for me. Others?

**Comment by MilosKozak** [comment]
i was testing it but bigger button caused less graphs fitted on page when printing. not sure if to do it :(

**Comment by xpucuto** [comment]
Ok. If it's not practical then leave it like that . I will survive :)
