### ISSUE TITLE
Future Data admin tool 

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1162]
Future data removal does not appear to be working. Pulled up a backup database to try an uploader fix, and apparently that database has future data. 

Admin tool shows me 10 future data points.
Attempt to removal pops up that it knows there are 10... and I confirm to remove.
It appears to process... you see a few removal status notes roll across.
Go back to the site, and future data is still there.
Open admin tool again, and it still shows 10 future data points.

Running current dev.

![admin-future](https://cloud.githubusercontent.com/assets/9641700/10250088/b4fc6e6c-68dd-11e5-8814-33b135e6c769.png)

![admin-remove-confirm](https://cloud.githubusercontent.com/assets/9641700/10250096/b8000132-68dd-11e5-8e86-d06e602c7a2a.png)

![admin-removed](https://cloud.githubusercontent.com/assets/9641700/10250097/bba2b3a2-68dd-11e5-87da-efebdadf9d53.png)

Then 10 still remain.

**Comment by MilosKozak** [comment]
hmmm tested now and it worked. @jasoncalabrese how about you?

**Comment by MilosKozak** [comment]
just tested and worked like a charm? @jasoncalabrese could yout test too?

**Comment by jasoncalabrese** [comment]
I'm planning to test xdrip soon with my extra uploader, I'll try messing with it's clock to create some future data.  Need to get 1 more test environment setup first.

**Comment by MilosKozak** [comment]
we've no testing hardware so i only add future record to mongo and then test on it. maybe there is some difference

**Comment by MilosKozak** [comment]
I'm unable to reproduce it. Need url of site where is this happening

**Comment by stavlor** [comment]
Worked for me on dev ddd2577
