### ISSUE TITLE
Cloud Group / COB decay

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1174]
I am not seeing this issue... but please see this thread... that she ended up entering a string rather than just a number doesn't seem right. (It seems like that field should ONLY allow a numeric entry.)

User reported problems with seeing COB decay.
We instructed her to make sure she specified a value here: "Carbs activity / absorption rate: [g/hour]"

She said the only way she got it to work was by entering '25g/hour' (the string)...
## Not sure this is a confirmable issue... but wanted to flag it since we've seen more than one user with a COB decay issue.

https://www.facebook.com/groups/cgminthecloud/permalink/824768804311044/
##

**Comment by sulkaharo** [comment]
I suspect this is a string vs number bug introduced with the profile editor; will be fixed with next release. Can't replicate with current dev.

**Comment by Kdisimone** [comment]
@oamyoamy can this issue be closed?

**Comment by PieterGit** [comment]
We are closing issues that are not updated. There has not been much activity with this issue in the last 2 years.
I'm closing this issue for now. If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
Please let use know if this issue still persist in the latest release of Nightscout.
