### ISSUE TITLE
Deployment failed msg

### ISSUE THREAD

**Issue by hanawait** [nightscout/cgm-remote-monitor#1182]
Getting a deployment failed msg from log from Azure 

> Nightscout@0.8.1 postinstall d:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install
>  bower                 MODULE_NOT_FOUND Cannot find module 'end-of-stream'
>  npm ERR! Nightscout@0.8.1 postinstall: `node node_modules/bower/bin/bower --allow-root install`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the Nightscout@0.8.1 postinstall script.
> An error has occurred during web site deployment.
> npm ERR! This is most likely a problem with the Nightscout package,
> npm failed
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node node_modules/bower/bin/bower --allow-root install
##

**Comment by stavlor** [comment]
This happens quite often on Azure a re-deploy should fix it

**Comment by hanawait** [comment]
I tried 10 - 15 times this morning though.

**Comment by joeyede** [comment]
I am seeing similar issues not able to deploy on Azur

**Comment by stavlor** [comment]
@joeyede see #1142 there is an issue with current azure builds we are working to solve it

**Comment by joeyede** [comment]
Thanks for the update!

**Comment by Kdisimone** [comment]
I believe this issue has been resolved?  Can someone update their status who has posted here?

**Comment by PieterGit** [comment]
@hanawait @joeyede @stavlor  We are closing issues that are not updated. There has not been much activity with this issue in the last 2 years.
I'm closing this issue for now. If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
Please let use know if this issue still persist in the latest release of Nightscout.

Azure hosting seems to give several problems. You can also try to use Heroku instead.
