### ISSUE TITLE
Reports:Day of Week Selection Boxes Shows Data For Following Day

### ISSUE THREAD

**Issue by aaronjknox** [nightscout/cgm-remote-monitor#1186]
e.g. Check the Monday box. Click Show. Site displays Tuesday Data.
This is easiest to observe in the day-to-day output.

**Comment by MilosKozak** [comment]
should be solved in latest beta. reopen if still appears

**Comment by aaronjknox** [comment]
I believe this problem still persists. I'm seeing it in v0.8.2 and v0.8.2-beta2
![image](https://cloud.githubusercontent.com/assets/7867106/11153225/beed84d2-89f4-11e5-96cf-2a5321d6a058.png)

**Comment by MilosKozak** [comment]
@aaronjknox  pm me your site and timezone pls

**Comment by aaronjknox** [comment]
Hi Milos, I'm not sure how to pm in github so I sent you that info via facebook message. Thanks

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/cgm-remote-monitor/commit/2c73df90384b4ae0c43b90dab3dd3cb730633737
Thanks
