### ISSUE TITLE
Single values in alarm snooze attributes does not work

### ISSUE THREAD

**Issue by dexterbooty** [nightscout/cgm-remote-monitor#1199]
Hi,
When trying to set the variables for the options to snooze alarms e.g. ALARM_HIGH_MINS, if you enter a single value made up of 2 or more characters the option is split into multiple snooze options.

Using Azure and Nightscout V0.8.1

For example if entering the value of 120 into ALARM_HIGH_MINS; this will translate into 3 options of 1 minute, 2 minutes and zero minutes.  The workaround is to enter the value twice into Azure e.g 120 120. which then shows in the Gui as snooze options as 120 minutes , 120 minutes.

Think its worthwhile allowing single options for snooze alarms as typically I use a default snooze based on alarm type e.g. 5 mins for low / 2 hours for highs.  This would avoid users incorrectly snoozing for the wrong amount of time.

Thanks Olly

![azure setting](https://cloud.githubusercontent.com/assets/10778986/10479162/6cf13f0e-725a-11e5-87bc-9ac9ee000f18.png)
![gui view](https://cloud.githubusercontent.com/assets/10778986/10479171/7f1e8768-725a-11e5-8b79-cb361e29c05c.png)

**Comment by jasoncalabrese** [comment]
Strange bug, agree that we should be able to handle a single value
