### ISSUE TITLE
Reports: Weekly success figures don't match distribution figures

### ISSUE THREAD

**Issue by zjedr** [nightscout/cgm-remote-monitor#1221]
Weekly success figures (low,in range, high, average)  look incorrect when compared to the Distribution report.

![ns-distrib](https://cloud.githubusercontent.com/assets/13398921/10593226/84666814-770d-11e5-8471-5552dd3f800b.jpg)
![ns-weekly](https://cloud.githubusercontent.com/assets/13398921/10593227/8467eb12-770d-11e5-9b4e-7bd0b16aba58.jpg)

**Comment by MilosKozak** [comment]
weekly success is alligned to week. it possible it takes another data into a count

**Comment by zjedr** [comment]
The problem is my low/high targets are converted to integers, this is not accurate enough when people are running in mmol. 
My low target of 3.8 and high target of 7.5 are being set to 3 & 7, therefore I'm getting inaccurate results.
(success.js:61)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/1270
