### ISSUE TITLE
Timeformat setting does not work

### ISSUE THREAD

**Issue by mrinnetmaki** [nightscout/cgm-remote-monitor#1245]
I tried setting TIME_FORMAT in Azure's App Settings to 24, but the website still defaults to 12 hour presentation.

Quick check revealed that lib\client\index.js (rows 103 and 111) check the setting as a number, when it is in fact present in client.settings as a string.

README.md, tests\fixtures\default-server-settings.js, \lib\report_plugins\daytoday.js, static\profile\js\profileeditor.js all seem to treat the value as a string.

static\js\client.js is agnostic and uses == instead of ===

**Comment by jasoncalabrese** [comment]
Setting values that are numbers should be getting converted as they are read from the env, this is from a recent version?

**Comment by mrinnetmaki** [comment]
Yes, deployded the latest master. At least tried. And about pane says version 0.8.1.

**Comment by mrinnetmaki** [comment]
Fixed in https://github.com/nightscout/cgm-remote-monitor/blob/887c02eaa55cd46ea0d89f02254c7df75e154dd2/lib/settings.js.
