### ISSUE TITLE
Toggling Basal display (mobile) 

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1246]
Very difficult on mobile to work with the inset checkbox for the basal display. Clicking it, activates the popup box for 'basal,' and it is very difficult to find a space on the page that will release it. (The 3/6/9/12 view selectors, in contrast, work great because they are not inset.)

**Comment by jasoncalabrese** [comment]
Yeah, that bugs me too, I tried fixing it before and didn't get anywhere, but I'll try again.  Making the setting sticky (between reloads) will help some too.

**Comment by MilosKozak** [comment]
Yes, basal visualisation had success. It will be redesigned for better match with other controls

**Comment by jasoncalabrese** [comment]
resolved by #1261
