### ISSUE TITLE
Alignment of 'note' on small-duration exercise blocks

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1248]
While a "long" block of exercise looks right with centered note text, when it's a shorter duration (like 45 mins), centering the text makes it less than useful. 

Stylistically, not sure of the best approach, unless the note is simply note shown at all for shorter blocks.

I don't mind truncation on the shorter block. But I don't want to see it cut off in the middle this way:

The note says "Mile day in PE." Next time I'll just enter "Mile" since I know it won't fit.

![exercise-note](https://cloud.githubusercontent.com/assets/9641700/10707379/ae38adc8-79a6-11e5-8856-dd401f55a88a.png)

Short and long display:

![exercise-note-full](https://cloud.githubusercontent.com/assets/9641700/10707386/bc8f8680-79a6-11e5-97a5-34064569c4d6.png)

**Comment by oamyoamy** [comment]
After several reloads... the display of the original note (a 45 minute block) appears right. Will try it again and see if I can reproduce what happened with that one.

**Comment by oamyoamy** [comment]
Something happening with the scale (time scale), and it shifts very differently based on 3/6/9/12 hr view. This is the same exact 45 min exercise block (12:15-1). Look how deceptively different it looks in the one view in terms of duration. But in both of these, it looks like it spans past 1. 

![exercise-scale](https://cloud.githubusercontent.com/assets/9641700/10707613/124c6194-79aa-11e5-806a-c91d1f284d36.png)

![exercise-scale2](https://cloud.githubusercontent.com/assets/9641700/10707615/14c9e842-79aa-11e5-82bb-8a7788e4a563.png)

![exercise-span3](https://cloud.githubusercontent.com/assets/9641700/10707616/186f860a-79aa-11e5-9074-6c8dcadf7680.png)

**Comment by oamyoamy** [comment]
And I've seen this twice now in testing this. Reload the page. Hit 6hr view. And look at the sequence of the hours on the x axis.

![exercise-timewarp](https://cloud.githubusercontent.com/assets/9641700/10707633/6111b716-79aa-11e5-8be2-b1d0e3b63574.png)

**Comment by jasoncalabrese** [comment]
I've seen something strange with the scale, and needed to reload.

For the notes, I think the trick is to detect the edge of the screen and move the text all the way to the left or right.  Maybe for short durations we should only have a dot and put the text next to it.  Could also be good to have `title` and `note`, and then display the `title` (shorter) if it's available.

**Comment by MilosKozak** [comment]
solved by https://github.com/nightscout/cgm-remote-monitor/issues/1248
