### ISSUE TITLE
Temp Basal / conflicting info

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1249]
I am not sure it makes sense (and possibly it invites error) that you can edit a temp basal rate and concurrently change either or both the percentage of change AND change represented as an absolute basal rate -- even if the values are at odds with one another.

(You can't enter both when SETTING the temp basal. But when editing it in the reports area, you can change both, resulting in a skewed picture.)

The system knows the current basal rate setting from the user's profile. If it is, for example, 1u, then both a 50% (-50% change) temp rate and an absolute 3u are not both valid at the same time. 

Seems like you should be editing one or the other -- not able to do both... 

This temp basal was edited and now says it is both -50% and 3u:

![tempbasal-conflict](https://cloud.githubusercontent.com/assets/9641700/10707514/4f0d6260-79a8-11e5-803f-c55c2c522202.png)

**Comment by jasoncalabrese** [comment]
Shouldn't be able to do that, I saw the field get hidden, but should also check before submit.

**Comment by MilosKozak** [comment]
Yeah, entering treatment from careportal is safe. NS does validity check. Use of editor allows you to change anything you want on your own responsibility. It's by design and there is no plan to change it

**Comment by oamyoamy** [comment]
Good to know that it is "by design" that you can enter conflicting info.

**Comment by jasoncalabrese** [comment]
Think we can do better, but adding too many rules will complicate things

**Comment by MilosKozak** [comment]
Well if we add strict checking you'll not be able to do all changes you want or you'll loose some info when you for example change event type.
It's a replacement of direct mongo edit where you can break everything too.

I think people are using is to change wrong entered number or so. Not to create from one treatment completely another one
