### ISSUE TITLE
Use a simple syntax to enter durations

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1250]
Maybe something like this: https://www.npmjs.com/package/parse-duration

```javascript
var ns = parse('1ns') // => 1 / 1e6 
var μs = parse('1μs') // => 1 / 1000 
var ms = parse('1ms') // => 1 
var s = parse('1s')   // => ms * 1000 
var m = parse('1m')   // => s * 60 
var h = parse('1h')   // => m * 60 
var d = parse('1d')   // => h * 24 
var w = parse('1w')   // => d * 7 
var y = parse('1y')   // => d * 365.25 
```

`parse('1hr 20mins') // => 1 * h + 20 * m`
whitespace

And most other types of noise
`parse('running length: 1hour:20mins') // => 1* h + 20 * m`

You can even use negatives
`parse('2hr -40mins') // => 1 * h + 20 * m`

**Comment by MilosKozak** [comment]
Yeah, i was thinking about add something like this
:+1:

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/1271
