### ISSUE TITLE
Reports / overlapping text

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1251]
When two entries of the same type are in close proximity on the graph, the labels overlap.

![reports-overlay](https://cloud.githubusercontent.com/assets/9641700/10708566/3a73a1a6-79c2-11e5-8e61-afe542e1e991.png)

(Image is from the Day to Day report screen; the two events are each 8u carb corrections, 18 minutes apart.)

**Comment by MilosKozak** [comment]
would you prefer this way?
![image](https://cloud.githubusercontent.com/assets/11146458/10718896/43350250-7b7d-11e5-8000-7e2da76cb5af.png)
but when they are too close they will overlap anyway
@jasoncalabrese

**Comment by bewest** [comment]
I like it at a degree... I was thinking the offset and radians could be controlled by number and distance of neighbors, so they might get splayed out, but not quite sure how to do it.

**Comment by jasoncalabrese** [comment]
Looks like an improvement, wonder if the text will get in the way of the other things now

**Comment by MilosKozak** [comment]
![image](https://cloud.githubusercontent.com/assets/11146458/10723315/e4c22e18-7bb9-11e5-8570-46315e6d8ce6.png)

**Comment by MilosKozak** [comment]
@bewest you can write a CAD system for reports :)
