### ISSUE TITLE
Temp Basals of 0u/h do not display

### ISSUE THREAD

**Issue by audiefile** [nightscout/cgm-remote-monitor#1276]
![temp basal issue](https://cloud.githubusercontent.com/assets/8140689/10744381/e2ad7366-7c0f-11e5-8cf8-ef07273d604a.jpg)

Temp basals of 0 (or 0.0) units per hour (absolute) do not display the same way as -100% as shown in the image above

**Comment by jasoncalabrese** [comment]
I think this is because the 0 is seen as temp basal percent not being set, probably should check with `=== undefined` or `isNaN`
