### ISSUE TITLE
Exercise popup (addition)

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1297]
It seems logical to have "duration" shown in the popup so that you don't have to guess the approximate duration based on the size of the box between time markers.

![exercise-tooltip](https://cloud.githubusercontent.com/assets/9641700/10866001/aca0cc58-7fdb-11e5-8928-9319892bfa98.png)

**Comment by MilosKozak** [comment]
Agree. Will be added

**Comment by MilosKozak** [comment]
coverd by https://github.com/nightscout/cgm-remote-monitor/pull/1317
