### ISSUE TITLE
Feature request / Note visualization

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1298]
Would love to be able to have visualization (similar to exercise block; different color) for an entry of type Note.

(Otherwise, misusing or co-opting the exercise block to "get" that information on the graph will be a logical way to take advantage of the field. But I would rather log exercise separately and be able to visualize note info in a very similar way.)

**Comment by MilosKozak** [comment]
If you add duration to note is displayed the same way ...

**Comment by oamyoamy** [comment]
Awesome. (Icky color, but great to know the feature exists.)  Thanks!

**Comment by jasoncalabrese** [comment]
We should think about the colors, and make some updates with 0.9
