### ISSUE TITLE
Editing TB entries

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1299]
Taking screenshots for documentation, and ran into a problem with edited TB entries.

Changing a positive (e.g., +75%) temp basal entry to another positive value (e.g., +50%) is rendering incorrectly on the graph.

Similarly... in one test, the change rendered incorrectly and the label was also oddly written (see the 30u one below). In another test, the label disappeared completely after the change.

(Users may not have a need to edit a TB often, but it should render properly on the graph if they do.)

Before editing -- a 175% (75% change) temp basal:

![tb-test](https://cloud.githubusercontent.com/assets/9641700/10869338/bd2888a0-8061-11e5-9ce3-f4c5f1b70620.png)

Pulling it up in editor:

![tb-test-treatmentseditor](https://cloud.githubusercontent.com/assets/9641700/10869339/c7c3eca0-8061-11e5-85f9-d9abfb45eba6.png)

Changing the value from 75 (change) to 60 (change). (No other edits made.)

![tb-test-treatmentseditor-change](https://cloud.githubusercontent.com/assets/9641700/10869343/db1762d2-8061-11e5-9c36-ce2109b6e767.png)

Rendered on graph the same as the NEGATIVE (decrease) temp basal values (and the label disappeared):

![tb-test-after2](https://cloud.githubusercontent.com/assets/9641700/10869344/f0a38572-8061-11e5-8de6-a29e68d00a5a.png)

A larger view of the same graph with both TB edit tests shown. BOTH were positive values, edited to different positive values. The first one shows a label, but the label syntax is different than the other temp basal labels.

![tb-test-after](https://cloud.githubusercontent.com/assets/9641700/10869348/0ddb70b4-8062-11e5-984f-7272ee0d3a8f.png)

**Comment by jasoncalabrese** [comment]
Does reloading the page help, right now the treatments are cached on the server so the old treatment isn't getting removed you just get 1 more added.

**Comment by oamyoamy** [comment]
Did not help. Tried that BEFORE I filed a report.

**Comment by oamyoamy** [comment]
If you review my filed report above, 1 was not added. Instead, the TB that was edited changes in appearance and is no longer being properly shown as a POSITIVE (increased) TB. Instead, it's rendering the same as the negative ones.

**Comment by MilosKozak** [comment]
covered by https://github.com/nightscout/cgm-remote-monitor/pull/1316
