### ISSUE TITLE
No cob in pebbel endpoint

### ISSUE THREAD

**Issue by AdrianLxM** [nightscout/cgm-remote-monitor#1304]
While iob, bwp and bwpo is there cob is not.

I'd like to bring those to the watchfaces.

**Comment by jasoncalabrese** [comment]
I thought we'd have a new summary endpoint by now that would expose all this info, the `/pebble` endpoint is such a hack

**Comment by YYGIRL** [comment]
Everyone - Just be careful. Every time you add a field, you add data which
adds $$$. Especially when pulling multiple records. It's a big concern for
people on small data plans, especially the Ting users.

I had shortened the slope, intercept, and scale fields to a smaller memory
size, and saw someone expanded them again later and we didn't need that.
It's just adding memory and space, and therefore $$$.

Just be sure when adding things to the pebble end point that 1. you really
want to add the field, and 2. you add it in the smallest amount of memory
as possible. Thank you.

On Sun, Nov 1, 2015 at 1:34 PM, Jason Calabrese <notifications@github.com>
wrote:

> I thought we'd have a new summary endpoint by now that would expose all
> this info, the /pebble endpoint is such a hack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/issues/1304#issuecomment-152850895>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **jackattack.deltrap.com
<http://jackattack.deltrap.com>*

**Comment by jasoncalabrese** [comment]
We could save space by sending the calculated raw instead of the
components...  But seeing different values on pebble and website wasn't
good so it had to be changed.

I think we should consider the /pebble endpoint to be frozen and start on a
new and flexible endpoint.

Also should try using long polling to reduce the number of requests and
make the data update in real-time.

**Comment by sulkaharo** [comment]
Please note the protocol optimizations we put into 0.8 saves a day worth of pebble data loads in 15 minutes of having the site open. We should probably set some kind of a data target for a day of overall use and then look at how to get there - using json as a wire format is a good example of not exactly optimizing for minimizing data use. Another decision that probably needs making is what cost level we're optimizing for.

Sulka

**Comment by AdrianLxM** [comment]
Well, I have to admit I didn't think of data consumption.
Over here, for the yearly costs of running a NS site (just for having a credit card - without billing anything on it) we get about 30GB of mobile data.

I don't use cob - but would include it in the Android watchfaces as people requested it. I will stick to iob, and the bolus wizard ones for now.
It would be nice if you could drop me a note if/when it is available through any endpoint in the future. Preferably together with the other data to not having to open multiple connections - what would cost much more data.

**Comment by MilosKozak** [comment]
i'd like to have endpoint with param like
`/api/v1/getdata?profile=pebble`
with predefined sets (profiles) of returned values
or return all available with no param

**Comment by AdrianLxM** [comment]
@MilosKozak this would be ideal. You could just ask for what you actually want to display.
It will have to be documented though - that's usually a huge problem that a lot of things are there - but anyone not familiar with one end cannot use it.

**Comment by jasoncalabrese** [comment]
I'm thinking that we may be heading to order device/user config for most options.  If we did that an app like nightwatch would create a settings profile with all the options the and user need.  Then would be able to reuse or until changed

**Comment by jasoncalabrese** [comment]
Think that could work for the pebble too, store an id in a cookie

**Comment by jasoncalabrese** [comment]
Have some predefined settings too

**Comment by MilosKozak** [comment]
if we'd implement GET and PUT there would not be necessary to have any profile hardcoded.

comm could be somethink like

`GET /api/v1/endpoint?p=myprofile`
with return
`
{
 ... alldata ...
, notexists: true
}
`

client will react with
PUT /api/v1/endpoint
{ data: profiledefinition }

and next
GET /api/v1/endpoint?p=myprofile
would produce only data needed

what do you think? not sure what are pebble (and others) app capabilities

**Comment by AdrianLxM** [comment]
@MilosKozak: In theory I'd really really like the solution of client defined profile definition.

But: Things like that easily become non-self-explanatory. There must be some kind of documentation (at least of what fields are available and how to activate them) and usually no one wants to write or expand it.

At least that's how I experience how many of the small contributions to OS projects work: You've got an idea (or read it on fb), look at the data and think "well that's a starting point".

That said - "If you show me how to use it, I will love it!"

**Comment by MilosKozak** [comment]
so far we discussing possibilities
@jasoncalabrese @bewest @YYGIRL @ELUTE @jimsiff

**Comment by jasoncalabrese** [comment]
This had been on dev for a while
