### ISSUE TITLE
Profile Switch (dev-0.9)

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1330]
Running dev-0.9 and tested the profile switch to see how it renders. Selecting my second profile (weekend) incorrectly put the label for my other (primary/first) profile on the graph. 

Selecting WEEKEND
![ps-weekend](https://cloud.githubusercontent.com/assets/9641700/10979707/dfa5a148-83b2-11e5-8d0e-a69c92b7b8ae.png)

Graph shows the schoolday profile. (Ran this test twice with same results.)

![ps-weekend-fail](https://cloud.githubusercontent.com/assets/9641700/10979723/f37236dc-83b2-11e5-8034-edd7272d9d2a.png)

**Comment by MilosKozak** [comment]
label with arrows should always appear on the left side of graph indicating last selection. i see there is some rendering issue sneaked in with some changes... thanks !

**Comment by oamyoamy** [comment]
Not sure how that would work... left edge would show the profile for the "time" at the left edge, wouldn't it?

WEEKEND should be the profile that begins showing at the time of the switch. Instead, SCHOOLDAY was retained. On the left edge, schoolday was the current profile. When I did a profile switch (for testing), schoolday recurs as you see in the middle... why would it not appear now with the "new" profile name?

The UI logic of this display is confusing as is... users will expect to see the name of the new profile show up... at the point of the change.)

This screenshot shows both... the original profile and what I see after making a change:

![ps-fail2](https://cloud.githubusercontent.com/assets/9641700/10979936/460296c0-83b4-11e5-98e2-636b62268316.png)


(Really like being able to have profiles.)

**Comment by oamyoamy** [comment]
Continued testing and reloading... 
Looks like it shows up always with label of the first profile in the list. But reloading now IS bringing up the selected profile. 

(That didn't happen in my first tests. Hmmm.)

**Comment by MilosKozak** [comment]
yeah that's the bug. name of the selected profile should be there. going to look for it

**Comment by MilosKozak** [comment]
it's only rendering issue. tooltip on basal pill should show correct profile

**Comment by oamyoamy** [comment]
Yes.... it does.

**Comment by MilosKozak** [comment]
after refresh it's rendered fine
![image](https://cloud.githubusercontent.com/assets/11146458/10980268/69ec155a-8401-11e5-8cfb-0b5301a61afe.png)

**Comment by oamyoamy** [comment]
Yes. That's what I said.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/cgm-remote-monitor/commit/12374aee91b4df2fda15cf2d19e1188c6d50e47d
thanks again @oamyoamy
