### ISSUE TITLE
No profile editor 

### ISSUE THREAD

**Issue by Tobydex** [nightscout/cgm-remote-monitor#1354]
![image](https://cloud.githubusercontent.com/assets/10146465/11169409/b1ff111c-8bae-11e5-95f8-8d891edcb225.jpg)

No profile editor showing in drop down

**Comment by AdrianLxM** [comment]
(I cannot help, but from the fb-conversation some additional info):

 * There is no "Profile Editor" botton below the "Reports" button.
 * Version: version 0.8.1 head daf70a5d7e61e44d7c4aa972f2cfd6cbefb95c48

**Comment by MilosKozak** [comment]
not sure when was this link added. could you upgrade to latest release 0.8.2?

**Comment by jasoncalabrese** [comment]
The profile editor link is only added when 1 of several plugins is enabled (iob, cob, bwp, basal, etc)

**Comment by AdrianLxM** [comment]
Good to know. But isn't the profile editor needed even if those are not active. For setting the time zone, e.g.

**Comment by jasoncalabrese** [comment]
I see that as a work around for a bug, if there isn't a treatment profile we should use the local time, think there's a bug there.  Also even without the link the profile editor is there, if you have the url such as https://YOUR-SITE/profile/
