### ISSUE TITLE
Generic Pump Monitoring [$15]

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1355]
I've been thinking about how similar the monitoring could be between Connect, OpenAPS, RileyLink, MMComander, etc

Currently we have initial uploads from OpenAPS and also @mddub's #1253

I think we should attempt to use similar methods to monitor pumps in general, and then try to make that work for everything.

### Properties to track
  * Treatments
  * IOB
  * Battery
  * Reservoir 
  * Recency (time since polling/active connection status)
  * CGM BG

### Proposal

  * Use treatments for all treatments (stop trying to use entries for them)
  * Extend the device status api/collection to support non-cgm devices
  * Use entries for pump status entries like #1253 including the `IOB_SOURCE` extended setting
  * Don't combine recency/connection status with iob
  * Finally create that new endpoint to expose all this info instead of continually hacking the /pebble endpoint

@nightscout/dev

**Comment by ps2** [comment]
This is good timing, as I'm working on uploading treatments from RileyLink right now. I was planning on using the REST api to upload them, but I'll follow this thread to see if a new consensus is arrived at.

**Comment by mddub** [comment]
Great idea. If I'm interpreting correctly, this is what it should look like for the Connect bridge in particular:

`entries` collection:
```json
{
    "type": "pump_status",
    "reservoirLevelPercent": ​50,
    "reservoirAmount": ​79,
    "activeInsulin": ​0
}
```

`devicestatus` collection:
```json
{
    "pumpUploaderConnected": true,
    "pumpConnected": true,
    "sensorConnected": true,
    "pumpUploaderBattery": ​44,
    "pumpBattery": ​100,
    "sensorDurationHours": ​119,
    "timeToNextCalibHours": ​7,
    "sensorState": "NORMAL",
    "calibStatus": "LESS_THAN_NINE_HRS"
}
```

I'm just using the MiniMed Connect keys, except I propose replacing the current "conduit" keys with more generic terms (conduitBatteryLevel -> pumpUploaderBattery, conduitInRange -> pumpUploaderConnected, etc.). This is what the Connect entries look like right now: https://github.com/mddub/minimed-connect-to-nightscout/blob/master/test/integration.js#L42

Happy to help compile a list of standard keys somewhere (a wiki page?).

**Comment by PieterGit** [comment]
Got Nightscout and MangoDB working on a portable Ockel Sirius B (Windows 10, 32 bits, Quad core Intel Atom Bay-trail Z3735F processor, 120 grams) with FreeStyle Libre. 
I just give a small contribution of $15 because of the good job you guys are doing for improving Nightscout. I'll try to contribute, but I'm only a novice programmer.

**Comment by ps2** [comment]
I can commit to updating the RileyLink app to match this once there is a format.  I've seen the one proposed by @mddub above, and discussed the openaps one on gitter with @jasoncalabrese, and there's what I've been uploading from the RL app.  I think that the openaps one seems to have the most considerations thought through, since there are a variety of devices involved in openaps, so I think heading in that direction would not be a bad idea.

**Comment by jasoncalabrese** [comment]
I have some of the basic working with https://github.com/nightscout/cgm-remote-monitor/pull/1455

**Comment by mddub** [comment]
I switched to @jasoncalabrese's openaps format for Connect: https://github.com/mddub/minimed-connect-to-nightscout/pull/1 + #1460.

**Comment by jasoncalabrese** [comment]
There are some open questions on https://github.com/nightscout/cgm-remote-monitor/pull/1455, the main thing missing there is a way to pick what you want displayed in the pill.  It might also be that we want multiple pills.

**Comment by ps2** [comment]
Posting the openaps version that @jasoncalabrese described here for reference.
```
{
  pump: {
    battery: {
      status: 'normal',
      voltage: 1.52
    },
    status: {
      status: 'normal',
      timestamp: '2015-12-05T18:59:37.000Z',
      bolusing: false,
      suspended: false
    },
    reservoir: 86.4,
    clock: '2015-12-05T10:58:47-08:00'
  },
  openaps: {
    suggested: {
      bg: 147,
      temp: 'absolute',
      snoozeBG: 125,
      timestamp: '2015-12-05T19:02:42.000Z',
      rate: 0.75,
      reason: 'Eventual BG 125>120, no temp, setting 0.75U/hr',
      eventualBG: 125,
      duration: 30,
      tick: '+1'
    },
    iob: {
      timestamp: '2015-12-05T19:02:42.000Z',
      bolusiob: 0,
      iob: 0.6068340736133333,
      activity: 0.016131569664902996
    },
    enacted: {
      bg: 147,
      temp: 'absolute',
      snoozeBG: 125,
      recieved: true,
      reason: 'Eventual BG 125>120, no temp, setting 0.75U/hr',
      rate: 0.75,
      eventualBG: 125,
      timestamp: '2015-12-05T19:03:00.000Z',
      duration: 30,
      tick: '+1'
    }
  }
}
```
"need to add pump model info, and normalize some fields"

**Comment by jasoncalabrese** [comment]
The plugin is also looking for `pump.battery.percent`in addition to voltage and will use whichever it gets.

One thing to note is the devicestatus collection gets big, and older data isn't so interesting, so I'm thinking about setting TTL in mongo.

**Comment by jasoncalabrese** [comment]
I think https://github.com/nightscout/cgm-remote-monitor/pull/1455 is done and ready for extra testing.  I have it running on my prod site and will merge tomorrow unless we find an issue.  Take a look at the pump plugin in readme for all the options: https://github.com/nightscout/cgm-remote-monitor/tree/wip/pump#built-inexample-plugins

**Comment by jasoncalabrese** [comment]
I merged #1455 to dev let me know if anything isn't working for you, hoping we can extend it to work with all pumps

**Comment by PieterGit** [comment]
is everybody fine that this bounty will be claimed by @danamlewis on behalve of the openaps/nightscout community. otherwise the money will go to bountysource (which i did not intendend).

**Comment by jasoncalabrese** [comment]
That's fine with me, I looked into turning off bounty source, but looks like it might be something @bewest setup
