### ISSUE TITLE
When profile is in mg/dL and you set your site to mmol (and vice versa) all calculations are off

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#1356]
##

**Comment by sulkaharo** [comment]
Should we change the profile object API so that the calls to access the data have to specify the units & translate the units on the fly?

**Comment by oskarpearson** [comment]
This looks like a duplicate of https://github.com/nightscout/cgm-remote-monitor/issues/367 - I'm closing it unless there are objections. Please re-open if necessary.
