### ISSUE TITLE
Admin Tools - Device Status Collection 0

### ISSUE THREAD

**Issue by ELUTE** [nightscout/cgm-remote-monitor#1357]
A user deleted the documents in device status collection using the admin tools on his website. It says there are 0 documents but his collection in mongo is growing. Battery information has not returned to the website despite there being over 500 devicestatus records. api/v1/devicestatus is showing [] 
![screen shot 2015-11-16 at 8 55 33 am](https://cloud.githubusercontent.com/assets/7684327/11183546/53ba19de-8c40-11e5-8066-d7f24ea78307.png)
##

**Comment by MilosKozak** [comment]
there will be something wrong with mongo connection. restart site?

**Comment by ELUTE** [comment]
restart did not resolve issue

**Comment by MilosKozak** [comment]
api/v1/devicestatus still showing [] ?

**Comment by ELUTE** [comment]
yes

**Comment by MilosKozak** [comment]
never seen such issue. i'd remove entire collection from mongo gui and then refresh site again to recreate it

**Comment by ELUTE** [comment]
I did.

**Comment by MilosKozak** [comment]
then count of documents in mongo gui must be 0 (or small) and must equal to api/v1/devicestatus. is it?

**Comment by ELUTE** [comment]
It was 500 and was showing [] I deleted it and now it is small and still [] user is using mongodb upload with xDrip.... Asked them to switch to rest api to see if that makes a difference. Will have to wait until child is home from school.

**Comment by sulkaharo** [comment]
Sounds to me like the uploader and the website are configured to read a different collection for device status? AFAIK that's configurable, so it's possible for someone to just set the two to look at different places.

**Comment by ELUTE** [comment]
it is coming in as devicestatus they did not change it on the uploader.
