### ISSUE TITLE
Uploading raw values, need calibration support

### ISSUE THREAD

**Issue by skjelland** [nightscout/cgm-remote-monitor#1363]
It would be nice if we could upload raw values read from a wixel without preprocessing, using a simple wifi or 3g/gprs device.  The calibration, timestamp and direction should in this case be calculated on the server side.  xdrip currently uploads this structure:

{
    "direction": "SingleDown",
    "noise": 1,
    "dateString": "2015-10-18T11:53:50.087+0200",
    "sgv": 321,
    "date": 1445162030087,
    "unfiltered": 250048,
    "rssi": 100,
    "device": "xDrip-BluetoothWixel",
    "filtered": 250048,
    "type": "sgv"
}

if the full output is used from the wixel (including sender id), we get this data:

6600358 153984 117536 216 -89 201 0

this could translate into the following json structure to be uploaded:

{
    "senderid": 6600358,
    "unfiltered": 153984,
    "filtered": 117536,
    "rssi": 89,
    "senderbattery": 216,
    "wixelbattery": 3029,
    "device": "wDrip",
}

the server side could then use the current calibration data and calculate current bg value and raw value.  date for the reading should be the current time.  direction could also be detected on the server based on previous values.

if the senderid is also uploaded, the wanted senderid could be configured on the serverside, hence the wixel code won't have to be updated when getting a new sender.

we also need a simple webpage to enter the current fingerstick value to be used for calibrations, perhaps the careportal could be used for this, just use the fingerstick values uploaded?

what do you think?

:)
##

**Comment by stavlor** [comment]
this looks like something that you may want to bring up with the xDrip folks instead of creating an issue here https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental

**Comment by skjelland** [comment]
@stavlor no, this is not related to xdrip, a standalone wifi/wixel combo could upload readings directly to nightscout, no phone and no xdrip..  For this to work properly, we need some kind of web interface to create the cal records, and support in the upload (api/entries) rest api to apply the calibrations to the uploaded values

**Comment by thecubical** [comment]
It looks like wdrip is already doing this  

https://github.com/skjelland/wdrip/blob/master/arduino/arduino.ino#L69

**Comment by whoiswes** [comment]
+1 for this functionality

**Comment by analogmonster** [comment]
This is totally doable.  If you look at the xdrip schematic, the bluetooth module receives its data via a serial connection.  If you had a microcontroller with ethernet or WIFI (arduino mbed and esp8266 all come to mind) you would simply need to program the microcontroller to interpret the data from the wixel and upload it straiht into your mongo database, so nightscout or xdrip could access the data for processing.

Before I found xdrip+ that was the way I was planning to go myself - no android, just website from iphone and my own DIY WIFI uploader that shared the iphones connection via tethering.  However I find the xdrip+ predictive algorithm to be far superior to nightscout so it looks like I will have to bite the bullet and carry 2 phones.

I do agree this is an issue to raise in the xdrip hardware section not nightscout though.
