### ISSUE TITLE
API is Providing Numbers as Strings

### ISSUE THREAD

**Issue by someoneAnyone** [nightscout/cgm-remote-monitor#1368]
In working through some bugs on Nightscouter I discovered that some nightscout sites seem return numbers as strings for things like:

``` javascript
"alarmTimeagoWarnMins": "15",
 "alarmTimeagoUrgentMins": "30",
```

``` javascript
"alarmTimeagoWarnMins":  15,
 "alarmTimeagoUrgentMins":  30,
```

Have you encountered this before?
##

**Comment by MilosKozak** [comment]
maybe versions 0.7 and older before hure @jasoncalabrese refactoring

**Comment by someoneAnyone** [comment]
It's an 0.8.2 site
