### ISSUE TITLE
Combo Bolus

### ISSUE THREAD

**Issue by GrantKY** [nightscout/cgm-remote-monitor#1372]
Additional feature request more than an issue. Would be nice to have the ability to input a combo bolus to the careportal. We are currently using some guidance on how to bolus for fats and proteins and for some meals that recommends a bolus spread over 8 hours.

**Comment by MilosKozak** [comment]
No problem to add it as an input but not sure we can handle it as IOB etc
@scottleibrand @jasoncalabrese

**Comment by scottleibrand** [comment]
If you go ahead and add it, we can add support for combo bolus IOB tracking at the same time we add support for temp basal IOB, which hopefully will be soon.

**Comment by jasoncalabrese** [comment]
Maybe we can enter it with a. bolus and absolute temp for the extended period.  Maybe use white instead of the blue we use for temps?

**Comment by MilosKozak** [comment]
so split combo bolus into a 2 treatments (bolus + temp basal with some special flag)
we don't use it much. what is usual pump interface for it?
 - total insulin
 - percent of delayed basal
 - duration
?

**Comment by jasoncalabrese** [comment]
There are several different extended boluses with the different pumps.  The medtronics have both extended and square.  I'm assuming extended is a lot like combo's on the ping.  You set the percent now, and the percent over the extended period, and the duration.

Would need someone that uses the square/dual wave to better explain them.

But either way for us I think it would come down to 2 treatments, for the initial bolus and the extended portion and we'd need to calculate the absolute U/hr.  Then just like temps we could cancel them.
