### ISSUE TITLE
Reports don't work on a funnel cake fork

### ISSUE THREAD

**Issue by fichtenweg** [nightscout/cgm-remote-monitor#1376]
![capture](https://cloud.githubusercontent.com/assets/10168739/11430126/85dce19c-948a-11e5-9239-e0a19f43bba4.JPG)

Hi All,

Does anyone have issues with the reporting part of the funnel cake version. I am selecting a time span and then click the show button but no graphs are drawn. I have tried out everything that came to my mind:

re-deployment of the website
re-deployment + disconnect from github
I have thoroughly checked web page configurations on azure, nothing more nothing less, no duplicate entries
I have tried IExplore, Mozilla and Chrome browsers, no diference, graphs are not drawn
API_SECRET is configured as per instructions, no duplicate entries, 12 chars longs
When starting a particular report I see data being loaded and processed, only no graphs are drawn.
I have compared all possible settings to another cgm web page where reports are getting generated fine and there are no differences.

I am open for suggestions

Regards,
Svet

**Comment by jasoncalabrese** [comment]
I saw an issue like this that turned out to be solved by using mongo 3.0, I think 1 of the queries used to get temp basals doesn't work on with mongo < 3

**Comment by fichtenweg** [comment]
Hi Jason,

Thanks for the quick response. I use mongolab in the example above (never used REST API)
Since mongo is already at version 3.0.0 since 30th September, should the temp basal query be a problem here.
Meanwhile I checked all settings against a cgm web page with working reports and I couldn't find a single char missing or redundant.

To be on the safe side I created a second db just few hours ago and made the necessary azure configurationis so as to start using the new db.  No good news so far, still no graphs are drawn.

As far as the temp basal query is concerned, I checked the reports at:
https://cloudcgm.azurewebsites.net/
there you could see the temp basal query message appearing for a second, but still
all graphs are gettings drawn.

**Comment by MilosKozak** [comment]
What is the url of not working site?

**Comment by fichtenweg** [comment]
Hi Milos,

Here it is

https://valcgm.azurewebsites.net

**Comment by sulkaharo** [comment]
I think it's hanging due to the missing treatment profile. Can you try entering a profile using the built-in editor and see if the reports start working?

**Comment by fichtenweg** [comment]
Hi Sulkaharo,

Entering pump profile has already been tried previously with negative results.

**Comment by sulkaharo** [comment]
Right - @MilosKozak the site throws this into Javascript error console upon loading the site. Deployment gone wrong?

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (regular.json, line 0)
[Error] WebSocket connection to 'wss://valcgm.azurewebsites.net/socket.io/?EIO=3&transport=websocket&sid=JjlXu1GMgYDXTaEiAAA0' failed: Unexpected response code: 503

**Comment by fichtenweg** [comment]
Please tell me if there is something I should do on my end.

**Comment by MilosKozak** [comment]
Yeah, probably

Odesl�no z iPhonu
MK

**Comment by MilosKozak** [comment]
redeploy

**Comment by fichtenweg** [comment]
Hi Milos,

What I tried before is

- redeployment, 
- redeployment with disconnect and reconnected

Now I also tried deletion of the fork and re-fork - nothing still works.

So I decided to go for re-creation of the azure web site and followed the guide below step by step

http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie/recreate-a-site-in-azure

as result cgm web page reporting still doesn't work

**Comment by MilosKozak** [comment]
i see this on your site now
![image](https://cloud.githubusercontent.com/assets/11146458/11466434/290a98ce-9741-11e5-8b3d-abbd68bf82b7.png)
which is probably wrong bundle (deployment). i'd try to redeploy one more time ... or you can try to setup another site from dev brach

**Comment by fichtenweg** [comment]
Hi Milos,

I re-deployed one more time but still reports don't work. When I did the web site re-creation above I went through too many errors, mostly azure portal returned messages that the fork cannot be connected or deployment finished with errors.

I guess we will stick for now with the plugin above to substitute reporting function.

**Comment by jasoncalabrese** [comment]
I was seeing the same `d3 is not defined` error on my site today, but it worked before,  maybe there's might be a timing issue.  Could also try adding d3 to the window in bundle.source.js or requiring it.

**Comment by diabetes123** [comment]
Hi, I have the same issue with two new sites I created in the previous two weeks for myself.  My son's sites were setup earlier with the same github deployment and the reports on his sites as of last night continue to work correctly.

**Comment by diabetes2** [comment]
New Mongo data base, new github account with new fork, new site, tried master and dev branches... same temp basal loading issue causing reports not to show.  Is anyone able to create a new site with reports working at this time?

**Comment by jasoncalabrese** [comment]
Maybe there was a change to 1 of the dependencies that is causing this issue with new deploys?  If you open the javascript developeer console in you browser do you see an error like https://github.com/nightscout/cgm-remote-monitor/issues/1376#issuecomment-160550505

**Comment by diabetes2** [comment]
where should I look?

**Comment by jasoncalabrese** [comment]
Open the console before pressing the "Show" button, then if there's an error you should see it

**Comment by diab1234** [comment]
Errors
404 not found
Failed: error during web socket handshake unexpected response code 503
Warnings
Unable to find element

**Comment by diabetes2** [comment]
no error like that

**Comment by oamyoamy** [comment]
d3 error showing on a new deployment. This deployment is 0.9, but the same version I am running (and my reports are fine): 
![charterror](https://cloud.githubusercontent.com/assets/9641700/11582665/5bc1c4f0-9a06-11e5-891c-b98a27a17f92.png)

**Comment by fichtenweg** [comment]
Same here

![capture](https://cloud.githubusercontent.com/assets/10168739/11583043/450cdc06-9a5e-11e5-810c-4caf9f0fe6ee.JPG)

**Comment by jasoncalabrese** [comment]
I started a hotfix #1387 with a few minor changes to master that I hope will fix some of these issues.  If you'd like to try it out just create a new branch named `hotfix/report-fixes` in your fork and I'll send you a pull request.

<img width="343" alt="screen shot 2015-12-03 at 10 20 46 pm" src="https://cloud.githubusercontent.com/assets/751143/11583210/36830388-9a0c-11e5-8164-6517bb3b71cc.png">

**Comment by diab1234** [comment]
i would like to try

**Comment by jasoncalabrese** [comment]
@diab1234 I sent you https://github.com/diab1234/cgm-remote-monitor/pull/14 thanks for testing

**Comment by violetta-markova** [comment]
Jason, please send me too

**Comment by diab1234** [comment]
Fantastic!  It worked.  Thank you!

**Comment by jasoncalabrese** [comment]
Glad that worked @diab1234, @violetta-markova I sent you https://github.com/violetta-markova/cgm-remote-monitor/pull/1

**Comment by violetta-markova** [comment]
Hi Jason,

I can confirm its working on our end too :-)

Kudos!!!

**Comment by jasoncalabrese** [comment]
Great, should be able to get the hotfix out for everyone this weekend

**Comment by fichtenweg** [comment]
It worked for me too :+1:

**Comment by swilkata77** [comment]
Hi Jason,

Please send me the hotfix

**Comment by jasoncalabrese** [comment]
@swilkata77 I sent you https://github.com/swilkata77/cgm-remote-monitor/pull/1

**Comment by swilkata77** [comment]
Working like a charm :+1: :+1: :+1:

**Comment by jasoncalabrese** [comment]
Thanks for all the help testing this, the patch release is out.  

If I sent you a pull request, you can update your master branch when you get a chance using the update too http://nightscout.github.io/pages/update-fork/.

You'll then want to point Azure or Heroku back to the master branch.  There isn't any rush for doing that, but it will get you setup for the next release.
