### ISSUE TITLE
Plot values higher than 400 somehow special

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#1379]
Very high values in the CGM plot cause rendering issues. Special handling for high values needed? See attached.

![12289554_10206640009852724_1228515919684431741_n](https://cloud.githubusercontent.com/assets/1001330/11478334/facc170e-9794-11e5-981d-4ce81c486021.jpg)
##

**Comment by jasoncalabrese** [comment]
I wonder if this is for all scaling types or just linear
