### ISSUE TITLE
Minor issue viewing Care Portal on IOS devices

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#140]
After bringing up a care portal entry by tapping on the dot, I cannot get the pop up to go away unless I tap on another care portal entry, or manually refresh the browser window.  Tapping another care portal entry just moves the active care portal popup, so the only real workaround is to refresh the browser window.  The only way to refresh the screen in the full screen Home Screen view is to switch apps then back to Nightscout.
##

**Comment by oskarpearson** [comment]
I've confirmed that this is still a problem in 0.9.3-dev-20161212b

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
