### ISSUE TITLE
Error codes firing even though configured to OFF

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1402]
According to github info, 

ERRORCODES_URGENT defaults to an urgent alarm for codes 9 and 10.

I have this variable set to OFF

ERRORCODES_URGENT     OFF

We've had sensor issues over the last few days, lots of ???. The error is firing, continuously, through pushover.

Acknowledging the notification doesn't seem to be stopping it either. (And, yes, I have my BASE_URL set.)
##

**Comment by jasoncalabrese** [comment]
maybe fixed by #1626

**Comment by jasoncalabrese** [comment]
Was this fixed with beta 1?

**Comment by oamyoamy** [comment]
I updated my dev fork on 4/26.

I have errorcodes_urgent set to "off" 

On 4/29, PM, we had a sensor restart, and I continued to get the Pushover notifications for the ??? (startup period).

**Comment by jasoncalabrese** [comment]
A couple things to try as a workaround that might help narrow it down: `ERRORCODES_URGENT="false"` `ERRORCODES_URGENT="0 0"`

Also see what's in `/api/v1/status.json`

**Comment by jasoncalabrese** [comment]
Thought of something else, it's probably code 5 that you're getting during the restart, that's an info level.

The default ERRORCODES_URGENT is 9 and 10 (hourglass and ???) the default ERRORCODES_INFO includes a bunch of codes: 1 2 3 4 5 6 7 8

So I think what you may be after is the default ERRORCODES_URGENT and a custom ERRORCODES_INFO=false or some subset.

**Comment by oamyoamy** [comment]
Could be. That the pushover comes through with ??? as the error msg may be what was throwing me looking at the notes. I thought I was seeing errorcode 10 happening. You could be right that it's 5 instead.

I've set the ERROCODES_INFO to off... will see if that resolves the issue. 

Thanks

**Comment by jasoncalabrese** [comment]
What uploader are you using, maybe error codes are mixed up?  But it's possible toget 10 during startup, if there are some really fast changes in the last hour of warmup.

**Comment by jasoncalabrese** [comment]
@oamyoamy did setting `ERROCODES_INFO` help?

**Comment by oamyoamy** [comment]
Sensor restart last night. (That's the only time I can see this in action.)  Uploader setup is xdrip beta 4 on motog.

I still got Pushover notifications every 2 minutes during the 2-hour warmup -- coming through as an alert for ???. 

Based on the suggestions above, I have:
ERRORCODES_URGENT  false
ERRORCODES_INFO false

(Previously I was using "off" not "false" -- I can change them both to "off" and try again.)

Here's a snippet from Pushover through the night. 

![img_1595](https://cloud.githubusercontent.com/assets/9641700/15627496/da53cc2c-249a-11e6-8bbd-e08f371741f0.PNG)

**Comment by oamyoamy** [comment]
I reset both variables to OFF (rather than false) after confirming that the alarms (triggered as URGENT) were still firing during startup.

Today, we are having sensor failure... I am still getting notifications for the ???. 

I am getting them whether I have OFF or FALSE as the value.

(Ultimately... this leads me to turn alarm notifications off entirely, which defeats the purpose of the alarms since I might want to be notified of high or low...  Or, I silence my phone, which also defeats the purpose.)

**Comment by jasoncalabrese** [comment]
With the new alarm groups errorcodes are separate from the default group, so snoozing then for a long time wont block other alarms like before.  I think there's something wrong with xdrip beta4.  It should be sending a code 5, instead of a code 10.

I'm using xdrip, but a little past beta5 I think.

**Comment by oamyoamy** [comment]
I am running xdrip + (as of this weekend). And today, as this sensor continues to fail, I am getting ??? notifications again even though both of the variables are "off" --

Anything else I should try while i have a scenario where I am seeing ??? regularly and may be able to test?

**Comment by oamyoamy** [comment]
(And I don't know if xdrip+ might still have the code you think is buggy in terms of what it is passing... that could be. Could be it doesn't have the same 5+ guts that you have running. )

**Comment by fallon225** [comment]
I'm still getting these too.  I forgot they were supposed to be off (I have it set to off in azure). Anything I should try?

**Comment by neconeco1** [comment]
Hi, i have dexcom G4 and we started sensor yesterday and than my xdrip started showing ?AD and my nightscout shows hourglass. This is the first time i see that, could someone help me ? What i shoud do?
Thank you
