### ISSUE TITLE
Trend line rendering issue when using Nightscout as a Home Screen App on iOS

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#141]
If you save your Nightscout URL to the Home Screen on IOS, it opens full screen with no browser address bar.  If the screen switches from portrait to landscape, then back to portrait, the trend line disappears.  It will render properly again at the next refresh or when switching apps then back to Nightscout.  The problem easily recurs if phone orientation switches the screen to landscape.  A workaround is to turn on portrait screen lock.

**Comment by jasoncalabrese** [comment]
Haven't seen anything like this for a long time, assuming it's been fixed in all the UI reworking
