### ISSUE TITLE
CGM Data collection standardization?

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#143]
Does it still make sense to have each user create a custom collection name for their CGM data?  With the recent push towards API standards that create their own collections (devicestatus, treatments), is it worth considering automatically creating a "cgmdata" collection instead of a custom name?  It would simplify the Mongo URI somewhat.  I'm not sure how invasive this change would be given that so many people already have working (but non-standard) data collections.
##

**Comment by oskarpearson** [comment]
I don't know much about the history of this - but from https://github.com/nightscout/cgm-remote-monitor#core it seems that MONGO_COLLECTION now has default values for collections. It doesn't, however, include a CGM specific collection from what I can see.

Can we close this issue?
