### ISSUE TITLE
Add support for Azure Deploy Button

### ISSUE THREAD

**Issue by davidebbo** [nightscout/cgm-remote-monitor#1433]
Creating as a follow up to #1412. I can help get this together.

**Comment by davidebbo** [comment]
Doc says there are 3 required params:

- `MONGO_CONNECTION`: straightforward enough. It'll be a text box in the Deploy to Azure site.
- For `DISPLAY_UNITS`, it looks like we want a drop down at creation time to select either `mg/dl` or `mmol`? Or maybe it has a good default and can be skipped at creation time?
- Is `BASE_URL` really required? Can't the site just infer it from the request that it gets? It would make the deploy workflow a bit dirty to have to ask the user to hand type it.

My problem is that I don't really know anything about this site, so I don't know how to tell if it's working. When I deploy it to Azure, it seems to run but displays `--- undefined︎` in the corner. Is that expected?

**Comment by amazaheri** [comment]
Hi there, I am on phone now but I can follow up with you tomorrow to go over the site and it's pre-reqs.

**Comment by stavlor** [comment]
Only other ones i can think of at the moment would be API_SECRET which is used to control write access via the api it has to be at least 12 characters and is usually required for configuring the uploaders and only other thing i can potentially think of would be perhaps a optional ENABLE space not sure what kind as far as other ones you can look at the Deploy to Heroku fields we ask for but i think that covers the majority of the required ones

**Comment by amazaheri** [comment]
@stavlor can you send a link to Heroku deploy. We can start with something simple and add more features with future releases like supporting share2nightscout web job deployment as option, etc. As for share it would be great to have them as check boxes to be selected by users and for us to populate ENABLE property during deployment.

**Comment by amazaheri** [comment]
@davidebbo let us know if you want to get an overview  of the site architecture and data flow

**Comment by stavlor** [comment]
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fnightscout%2Fcgm-remote-monitor%2Ftree%2Fdev&template=https%3A%2F%2Fgithub.com%2Fnightscout%2Fcgm-remote-monitor%2Ftree%2Fdev

**Comment by jasoncalabrese** [comment]
The main part of the current deploy process that we need to keep is having everyone use their own forks.  We use the forks for tracking and also to let everyone pick their own update timing.  We don't want to auto update hundreds or thousands of sites automatically when we push to main Nightscout master branch.

Does the Deploy to Azure change any of that?

**Comment by stavlor** [comment]
@jasoncalabrese I believe Deploy to azure will require the user to fork the repo where as Heroku will just use the ns repo and not initiate a fork which is the one bone i have to pick with heroku heh

**Comment by stavlor** [comment]
@jasoncalabrese Though after the initial deploy Heroku disconnects the continuous deployment from git unless the user sets it up again after the deploy is done

**Comment by amazaheri** [comment]
The deploy to azure button would be added to readme which points to azuredeploy.net and send the git url as referrer along with custom azuredeploy.json. Meaning folks can fork and use the deploy right from their repo.

**Comment by davidebbo** [comment]
With Azure, it works whether you fork the repo or not. But note that it's not continuous (though that's supported as well). So even if everyone is going after the main repo, they need to take an explicit action to update to the latest, but clicking Sync in the Azure portal (details about this mode [here](http://blog.davidebbo.com/2013/04/publishing-to-azure-web-sites-from-any.html)). That should remove your concern about everyone getting updated at once.

To easily try this now:

- Go to https://github.com/davidebbo/cgm-remote-monitor/tree/dev
- Click the Deploy To Azure button and go from there

If that works for everyone, let's get that in, and then we can iterate from there.

**Comment by amazaheri** [comment]
👍

**Comment by stavlor** [comment]
:+1: works nicely for me and makes the deploy process relatively painless
