### ISSUE TITLE
Reports freezing 8.4

### ISSUE THREAD

**Issue by christerjensen** [nightscout/cgm-remote-monitor#1444]
A friends site had problems with reports in 8.2 - saw an issue with reports was resolved in 8.3 and helped her update to 8.4. The same problem that was reported in 8.3 seems to persist in 8.4. I have included the error when the reports freezes. Rawbg and careportal is enabled - no future data in admin tab. 
![nightscout](https://cloud.githubusercontent.com/assets/11073675/12072496/dc7b80c2-b0e0-11e5-9b28-9cb699a05ffc.jpg)

**Comment by christerjensen** [comment]
Set up a new site for another friend today from scratch - reports work perfectly.

**Comment by jasoncalabrese** [comment]
Maybe the older js was cached by your browser?

**Comment by christerjensen** [comment]
No - I had never opened here site, and also tried Firefox and Chrome on 3 computers. All data in Mongolab was deleted, problem persists. I guess it must be something with the settings in Azure since the problem has been there pre/post update and with several new deploys (and deleted the Github-link). Guess I will have to delete the site and re-create it for here.

There is no pop-up window when I push the link that I would like to authenticate the device either.

**Comment by MilosKozak** [comment]
deployment issues should be solved now
