### ISSUE TITLE
Error Trapping on MONGO_COLLECTION variable

### ISSUE THREAD

**Issue by jwedding** [nightscout/cgm-remote-monitor#145]
The Collection should be polled for the quantity of points before display is rendered. We can trap for 0, <3, or valid data instead of just displaying dashes on the rendering.
##

**Comment by oskarpearson** [comment]
From what I can tell this was an issue when users wouldn't enter the MONGO_COLLECTION environment variable. As it had no default, it would then attempt to render an empty collection.

The collection now has a default value, so my understanding is that this is no longer relevant. Sorry to do things this way, but could you please re-open this with some more detail if it's still an issue?

Thanks!
