### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by GrantKY** [nightscout/cgm-remote-monitor#1453]
New user can't get cgm-remote-monitor to deploy. Branch is up to date and have tried re forking, and syncing multiple times with no success (also tried dev branch rather than master - also with no success). Info is getting through to the /pebble page but not the main page (black screen with dashes). 

Error log message below. Suggestions to resolve appreciated. Did consider trying the new deploy to azure option created by #davidebbo - is this option now available? 

---

Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 5.0.0, 5.1.1, 5.3.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml

> Nightscout@0.8.4 postinstall d:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install
>  module.js:340
>     throw err;
>           ^
> Error: Cannot find module 'q'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (d:\home\site\wwwroot\node_modules\bower\bin\bower:6:9)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
> An error has occurred during web site deployment.
>  npm failed
> npm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`
> npm ERR! Exit status 8
> npm ERR! 
> npm ERR! Failed at the Nightscout@0.8.4 postinstall script.
> npm ERR! This is most likely a problem with the Nightscout package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node node_modules/bower/bin/bower --allow-root install
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls Nightscout
> npm ERR! There is likely additional logging output above.
> npm ERR! System Windows_NT 6.2.9200
> npm ERR! command "d:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"
> npm ERR! cwd d:\home\site\wwwroot
> npm ERR! node -v v0.10.40
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm
##

**Comment by jasoncalabrese** [comment]
This may have been an intermittent issue, seems like the bower cache at Azure might not have been current

**Comment by longlandm** [comment]
Still receiving this error today.  (I'm not the same person Grant referred to).  I was trying to deploy a dev fork and got the same error.  Thought I would keep it current.

**Comment by turbofart** [comment]
Tried just now. Issue still persist.

**Comment by turbofart** [comment]
So the `q` module was just the first missing module.
I have managed to have it deployed by issuing the following commands in the console:

```
npm install q
npm install mout
npm install user-home
npm install optimist
```

**Comment by GrantKY** [comment]
There does seem to be an ongoing (but intermittant)  azure deployment issue.   Sometimes multiple redeploys does not result in a working site.  However,  users I have dealt with have found that when faced with this issue creating a new website in azure using same github fork subsequently works.

**Comment by RowanDoel** [comment]
Hi

I am getting the same error, see below, does this mean I just need to wait until Azure sorts itself out?

thanks

module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.8.4 postinstall script.
npm ERR! This is most likely a problem with the Nightscout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
An error has occurred during web site deployment.
npm failed
npm ERR!     node node_modules/bower/bin/bower --allow-root install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd d:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
module.js:340\r\n    throw err;\r\n          ^\r\nError: Cannot find module 'q'\r\n    at Function.Module._resolveFilename (module.js:338:15)\r\n    at Function.Module._load (module.js:280:25)\r\n    at Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n    at Object.<anonymous> (d:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)\r\n    at Module._compile (module.js:456:26)\r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.Module._load (module.js:312:12)\r\n    at Module.require (module.js:364:17)\r\n\r\nnpm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`\r\nnpm ERR! Exit status 8\r\nnpm ERR! \r\nnpm ERR! Failed at the Nightscout@0.8.4 postinstall script.\r\nnpm ERR! This is most likely a problem with the Nightscout package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     node node_modules/bower/bin/bower --allow-root install\r\nnpm ERR! You can get their info via:\r\nnpm ERR!     npm owner ls Nightscout\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! cwd d:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\nnpm\r\nC:\Program Files (x86)\SiteExtensions\Kudu\53.50324.2154\bin\scripts\starter.cmd bash deploy.sh

**Comment by MilosKozak** [comment]
you may try deploying using button on github repo. i tested it yesteday on dev branch and it worked great

**Comment by RowanDoel** [comment]
Ah, Iv used Azure, don't think there is an Azure deploy function is there?

**Comment by MilosKozak** [comment]
on dev branch

**Comment by RowanDoel** [comment]
Ah right thanks Ill give it a try

**Comment by RowanDoel** [comment]
Just go tit working by following GrantKY suggestion of deploying a new site, so didn't need to try that in the end, Azure can definitely be a bit twitchy with its deployments, but relly pleased it running now

**Comment by adezan** [comment]
Evening all,
    Was there a solution to this issue? I have tried creating a new site through Azure but the deployment will continually fail with the aforementioned errors. How would I go about issuing the console commands mentioned by turbofart?

**Comment by nicolaswebb** [comment]
I am having the same problem. I suspect it's something to do with the Node versions? I tried creating an entirely new site.

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json mongodb@2.1.18 No README data

> Nightscout@0.8.4 postinstall d:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install


module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.8.4 postinstall script.
npm ERR! This is most likely a problem with the Nightscout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower --allow-root install
An error has occurred during web site deployment.
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm failed
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd d:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
npm WARN package.json mongodb@2.1.18 No README data\r\n\r\nmodule.js:340\r\n    throw err;\r\n          ^\r\nError: Cannot find module 'q'\r\n    at Function.Module._resolveFilename (module.js:338:15)\r\n    at Function.Module._load (module.js:280:25)\r\n    at Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n    at Object.<anonymous> (d:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)\r\n    at Module._compile (module.js:456:26)\r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.Module._load (module.js:312:12)\r\n    at Module.require (module.js:364:17)\r\n\r\nnpm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`\r\nnpm ERR! Exit status 8\r\nnpm ERR! \r\nnpm ERR! Failed at the Nightscout@0.8.4 postinstall script.\r\nnpm ERR! This is most likely a problem with the Nightscout package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     node node_modules/bower/bin/bower --allow-root install\r\nnpm ERR! You can get their info via:\r\nnpm ERR!     npm owner ls Nightscout\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! cwd d:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\nnpm\r\nC:\Program Files (x86)\SiteExtensions\Kudu\54.50506.2209\bin\scripts\starter.cmd bash deploy.sh

**Comment by jlucasvt** [comment]
I'm having the same issue deploying to Azure.  I have re deployed many many times, I tried adding the 10+ npm install xxxx packages via console that it failed on and redeployed each time.  

I then deleted the site and re-created it in a different Azure region (US East) and still more package errors.   What is wrong here?  Has anyone been able to successfully deploy this on Azure?

<img width="681" alt="screen shot 2016-06-15 at 9 45 05 pm" src="https://cloud.githubusercontent.com/assets/19819388/16102960/7e2e7846-3342-11e6-88f4-5f32a0ec69f4.png">

**Comment by RowanDoel** [comment]
I did have problems initially, I was told that sometimes Azure deploy stuff and don't always fix it straight away.  I deleted mine and started again and it worked. it was frustrating though, is this one one where u initially get a choice between deploying to Amazon cloud or Azure.. think I did Amazon

**Comment by jlucasvt** [comment]
## Here is what I did to fix my deployment issue.

1.) Deploy as directed in documentation and login to site and find that it's not working. 👎 
2.) If you get a similar error in deployment log from Azure where node install is giving you [Error: Cannot find module 'xxxx' ]
<img width="545" alt="screen shot 2016-06-16 at 8 33 54 am" src="https://cloud.githubusercontent.com/assets/19819388/16116859/2bcffcea-339d-11e6-8661-3146ca0e7d7b.png">
<img width="554" alt="screen shot 2016-06-16 at 8 34 05 am" src="https://cloud.githubusercontent.com/assets/19819388/16116860/2ed85b30-339d-11e6-9244-b20ac9fbe40a.png">
<img width="453" alt="screen shot 2016-06-16 at 8 34 22 am" src="https://cloud.githubusercontent.com/assets/19819388/16116866/30bb6410-339d-11e6-8a7c-7617490319d0.png">

### Login to Kudu site console manager in Azure from a web browser

`https://[YOUR_SITE_NAME].scm.azurewebsites.net` [Replace YOUR_SITE_NAME with your azure site address]

From the menu at the top of Kudu Select  [Debug Console] > [CMD] 
<img width="357" alt="screen shot 2016-06-16 at 8 36 17 am" src="https://cloud.githubusercontent.com/assets/19819388/16116909/6e30306e-339d-11e6-9fab-921c5937d066.png">


Navigate to site > wwwroot folder using the clickable folder UI

<img width="1061" alt="screen shot 2016-06-16 at 8 24 24 am" src="https://cloud.githubusercontent.com/assets/19819388/16116589/cb55aab4-339b-11e6-84df-2f0a052d31f3.png">

Enter the following into the commands in the command prompt one by one pressing [Enter] when you finish you can copy and paste the commands into the command prompt.
<img width="627" alt="screen shot 2016-06-16 at 8 28 15 am" src="https://cloud.githubusercontent.com/assets/19819388/16116687/5407b87a-339c-11e6-9df8-01e20b2478e4.png">

`npm install rimraf -g`  [press Enter and wait for a command prompt to return]

`rimraf node_modules` [press Enter and wait for a command prompt to return]

`npm install` [press enter and wait a while for this to finish it may throw some warnings but site should deploy]

Go to your site and see how it's doing:  https://[YOUR_SITE_NAME].azurewebsites.net  
(if the Application Settings are correct it should be working)

**Comment by ruess** [comment]
That worked for me - thank you @jlucasvt for the thorough guide!

**Comment by tylergale** [comment]
Frustratingly encountered this today.  To fix mine, I had to run all of the following, all mentioned in this post:
```
npm install q
npm install mout
npm install user-home
npm install optimist
npm install rimraf -g
rimraf node_modules
npm install
```
