### ISSUE TITLE
Outside US Support for Dexcom Share/G5 users

### ISSUE THREAD

**Issue by urmc-costik** [nightscout/cgm-remote-monitor#1471]
please add an option to use: shareous1.dexcom.com for auth & get data for Share users outside the USA.

**Comment by jasoncalabrese** [comment]
Might need to expose something on the share bridge, then it will be as simple as using a new extended settings in the bridge plugin.

**Comment by LLLIEFA** [comment]
Seems this was fixed in the new code so that non-US cloud users are getting their data in,
using App setting:
BRIDGE_SERVER with value: EU

I added it on saturday after a new pull from master and it worked for us!
Great work guys!

**Comment by jasoncalabrese** [comment]
Fixed with https://github.com/bewest/share2nightscout-bridge/pull/24
