### ISSUE TITLE
Dexcom G5 sharing - where to get a follower's password?

### ISSUE THREAD

**Issue by iroller** [nightscout/cgm-remote-monitor#1479]
Hi, thanks for the work on this project!

I'm a bit confused on where can I get `BRIDGE_USER_NAME` and `BRIDGE_PASSWORD`.
Should I create a new follower in Dexcom app and use his email as `BRIDGE_USER_NAME`? If so - where can I get a password? It doesn't seem to create one.

Thanks!

**Comment by stavlor** [comment]
the BRIDGE_USER_NAME and BRIDGE_PASSWORD need to be the same dexcom account that the sharer that are uploading using Share are using you would need to get this from the sharer as the share system doesn't create accounts for followers.

**Comment by iroller** [comment]
Ah so that's the same one as for https://store.dexcom.com/ and I had to add it to my.env.
Thanks!
