### ISSUE TITLE
Care Portal: No decimal point in Carb, Insulin Given fields

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#148]
On my Samsung Galaxy S3 running Kit Kat, I get a numeric keypad when entering data in the Carb and Insulin Given fields on the Care Portal form.  There is no way to add a decimal point.  Probably not a big deal for carbs, but entering fractional units of insulin should be an option.  

I'm not sure if this is specific to the S3 because I remember entering CP entries with fractional units on Android tablets at Best Buy last week.  This problem doesn't occur on IOS.
##

**Comment by oskarpearson** [comment]
I'm going through old issues and seeing if we can close them. Could someone verify that this is still an issue? The issue is over 2 years old now.

Thanks!
