### ISSUE TITLE
Color on BG trend line dims over time

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#149]
When viewing Nightscout in a browser window, the trend line color dims.  The recent BG readings dim from bright green to a darker green.  The BG cone prediction dims from a bright light blue to a dim blue.  This only occurs if the browser window is refreshing automatically.  If I do a manual refresh, the BG trend line and cone render properly.  Running the latest dev, color, mg/dl.

![screen shot 2014-09-10 at 1 20 41 pm](https://cloud.githubusercontent.com/assets/6069420/4224861/0fb4946e-3929-11e4-85c0-d9973e25687f.png)

![screen shot 2014-09-10 at 1 20 51 pm](https://cloud.githubusercontent.com/assets/6069420/4224865/1aaa6d9e-3929-11e4-85a7-a220fe6f85c9.png)

**Comment by jasoncalabrese** [comment]
Resolved during Dreamsicle
