### ISSUE TITLE
Nightscout API http post treatment problem

### ISSUE THREAD

**Issue by baembel08** [nightscout/cgm-remote-monitor#1507]
Hi to you all,

I'm trying to send http post requests for automatically adding treatments. 
My json body using Nightscout API website with swagger looks like this:
[
  {
   
    "eventType": "Exercise",
    "created_at": "2016-02-07T10:00:00.000Z",
    "duration": 60,
    "notes": "indoor cycling",
    "enteredBy": "Strava_Sync"
  }
].
the response body is this 
{
  "result": {
    "ok": 1,
    "n": 1
  },
  "ops": [
    {
      "eventType": "Exercise",
      "created_at": "2016-02-07T10:00:00.000Z",
      "duration": 60,
      "notes": "indoor cycling",
      "enteredBy": "Strava_Sync",
      "_id": "56b760f173bfd86c128267e9"
    }
  ],
  "insertedCount": 1,
  "insertedIds": [
    "56b760f173bfd86c128267e9"
  ]
}
Everything seems to be ok.

My problem: when working with a **script** to send data, the original time (my value for created_at)
is overwritten by webserver time (current time). I'm working with powershell, which has a modified version of curl command.

What can I do ?

Thanks in advance

**Comment by MilosKozak** [comment]
Use `eventTime` key
https://github.com/MilosKozak/cgm-remote-monitor/blob/master/lib/treatments.js#L106

**Comment by jasoncalabrese** [comment]
another workaround is to send an array instead of a single object

**Comment by baembel08** [comment]
Hi Milos, I did try eventTime as date and it works. Thanks.
