### ISSUE TITLE
Looking for a list of data document

### ISSUE THREAD

**Issue by msftkevin** [nightscout/cgm-remote-monitor#1531]
Looking through the code, I am trying to get an understanding of all the data schemas in MongoDb.

It would appear that there are schemas defined in various code libs throughout the repo. Does anyone have a consolidate view of them and any additional information about their usage?

Thanks!

**Comment by jasoncalabrese** [comment]
The best we have is Swagger: https://github.com/nightscout/cgm-remote-monitor/blob/dev/swagger.yaml or https://YOUR-SITE.com/api-docs.html

It's not 100% complete, but it's close for the core fields, if you find something missing/not right a PR would be great
