### ISSUE TITLE
Nightscout: Time view does not correspond to care portal entries without sensor data

### ISSUE THREAD

**Issue by Deweyoxberg** [nightscout/cgm-remote-monitor#1532]
Hi,

T1's sensor expired last week. We've been using the careportal to keep up with things until new sensors arrive. However the entries are no longer in sync with the 3/6/12/24hr views. Things which happened last Monday are now showing up as if they were new events.

Is there a way to keep date/time advancing forward normally without sensor data? It's our only link for now.
##

**Comment by YYCMichael** [comment]
Any news on this issue?

**Comment by MilosKozak** [comment]
it should be fixed in dev branch .... what version are you using?

**Comment by YYCMichael** [comment]
I just updated to the latest production branch under master.

**Comment by MilosKozak** [comment]
dev is  still under development. you can create another site from dev branch to test it. remember to specify different profile collection because the format has changed

**Comment by YYCMichael** [comment]
Not sure what you mean by different profile collection.

**Comment by MilosKozak** [comment]
you have to set MONGO_PROFILE_COLLECTION

**Comment by YYCMichael** [comment]
Is the fix still in dev only? Any ETA on commit to master?

**Comment by YYCMichael** [comment]
Looks like this issue still exists in dev; I've attached two images to help explain the issue.

I would  expect that even without a CGM reading I could manually enter a result and have it displayed on the graph like any other value, along with careportal entries. What I have found is unless there is an upload from the CGM we cannot use the portal to manually track activity.

![nodata](https://cloud.githubusercontent.com/assets/417795/14317264/b46dfb44-fbc4-11e5-8545-638d8ff6086b.PNG)
![treatments](https://cloud.githubusercontent.com/assets/417795/14317265/b472890c-fbc4-11e5-80e4-80888b6143fb.PNG)

**Comment by PoweRGbg** [comment]
I know what the main goal of this project is but it is really disappointing to not have this kind of functionality (manual entries in the graph) when there is no cgm around. 
These entries show in the report graphs but not on the real-time site

**Comment by sulkaharo** [comment]
Hi! Sadly the timeline rendering code is structured in a manner that makes is pretty dependent on the CGM data being present. If you can figure out how to refactor the code to fix this or find a programmed who's savvy in the D3 library and willing to spend time with this, we'd be happy to get a pull request to solve this. ;)

**Comment by tynbendad** [comment]
fyi, I'm running into this also, since my kid takes "cgm breaks".  Have actually been running into it for a long time, but the breaks are more frequent lately.  And, I need nightscout to work well regardless, since I track his pump reservoir/etc with it.  But, without the cgm data, after 48 hours the pump pill (and other pills) disappear.  So, is there a way to fix the pill issue without solving the whole problem?

fwiw, currently I have a workaround where i manually add a cgm entry to mlab with a recent epoch time (from https://www.epochconverter.com/).  but, would prefer it to just work of course.
