### ISSUE TITLE
Future Data Admin Tool

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1553]
Helped a user tonight who updated to 0.8.4 so that she could clear Future Data. 
Using the admin tool (only), all of her records seem to have been cleared... not just the future data ones.
##

**Comment by MilosKozak** [comment]
treatments?

**Comment by oamyoamy** [comment]
No... cgm readings (her entries). Everything wiped out using the admin tool, not just the isolated future data points.

**Comment by jasoncalabrese** [comment]
Maybe the time on her machine was old and we use local time?
