### ISSUE TITLE
Authenticate button doesn't do anything

### ISSUE THREAD

**Issue by elminah** [nightscout/cgm-remote-monitor#1554]
Authenticate button doesn't do anything
- centos standalone server, node server.js on 1337 port
- everything else works (anything that does not require auth)
- auth test (experiments) is working, also the rest_api is working with api_secret

**Comment by MilosKozak** [comment]
pm me site with this issue

**Comment by elminah** [comment]
Can't pm:
ary.ampc.ro

**Comment by elminah** [comment]
Hello Kozak,

Thank you for the answer, the site is:
ary.ampc.ro


On Sun, Apr 3, 2016 at 10:47 PM, Milos Kozak <notifications@github.com>
wrote:

> pm me site with this issue
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/issues/1554#issuecomment-205042719>
>



-- 
Cleo Preda
+40721250290

**Comment by MilosKozak** [comment]
looks like your deployment is not complete .... rerun `npm install` and check errors

**Comment by elminah** [comment]
ok, will try that, but last time it destroyed all configuration.

On Mon, Apr 4, 2016 at 5:06 PM, Milos Kozak <notifications@github.com>
wrote:

> looks like your deployment is not complete .... rerun npm install and
> check errors
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/issues/1554#issuecomment-205308392>
>



-- 
Cleo Preda
+40721250290
