### ISSUE TITLE
Pushover not working properly

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1605]
Been noticing for a while that Pushover is not behaving properly...

-- doesn't matter if certain things are turned off (like alarms or error codes), you get them all
-- ack'ing from Pushover doesn't always snooze properly (ack'ing from site works fine)

**Comment by oamyoamy** [comment]
Alarms like CAGE are also not triggering either alerts (in site) or Pushover notifications.

**Comment by jasoncalabrese** [comment]
Is this with master or dev, I think there are several issues, I got a CAGE alarm for the first time in a long time last week, so there are some conditions that can make it work...

1 of the issues that I'd really like to fix is there are only 2 types of alarms urgent and warning, if you ack an urgent alarm you ack all alarms for that time period.

**Comment by oamyoamy** [comment]
Running dev.

Beyond CAGE issue, I don't find that the settings to control pushover are working.

I have PUSHOVER_ALARM_KEY set to off... still get all alarms.

I have ERRORCODES_URGENT set to off... still get alarms for ??? every 1-2 minutes via pushover

**Comment by jasoncalabrese** [comment]
I think I see the issue here, there was a change to treat `'off'` as `false`, but pushover code wasn't updated

**Comment by sulkaharo** [comment]
I've actually observed the pushover notifications randomly (but rarely) being triggered by the backend when the client data indicates they should not have. Wonder if the OpenAPS IOB is causing issues with the IOB snooze?

**Comment by jasoncalabrese** [comment]
That might be a different issue, I think the iob plugin starts ignoring devicestatus iob after it get old, I think we should extend that period and then have a fallback to treatment based iob.

**Comment by jasoncalabrese** [comment]
@oamyoamy I think this is really fixed now, there were multiple issues but it's been working in my tests for last week or so.  I've also added some extra logging for notifications so if we see anything else strange it might be easier to debug.

**Comment by oamyoamy** [comment]
Just got a CAGE alarm, Jason. First time in a long time!

**Comment by jasoncalabrese** [comment]
Great, keep an eye on alarms in general
