### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1617]
I used to see this in dev; but now the icon is not there. Show edit mode is checked in the settings panel. Updated dev branch. No edit mode icon showing in top bar where it used to be.

**Comment by jasoncalabrese** [comment]
Maybe not logged in?  Edit mode is showing for me, but there could be other things going on.

**Comment by oamyoamy** [comment]
No authenticated... that may have been it. Re-authenticated, and I see it. This leads me to note that on the "settings" panel, there is no link to authenticate. (You have to go to one of the admin tools to authenticate even if using those tools isn't your goal.) Could an authent link/status be added to the settings panel, down at the bottom?

**Comment by jasoncalabrese** [comment]
auth is on the careportal drawer too, but adding to settings makes sense for now

**Comment by jasoncalabrese** [comment]
the auth link was moved to the settings panel with the new tokens feature
