### ISSUE TITLE
IAGE goes to N/A if older than 7 days

### ISSUE THREAD

**Issue by GrantKY** [nightscout/cgm-remote-monitor#1618]
Running  0.9.0-dev and if IAGE is more than 7 days old it reports n/a  in the treatment pill. If mouse pointer  over pill and it states last change 1/1/1970. Appreciate many users will not expect IAGE > 7 days but as our ds uses a cartridge every few days (which is the same as his set changes) it seemed logical to use IAGE to note date of his backup insulin pen which we change every month.

(same issue on older dev but updated before reporting issue to check)

**Comment by sulkaharo** [comment]
Sounds like we need to do a change similar to the sensor change events, where >14 days is loaded and sent to client.

**Comment by sulkaharo** [comment]
#1624 is now merged to dev, which fixes this in my test; @GrantKY can you verify

**Comment by GrantKY** [comment]
@sulkaharo just tried dev branch from today to test this issue and now getting white screen (master branch works fine on same site).

**Comment by GrantKY** [comment]
Updated website as I see there was another ongoing issue today. Website now fine and IAGE shows older data. Many Thanks.
