### ISSUE TITLE
Pump res = 0 does not show alerts

### ISSUE THREAD

**Issue by CrushingT1D** [nightscout/cgm-remote-monitor#1651]
If res is 0.0 it is removed from the pill and no longer shows a value. Instead, it should show value 0.0 as passed in from openaps,etc  (just as it does anything greater than zero). This way users will continue to be alerted (possibly urgently if they so desire) that the reservoir  is empty.
<img width="351" alt="screen shot 2016-04-25 at 5 27 20 pm" src="https://cloud.githubusercontent.com/assets/18058098/14804059/84406ed4-0b14-11e6-8568-b6b244f2e576.png">
<img width="432" alt="screen shot 2016-04-25 at 5 25 16 pm" src="https://cloud.githubusercontent.com/assets/18058098/14804058/84403ab8-0b14-11e6-8b6d-a7508205c35c.png">

**Comment by stavlor** [comment]
Well as empty as you can call what Medtronic calls 0.0 there's still about 12u left at that point
