### ISSUE TITLE
Grilled Cheese contributors

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1681]
If you've contributed to Nightscout since the funnel cake release and would like to be tagged in release Facebook posts, add a comment to this issue with your FB username or send me DM.

It's hard to match up some of the github names with facebook
##

**Comment by apanasef** [comment]
Russian translation - Fedor Apanasenko (me). (If translators are to be mentioned)

**Comment by bogdangorescu** [comment]
Romanian translation - Bogdan Gorescu (Bog Dan on FB).
Thanks!

**Comment by sulkaharo** [comment]
Sulka Haro - not sure anymore. Optimization, bug fixes?

**Comment by jasoncalabrese** [comment]
@sulkaharo you're on the permanent list, I was just looking at the github for the diff and it shows 25 contributors and didn't want to miss anyone

**Comment by xpucuto** [comment]
Bulgarian translation Hristina Dimova :p

**Comment by lifeexcellence** [comment]
German translation - Thorsten Feige / lifeexcellence on GitHub

**Comment by skjelland** [comment]
added some Norwegian translations just now

**Comment by baembel08** [comment]
Unattended Nightscout installtion -> Deploy to Azure 
some parts of German translation

**Comment by PieterGit** [comment]
Fixed units test, upgrade to Node 8.4.0
