### ISSUE TITLE
interface idea - CAGE alarm

### ISSUE THREAD

**Issue by mark3189** [nightscout/cgm-remote-monitor#1701]
Nice to have: create a warning for site change overdue. Could be like the battery icon where CAGE icon turns yellow after so many (user-settable) hours. Would make it more noticeable in the webview when site is needed and/or counter has not been reset.

thanks!

**Comment by jasoncalabrese** [comment]
We're doing that for the pump and openaps plugins too, so it makes sense to add it to the *AGE plugins

**Comment by jasoncalabrese** [comment]
This is in place for CAGE on dev now, I'm planning to add for SAGE and IAGE too
