### ISSUE TITLE
v0.9.0-beta2: Vanishing Rig Battery Monitor 

### ISSUE THREAD

**Issue by chadmmartin** [nightscout/cgm-remote-monitor#1710]
When loading Nighscout via the iPhone App as well as on a Chrome browser (Version 50.0.2661.94 m) the rig battery life appears then disappears after <10 seconds. About a minute later it will reappear and usually stick around from there out.

![image](https://cloud.githubusercontent.com/assets/8141464/14974398/59849ae0-10c2-11e6-9129-29b9a9f5d039.png)

![image](https://cloud.githubusercontent.com/assets/8141464/14974403/64e36754-10c2-11e6-9d14-552542eb07a6.png)

**Comment by jasoncalabrese** [comment]
check that `DEVICESTATUS_ADVANCED="true"` is set see https://github.com/nightscout/cgm-remote-monitor/blob/dev/README.md#devicestatus-device-status

**Comment by chadmmartin** [comment]
specifically enabling devicestatus and setting DEVICESTATUS_ADVANCED="true" seemed to do the trick. thank you.
