### ISSUE TITLE
v0.9.0-beta2:Temp Basil Start Treatment

### ISSUE THREAD

**Issue by chadmmartin** [nightscout/cgm-remote-monitor#1712]
When entering a Temp Basil Start the dynamic form clears the duration. Steps to recreate:
1. Enter a duration (60)
2. Tab or click on either Percent or Basal value.
3. When entering a value into either field the other is hidden AND the value entered for Duration is cleared out.

Even when going back and entering the duration, this value isn't being captured and passed with the form. End result is the duration is written as blanks/null. You are able to edit the treatment under reports to add the duration in afterward. I believe this was working in 9.0 beta 1
 

![image](https://cloud.githubusercontent.com/assets/8141464/14974749/ff4a9ba6-10c6-11e6-8d85-96591b860e8a.png)

**Comment by oamyoamy** [comment]
Seeing the same issue.
