### ISSUE TITLE
COB  appears to be off compared to production

### ISSUE THREAD

**Issue by rdobb** [nightscout/cgm-remote-monitor#1723]
Running beta site shows cob as 51.3 but production site shows 0 cob. I have screen shots if needed
##

**Comment by Kdisimone** [comment]
@rdobb is this issue resolved?  can this be closed?

**Comment by rdobb** [comment]
Sure, I am not sure any more, I went back to production build…

Thank you,
Ryan Dobb

[cid:image001.jpg@01CDFB12.48AA8410]   [cid:image002.jpg@01CDFB12.48AA8410]
• Email: rdobb@nquest.com<mailto:rdobb@nquest.com>
• Office: 410-823-6767

**Comment by Kdisimone** [comment]
thanks...do you mind closing it?
