### ISSUE TITLE
careportal temp basal issue

### ISSUE THREAD

**Issue by LynneRB** [nightscout/cgm-remote-monitor#1725]
9.0-beta 2 not showing temp basal on graph as it did in 9.0-beta 1. Temp basal is listed in treatments only.

**Comment by oamyoamy** [comment]
Confirmed. This is not displaying properly for me either in 9.0-beta2

**Comment by oamyoamy** [comment]
This is related to this: https://github.com/nightscout/cgm-remote-monitor/issues/1712

When a temp basal is set from the Pebble CarePortal app, it renders properly on the graph. It is only when entered from the website CarePortal that the display isn't working.... seems like the duration issue is the problem.
