### ISSUE TITLE
Color coding in pill boxes

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1771]
Feature request:

Since we now can set warning/alarm duration thresholds for SAGE and IAGE, just like CAGE, can similar color-coding be applied?

I thought it might already be in place, but my IAGE is well over the 'hours' level I have set for both warning and urgent -- and text is white in the pillbox.

In comparison, my CAGE text in the pillbox is red, visually reminding me that action is needed (or that I didn't update in careportal).

Personally, I would love to see the box take on warning color at warning level or urgent color at urgent level. But I'd be happy with red text for IAGE at urgent level (at least).

**Comment by jasoncalabrese** [comment]
Yes, I want this too, just wanted to get the other PR merged in first, planning on working on it now

#1769
