### ISSUE TITLE
Scrollbars appear when hovering over recent treatment details and settings button 'hamburger button'

### ISSUE THREAD

**Issue by rkresha** [nightscout/cgm-remote-monitor#1788]
Copying this over from #1730 since it's a larger problem. Seeing this with 0.9.0-beta3 and dev branches

Seeing this in Chrome, Internet Explorer, and Firefox

Broken: when hovering over a recent treatment or hamburger button
![image](https://cloud.githubusercontent.com/assets/19247761/15683306/40b3a95e-2727-11e6-9dbb-bcb562cfed95.png)
![image](https://cloud.githubusercontent.com/assets/19247761/15683370/902f2ca6-2727-11e6-9dd2-cb6dc95b739b.png)

Works: when hovering over an older treatment
![image](https://cloud.githubusercontent.com/assets/19247761/15683336/6503210e-2727-11e6-9662-3ebc5895e296.png)

**Comment by rkresha** [comment]
Working on this... just testing the changes to make sure they truly do fix both cases. More to come in the next few days.

**Comment by rkresha** [comment]
The settings/hamburger button is good now. The treatment tooltip is still being a pain

**Comment by PieterGit** [comment]
I sometimes reproduce this with the settings/hamburger button (with 0.9.0-dev-20161010, head e0d0a98). Tested with Firefox/Edge. 

I can easily reproduce this with a unauthenticated browser (I tried Edge). It seems the tooltip "settings" triggers the invalid horizontal scrolling bar. Please fix this for the final 0.9 version.

**Comment by rkresha** [comment]
Treatment hover still not adjusted, but it not nearly as noticeable. Hamburger button certainly fixed imho.

**Comment by rkresha** [comment]
@jasoncalabrese So if I hover over the hamburger button, the page resizes fixing the scrollbar issues somewhere between 15-25 seconds after hovering. I move the mouse away and the page resizes again within 5 - 15 seconds and brings the scrollbar back... does that help at all?

**Comment by rkresha** [comment]
Fixed with #2139
