### ISSUE TITLE
Don't include future basal the Basal/Bolus stats in the day-to-day report

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1789]
Currently if you look at the day-to-day report for the current day, any remaining planned basal is included.  It would be nice if it only included basal already delivered.

@MilosKozak any thoughts on how hard this would be?

**Comment by MilosKozak** [comment]
only delivered is counted

**Comment by MilosKozak** [comment]
do you have an example?
