### ISSUE TITLE
Allow automated careportal entries when bolusing from pump

### ISSUE THREAD

**Issue by YYCMichael** [nightscout/cgm-remote-monitor#1836]
I may be missing a feature, but at the moment bolusing via pump requires a manual entry via careportal. Is there a way whether existing or future planned to have the pump send this information to NS so it's automatically logged as a treatment?

**Comment by bewest** [comment]
Sure, you need an uploader to upload the data from the pump into Nightscout.
It's possible to use `openaps` for this purpose, and that's what I recommend.  There's a tool in the oref0/openaps toolkit that fetches the data from the pump, reformats it for Nightscout, and then sends the data to Nightscout.

**Comment by YYCMichael** [comment]
We're using the Medtronic 640G uploader app for Android; how do we go about getting this auto posted? Or does that app even send the data to start with?

**Comment by jasoncalabrese** [comment]
@YYCMichael I think that should work, you should probably file an issue over at https://github.com/pazaan/640gAndroidUploader
