### ISSUE TITLE
Alarm snoozing problem

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#1841]
Sometimes happen I'm unable to snooze alarm on client. After snooze it sounds immediately again and this appears on server
![image](https://cloud.githubusercontent.com/assets/11146458/16371413/b261e00a-3c46-11e6-95e8-6b747da57709.png)

**Comment by jasoncalabrese** [comment]
I've seen this too and I think I know where it is, I'll try to get a fix in soon

**Comment by jasoncalabrese** [comment]
@MilosKozak this should be fixed now, let me know if it's working for you or not
