### ISSUE TITLE
Merge pull request #1671 from martijnmcb/patch-2 Update language.js

### ISSUE THREAD

**Issue by rgilbert03** [nightscout/cgm-remote-monitor#1843]
Hi All,

Thank you for the great work on this project!  I am setting up Nightscout for the first time and am receiving an deployment failed error in Azure. I've tried re-deploying, removing the source and setting it up again, as well as deleting my forked copy and recreating with no luck.  The logs are below.  Appreciate any assistance!!

Updating branch 'e1e07e563df3e0c21045cefd823b01a2279499ed'.
Updating submodules.
Preparing deployment for commit id 'e1e07e563d'.
Running custom deployment command...
Running deployment command... FAIL

Activity Logs
Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json mongodb@2.1.18 No README data

> Nightscout@0.8.4 postinstall D:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install

module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.8.4 postinstall script.
An error has occurred during web site deployment.
npm ERR! This is most likely a problem with the Nightscout package,
npm failed
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/bower/bin/bower --allow-root install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
npm WARN package.json mongodb@2.1.18 No README data\r\n\r\nmodule.js:340\r\n    throw err;\r\n          ^\r\nError: Cannot find module 'q'\r\n    at Function.Module._resolveFilename (module.js:338:15)\r\n    at Function.Module._load (module.js:280:25)\r\n    at Module.require (module.js:364:17)\r\n    at require (module.js:380:17)\r\n    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)\r\n    at Module._compile (module.js:456:26)\r\n    at Object.Module._extensions..js (module.js:474:10)\r\n    at Module.load (module.js:356:32)\r\n    at Function.Module._load (module.js:312:12)\r\n    at Module.require (module.js:364:17)\r\n\r\nnpm ERR! Nightscout@0.8.4 postinstall: `node node_modules/bower/bin/bower --allow-root install`\r\nnpm ERR! Exit status 8\r\nnpm ERR! \r\nnpm ERR! Failed at the Nightscout@0.8.4 postinstall script.\r\nnpm ERR! This is most likely a problem with the Nightscout package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     node node_modules/bower/bin/bower --allow-root install\r\nnpm ERR! You can get their info via:\r\nnpm ERR!     npm owner ls Nightscout\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command "D:\Program Files (x86)\nodejs\0.10.40\node.exe" "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\npm-cli.js" "install" "--production"\r\nnpm ERR! cwd D:\home\site\wwwroot\r\nnpm ERR! node -v v0.10.40\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\nnpm\r\nC:\Program Files (x86)\SiteExtensions\Kudu\56.50629.2304\bin\Scripts\starter.cmd bash deploy.sh
##

**Comment by nevincoskunazr** [comment]
Hello i am getting nearly same error. 
Log is

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: '.bowerrc'
Copying file: '.gitattributes'
Copying file: '.gitignore'
Copying file: '.travis.yml'
Copying file: 'app.js'
Copying file: 'app.json'
Copying file: 'azuredeploy.json'
Copying file: 'bower.json'
Copying file: 'CONTRIBUTING.md'
Copying file: 'COPYRIGHT'
Copying file: 'database_configuration.json'
Copying file: 'env.js'
Copying file: 'example-profiles.md'
Copying file: 'LICENSE'
Copying file: 'Makefile'
Copying file: 'package.json'
Copying file: 'prep_repo_release.sh'
Copying file: 'Procfile'
Copying file: 'README.md'
Copying file: 'scm-commit-id.json'
Copying file: 'server.js'
Copying file: 'setup.sh'
Copying file: 'swagger.yaml'
Copying file: 'Vagrantfile'
Copying file: 'bin\create_svg.sh'
Copying file: 'bin\post-devicestatus.sh'
Copying file: 'bin\post-mbg.sh'
Copying file: 'bin\post-sgv.sh'
Copying file: 'bin\post-treatment.sh'
Copying file: 'bin\tsvtojson.sh'
Copying file: 'bundle\bundle.source.js'
Copying file: 'bundle\index.js'
Copying file: 'lib\booterror.js'
Copying file: 'lib\bootevent.js'
Copying file: 'lib\bus.js'
Copying file: 'lib\constants.json'
Copying file: 'lib\devicestatus.js'
Copying file: 'lib\entries.js'
Copying file: 'lib\food.js'
Copying file: 'lib\hashauth.js'
Copying file: 'lib\language.js'
Copying file: 'lib\levels.js'
Copying file: 'lib\mqtt.js'
Copying file: 'lib\notifications.js'
Copying file: 'lib\pebble.js'
Copying file: 'lib\profile.js'
Copying file: 'lib\profilefunctions.js'
Copying file: 'lib\pushnotify.js'
Omitting next output lines...
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 7.0.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN engine jsonwebtoken@7.1.9: wanted: {"npm":">=1.4.28","node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine ignorefs@1.1.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine joi@6.10.1: wanted: {"node":">=0.10.40","npm":">=2.0.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine ignorepatterns@1.1.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm WARN engine form-data@2.1.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})

> typechecker@2.0.8 preinstall D:\home\site\wwwroot\node_modules\browserify-express\node_modules\watchr\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall D:\home\site\wwwroot\node_modules\browserify-express\node_modules\watchr\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN engine ambi@2.5.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
Thread was being aborted.
Thread was being aborted.

**Comment by Kdisimone** [comment]
can this issue be closed?  have you resolved the problem?

**Comment by PieterGit** [comment]
@rgilbert03 @nevincoskunazr 
Please let use know if this issue still persist in the latest release of Nightscout.
Azure hosting seems to give several problems. You can also try to use Heroku instead.
I'm closing this issue for now. If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
