### ISSUE TITLE
Configurable history in node application?

### ISSUE THREAD

**Issue by cjbeck** [nightscout/cgm-remote-monitor#186]
Is it possible to configure the number of days displayed in the node application? Possibly a historical view, somehow, weekly, monthly, etc.
##

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
