### ISSUE TITLE
Can we check the mongo version before trying to run report?

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#1866]
@ecc1, @johnmales, and others have ran into an issue where reports don't work.  Upgrading to mongo 3 seems to be the fix.

If we can check the version and show a message it would help.  Maybe add the mongo version to `/api/status.json`?
##

**Comment by oskarpearson** [comment]
We can find the API as follows.

> db.runCommand( { serverStatus: 1 } ).version
3.0.12
