### ISSUE TITLE
BG_TARGET_ and BG_ app settings not used in maker?

### ISSUE THREAD

**Issue by Mendanbar** [nightscout/cgm-remote-monitor#1870]
I'm using the maker addon with IFTTT, and I'm seeing alerts fired at the default values of these variables instead of the specified app settings variables.  The website shows the user specified levels correctly along with colors, so I know they are being at least partially properly applied... just not when it comes to the maker ns-events.

**Comment by Mendanbar** [comment]
Just saw this in app.json: "Alarm behavior currently 2 alarm types are supported simple and predict, and can be used independently or combined. The simple alarm type only compares the current BG to BG_ thresholds above, the predict alarm type uses highly tuned formula that forecasts where the BG is going based on it's trend. **predict DOES NOT currently use any of the BG_* ENV's**"  I've had predict enabled this whole time... so could this be why I'm seeing the alarms not use my BG_ values?

**Comment by jasoncalabrese** [comment]
Maker is only using the env var/app settings, the server isn't able to use the settings you change in the browser.  If you combine predict and simple you'd get an alert if either trigger, but you won't get double alerts.

**Comment by Mendanbar** [comment]
@jasoncalabrese Yes, I'm only referring to the server app settings.  It seems like the BG_* settings are only used in the "simple" alarms, while "predict" uses the default levels to decide what is high, low, urgent, etc.  The comment from the section of code I mentioned is the only documentation I could find on the matter.    I'm wondering if "predict" is intended to use the BG_* values eventually, but the feature hasn't been implemented yet?  For now I'm using "simple", but it would be great if "predict" would use my definition of high/low in the future to determine when to send me (maker) alerts.

**Comment by jasoncalabrese** [comment]
The thresholds for AR2 (predict) aren't based on absolute levels, and there aren't any options for it other than adjusting the width of the cone for display.

If you look at the code the thresholds for AR2 are here: https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/ar2.js#L10-L15

**Comment by Mendanbar** [comment]
@jasoncalabrese thanks for the clarification. I was misunderstanding the fundamental nature of predict mode, but now *think* I get it.
