### ISSUE TITLE
Mongo Error : sockets closed

### ISSUE THREAD

**Issue by Baum-BZ** [nightscout/cgm-remote-monitor#1899]
Every time when I start the server (Ubuntu Server), I become some errors from Mongo.
Here is a picture: 
![img_4674](https://cloud.githubusercontent.com/assets/18557397/17839148/ef52b84e-67df-11e6-9cd0-696c39ca055b.JPG)

**Comment by sulkaharo** [comment]
The error indicates your cgm-remote-monitor instance doesn't have all it's dependencies installed. Can you run ```npm install``` in the app directory to install the dependencies and then try again?

**Comment by Baum-BZ** [comment]
I install the cgm-remote-monitor on an other "newer" computer and there it works.
Also Thank You
