### ISSUE TITLE
OpenAPS as data source 

### ISSUE THREAD

**Issue by ramjar** [nightscout/cgm-remote-monitor#1910]
Hi guys,

First of all, great project!! 

Is it possible to use openaps as a data source, in order to upload data to mongodb (nightscout)?

I have a raspberry pi with nightscout, mongodb, openaps, which pulls the data from dexcom controller as bellow:
{
    "trend_arrow": "FLAT", 
    "system_time": "2016-08-24T11:03:22", 
    "direction": "Flat", 
    "sgv": 177, 
    "display_time": "2016-08-24T04:02:39", 
    "date": 1472004159000.0, 
    "dateString": "2016-08-24T04:02:39", 
    "unfiltered": 218304, 
    "filtered": 211584, 
    "device": "openaps://cgm", 
    "rssi": 183, 
    "type": "sgv", 
    "glucose": 177
  }

Do nightscout have support to get the data from openaps (for glucose and other Dexcom data), or do I need to create a wrapper which pulls and convert the data to mongodb/nightscout?

**Comment by bewest** [comment]
One of the components of openaps is oref0, which ships with a tool called `nightscout`.  The tool sends the data to Nightscout.  Here's some links for how to use the tool:

* https://github.com/openaps/docs/issues/129#issuecomment-216394218
* http://openaps.readthedocs.io/en/latest/docs/walkthrough/phase-1/using-openaps-tools.html#nightscout-endpoints

**Comment by ramjar** [comment]
Thank you!
