### ISSUE TITLE
plugins disappearing

### ISSUE THREAD

**Issue by analogmonster** [nightscout/cgm-remote-monitor#1911]
Plugins just randomly turn off - all of them at once usually.  For example they were all alive when I went to bed, first time I load the page this morning they were inactive.  Not a massive deal as they come back when I go into the settings, reset their tick boxes then refresh the page and they work again no problem.
##

**Comment by Kdisimone** [comment]
@analogmonster has this issue resolved for you?  If so, can you please close the issue.  thanks
