### ISSUE TITLE
stale data alarms off no longer strikes-through bg 

### ISSUE THREAD

**Issue by tynbendad** [nightscout/cgm-remote-monitor#1915]
when the data is >15 minutes old, even with stale data alarms disabled (unchecked), funnel-cake release used to cross out (strike though) the BG value, but the latest dev branch doesn't strike it through unless the alarm is enabled.
##

**Comment by jasoncalabrese** [comment]
There have been some changes in that area, so maybe I broke something, I'll see if I can reproduce it

**Comment by human911** [comment]
I was able to recreate this issue

**Comment by Kdisimone** [comment]
I can confirm this has been fixed.  Issue can be closed.
<img width="1149" alt="screen shot 2018-02-20 at 3 56 22 pm" src="https://user-images.githubusercontent.com/12402160/36455791-a58b6f5e-1656-11e8-96bd-23ac9866761b.png">

**Comment by tynbendad** [comment]
It looks like you have alarms on, or does it go yellow now even with alarms off?

**Comment by Kdisimone** [comment]
I’ll test. One sec

**Comment by Kdisimone** [comment]
You’re just looking for it to strike through, right?  Regardless of alarm setting?

**Comment by tynbendad** [comment]
Yes at a minimum, color change is ok but sound off if alarm is off...

**Comment by Kdisimone** [comment]
If that's what you'd want...You can add it back with this apparently:

https://github.com/Kdisimone/cgm-remote-monitor/commit/311672b0f0a99677d115db86e1e3af98b16ef730

**Comment by tynbendad** [comment]
Yes, that looks good - is it the same with all the alarm check boxes off? Thx

**Comment by tynbendad** [comment]
Ok thanks, will try it sometime.

**Comment by Kdisimone** [comment]
Seems to work when all the alarm settings are off as well, yes

**Comment by PieterGit** [comment]
Closing issue per @Kdisimone comment.
@tynbendad : please report back if this issue is fixed for you or not.
