### ISSUE TITLE
Pushover / BWP

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#1939]
I was helping someone in the CGMitC group, and he was asking about Pushover... and wanting notifications when BWP basically was <0.  

Looks like BWP currently only triggers an alarm if the BG needs to be brought into range, and based on these variables:

BWP_WARN (0.50) - If BWP is > BWP_WARN a warning alarm will be triggered.
BWP_URGENT (1.00) - If BWP is > BWP_URGENT an urgent alarm will be triggered.

I can see that having a way to set BWP high and BWP low alerts...  might be useful.
##

**Comment by sulkaharo** [comment]
The BWP < 0 is triggered after every meal bolus, which is probably not a useful moment to alert the user? Was the person thinking of alarming on excess IOB detected if there is no COB?

**Comment by oamyoamy** [comment]
Hmmm... I use pushover, and I don't get BWP notifications for that.

At any rate, the person was trying to understand what is available... and looking at his site (in that moment), the BWP on the site was suggesting the estimated outcome of 40mg/dL  (both IOB and COB were recorded). He couldn't understand why he wasn't getting a pushover to that effect... or when it might happen.

Looking at the variables... I was only seeing where a "high" alert would come through... maybe I'm missing something about how he can fine tune it.  (We keep our variables high because we don't necessarily want warnings for the "high"... but I can see how separating them out and sending warnings for possible low... could be something people want.)
