### ISSUE TITLE
Enabled plugins needs to be activated manually

### ISSUE THREAD

**Issue by ramjar** [nightscout/cgm-remote-monitor#1948]
I have enabled plugins via my.env 
ENABLE=careportal%20iob%20food%20sage%20openaps%20maker%20pump%20cob%20bwp%20bwpo

But in order to get the plugins enabled and active, i need to check them in the checkbox (for every plugin) and save the settings, for every new browser or device. Shouldn't the plugins which has been enabled via startup/my.env, be activated directly?

Is there any work around to have them activated and enabled by default?

**Comment by Chewwy420** [comment]
See here. You need to enable it so it shows by default.
https://github.com/nightscout/cgm-remote-monitor#predefined-values-for-your-browser-settings-optional
SHOW_PLUGINS iob cob careportal (and so on).

**Comment by jasoncalabrese** [comment]
The solution is what @Chewwy420 says, use `SHOW_PLUGINS`
