### ISSUE TITLE
No getting reports from Azure

### ISSUE THREAD

**Issue by gusponce** [nightscout/cgm-remote-monitor#1949]
Hello, can't figure it out yet why I am not getting full reports. Does anyone know the reason? (Azure, xDrip, G5)

![image](https://cloud.githubusercontent.com/assets/20726896/18445787/362aec28-78ed-11e6-895a-f163905a7a12.png)
##

**Comment by oskarpearson** [comment]
Hi @gusponce - could you verify that you're running a recent version of MongoDB? As per https://github.com/nightscout/cgm-remote-monitor/issues/1866 MongoDB 3 is required.

**Comment by gusponce** [comment]
Hello,
I could but I deactivated my account :(

Gustavo

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Dec 12, 2016 at 6:34 PM -0500, "Oskar Pearson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @gusponce<https://github.com/gusponce> - could you verify that you're running a recent version of MongoDB? As per #1866<https://github.com/nightscout/cgm-remote-monitor/issues/1866> MongoDB 3 is required.

-

**Comment by gusponce** [comment]
Hello,
I could but I deactivated my account :(

Gustavo

Get Outlook for Android<https://aka.ms/ghei36>


On Mon, Dec 12, 2016 at 6:34 PM -0500, "Oskar Pearson" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @gusponce<https://github.com/gusponce> - could you verify that you're running a recent version of MongoDB? As per #1866<https://github.com/nightscout/cgm-remote-monitor/issues/1866> MongoDB 3 is required.

**Comment by oskarpearson** [comment]
Thanks Gustavo. I hope it's ok if we close the issue for now then. I think we've got a reasonable idea of what cause things.

If you or anyone encounters this again, please re-open!
