### ISSUE TITLE
Token/Role based access controls breaks OpenAps ns-upload-entries

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#1955]
can it be that pull Request nightscout/cgm-remote-monitor#1868 (Token/Role based access controls) caused the uploading of Dexcom cgm entries to fail with Nightscout@0.9.0-beta3

> %ns-upload-entries cgm/cgm-glucose.json
> {"status":401,"message":"Unauthorized","description":"Invalid/Missing"}

And nightscout 0.9.0-dev shows DENIED

> GRANTED:  ::ffff:1.2.3.4 no-token api:entries:read default
> DENIED:   ::ffff:1.2.3.4 no-token api:entries:create

I checked API_SECRET and TREATMENTS_AUTH=off

I would assume 0.9.0 does not cause uploading in OpenAps to fail.

**Comment by jasoncalabrese** [comment]
Are you still seeing a problem with this?  If openaps is using your api-secret any requests should be authorized

**Comment by PieterGit** [comment]
I think it's solved. My  custom `ns-upload-entries` still got a  `-H 'Authorization: Bearer ` header, but I think the token is not valid anymore and the uploading still works. will investigate later to confirm.

**Comment by jasoncalabrese** [comment]
Closing for now, reopen if you find a problem that looks like something on the NS side

**Comment by cbruyndoncx** [comment]
I'm getting the same denied message, I use the android medtronic uploader app and SandraK82 installation scripts for local rpi installation.
I'm new at this, but I have some IT experience, and will digg a little bit further into the startup options to see if I can get some more detailed error info, or try with the other options to see if it makes a difference

**Comment by jasoncalabrese** [comment]
the old medtronic uploader doesn't send the api secret when posting to device status, the work around is setting the `AUTH_DEFAULT_ROLES="readable devicestatus-upload"` env var

**Comment by tuzoenduro** [comment]
@jasoncalabrese where do I set this up? I'm trying to upload carbs from a shortcut in IOS and keep getting this message.. thanks for the help

**Comment by ondrejpelak** [comment]
@tuzoenduro Hi, did you figure it out? I am trying to do the same thing... Not really smart from the documentation
