### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cgmnellanuvola** [nightscout/cgm-remote-monitor#199]
As discussed with Ben and Kevin I would like to localize the three parts of Nightscout. I'm Italian and I'm supporting the Italian community in order to setup and manage Nightscout and I think it would beneficial for many to have a localized software.
I'm translating android-uploader in Italian and German via a German friend of mine.

I'm not sure how to do it for cgm-remote-monitor but maybe with a choice in the setup. 

I hope I'm using the right tool to start a discussion and keep track of changes, if not please let me know.

Ivan

**Comment by sulkaharo** [comment]
Hi! It took a while but this is now done in Funnel Cake.
