### ISSUE TITLE
IOB from Loop app isn't correct. 

### ISSUE THREAD

**Issue by xpucuto** [nightscout/cgm-remote-monitor#2036]
When uploading from Loop the IOB shows only the pump bolus IOB . The Loop pill box shows the real IOB with included temp basal in it . 
<img width="1244" alt="screen shot 2016-10-05 at 17 18 46" src="https://cloud.githubusercontent.com/assets/11740423/19116984/167423c8-8b20-11e6-885a-176d849c317a.png">

**Comment by jasoncalabrese** [comment]
Thanks @xpucuto, can you include some devicestatus json that includes the Loop IOB. You should be able to get it from `https://YOUR_SITE/api/v1/devicestatus.json`

**Comment by xpucuto** [comment]
here it is 

[{"_id":"57f5149bc305130b009e1392","pump":{"pumpID":"417655","battery":{"voltage":1.41,"status":"normal"},"reservoir":105.5,"clock":"2016-10-05T14:53:46Z"},"uploader":{"timestamp":"2016-10-05T14:56:27Z","name":"Anabelita","battery":89},"device":"loop://Anabelita","created_at":"2016-10-05T14:56:27Z"},{"_id":"57f51499c305130b009e1391","device":"loop://Anabelita","loop":{"name":"Loop","recommendedBolus":0.125,"enacted":{"received":true,"duration":30,"timestamp":"2016-10-05T14:56:23Z","rate":1.625},"version":"1.0rc1","timestamp":"2016-10-05T14:56:25Z","iob":{"timestamp":"2016-10-05T14:50:00Z","iob":3.485519441136287},"recommendedTempBasal":{"timestamp":"2016-10-05T14:56:24Z","duration":30,"rate":2.925},"predicted":{"startDate":"2016-10-05T14:55:56Z","values":[213,217,220,221,221,220,216,211,205,200,195,189,184,179,174,169,165,161,157,154,151,148,145,143,141,139,137,135,134,132,130,129,128,127,126,126,126,126]}},"created_at":"2016-10-05T14:56:25Z"},{"_id":"57f51368c305130b009e1390","pump":{"pumpID":"417655","battery":{"voltage":1.41,"status":"normal"},"reservoir":105.6,"clock":"2016-10-05T14:48:40Z"},"uploader":{"timestamp":"2016-10-05T14:51:20Z","name":"Anabelita","battery":89},"device":"loop://Anabelita","created_at":"2016-10-05T14:51:20Z"},{"_id":"57f51365c305130b009e138f","device":"loop://Anabelita","loop":{"name":"Loop","recommendedBolus":0,"enacted":{"received":true,"duration":0,"timestamp":"2016-10-05T14:51:16Z","rate":0},"version":"1.0rc1","timestamp":"2016-10-05T14:51:17Z","iob":{"timestamp":"2016-10-05T14:45:00Z","iob":3.369509586258584},"recommendedTempBasal":{"timestamp":"2016-10-05T14:51:17Z","duration":30,"rate":2.075},"predicted":{"startDate":"2016-10-05T14:50:55Z","values":[212,210,206,203,199,194,190,185,179,174,169,164,159,154,149,145,140,136,133,129,126,123,120,118,116,114,112,111,109,108,106,105,103,102,102,101,101,101]}},"created_at":"2016-10-05T14:51:17Z"},{"_id":"57f51235c305130b009e138e","pump":{"pumpID":"417655","battery":{"voltage":1.41,"status":"normal"},"reservoir":105.9,"clock":"2016-10-05T14:43:33Z"},"uploader":{"timestamp":"2016-10-05T14:46:13Z","name":"Anabelita","battery":89},"device":"loop://Anabelita","created_at":"2016-10-05T14:46:13Z"},{"_id":"57f51211c305130b009e138d","device":"loop://Anabelita","loop":{"name":"Loop","version":"1.0rc1","recommendedBolus":0,"timestamp":"2016-10-05T14:45:37Z","iob":{"timestamp":"2016-10-05T14:40:00Z","iob":3.315125927620089},"predicted":{"startDate":"2016-10-05T14:40:56Z","values":[218,222,226,228,229,227,224,220,214,209,204,199,194,189,184,180,175,170,166,162,159,155,152,149,147,144,142,141,139,137,136,134,133,132,130,129,129,129,128,128]}},"created_at":"2016-10-05T14:45:37Z"},{"_id":"57f511cfc305130b009e138c","pump":{"pumpID":"417655","battery":{"voltage":1.41,"status":"normal"},"reservoir":106,"clock":"2016-10-05T14:41:50Z"},"uploader":{"timestamp":"2016-10-05T14:44:30Z","name":"Anabelita","battery":89},"device":"loop://Anabelita","created_at":"2016-10-05T14:44:30Z"},{"_id":"57f51199c305130b009e138b","device":"loop://Anabelita","loop":{"name":"Loop","version":"1.0rc1","recommendedBolus":0,"timestamp":"2016-10-05T14:43:37Z","iob":{"timestamp":"2016-10-05T14:40:00Z","iob":3.315125927620089},"predicted":{"startDate":"2016-10-05T14:40:56Z","values":[218,222,226,228,229,227,224,220,215,210,205,200,195,190,185,180,176,171,167,164,160,157,154,151,149,146,144,143,141,139,138,137,136,134,133,132,131,131,131,131]}},"created_at":"2016-10-05T14:43:37Z"},{"_id":"57f51170c305130b009e138a","pump":{"pumpID":"417655","battery":{"voltage":1.41,"status":"normal"},"reservoir":106.1,"clock":"2016-10-05T14:40:15Z"},"uploader":{"timestamp":"2016-10-05T14:42:56Z","name":"Anabelita","battery":89},"device":"loop://Anabelita","created_at":"2016-10-05T14:42:56Z"},{"_id":"57f51148c305130b009e1389","device":"loop://Anabelita","loop":{"name":"Loop","version":"1.0rc1","recommendedBolus":0,"timestamp":"2016-10-05T14:42:16Z","iob":{"timestamp":"2016-10-05T14:40:00Z","iob":3.236375927620081},"predicted":{"startDate":"2016-10-05T14:40:56Z","values":[218,222,226,228,229,227,225,220,215,210,205,200,195,191,186,182,177,173,169,165,162,159,156,153,151,148,146,145,143,142,140,139,138,137,135,134,134,134,134]}},"created_at":"2016-10-05T14:42:16Z"}]

**Comment by jasoncalabrese** [comment]
Resolved by #2047
