### ISSUE TITLE
Treatments BG Check is not shown in mmol/l

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#2045]
When I create a treatments report the BG Check is not shown in mmol/l but in mg/dL.
For example with a finger prick from the Medtronic pump.
##

**Comment by PieterGit** [comment]
Screenshot 
![image](https://cloud.githubusercontent.com/assets/6500826/19221568/1dc2d51a-8e46-11e6-85fe-963f9103a9de.png)

**Comment by jasoncalabrese** [comment]
Short of fixing the issue in oref0 I wonder if we can do something on the NS side by assuming the value is mgdl if it's > than 30 and then converting to mmol

**Comment by ELUTE** [comment]
+1 I have this issue as well

**Comment by MilosKozak** [comment]
try it now

**Comment by PieterGit** [comment]
Issue still exists. Lets put it on the list for 0.12.x
