### ISSUE TITLE
Authentication role / denied

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#2084]
1) Setting a user with "denied" as the role... using that link in a browser still brings up a fully-readable site.

2) Editing an existing user and changing the role to "denied" also still brings up a fully readable-site. 

[Documenting authentication roles for Nightscout.info]
##

**Comment by jasoncalabrese** [comment]
Need to first set the overall default roles to denied
`AUTH_DEFAULT_ROLES="denied"

Then you create subjects/tokens, with additional permission such as readable or careportal

**Comment by jasoncalabrese** [comment]
But sure if that made sense, roles can only ADD permissions, they can't remove, so denied only works if `AUTH_DEFAULT_ROLES="denied"` is set.

I think showing the default roles on the admin page and hiding the disabled role in that case will help.

**Comment by oamyoamy** [comment]
If you set AUTH_DEFAULT_ROLES="denied" -- are you also blocking upload? For someone wanting to start with a baseline of "denied" so that all viewers require roles/tokens, do they also need to set devicestatus-upload?

AUTH_DEFAULT_ROLES="denied devicestatus-upload"

?

**Comment by jasoncalabrese** [comment]
If the uploader is correctly passing the api-secret setting `AUTH_DEFAULT_ROLES="denied"` won't block access, but for some older uploaders they'll need `devicestatus-upload` also, but that can be combined with `denied`

**Comment by oskarpearson** [comment]
I'm closing this, since things are working as described for me. Please let us know if you need any more detail here. Thanks!
