### ISSUE TITLE
Care portal temp target proposes 80 for Eating Soon, when server is in mmol mode 

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#2093]
When I set a temp target it proposes 80

![image](https://cloud.githubusercontent.com/assets/6500826/19413241/e8d8878c-9327-11e6-873e-f63218601e7c.png)

which is fine in mg/dL mode, but I would assume that when you have your server in mmol mode it would propose 4.5 mmol/l
##

**Comment by PieterGit** [comment]
The targets don't accept mmol values, and make the cell red:

![image](https://cloud.githubusercontent.com/assets/6500826/19413286/ffa58edc-9328-11e6-910d-3e8de7845fee.png)


The corresponding tooltip also does not use mmol mode

![image](https://cloud.githubusercontent.com/assets/6500826/19413291/17f87b70-9329-11e6-83ab-716da794ea2d.png)

**Comment by jasoncalabrese** [comment]
I was thinking of a way to customize the temp targets, maybe we can combine that with mmol support.  I think we'll need to store the treatment with mg/dl values since that's what oref0 will expect

**Comment by ELUTE** [comment]
+1, I have this issue as well

**Comment by PieterGit** [comment]
@sulkaharo fixed this with https://github.com/nightscout/cgm-remote-monitor/pull/3670
I can confirm that it works. This will be released with Nightscout 0.10.3 release.

@ELUTE : please give latest `dev` branch a try to help testing this next Nightscout release.

**Comment by sulkaharo** [comment]
Let’s create a separate ticket for configurability

**Comment by d3xr** [comment]
Is it work now? Temp target in mg/dl is terrible!
