### ISSUE TITLE
Deploy to azure / mongo collection

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#2126]
The deploy to azure screen really needs to have the mongo_collection field.

While the default (now) is "entries," anyone using this form who already has a setup may have a custom-named collection. If they can't enter this info on the main screen when using Deploy to Azure, we have to instruct them to then go into azure and set it after deployment to continue using their collection.

It would be easier to have this on the form with a note to NOT specify it unless they already have a collection named something other than "entries"
##

**Comment by MilosKozak** [comment]
How many poeple could use this feature? I think if you have NS already installed you do only update ....
It's really simple to add it but we should not do it more complicated for 1st time users.

thoughts?

**Comment by jasoncalabrese** [comment]
I'm working on a branch that will deprecate the old `MONGO_*` envs, preferred with be `STORAGE_URI` and `ENTRIES_COLLECTION` but it will maintain backwards compatibility with the old ones.

**Comment by oamyoamy** [comment]
To answer Milos' question... there are _many_ cases in which existing users have to create a new website -- and they now may use this new feature to simplify deployment. If the reality is that the deployment form doesn't allow them to enter their collection name... we just won't recommend the feature. If they know about it and do this, however, there will be confusion unless they catch a support person who realizes this variable needs to be manually entered.

**Comment by baembel08** [comment]
Hi, I'm testing the parameter and make a request for updating the dev branch.
