### ISSUE TITLE
No sound alarms

### ISSUE THREAD

**Issue by getek-nightscout** [nightscout/cgm-remote-monitor#2136]
Alarms are properly triggered by the BG value (BG value background is getting yellow) but there's no sound. Only "urgent" alarms give sound (urgent for low bg, high bg, and stale data)
Clicking "alarm test" works fine.
This issue appears on Samsung Smart TV browser.
##

**Comment by RRS10** [comment]
I am having a similar issue.  I am getting alarms on highs just not lows.  I tried to go back through the setup and reload everything.  Still no luck.

**Comment by jarmfl** [comment]
Stale data warning and urgent is not trigger any sound.
