### ISSUE TITLE
Glucose Values Depiction - URGENT

### ISSUE THREAD

**Issue by mdomox** [nightscout/cgm-remote-monitor#2154]
While the mongoDB value in "entries" collection is: 
{
    "_id": {
        "$oid": "580f2fc91374dbfc3ac32e60"
    },
    "date": 1477390230000,
    "dateString": "2016-10-25T10:10:30.000Z",
    "rssi": 100,
    "device": "glimp://libre/0M0000G6YLH",
    "direction": "FortyFiveDown",
    "rawbg": 68,
    "sgv": 66,
    "type": "sgv"
}

The depiction shows 120 : 
[screenshot2.docx](https://github.com/nightscout/cgm-remote-monitor/files/550492/screenshot2.docx)

**Comment by sulkaharo** [comment]
What's your time zone setting in Nightscout? The data point stored at 10:30 UTC time in the database is only drawn to the 10:30 point in the timeline if your website runs in the UTC time zone.

**Comment by mdomox** [comment]
30 minutes ago: 

 },
    "date": 1477398750000,
    "dateString": "2016-10-25T12:32:30.000Z",
    "rssi": 100,
    "device": "glimp://libre/0M0000G6YLH",
    "direction": "Flat",
    "rawbg": 105,
    "sgv": 117,
    "type": "sgv"
}

[screenshot3.docx](https://github.com/nightscout/cgm-remote-monitor/files/550635/screenshot3.docx)

And without doing anything the values are consistent. 

The weird is that this issue does not appear 100% of the times.

**Comment by sulkaharo** [comment]
The new screenshot shows the 13:40 mark where indeed the graph shows points around 120. There's points at 66 just before this though, which makes me wonder what's up, wonder if there's multiple overlapping records for the timestamp.

**Comment by sulkaharo** [comment]
(Also, can you post screenshots as images, the word documents are pretty difficult to view.)

**Comment by mdomox** [comment]
13.00 is when the false data stopped appearing (data that are not in the database)

![new bitmap image](https://cloud.githubusercontent.com/assets/2255012/19688295/d791e098-9ad1-11e6-8a40-e519193f8a3b.jpg)

**Comment by sulkaharo** [comment]
Right, to reinterate: which time zone are you in? The timestamp stored in the database is NOT the time for which the data is SHOWN.

In the first record, "dateString": "2016-10-25T10:10:30.000Z", means the record is stored for October 25th 10:10:30 in the UTC time zone. Based on the screenshots it looks like you're in the UTC+3 time zone, so the first record would be for 13:10 in your time, which is the moment where your screenshot shows the plot showing the data at 66, which is correct.

**Comment by mdomox** [comment]
Yes, the timezone is UTC+3 . You are correct. The entry for 12.59 UTC+3 is: 
{
    "_id": {
        "$oid": "580f2da11374dbfc3ac32e44"
    },
    "date": 1477389570000,
    "dateString": "2016-10-25T09:59:30.000Z",
    "rssi": 100,
    "device": "glimp://libre/0M0000G6YLH",
    "direction": "NOT COMPUTABLE",
    "rawbg": 79,
    "sgv": 125,
    "type": "sgv"
}

Since I had configured to "always show raw data" and since there was one plot I had the impression that the rawbg should be depicted. You are saying that this is not the case?
