### ISSUE TITLE
Error: Cannot find module 'q'

### ISSUE THREAD

**Issue by dinnouti** [nightscout/cgm-remote-monitor#2183]
I was trying to deploy following this steps "http://www.nightscout.info/wiki/welcome/monitor-cgm-web", when the install was done the browser was showing a 500 error. Looked at Azure log and found this error:

```
Merge pull request #2090 from baembel08/patch-1 Update language.js

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'scm-commit-id.json'
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 7.0.0.
Selected node.js version 0.10.40. Use package.json file to choose a different version.
Selected npm version 1.4.28
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN package.json mongodb@2.1.18 No README data

> Nightscout@0.9.0 postinstall D:\home\site\wwwroot
> node node_modules/bower/bin/bower --allow-root install


module.js:340
    throw err;
          ^
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Nightscout@0.9.0 postinstall: `node node_modules/bower/bin/bower --allow-root install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Nightscout@0.9.0 postinstall script.
npm ERR! This is most likely a problem with the Nightscout package,
npm ERR! not with npm itself.
An error has occurred during web site deployment.
npm ERR! Tell the author that this fails on your system:
npm failed
npm ERR!     node node_modules/bower/bin/bower --allow-root install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Nightscout
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
npm WARN package.json mongodb@2.1.18 No README data

module.js:340
   throw err;
         ^
         Error: Cannot find module 'q'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   
   npm ERR! Nightscout@0.9.0 postinstall: `node node_modules/bower/bin/bower --allow-root install`
   npm ERR! Exit status 8
   npm ERR! 
   npm ERR! Failed at the Nightscout@0.9.0 postinstall script.
   npm ERR! This is most likely a problem with the Nightscout package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node node_modules/bower/bin/bower --allow-root install
   npm ERR! You can get their info via:
   npm ERR!     npm owner ls Nightscout
   npm ERR! There is likely additional logging output above.
   npm ERR! System Windows_NT 6.2.9200
   npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.40\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
   npm ERR! cwd D:\home\site\wwwroot
   npm ERR! node -v v0.10.40
   npm ERR! npm -v 1.4.28
   npm ERR! code ELIFECYCLE
   npm
   D:\Program Files (x86)\SiteExtensions\Kudu\58.51026.2494\bin\Scripts\starter.cmd bash deploy.sh

```

**Comment by LoriLori** [comment]
It is just bad luck on Azure, sometimes it doesn't work :(

**Comment by LoriLori** [comment]
You can do these manual steps you can fix

> node node_modules/bower/bin/bower --no-color install
D:\home\site\wwwroot
module.js:327
    throw err;
    ^

Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


> cd node_modules
D:\home\site\wwwroot\node_modules

> cd bower
D:\home\site\wwwroot\node_modules\bower

> npm install
D:\home\site\wwwroot\node_modules\bower

> cd .. 
D:\home\site\wwwroot\node_modules

> cd ..
D:\home\site\wwwroot

> node node_modules/bower/bin/bower --no-color install
D:\home\site\wwwroot
module.js:327
    throw err;
    ^

Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\lib\bin\bower.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


> cd node_modules
D:\home\site\wwwroot\node_modules

> cd bower
D:\home\site\wwwroot\node_modules\bower

> dir
D:\home\site\wwwroot\node_modules\bower
Volume in drive D is Windows
 Volume Serial Number is 183C-D95A

 Directory of D:\home\site\wwwroot\node_modules\bower

11/16/2016  12:19 AM    <DIR>          .
11/16/2016  12:19 AM    <DIR>          ..
11/16/2016  12:19 AM    <DIR>          bin
11/16/2016  12:19 AM            40,418 CHANGELOG.md
11/16/2016  12:19 AM    <DIR>          lib
11/16/2016  12:19 AM             1,074 LICENSE
11/16/2016  12:19 AM               353 package.json
11/16/2016  12:19 AM             4,802 README.md
               4 File(s)         46,647 bytes
               4 Dir(s)     778,207,232 bytes free


> cd lib
D:\home\site\wwwroot\node_modules\bower\lib

> dir
D:\home\site\wwwroot\node_modules\bower\lib
Volume in drive D is Windows
 Volume Serial Number is 183C-D95A

 Directory of D:\home\site\wwwroot\node_modules\bower\lib

11/16/2016  12:19 AM    <DIR>          .
11/16/2016  12:19 AM    <DIR>          ..
11/16/2016  12:19 AM    <DIR>          bin
11/16/2016  12:19 AM    <DIR>          commands
11/16/2016  12:19 AM             1,629 config.js
11/16/2016  12:19 AM    <DIR>          core
11/16/2016  12:19 AM               634 index.js
11/16/2016  12:20 AM    <DIR>          node_modules
11/16/2016  12:19 AM    <DIR>          renderers
11/16/2016  12:19 AM    <DIR>          templates
11/16/2016  12:19 AM    <DIR>          util
11/16/2016  12:19 AM               116 version.js
               3 File(s)          2,379 bytes
               9 Dir(s)     778,194,944 bytes free


> cd node_modules
D:\home\site\wwwroot\node_modules\bower\lib\node_modules

> dir
D:\home\site\wwwroot\node_modules\bower\lib\node_modules
Volume in drive D is Windows
 Volume Serial Number is 183C-D95A

 Directory of D:\home\site\wwwroot\node_modules\bower\lib\node_modules

11/16/2016  12:20 AM    <DIR>          .
11/16/2016  12:20 AM    <DIR>          ..
11/16/2016  12:19 AM    <DIR>          align-text
11/16/2016  12:19 AM    <DIR>          amdefine
11/16/2016  12:19 AM    <DIR>          ansi-escapes
11/16/2016  12:19 AM    <DIR>          ansi-regex
11/16/2016  12:19 AM    <DIR>          ansi-styles
11/16/2016  12:19 AM    <DIR>          ansicolors
11/16/2016  12:19 AM    <DIR>          archy
11/16/2016  12:19 AM    <DIR>          array-filter
11/16/2016  12:19 AM    <DIR>          array-find-index
11/16/2016  12:19 AM    <DIR>          array-map
11/16/2016  12:19 AM    <DIR>          array-reduce
11/16/2016  12:19 AM    <DIR>          asn1
11/16/2016  12:19 AM    <DIR>          assert-plus
11/16/2016  12:19 AM    <DIR>          async
11/16/2016  12:19 AM    <DIR>          aws-sign2
11/16/2016  12:19 AM    <DIR>          balanced-match
11/16/2016  12:19 AM    <DIR>          bcrypt-pbkdf
11/16/2016  12:19 AM    <DIR>          binary
11/16/2016  12:19 AM    <DIR>          bl
11/16/2016  12:20 AM    <DIR>          boom
11/16/2016  12:20 AM    <DIR>          bower-config
11/16/2016  12:20 AM    <DIR>          bower-endpoint-parser
11/16/2016  12:20 AM    <DIR>          bower-json
11/16/2016  12:20 AM    <DIR>          bower-logger
11/16/2016  12:20 AM    <DIR>          bower-registry-client
11/16/2016  12:19 AM    <DIR>          junk
               0 File(s)              0 bytes
              28 Dir(s)     778,186,752 bytes free


> npm -v
D:\home\site\wwwroot\node_modules\bower\lib\node_modules
2.15.8


> cd ..
D:\home\site\wwwroot\node_modules\bower\lib

> cd ..
D:\home\site\wwwroot\node_modules\bower

> dir
D:\home\site\wwwroot\node_modules\bower
Volume in drive D is Windows
 Volume Serial Number is 183C-D95A

 Directory of D:\home\site\wwwroot\node_modules\bower

11/16/2016  12:19 AM    <DIR>          .
11/16/2016  12:19 AM    <DIR>          ..
11/16/2016  12:19 AM    <DIR>          bin
11/16/2016  12:19 AM            40,418 CHANGELOG.md
11/16/2016  12:19 AM    <DIR>          lib
11/16/2016  12:19 AM             1,074 LICENSE
11/16/2016  12:19 AM               353 package.json
11/16/2016  12:19 AM             4,802 README.md
               4 File(s)         46,647 bytes
               4 Dir(s)     778,166,272 bytes free


> npm un
D:\home\site\wwwroot\node_modules\bower
npm WARN uninstall not installed in D:\local\AppData\npm\node_modules: "bower"


> npm install
D:\home\site\wwwroot\node_modules\bower

> npm install >log
D:\home\site\wwwroot\node_modules\bower

> cat log
D:\home\site\wwwroot\node_modules\bower

> npm install 2>log
D:\home\site\wwwroot\node_modules\bower

> cat log
D:\home\site\wwwroot\node_modules\bower

> rm lib
D:\home\site\wwwroot\node_modules\bower
rm: cannot remove 'lib': Is a directory


> rm -rf lib
D:\home\site\wwwroot\node_modules\bower

> npm install
D:\home\site\wwwroot\node_modules\bower

> cd ..
D:\home\site\wwwroot\node_modules

> cd ..
D:\home\site\wwwroot

> npm install
D:\home\site\wwwroot
npm WARN engine share2nightscout-bridge@0.1.4: wanted: {"node":"~0.10.0"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN engine minimed-connect-to-nightscout@1.1.0: wanted: {"node":"0.10.x"} (current: {"node":"4.4.7","npm":"2.15.8"})


> node node_modules/bower/bin/bower --no-color install
D:\home\site\wwwroot
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/bin/bower'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\bower\bin\bower:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)


> pwd
D:\home\site\wwwroot
/d/home/site/wwwroot


> npm install bower
D:\home\site\wwwroot
bower@1.8.0 node_modules\bower


> node node_modules/bower/bin/bower --no-color install
D:\home\site\wwwroot
bower jQuery-Storage-API#~1.7.2     invalid-meta for:D:\local\Temp\WORKGROUP-RD00155D806A57$\bower\1a5e58287ea29bb2e2d5a316742060d1-6692-k263l5\bower.json
bower jQuery-Storage-API#~1.7.2     invalid-meta The "description" is too long, the limit is 140 characters
bower jquery-flot#0.8.3             invalid-meta for:D:\local\Temp\WORKGROUP-RD00155D806A57$\bower\28b67880290306543efb86ebf5d97e19-6692-o9U2A9\component.json
bower jquery-flot#0.8.3             invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower jquery-flot#0.8.3               deprecated Package jquery-flot is using the deprecated component.json


>

**Comment by LoriLori** [comment]
Also there is a solution in https://github.com/nightscout/cgm-remote-monitor/issues/1453

**Comment by jasoncalabrese** [comment]
closing as this is a duplicate
