### ISSUE TITLE
/devicestatus is not able to handle POST collections

### ISSUE THREAD

**Issue by volkerrichert** [nightscout/cgm-remote-monitor#2199]
I did some deep digging into the 640gAndroidUploader and den nightscout source code. the uploader try to submit a collection (maybe just one) of devicestauts update. 

e.g. POST [{"uploaderBattery":96,"device":"medtronic-640g:\/\/6212-1051393","pump":{"clock":"2016-11-06T11:48:30+0100","reservoir":24.575000762939453,"iob":{"timestamp":"Sun Nov 06 11:48:30 MEZ 2016","bolusiob":0.5},"battery":{"percent":50}}}]

It will not be stored. line 8ff:

  function create(obj, fn) {
    if (! obj.hasOwnProperty('created_at')){
      obj.created_at = (new Date()).toISOString();
    }
   ...

**Comment by jasoncalabrese** [comment]
It's possible that the api secret isn't being sent, if you look at the Nightscout log (in papertrail if your using heroku or at YOURSITE.scm.azurewebsites.net) do you see DENIED messages for the upload?

Also check that you have a current version of the 640gAndroidUploader

**Comment by volkerrichert** [comment]
i use the latest version of 640guploader und the secret is set. Bulk upload of sgv works fine.... 

If you take a look at doPost (https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/api/devicestatus/index.js#L33-L42) the body will be passed directly into devicestatus.create (https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/devicestatus.js#L8-L16) which only handle one object.

If you compare it to entries (https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/entries.js#L81-L99) you'll see that it loops over an array.
