### ISSUE TITLE
Shaded areas not confined to times assigned

### ISSUE THREAD

**Issue by tatigger** [nightscout/cgm-remote-monitor#2224]
Shaded areas for Temporary Target and Exercise do not remain confined to their assigned time areas, and expand to fill other areas or re-appear at times they were not created for.  The data displayed when you hover over the shaded area is correct.  For example, an Eating Soon Temporary Target set at 12:45 for target of 80 for 60 minutes might expand to cover 12:45 to 2:30, or extend into future even though the time interval has ended.  Or an Exercise entry "walk dog" of 30 minutes from yesterday might appear on this morning's graph.  This occurs on the webpage accessed from my MacBook via Safari, and on my IPhone via Safari.  I use Grilled Cheese and XDrip+.  Thank you

**Comment by jasoncalabrese** [comment]
@MilosKozak have you seen this issue?  The transition doesn't seem to be working with any treatments with durations
