### ISSUE TITLE
Ignore pump-reported IOB if Loop IOB is available

### ISSUE THREAD

**Issue by mddub** [nightscout/cgm-remote-monitor#2227]
When using the IOB pill + Loop + an x23 pump, a devicestatus with MySentry pump-reported IOB may take precedence over a devicestatus with Loop IOB because the timestamp on the MySentry IOB is more recent. Here's an example:

https://gist.github.com/mddub/a34f980c7124ef3f719aa38ff14516ff

The issue is here:

https://github.com/nightscout/cgm-remote-monitor/blob/00b93d5/lib/plugins/iob.js#L95-L112

Simplest solution I can think of is to explicitly prioritize any Loop status over any pump status in `lastIOBDeviceStatus`. Something like:

```diff
--- a/lib/plugins/iob.js
+++ b/lib/plugins/iob.js
@@ -56,15 +56,18 @@ function init() {
     }
     var futureMills = time + times.mins(5).msecs; //allow for clocks to be a little off
     var recentMills = time - iob.RECENCY_THRESHOLD;
-    return  _.chain(devicestatus)
+    var iobs =  _.chain(devicestatus)
       .map(iob.fromDeviceStatus)
       .reject(_.isEmpty)
       .filter(function (iobStatus) {
         return iobStatus.mills <= futureMills && iobStatus.mills >= recentMills;
       })
-      .sortBy('mills')
-      .last( )
-      .value( );
+      .sortBy('mills');
+    // Loop uploads both Loop IOB and pump-reported IOB, so prioritize Loop IOB if available
+    var loopIOBs = iobs.filter(function (iobStatus) {
+      return iobStatus.source === 'Loop';
+    });
+    return loopIOBs.last().value() || iobs.last.value();
   };

   iob.fromDeviceStatus = function fromDeviceStatus(devicestatusEntry) {
```

Better ideas?

**Comment by jasoncalabrese** [comment]
That makes sense and explains some of the issues I've heard about with Loop iob not showing. 

An other option is to set the iob property in the openaps and loop plugins and not have the iob plugin even look at devicestatus.

**Comment by dm61** [comment]
With 523 pump, I've had issues with IOB pill showing pump's IOB instead of Loop's IOB. With iob.lastIOBDeviceStatus modified as @mddub suggested, the IOB pill correctly displays Loop's IOB. The fix is Loop specific, however. I do not know if there are similar issues with openaps.

**Comment by jasoncalabrese** [comment]
We don't upload pump iob from openaps

**Comment by jasoncalabrese** [comment]
@dm61 @mddub want to send a PR for this?

I noticed a type in the diff above the `()`'s were missing from `iobs.last` in `return loopIOBs.last().value() || iobs.last().value();`

**Comment by dm61** [comment]
Just did a PR to dev. Tested the code on my NS for several days, have not noticed any problems, Loop IOB correctly reported in NS IOB pill. Warning: I am very new to all this, hope I have not messed up anything. Thank you @mddub and @jasoncalabrese
