### ISSUE TITLE
Help! Is it Possible?

### ISSUE THREAD

**Issue by jungyu2** [nightscout/cgm-remote-monitor#2241]
Hello~

I'm diabetes patient type I, and Korean.
Well my english skill is very low so Maybe there is a lot of misinterpretation in writing with the help of Google translator.

Can I store data in mongoDB via the cgm-remote-monitor program via the azure website, like Glimp in my diabetes diary application?
My diary diary application is made available for both Android / iPhone / PC.
Libre sensor tagging is also available (only Android)

You can access the mongo DB to import the data, but if you do, you want to build it easily because you have to input a lot of parts.
Many people in Korea know NightScout.
I would like to do so for comfort and stability of blood sugar without commercial purpose.

I have been using cgm-remote-monitor for some time now.
Thanks for reading.

**Comment by oskarpearson** [comment]
Hi

I apologise if I'm answering the wrong question here! My understanding is that you've written a diabetes application, and you'd like to be able to push data to the cgm-remote-monitor program.

If my assumption about the situation is correct, then the answer is yes - you can. Nightscout includes an API for storing glucose values, carbohydrate values, and other such things. OpenAPS, Loop, and numerous other apps use them to upload. Nightscout provides a REST api.

Although there are ways to upload directly to MongoDB, you should no longer use them. Nightscout is transitioning away from them.

I may be wrong, but so far as I know there's not a formal API definition. http://www.nightscout.info/wiki/labs/mongodb-upgrade-to-3-0 Provides provides a bit of overview info about the transition to the new API.

https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/entries.js has some example code that may be relevant, as is https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/treatments.js 

Hope that helps. Please let me know if I've headed off on the wrong track with your question!
