### ISSUE TITLE
Reports not including Insulin Treatments despite showing on NS Home Page

### ISSUE THREAD

**Issue by kskandispersonal** [nightscout/cgm-remote-monitor#2242]
I noticed that my NS Report does not include all of my insulin treatments. The insulin shows on the NS site home page graph, but if I select Today - Show under Reports, two of the overnight insulin treatments are not included, nor are they included in the Bolus Insulin total, or on the Treatments Report page.

If I tick the IOB option on the Reports page, I do see that the two, missing insulin treatments are detected in IOB but the insulin labels are not displayed for these two, nor are they included in the total bolus insulin for the day.
![missinginsulintreatmentsinreports](https://cloud.githubusercontent.com/assets/16564065/20490925/b042cb9e-afdd-11e6-9784-a815bf49175e.PNG)

**Comment by kskandispersonal** [comment]
Here are the treatments from my mongoDB.  The two missing treatments, 0.55U and 0.45U, exist in the DB.
![missinginsulintreatmentsinreports-mongdb](https://cloud.githubusercontent.com/assets/16564065/20491591/e02b98d4-afdf-11e6-9248-50fa5481add2.PNG)

**Comment by kskandispersonal** [comment]
I included all treatments for today so that you could see that some indeed are displaying correctly.  The only ones that are NOT displaying in Reports are the following:
"created_at":"2016-11-21T01:46:02-0500"
"created_at":"2016-11-21T00:35:01-0500"

[missingTreatments.txt](https://github.com/nightscout/cgm-remote-monitor/files/604674/missingTreatments.txt)

**Comment by jasoncalabrese** [comment]
Is the timezone set in your NS treatment profile, if it's off that might be a possible cause

**Comment by kskandispersonal** [comment]
Timezone is set correctly in the NS Profile Editor.  Is there a separate timezone setting specifically for treatment profile?

**Comment by sulkaharo** [comment]
This should now be fixed in release 0.12
