### ISSUE TITLE
Integrate the simpancreas predictor

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#2244]
@bustavo

Port the ruby code from https://github.com/bustavo/simpancreas_predictor to JS and setup a NS plugin.

Should the plugin use an external dependency for the core predictor?  Or do the full ruby to JS port with in the plugin.

When the plugin is enabled you'll be able to show the forecast along with the AR2, OpenAPS, and Loop forecasts.

**Comment by bustavo** [comment]
I think I will go with doing the port to JS... Ruby is resource intensive & the other predictors are in JS from what I understand right?

I already created a branch, will work on it these following days and publish it as soon as I have the same results on both versions.

Where can I find the code from the nightscout predictors? I've never used nightscout and have no idea about its structure, organization, etc.

**Comment by jasoncalabrese** [comment]
In the NS plugin we can adjust the structure to match your predictor, but the in memory data will look like this (without other fields you don't use):

```
[
  {mgdl: 104, mills: 1479785500000} //oldest
  , {mgdl: 103, mills: 1479785800000}
  , {mgdl: 102, mills: 1479786100000}
  , {mgdl: 101, mills: 1479786700000}
  , {mgdl: 100, mills: 1479787000000} //most current
]
```

**Comment by jasoncalabrese** [comment]
https://github.com/bustavo/simpancreas_predictor/issues/1

**Comment by bustavo** [comment]
I think you can use the following function from bustavo/simpancreas_predictor/ ( javascript_port branch )

`bg_prediction(periods,cur_bg,bg_array,bg_date_array,time)`

With the above example, I think it could be something like:

bg_prediction(4,100,[104,103,102,101],[1479785500000, 1479785800000, 1479786100000, 1479786700000], 1479787000000)

Just need to make sure the mills date format is equal to
`new Date().getTime()`
