### ISSUE TITLE
Alexa response includes direction "NONE" when it should be an empty string

### ISSUE THREAD

**Issue by ryanpacker** [nightscout/cgm-remote-monitor#2268]
In my NS setup, when I ask Alexa any questions that would result in a sensor glucose value being returned, the text "NONE" is being added to the response (ie: 87NONE as of 3 minutes ago). In looking at the code, it appears that if none of the directions {Flat | SingleUp | Single Down | etc} are matched, `direction = records[0].direction;`. There's no attempt to see if `records[0].direction` exists. I suspect it doesn't, so directions is set to null and then converted to the string 'NONE'. I don't see the point of setting direction if it doesn't match a known value, but I am admittedly very unfamiliar with both the code base. I'm also new and unfamiliar to participating and contributing to an open source project, so please set me straight if I'm going about this all wrong.

**Comment by jasoncalabrese** [comment]
fixed with #2279 and on dev now
