### ISSUE TITLE
no night alarms

### ISSUE THREAD

**Issue by r0ller** [nightscout/cgm-remote-monitor#2271]
Hi All,

We're using nightscout with a 640g since august and everything went fine till a few weeks ago. The night alarms have just disappeared -both low and high. Interestingly enough, during the day, when the kid is in school, they set off appropriately. The issue also appears on my laptop with two different browsers (win7+IE11/Opera41) and on our android phones (jelly bean and marshmallow) with chrome. So I synced today my fork on github with the upstream master but as far as I can see now (it's 23:13 now and no alarm set off but nightscout shows 254mg/dl) the situation hasn't changed. Just wanted to ask before digging in the code if anyone has experienced the same?

Thanks&regards,
r0ller

**Comment by ryanpacker** [comment]
I'm new to all this, and likely not much help, but I'm trying to dive in head first and will offer what I can. 

I haven't experienced any issues with alarms, but a few questions might help zero in on what's going on:
- where are you running Nightscout? 
- can you confirm you're on 0.9.1 (scroll to bottom of settings panel)?
- what alarm related settings do you have (and by extension, which alarms do you have turned on)? 
- when you say night alarms have disappeared, do you mean just in the NS UI, or just Pushover notifications, or both, or something entirely different?

I'm not sure, but if I had this issue, I'd check out the logs on Azure (if that's where you're running). You may already be well aware, but you can turn on verbose logging under Settings > Monitoring > Diagnostic logs. 
![image](https://cloud.githubusercontent.com/assets/3837984/20653450/d63dcfd2-b4ca-11e6-8201-b00cba7dd87b.png)
Once making that change, you can view the logs immediately under Settings > Monitoring > Log stream. There may be information in the logs that could help diagnose what's going on. 

Wish I could be more help. Good luck.

**Comment by r0ller** [comment]
Hi Ryan,

Thanks for the questions. The answers are:

- NS runs on Azure.
- Yes, we 're on 0.9.1.
- All alarms are turned on: urgent high, high, low, urgent low, stale warn, stale urgent. Concerning alarm related settings, I've just realised that the target range is set to 0/0 which may explain why the alarms don't set off in 0.9.1 (if the alarms are now tied to them) but afaik those alarm related limits were hardcoded in the earlier version I had (forked NS on 31.07) so it doesn't explain why they didn't work for that version. But it's weird anyway that during the day everything worked but not during the night.
- I meant the NS UI related alarms. We don't yet use pushover but it's a good idea to start using that as well.

I'll check if setting now the target range changes anything. If not, I'll look at the logs. Thanks again!

Best regards,
r0ller

**Comment by sulkaharo** [comment]
Have you enabled the BWP plugin? The plugin silences high alarms if you mark boluses into Nightscout and the calculated IOB is high enough to cover the high glucose.

**Comment by r0ller** [comment]
No, no plugins are enabled at all. By the way, setting the target range hasn't changed anything.

**Comment by jasoncalabrese** [comment]
If you test the alarm with the speaker icon does it work?  On mobile browsers, and maybe some others you need user action to first enable the mp3 to play.

**Comment by r0ller** [comment]
Just as feedback: the setting for the BG_ values didn't change anything. What I also noticed, since I synced my fork with the new version of NS there's no alarm at all, neither during the day nor during the night. Interestingly enough, stale data warnings work:) This answers Jason's questions as well: the alarm otherwise would work e.g. when I test the alarm with the speaker icon, it works as well. I don't know if this adds anything to it but I thought it may be important: it's not that only the alarm sound is not played, the warning itself isn't triggered. I mean the BG number isn't highlighted in yellow or red either.

**Comment by oskarpearson** [comment]
Hi. This isn't a definitive answer, unfortunately, But since re-syncing my (old) fork over the weekend (to the dev branch) I've started receiving many alerts that I wasn't before. Perhaps it's worth a try updating all the way?

**Comment by r0ller** [comment]
@oskarpearson: Thanks, I'll check it out the weekend. However, the day before yesterday something strange happened: suddenly I got one low alarm on the laptop but since then nothing again. Yesterday, I slept with the laptop next to me but it gave no high alarms although it had its chances to do so.

**Comment by oskarpearson** [comment]
@r0ller Since we've not heard back in a while, I'm closing this issue. Please re-open it if you're still having problems with the latest version. Thanks!

**Comment by l1s2-jpg** [comment]
I follow my boyfriend on his url on my android phone. Is it supposed to be normal that I get the alarms only if I go to the url(open it)? I tried to make a widget so that I can get the alarms, but I don't know how to do it. We are on Heroku...

**Comment by unsoluble** [comment]
Yes, that is normal. Nightscout by itself is not able to send alarms if it's not actively running in a browser. You can set up Pushover or IFTTT (both described in the [Readme](https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md) if you want true push notifications.
