### ISSUE TITLE
Low Alarm Not Working

### ISSUE THREAD

**Issue by denvergail** [nightscout/cgm-remote-monitor#233]
Overnight last night, BG was <80 for an extended period.  Rose to over 80, then back down again for a few hours.  The low alarm never went off.  I asked someone else to verify on their computer if the alarm was working for them viewing my site.  It was not.  

I was able to look at our computer and verified that the alarm was not working, even though the alarm was enabled and had been open to our site all night.

![screen shot 2014-11-08 at 8 29 44 am](https://cloud.githubusercontent.com/assets/8145371/4965905/952e038a-679d-11e4-9652-be635eb274ac.png)
![screen shot 2014-11-08 at 8 29 50 am](https://cloud.githubusercontent.com/assets/8145371/4965904/9528ddba-679d-11e4-9bbd-bd27833f5238.png)

**Comment by jimsiff** [comment]
Can this be closed now that Dreamsicle is out?

**Comment by denvergail** [comment]
yes
