### ISSUE TITLE
Increased data use with websockets

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#235]
I heard some users have hit data caps post-Cookie Monster updates.  It appears that Cookie Monster uses ~5x Azure data out per idle browser remote monitor with Websockets enabled.  (tested on Mac / Firefox 33, Windows 7 / IE10).  This does not include uncached or cached browser session starts or manual browser refreshes.

I measured a websockets enabled CM site @ ~640 bytes/sec, websockets disabled CM site @ 143 bytes/sec, and a Brownie site @ 140 bytes/sec.  Those figures are from Wireshark for at least 10 minutes per session, filtered with "ip.src == $AZURE_IP" to remove browser ACKs and other client > server overhead from the throughput figures.  

Those figures translate to ~52 MB/day for Websockets, ~11.7 MB/day XHR polling w/ HTTPS, ~11.5 MB/day XHR polling w/ HTTP.

You can download my packet captures from http://bit.ly/1zFlllO

You can test yourselves using the following sites:

http://http-brownie.azurewebsites.net - Brownie 0.4.3
https://https-cookie.azurewebsites.net - CM 0.5.0 w/ Websockets
https://https-cookie-nows.azurewebsites.net - CM 0.5.0 w/o Websockets

All sites use the same Mongo store, my dev/test rig with live data.  Data out for these sites is purely monitoring, no REST uploads.

**Comment by jasoncalabrese** [comment]
fixed way back with 0.5.1
