### ISSUE TITLE
BWP not calculating correctly when using mmol

### ISSUE THREAD

**Issue by ltomovski** [nightscout/cgm-remote-monitor#2351]
Hi
I have set my profile correctly .. note I am using mmol/l
Expected outcome does always uses mg/dl to calculate .. check screen

Nightscout
version 0.9.0-beta3

**Comment by ltomovski** [comment]
https://s24.postimg.org/6nkddzclh/BWP.jpg

**Comment by sulkaharo** [comment]
You need to also set MMOL in the server - set DISPLAY_UNITS = mmol in Azure. @jasoncalabrese we should make the site enforce the mandatory variables.

**Comment by ltomovski** [comment]
great .. thanks .. it did the trick
