### ISSUE TITLE
Alexa says blood glucose is NaN

### ISSUE THREAD

**Issue by monkeymankjb** [nightscout/cgm-remote-monitor#2374]
When an Alexa request is made for blood glucose in either the MetricNow or the rollup, alexa/index.js attempts to get the data and the direction and build the status message.

`var status = sbx.scaleMgdl(records[0].sgv) + direction + ' as of ' + moment(records[0].date).from(moment(sbx.time)) + '.';`

If using MMConnect for loading, the data that is loaded is different.  Since the data is missing for records[0].svg and direction (undefined), Alexa states that the BG is Nan.

**Comment by scharfenort** [comment]
Hey all,
is there a fix for?

**Comment by inventor96** [comment]
@monkeymankjb @scharfenort Is this still an issue? If so, a lot of work has been done for the Alexa plugin in #4980, so could you try switching to the `wip/013alpha` branch and testing it to see if the problem exists with the new code?

**Comment by PieterGit** [comment]
Closing issue as it's not updated for more than 2 years. 
New Alexa features/bug fixes should be done on the new Alexa/Google Home codebase of 4980.
@monkeymankjb Please file a new issue if this is still relevant.
