### ISSUE TITLE
NS Site black after an update

### ISSUE THREAD

**Issue by Missdazzle** [nightscout/cgm-remote-monitor#2383]
Cause for the update: pump pillbox: empty, openAPS pillbox: x hours ago or unknown, loop visibly working fine
Tipp from @jbwittmer at this point: go to NS, use the administrator tools and clean up the Mongo DB devicestatus from here

BUT obviously you can´t do that once your NS site is black and deleting the collection devicestatus (plenty of space left though) directly at mLab didn´t help.
My final solution has been: a new fork of the cgm-remote-monitor (changing from dev to master branch on this occasion) and 
a)	disconnecting from Github at Azure and connect to the new fork
b)	At Heroku this wouldn´t help so I set up a new WebApp and did a manual deploy to the new fork.

**Comment by LadyViktoria** [comment]
same problem since a few weeks with the latest dev branch (since version 0.9.2)

**Comment by rkresha** [comment]
Maybe related to the following console error

bundle.js:19 Uncaught TypeError: Cannot read property 'scaleMgdl' of undefined
    at n (bundle.js:19)
    at s (bundle.js:19)
    at Function.n.loadAndWireForm (bundle.js:19)
    at Object.h.load (bundle.js:17)
    at Object.<anonymous> (bundle.js:16)
    at l (bundle.js:9)
    at Object.fireWith [as resolveWith] (bundle.js:9)
    at r (bundle.js:10)
    at XMLHttpRequest.<anonymous> (bundle.js:10)

![image](https://cloud.githubusercontent.com/assets/19247761/21614342/b6651a76-d19e-11e6-8f8b-e42dd5c1fbb4.png)

**Comment by clintonjg** [comment]
Just had the same problem with 0.9.3 dev...
0.9.2 master branch seems to be ok.

**Comment by sulkaharo** [comment]
Quickly checked the code and this looks like the site deployment might have failed or the backend component is down. Did this happen on both Azure and Heroku? Any logs from the server side?

**Comment by clintonjg** [comment]
I only have Azure set up, no Heroku and no logs. Sorry, I'm pretty new at this!

**Comment by Missdazzle** [comment]
Yes, this happened on both Azure and Heroku. I did "view logs" at Heroku (but sorry, no copy) and I can´t say if there was anything wrong as I don´t understand enough but what I can say is that the word "error" did not show up.

**Comment by rkresha** [comment]
Looking through the commits on github it looks like there was at least one that didn't pass the checks

**Comment by LadyViktoria** [comment]
@MilosKozak fixed it in his repo
https://github.com/MilosKozak/cgm-remote-monitor/commit/2e01501d16d43044e719ba7f3b4004b17ca97d13
it works now for me

**Comment by Mackwe** [comment]
I am guessing this is because a "yournssite.com/api/v1/devicestatus.json" only returns the last 10 device statuses. As long as the last OpenAPS rig status is one of them, the pills work. I have no idea where to locate that in the code, so if anyone could change that request to return 15 or 20 statuses, I believe this issue could be closed.
