### ISSUE TITLE
Wrong Date and time in reports

### ISSUE THREAD

**Issue by McHoffi** [nightscout/cgm-remote-monitor#2404]
When i'm opening my Reports it Shows the wrong Date and time in the graphs, f.e. today is the 10th and in the graph which should bei from today, it Shows the Data from the 9th, and the time is also an hour behind, if something is logged at 9pm it is shown at 8pm.
Sorry for my bad english :)

**Comment by MilosKozak** [comment]
usualy caused by wrong timezone setting (in profile, browser etc). You can pm me your site if the problem persist
