### ISSUE TITLE
Reports: Treatments Tab ignoring filters

### ISSUE THREAD

**Issue by rkresha** [nightscout/cgm-remote-monitor#2405]
I'm attempting to filter certain entries where the Notes contain "Low"... and it seems to have no effect on the result set that comes back. Also appears to be ignore "Event Type" as well if not others.. Date range works fine. I see the code finding the entries but it shows all of the results not the filtered result set.

![image](https://cloud.githubusercontent.com/assets/19247761/21857734/1c8329c6-d7ec-11e6-805e-629f2d027400.png)

**Comment by MilosKozak** [comment]
all filters are applied to days.
that means all days containing treatment with 'Low' will be displayed
