### ISSUE TITLE
"Can't find variable: Swagger" when loading https://MY-SITE.com/api-docs.html 

### ISSUE THREAD

**Issue by GlowingApple** [nightscout/cgm-remote-monitor#2420]
I'm trying to look at the API docs to figure out how to get access to iob.  

When I go to https://MY-SITE.com/api-docs.html, enter my site in the URL box and my secret passphrase in the api_secret box nothing happens; the page doesn't change and other than the URL box and api_secret box the page is blank.  Looking at the console, there's an error on line 56 ( "window.swaggerUi = new SwaggerUi(" ) with an error "Can't find variable: Swagger".  

I'm using Safari on macOS Sierra, but I get the same blank page on Firefox as well.  

I mostly just need to know how to access the insulin on board via the API, but can't seem to look it up via the documentation as it looks like the api-docs page may be broken.

**Comment by MilosKozak** [comment]
confirming
