### ISSUE TITLE
Feature Request: Dashboard mode?

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#2454]
(If this is the wrong venue for this kind of request, apologies!)

Am currently using NS as an always-on dashboard device like this:

![img_1705](https://cloud.githubusercontent.com/assets/801582/22866726/e9126c34-f12f-11e6-87ec-a66c86bb491e.JPG)

But it would be even better if we could tweak the settings on this one device to show something more like this:

![ns big](https://cloud.githubusercontent.com/assets/801582/22866735/02b327aa-f130-11e6-998b-f604c9848116.jpg)

Is that something that could be part of NS proper at some point? Or is there a different, more appropriate way to do this — via the API into a third-party dashboard I guess?

Anyway, thanks! :)

**Comment by MilosKozak** [comment]
/clock.html ?

**Comment by unsoluble** [comment]
Oh hello! That's awesome. Doesn't _quite_ render properly in MobileSafari, but I can tweak the CSS now that I know this is there. Thanks a ton! :)

**Comment by unsoluble** [comment]
Just reopening to ask: If I've made a bunch of changes (improvements, I hope) to the clock.html page, should I be submitting somehow for a pull request review? (Apologies, very new to this. :)

**Comment by MilosKozak** [comment]
feel free to PR ;)

**Comment by unsoluble** [comment]
Just gonna walk through that here for safety: Clone the main project to desktop, create a new branch, make changes in that branch, then submit PR?

**Comment by MilosKozak** [comment]
yes

**Comment by unsoluble** [comment]
Hmm. "You may not have permission to access..." on Pull Request.

**Comment by sulkaharo** [comment]
We should link to all the views from somewhere inside the app; any view people can't find by browsing effectively doesn't exist...

**Comment by unsoluble** [comment]
Wait, are there even more views?! Am I missing a doc somewhere that lists these? (Oh hey, radio.html... what the... wow...)
