### ISSUE TITLE
Temp graph and treatments not showing up on latest ver (Master and Dev)

### ISSUE THREAD

**Issue by amazaheri** [nightscout/cgm-remote-monitor#2459]
I am hoping this is just my issue but I cant get the temp basal or treatments rendered with latest build (Both Dev and Master) this was working flawlessly and stopped working. I have confirmed this is not related to number of documents in collections and I can see both showing up on my old NightScout (8.x.x) with no issue.

any thoughts? @jasoncalabrese

**Comment by amazaheri** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8312775/23291907/86dd1eee-fa10-11e6-8a84-939d1f4c4aff.png)
Seems like documents being inserted without id :( Only for treatments collection

**Comment by jasoncalabrese** [comment]
Are you still using documentdb, maybe some compatibility issue

**Comment by sulkaharo** [comment]
Yeah this is pretty weird; the _id is automatically generated by Mongo upon insert. If you're not on documentdb, can you check what version of the Mongo drivers and/or what version of Mongo you're running with and post here?

**Comment by amazaheri** [comment]
Thanks guys! adding @kirillg from DocumentDB team as well.

So I am running Mongo on DocumentDB using Mongo protocol, here is what I have observed:

1) All collections(entries, devicestatus, profile) except **Treatments** work as expected, meaning getting **_id** automatically upon insertion
2) To validate I dropped **Treatments** and saw the same issue after it was auto created by NS, same issue with no **_id**
3) Using MongoChef tool, inserting a document happens successfully we a populated _id
![capture](https://cloud.githubusercontent.com/assets/8312775/23316581/deabca84-fa7f-11e6-8c60-d621bfc738bb.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8312775/23316584/e2b197b2-fa7f-11e6-86ba-75f66fcafb7c.PNG)
![capture3](https://cloud.githubusercontent.com/assets/8312775/23316588/e4fe0244-fa7f-11e6-851a-dba34f1279f3.PNG)

**Comment by Kdisimone** [comment]
can this issue be closed now?  Just checking in....

**Comment by PieterGit** [comment]
@amazaheri This issue has not been updated for a year.
Please let use know if this issue still persist in the latest release of Nightscout.
I'm closing this issue for now. If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
