### ISSUE TITLE
"vagrant up" fails: Couldn't open file [path]/cgm-remote-monitor/precise64

### ISSUE THREAD

**Issue by dduugg** [nightscout/cgm-remote-monitor#247]
Hi,

I was working my way through the Nightscout setup process, and got stuck at the deploying to Azure step (trying to access my site returns a 500 error). I thought I would try cgm-remote-monitor locally on OS X Mavericks. I downloaded Vagrant & VirtualBox, but when I try to execute "vagrant up", I get the following error message:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'precise64' (v0) for provider: virtualbox
    default: Downloading: precise64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/dug/git/cgm-remote-monitor/precise64
```

Please advise.

**Comment by ericmarkmartin** [comment]
Is it worth changing `Vagrantfile`? Also, unrelated but while `README.md` says to run `setup.sh`, I had to run `postinstall.sh`. I know its small but it never hurts to have the README as accurate as possible.
