### ISSUE TITLE
Profile switch

### ISSUE THREAD

**Issue by mdomox** [nightscout/cgm-remote-monitor#2483]
When the profile is switched and each profile has different insulin DIA, the IOB is miscalculated.

**Comment by mdomox** [comment]
![capture0](https://cloud.githubusercontent.com/assets/2255012/23459190/ea59e6a2-fe87-11e6-82d4-ef1dc9782cb4.PNG)
![capture1](https://cloud.githubusercontent.com/assets/2255012/23459191/ea5d1796-fe87-11e6-845a-2192319e4cc6.PNG)

**Comment by MilosKozak** [comment]
do you use openaps?

**Comment by mdomox** [comment]
No, I am not.

**Comment by mdomox** [comment]
The DIA of the Novorapid profile is 2 hours and the DIA of the HUMULIN is 6 hours. In first picture , a treatment of 1.5 Units of Novorapid at 10.50 and 2.5 units of Humuling at 13.50 results in IOB 2.99, where it should not... it should only be 2.50 . In general the system does not behave well if the treatments have mixed DIAs...
