### ISSUE TITLE
Profile editor visibility depends on unrelated plugins

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#2484]
Seems as if certain plugins are required to be enabled before the Profile Editor will appear as a menu choice in the main NS sidebar. Shouldn't it appear if merely "profile" is enabled? There are things in there (like the basal rates in particular) that affect the main NS display without requiring extra plugins — should be able to reach the editor to change those without having to guess at which extra unrelated plugin to enable first.

(Yeah, I know about /profile, but new users won't.)

**Comment by MilosKozak** [comment]
agree. changed in https://github.com/nightscout/cgm-remote-monitor/pull/2496
