### ISSUE TITLE
Memory usage on the server?

### ISSUE THREAD

**Issue by ebarendt** [nightscout/cgm-remote-monitor#2536]
The memory usage of the server keeps growing:

When I started the server, it was 405MB (which seems really high for a newly started server), now two days later it's at 728MB and using almost half the RAM on my VPS. Restarting the server gets it back down. 

Restarting also takes a long time and appears to be printing out the entire history of data points? Is it loading the entire history at startup for some reason?

**Comment by sulkaharo** [comment]
Which Node version are you using? Which version of NS? The system should load the last two days of CGM values and a set of treatments from last couple weeks, so if you're seeing a huge amount of data being loaded, that's not normal. The startup time is probably related to NS packaging and compressing the client side JavaScript libraries, which can take up to 30 seconds or so.

**Comment by ebarendt** [comment]
Node 0.12 from the Docker image at https://github.com/nightscout/nightscout-docker
NS version 0.9.2.

I'll have to check later how far back the data is loaded at startup.

**Comment by ebarendt** [comment]
Ok, the data isn't loaded past 7 days ago at startup, so that's fine.

What's the recommended node version? I realize this 0.12 is pretty old, but I can't find any other recommended version here. 6.10? 7.9? Would that help?

**Comment by sulkaharo** [comment]
There's a separate pull request for upgrading node to 6.1, which is currently blocked due to similar issues.

**Comment by sigmonsays** [comment]
nightscout is running my system out of ram as well. I have had it running for a couple weeks now and memory usage is 300-400MB. Node version v0.10.25. After restart memory shot right back up to 300MB. Is this expected?

How is a weeks worth of data points total 300MB ?

**Comment by ebarendt** [comment]
This is so much better with 0.10.1. Thanks!

**Comment by ebarendt** [comment]
Just kidding. 700MB+ and going strong.

**Comment by tomasboudr** [comment]
NS leaks memory for sure. It crashes the NS app on my iPhone 5s and safari iPad Mini, as well as chrome on my Mac regularly. I have to reopen it and can’t just glance at it like I would like to be able to do.
