### ISSUE TITLE
Performance issue when COB is enabled and using openaps/Loop device status

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#2550]
As reported by @ELUTE here https://github.com/nightscout/cgm-remote-monitor/pull/2071#issuecomment-294202322

**Comment by Kdisimone** [comment]
This appears to be working fine now.  I've had COB pill on in both OpenAPS and Loop use, for over 8 months or so now, and the issue has not reappeared.  I think this can be closed.

**Comment by PieterGit** [comment]
Closing issue. If the issue still exists, please open another issue and link it to this one.
