### ISSUE TITLE
String comparison for future treatments

### ISSUE THREAD

**Issue by cjo20** [nightscout/cgm-remote-monitor#2559]
It looks like future treatments uses a string comparison to work out whether a treatment is in the future or not (https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/admin_plugins/futureitems.js#L64). 

This seems to fail when the treatments entered in to mLab are 'zoned' (e.g 2017-04-28T15:05:41+01:00) as the string comparison [$gt] doesn't have any concept of timezones. This causes treatments to appear as future treatments when they really aren't (and they display properly on the main nightscout graph).

Future entries seems to be based on a unix timestamp, which doesn't suffer from this problem.

**Comment by CaptainBalou** [comment]
I seem to face this issue or something similar.

https://gitter.im/nightscout/cgm-remote-monitor?at=5946cb9102c480e672582161

Can I give some more infos to help someone with that? Unfortunately I am not able to help coding here but I am willing to help with testing and stuff like that.

**Comment by sulkaharo** [comment]
@lawley the latest release now fixes this, thanks for getting the ball rolling!
