### ISSUE TITLE
Replace Nightscout Icon with current BG value  when user "pins" browser tab

### ISSUE THREAD

**Issue by roycesimpson** [nightscout/cgm-remote-monitor#2591]
Love having the current BG value and latest change value displayed on the Nightscout browser tab.  I would love to be able to "pin" the tab but then those values are no longer visible and only the Nightscout icon is there.  Would it be possible to show the current BG value instead when the tab is pinned?

**Comment by unsoluble** [comment]
As far as I can determine, there's no way to dictate a different appearance/content for pinned tabs in Chrome. Some modifications can be done via browser extension, but that'd be beyond the scope of Nightscout.

**Comment by gitanO0** [comment]
As I'm looking at my pinned tabs in both Chrome and Firefox for my Gmail site, I see there's the standard icon for gmail but then the number of unread emails is shown at the bottom/right of that icon.  Why wouldn't it be possible to do the same thing with Nightscout but with current BG as that number.

**Comment by unsoluble** [comment]
At a cursory glance it seems as if Gmail is doing dynamic favicon replacement to get the badging. Not sure if that's something that anyone here is into diving into, but maybe?
