### ISSUE TITLE
Current Dev Basal Pill not updating

### ISSUE THREAD

**Issue by ELUTE** [nightscout/cgm-remote-monitor#2658]
Users reporting that the basal pill is no longer showing temp basals, it is only showing the ones from the profile.

**Comment by rkresha** [comment]
Little clarification here.
The pill is showing it correctly. It's this api call that is only bringing back the default NS profile basal
"/api/v2/properties/iob,basal,loop,openaps?pretty=true" via the "basal" json object

This is being consumed by a pebble watchface so it doesn't give me the temp basal updates that I would expect to see. It was working from the dev channel back in April but I just repulled dev in the last couple weeks and it is no longer working. I've verified by going back to the pull in April it works again (I also pruned data from mongo to rule out a data issue). To compare the commits I've included the branches below

This is the older branch that still works https://github.com/rkresha/cgm-remote-monitor/tree/prod-old and this is the new branch that doesn't https://github.com/rkresha/cgm-remote-monitor/tree/prod

**Comment by ELUTE** [comment]
Sorry to clarify, the basal is not updating correctly here /api/v2/properties/basal?pretty=true

**Comment by sulkaharo** [comment]
#2867 should fix this

**Comment by ELUTE** [comment]
Resolved with #2868
