### ISSUE TITLE
Unknown slot type 'LIST_OF_METRICS' for slot 'metric'

### ISSUE THREAD

**Issue by Grizwald54** [nightscout/cgm-remote-monitor#2665]
When I'm building my Nightscout skill for Alexa, I get the following error regarding my Intent Schema:

Error: There was a problem with your request: Unknown slot type 'LIST_OF_METRICS' for slot 'metric'

Anyone have any idea why or how to resolve?

**Comment by Brogydog** [comment]
Same issue here

**Comment by tanja3981** [comment]
Did you configure section "Custom slot types" on page "Interaction model"?
![image](https://user-images.githubusercontent.com/7403966/31633032-507a1fe2-b2bf-11e7-8240-d09393822e62.png)

**Comment by Jwit25** [comment]
Need to click on Save after the adding the custom slot details.

**Comment by PieterGit** [comment]
Closing issue, because issue is more than a year old and not updated.
New Alexa features/bug fixes should be done on the new Alexa/Google Home codebase of 4980.
Please open a new issue if you have problems with that codebase.
