### ISSUE TITLE
Node.js vulnerabilties — action required?

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#2674]
Vulnerabilities [announced today](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/) in the 0.10.x line of Node.js. Will need advice to offer people who are being notified of this, from someone who knows whether or not this has the potential for any impact.

Do we need to tell folks to manually update their Node version? Will that break anything in NS? Is it not an issue at all? Other recommendations?

Update: According to folks who seem confident in the matter, updating Node to a newer release line doesn't appear to break anything (thread on FB [here](https://www.facebook.com/groups/cgminthecloud/permalink/1361338597320726/)). Current advice is to manually change the Node version requested to 6.11.1.

**Comment by chsnell** [comment]
Just adding some comments to this.  The security announcement is here:
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

It clearly mentions that the 0.10.x line is vulnerable as well.  I'm fairly new to nightscout, but from what I can see from the community, there are some fairly non-technical people installing this.  I'd probably recommend moving to an LTS version of node js, if possible. 

I also have both of the full content of the emails heroku sent out, if anyone needs them.

**Comment by Breeze773** [comment]
I would also like to know how to update, if possible.

**Comment by stavlor** [comment]
Updating will depend on how you are deployed, so it varies from different
deployment options, but the development branch currently uses node
6.10/6.11.

**Comment by Prosulpump** [comment]
Which pump you using?

**Comment by Breeze773** [comment]
@stavlor 
Thanks, I'll switch to the dev branch and deploy it to Heroku.  
@Prosulpump I am not using a pump, just a CGM-only.  Dexcom G5.

**Comment by Prosulpump** [comment]
I don’t know why I receive notification where I am actually banned. It is very annoying


A quick questions you might be to help me. I am making a App that I want to read data from CGM. Can you help?

Thank You

**Comment by unsoluble** [comment]
@Prosulpump Not entirely sure how you ended up in this thread, but it's clearly not what you think it is. :)

**Comment by Prosulpump** [comment]
I know actually I am banned and I am receiving notification!!. However I am writing a App to communicate through BLE with my device but I need to read data from CGM. I don’t have one. Do you share some insight about what format the data is and collaborate bit

Thank You

**Comment by unsoluble** [comment]
@Prosulpump This really isn't the place for that — can you please take your questions to an appropriate discussion forum? If you don't want to receive further notifications from here, hit the "mute the thread" link at the bottom of this email.

**Comment by Prosulpump** [comment]
I am sorry for the flurry of emails here I am not sure and I appologize

**Comment by davidofwatkins** [comment]
For the record, the `dev` branch currently uses Node v6.10.0, and the vulnerability was patched in v6.11.1 ([according to Heroku](https://kb.heroku.com/node-js-constant-hashtable-seeds-vulnerability-faq)), so I don't think simply deploying the dev branch will do the job. This should probably be hotfixed in both `master` and `dev`, as long as there are no breaking changes between Node versions.

**Comment by Chewwy420** [comment]
Updated my DEV site to 6.11.1 and after 7 hours been working fine so far...

**Comment by chsnell** [comment]
There are 3 files that I found that reference the 6.10.0 version in the dev branch:
.nvmrc
Dockerfile.example
package.json

package.json is the obvious one that needs an update, but the other two should be updated to stay in sync as well, most likely.

**Comment by sulkaharo** [comment]
I just pushed #2681, which updates dev to use the patched Node 6.11.1

**Comment by Breeze773** [comment]
Thanks @sulkaharo and everyone else.  Deploying the updated branch as I type this.

**Comment by Breeze773** [comment]
This may be a side issue, but the timestamp on my version is concerning.  It has a date in April.
`
0.10.0-dev-20170423`
Though my heroku build (deploy) log clearly shows an update happening.
` Installing binaries
       engines.node (package.json):  6.11.1`

This feels like possibly a cosmetic thing, but wanted to make folks aware.
