### ISSUE TITLE
Calculate current % unit test coverage

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/cgm-remote-monitor#268]

**Comment by dduugg** [comment]
Hi, I have this working on a feature branch on my fork. You can view the relevant change [here](https://github.com/dduugg/cgm-remote-monitor/commit/8868629398d7c80ae073c155b27b573c16b47fff).

I added a badge to the README as well, for quick access to the coverage level. It's visible on the [branch page](https://github.com/dduugg/cgm-remote-monitor/tree/coverage), but I'm also including a screen shot:

![image](https://cloud.githubusercontent.com/assets/697964/5793772/59f2ee94-9f05-11e4-8442-4142d896d17b.png)

Would love to turn this into a PR and close out this issue – let me know your thoughts.

**Comment by trhodeos** [comment]
Cool, looks good to me. Open a PR, and let's get this issue closed :)

**Comment by rnpenguin** [comment]
Look good!  Make sure to change repo from ddugg to nightscout for coveralls

**Comment by dduugg** [comment]
Great! I'll just wait for #363 to merge to avoid a conflict.

**Comment by trhodeos** [comment]
#363 is merged :)

**Comment by dduugg** [comment]
Ok, #365 is up. There's a pretty massive refactor to `Makefile` that might be overdone, @bewest in particular should check it out. Looks like there was an attempt to include coverage reports, but I got a ton of errors[*] and culled most of it.

\* e.g. `invalid reporter "travis-cov"`, `Cannot find module 'blanket'`, `./coverall.sh: No such file or directory`

**Comment by bewest** [comment]
Seems ok, I paste that script around and simply hadn't done it yet.
https://github.com/bewest/sgvdata/blob/master/coverall.sh

**Comment by dduugg** [comment]
#373 should merge before this is considered closed...
