### ISSUE TITLE
Loop: Temporal basals stopped working

### ISSUE THREAD

**Issue by elenavilla** [nightscout/cgm-remote-monitor#2725]
Hi, I had trouble with one sensor, called Dexcom, and deleted and reinstalled the dexcom app. Previously, I had updated my phone's os. Now, I can command boluses from the Loop app, and I can see the BG levels, but I have the grey circle, and the app doesn't recommend or use any temporal basal.
Below is my Riley Recent History. Thanks so much!
Found 67 events since 2017-08-02 16:36:58 +0000
Event: {
"_type" = TempBasal;
rate = 0;
temp = absolute;
timestamp = "2017-08-02T07:55:21Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T07:55:21Z";
}
Event: {
"_type" = TempBasal;
rate = 0;
temp = absolute;
timestamp = "2017-08-02T08:15:27Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 0;
timestamp = "2017-08-02T08:15:27Z";
}
Event: {
"_type" = TempBasal;
rate = "0.3";
temp = absolute;
timestamp = "2017-08-02T08:28:08Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 90;
timestamp = "2017-08-02T08:28:08Z";
}
Event: {
"_type" = TempBasal;
rate = 0;
temp = absolute;
timestamp = "2017-08-02T09:01:33Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 0;
timestamp = "2017-08-02T09:01:33Z";
}
Event: {
"_type" = TempBasal;
rate = "2.85";
temp = absolute;
timestamp = "2017-08-02T09:05:23Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:05:23Z";
}
Event: {
"_type" = TempBasal;
rate = "2.125";
temp = absolute;
timestamp = "2017-08-02T09:15:01Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:15:01Z";
}
Event: {
"_type" = TempBasal;
rate = "1.8";
temp = absolute;
timestamp = "2017-08-02T09:20:28Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:20:28Z";
}
Event: {
"_type" = TempBasal;
rate = "1.35";
temp = absolute;
timestamp = "2017-08-02T09:25:16Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:25:16Z";
}
Event: {
"_type" = TempBasal;
rate = "1.025";
temp = absolute;
timestamp = "2017-08-02T09:30:23Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:30:23Z";
}
Event: {
"_type" = TempBasal;
rate = "0.475";
temp = absolute;
timestamp = "2017-08-02T09:35:22Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T09:35:22Z";
}
Event: {
"_type" = BolusNormal;
amount = 1;
programmed = 1;
timestamp = "2017-08-02T09:36:27Z";
type = Normal;
}
Event: {
"_type" = Suspend;
timestamp = "2017-08-02T09:50:29Z";
}
Event: {
"_type" = Resume;
timestamp = "2017-08-02T10:59:59Z";
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 0;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = 0;
carbInput = 0;
carbRatio = 18;
correctionEstimate = 0;
foodEstimate = 0;
insulinSensitivity = 175;
timestamp = "2017-08-02T11:00:12Z";
unabsorbedInsulinTotal = 0;
}
Event: {
"_type" = BolusNormal;
amount = "0.2";
appended = {
"_type" = UnabsorbedInsulin;
data = (
{
age = 88;
amount = 1;
}
);
};
programmed = "0.2";
timestamp = "2017-08-02T11:00:13Z";
type = Normal;
}
Event: {
"_type" = TempBasal;
rate = "3.175";
temp = absolute;
timestamp = "2017-08-02T11:00:22Z";
}
Event: {
"_type" = TempBasalDuration;
duration = 30;
timestamp = "2017-08-02T11:00:22Z";
}
Event: {
"_type" = Suspend;
timestamp = "2017-08-02T11:08:37Z";
}
Event: {
"_type" = Resume;
timestamp = "2017-08-02T15:58:35Z";
}
Event: {
"_type" = ChangeTime;
timestamp = "2017-08-02T18:31:00Z";
}
Event: {
"_type" = NewTime;
timestamp = "2017-08-02T18:31:00Z";
}
Event: {
"_type" = ChangeTime;
timestamp = "2017-08-02T19:17:09Z";
}
Event: {
"_type" = NewTime;
timestamp = "2017-08-02T19:17:09Z";
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 0;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = 1;
carbInput = 16;
carbRatio = 16;
correctionEstimate = 0;
foodEstimate = 1;
insulinSensitivity = 175;
timestamp = "2017-08-02T20:13:39Z";
unabsorbedInsulinTotal = 0;
}
Event: {
"_type" = BolusNormal;
amount = 1;
programmed = 1;
timestamp = "2017-08-02T20:13:39Z";
type = Normal;
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 0;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = "0.6";
carbInput = 10;
carbRatio = 16;
correctionEstimate = 0;
foodEstimate = "0.6";
insulinSensitivity = 175;
timestamp = "2017-08-02T21:25:23Z";
unabsorbedInsulinTotal = 0;
}
Event: {
"_type" = BolusNormal;
amount = "0.6";
appended = {
"_type" = UnabsorbedInsulin;
data = (
{
age = 73;
amount = 1;
}
);
};
programmed = "0.6";
timestamp = "2017-08-02T21:25:23Z";
type = Normal;
}
Event: {
"_type" = Battery;
timestamp = "2017-08-02T23:36:07Z";
}
Event: {
"_type" = Battery;
timestamp = "2017-08-02T23:36:41Z";
}
Event: {
"_type" = AlarmPump;
alarm = "unknownType(55)";
timestamp = "2017-08-02T23:36:07Z";
}
Event: {
"_type" = ClearAlarm;
timestamp = "2017-08-02T23:36:45Z";
}
Event: {
"_type" = Battery;
timestamp = "2017-08-02T23:37:27Z";
}
Event: {
"_type" = Battery;
timestamp = "2017-08-02T23:37:50Z";
}
Event: {
"_type" = CalBGForPH;
amount = 140;
timestamp = "2017-08-03T02:08:36Z";
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 140;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = "0.2";
carbInput = 0;
carbRatio = 13;
correctionEstimate = "0.2";
foodEstimate = 0;
insulinSensitivity = 115;
timestamp = "2017-08-03T02:08:40Z";
unabsorbedInsulinTotal = 0;
}
Event: {
"_type" = BolusNormal;
amount = "0.2";
appended = {
"_type" = UnabsorbedInsulin;
data = (
{
age = 286;
amount = "0.6";
},
{
age = 356;
amount = 1;
}
);
};
programmed = "0.2";
timestamp = "2017-08-03T02:08:41Z";
type = Normal;
}
Event: {
"_type" = CalBGForPH;
amount = 216;
timestamp = "2017-08-03T04:20:01Z";
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 216;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = "0.8";
carbInput = 0;
carbRatio = 13;
correctionEstimate = "0.9";
foodEstimate = 0;
insulinSensitivity = 115;
timestamp = "2017-08-03T04:20:06Z";
unabsorbedInsulinTotal = "0.1";
}
Event: {
"_type" = BolusNormal;
amount = "0.8";
appended = {
"_type" = UnabsorbedInsulin;
data = (
{
age = 138;
amount = "0.2";
},
{
age = 418;
amount = "0.6";
}
);
};
programmed = "0.8";
timestamp = "2017-08-03T04:20:06Z";
type = Normal;
}
Event: {
"_type" = CalBGForPH;
amount = 201;
timestamp = "2017-08-03T04:51:24Z";
}
Event: {
"_type" = ChangeTime;
timestamp = "2017-08-03T07:23:43Z";
}
Event: {
"_type" = NewTime;
timestamp = "2017-08-03T07:23:44Z";
}
Event: {
"_type" = CalBGForPH;
amount = 129;
timestamp = "2017-08-03T07:37:34Z";
}
Event: {
"_type" = BolusWizardBolusEstimate;
bg = 129;
bgTargetHigh = 110;
bgTargetLow = 100;
bolusEstimate = "1.6";
carbInput = 20;
carbRatio = 13;
correctionEstimate = "0.1";
foodEstimate = "1.5";
insulinSensitivity = 160;
timestamp = "2017-08-03T07:37:42Z";
unabsorbedInsulinTotal = 0;
}
Event: {
"_type" = BolusNormal;
amount = "1.6";
appended = {
"_type" = UnabsorbedInsulin;
data = (
{
age = 205;
amount = "0.8";
},
{
age = 335;
amount = "0.2";
}
);
};
programmed = "1.6";
timestamp = "2017-08-03T07:37:42Z";
type = Normal;
}
Event: {
"_type" = ChangeTimeFormat;
timeFormat = 24hr;
timestamp = "2017-08-03T07:50:30Z";
}
Event: {
"_type" = BolusNormal;
amount = "0.5";
programmed = "0.5";
timestamp = "2017-08-03T07:52:22Z";
type = Normal;
}
Event: {
"_type" = BolusNormal;
amount = "0.2";
programmed = "0.2";
timestamp = "2017-08-03T07:54:50Z";
type = Normal;
}
Event: {
"_type" = TempBasal;
temp = absolute;
timestamp = "2017-08-03T07:57:34Z";
}
Event: {
"_type" = ChangeBasalProfilePattern;
timestamp = "2017-08-03T07:58:55Z";
}
Event: {
"_type" = ChangeBasalProfile;
timestamp = "2017-08-03T07:58:55Z";
}
Event: {
"_type" = BolusWizardSetup;
timestamp = "2017-08-03T07:59:30Z";
}
Event: {
"_type" = BolusWizardSetup;
timestamp = "2017-08-03T08:00:23Z";
}
Event: {
"_type" = BolusNormal;
amount = "2.5";
programmed = "2.5";
timestamp = "2017-08-03T12:41:55Z";
type = Normal;
}
Event: {
"_type" = BolusNormal;
amount = "0.3";
programmed = "0.3";
timestamp = "2017-08-03T12:48:38Z";
type = Normal;
}
Event: {
"_type" = BolusNormal;
amount = 1;
programmed = 1;
timestamp = "2017-08-03T12:56:11Z";
type = Normal;
}
Event: {
"_type" = BolusNormal;
amount = "0.3";
programmed = "0.3";
timestamp = "2017-08-03T14:04:36Z";
type = Normal;
}

**Comment by Kdisimone** [comment]
this issue can be closed.  is a Loop-related issue, not NS.
