### ISSUE TITLE
Decrease the mouse hover area around treatments and/or allow treatments to be toggled on/off

### ISSUE THREAD

**Issue by trpnblies7** [nightscout/cgm-remote-monitor#2765]
The mouse over hover area around treatments is too big at the moment, and I'm unable to see what my BG readings are if they're right near a treatment. Rather than hovering over a reading and seeing the value, I instead see the treatment. Decreasing the hover area so it's only the size of the treatment icon would help with this. Additionally, adding an ability to toggle treatments on or off would also help.

**Comment by jaylagorio** [comment]
Adding on to this one, reducing the hover area around treatments would be very helpful especially when using a phone or tablet.

**Comment by JoseeT1Bionique** [comment]
I also experience the same issue. Would appreciate the improuvement. Thank you.

**Comment by alimhassam** [comment]
Would it be good to also increase the BG reading area? I'm having trouble to show toolip on mobile.
