### ISSUE TITLE
Add sum of daily basalrate to Profile Editor and Profiles Report

### ISSUE THREAD

**Issue by winni67** [nightscout/cgm-remote-monitor#2766]
My doctor often asked me for this value, the sum of my daily basalrate. I missed this sum in the Profile Editor and the Profiles Report. For me, it's a checksum if my basalrate programming is ok.
Thanks in advance.

**Comment by MilosKozak** [comment]
daily sum of basals is diplayed when you turn on Insulin distribution checkbox

**Comment by winni67** [comment]
Where can I find this setting? I use NightScout version 0.10.1-dev-20170923.

**Comment by alimhassam** [comment]
You can see the insulin distribution box in the report I  believe. I also  added the requested feature a pull request 2921 https://github.com/nightscout/cgm-remote-monitor/pull/2921

**Comment by Kdisimone** [comment]
The requested feature is already incorporated, issue can be closed.
