### ISSUE TITLE
i am not getting high alarms only low alarms

### ISSUE THREAD

**Issue by amuladore** [nightscout/cgm-remote-monitor#2779]

**Comment by ELUTE** [comment]
Do you have BWP turned on? What are your thresholds set at?

**Comment by Kdisimone** [comment]
@amuladore have you resolved your issue?

Can we close this issue?

**Comment by amuladore** [comment]
Yes thank you

Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by PieterGit** [comment]
Issue resolved according to the reporter. Closing issue.
