### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#280]
Currently running cgm-remote-monitor with Safari 8.0 on Yosemite. Between opening the page in the evening and going to the computer in the morning, the page now seems to consistently bloat to ~3GB memory use during the night and the rendering process hangs, so the page needs to be killed in the morning. The use case for me running the page overnight is to get audio alerts on speakers.

**Comment by jasoncalabrese** [comment]
I never saw that crazy rendering, but the hang when opening a tab seems to be resolved so I'm going to close this

**Comment by sulkaharo** [comment]
Yup, the latest build seems to behave extremely well.
