### ISSUE TITLE
How to deploy for China Azure webapp

### ISSUE THREAD

**Issue by hahaxj** [nightscout/cgm-remote-monitor#2846]
I have change the web.config as following, but it does not work:
`          <conditions>
            <add input="{HTTP_HOST}" pattern=".+\.chinacloudsites\.cn$" />
            <add input="{HTTPS}" pattern="Off"/>
            <add input="{REQUEST_METHOD}" pattern="^get$|^head$" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}"/>
        </rule>`

https://testnode.chinacloudsites.cn/

What should i do ? thanks a lot.

**Comment by sulkaharo** [comment]
I suspect there's nobody in the team who knows how to help with this. Please post instructions if you find out

**Comment by PieterGit** [comment]
@hahaxj  the site gives a DNS_PROBE_FINISHED_NXDOMAIN for me and I'm using Heroku, so can't help you with chinacloudsites. Can you give an update?

**Comment by PieterGit** [comment]
@hahaxj can you give an update to this issue. Without more information we cannot help you fix this issue. I'm closing this issue for now due inactivity. Feel free to reopen it if you have more information so that we can help you.
