### ISSUE TITLE
DCA icons

### ISSUE THREAD

**Issue by davidmlb** [nightscout/cgm-remote-monitor#2847]
Hi, I updated the Ns to last version, as I thought everything was ok because at the end I achieved the purple icon saying the merge is complete. but I can't see the icons in nightspot.

Loop Versión 1.4
Nightscout
version 0.10.0-dev-20170423

**Comment by sulkaharo** [comment]
Can you post a screenshot with an annotation on what icons are missing? Thanks

**Comment by davidmlb** [comment]
@sulkaharo ,yes here I put the carrot icon
![dca](https://user-images.githubusercontent.com/28386261/30864805-0e08939a-a2d5-11e7-9632-603b4098be03.png)

**Comment by davidmlb** [comment]
or here I put pasta and Apple
![dca1](https://user-images.githubusercontent.com/28386261/30864943-76489a54-a2d5-11e7-8f9a-aba44c8c7bbc.png)

**Comment by MilosKozak** [comment]
Post treatments from reports please

**Comment by ELUTE** [comment]
@davidmlb you need to update to the latest version of Nightscout.

**Comment by Kdisimone** [comment]
Issue can be closed.  Original poster needed to update to latest ns version.  support provided in Looped group.

**Comment by davidmlb** [comment]
yes. solved
