### ISSUE TITLE
Distribution report miscalculates percentages when filtered by hour

### ISSUE THREAD

**Issue by bdr1177** [nightscout/cgm-remote-monitor#2864]
When filtered by hours, the distribution report miscalculates the percentages of readings that correspond to low, normal, and high.  Specifically, the percentage calculation uses the total unfiltered number of daily readings as the denominator in the calculation even when the readings have been filtered.  

You can see this in the two images attached below.  In the one labeled "All Hours Selected" 92 of the readings were high and the total number of readings were 285.  The percentage of high readings is correctly displayed as 32.3% (92 / 286 = 0.323).

However, in the image labeled "Hours Filtered," 50 of the readings were high and the total number of filtered readings was 104.  The correct percentage of high readings for the hours selected is 51.92% (50 / 104 = 0.5192).  However, the percentage of high readings is incorrectly displayed in the distribution report as 17.5% (50 / 286 = 0.1750) because the percentage calculation is using the total unfiltered number of daily readings as the denominator rather than using the total number of filtered readings.  

The pie graph on the left correctly displays the visual representation of the filtered percentage, even though the percentage of readings in incorrectly displayed in the chart.

![capture2ann](https://user-images.githubusercontent.com/8519000/30974899-d80367e6-a43e-11e7-8d28-287c8fb1729c.jpg)

![captureann](https://user-images.githubusercontent.com/8519000/30974877-ca7346d2-a43e-11e7-9b7f-b7656dc6cee8.jpg)

**Comment by sulkaharo** [comment]
Good catch!

**Comment by sulkaharo** [comment]
This is now fixed in dev branch, do you have the possibility of testing the fix?

**Comment by bdr1177** [comment]
Yes, I'll try to get the dev branch and test this evening.

**Comment by bdr1177** [comment]
Yes, I just tested and the fix worked.  Thanks for fixing it so quickly.

**Comment by Kdisimone** [comment]
This issue appears to be resolved and could be closed.

**Comment by PieterGit** [comment]
@bdr1177 can you report if this issue has been fixed for you. I'm closing it for now. Feel free to reopen or create a new issue if this issue persists.
