### ISSUE TITLE
MongoDB authentication process has changed. 

### ISSUE THREAD

**Issue by itsakmakidou** [nightscout/cgm-remote-monitor#2865]
MongoDB authentication has changed. How to update Nightscout?

**Comment by sulkaharo** [comment]
Not sure what you mean? Nightscout hasn't change anything and you don't need to touch Mongo to update the site, just follow instructions here: http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie

**Comment by itsakmakidou** [comment]
If you try to make a new account, you will see that now there is MongoAtlas Cloud with API authentication, No user/password authentication. No mongo-string

**Comment by sulkaharo** [comment]
That's the wrong Mongo hosting company. :) All Mongo versions do support the same authentication methods, but if you want the one we have instructions for, check https://mlab.com/

**Comment by itsakmakidou** [comment]
You are right.. Sorry... And thank you.
