### ISSUE TITLE
In Profile report - ISF not reporting partial values

### ISSUE THREAD

**Issue by JELCRAWFORD** [nightscout/cgm-remote-monitor#2869]
The profile report in NS reporting features in newest version is not reporting decimal values for ISF.  i.e. our pump entered ISF if 4.5, but the report indicates 4

**Comment by sulkaharo** [comment]
Strange, this is working for me as expected. Is it possible your data / computer has a conflict between separators used (point vs comma)?

**Comment by JELCRAWFORD** [comment]
I get the same output regardless of device (iPhone, iMac). I can have @jmcrawford look on his device(s) - non apple. Otherwise how would I know/investigate about a conflict between separators?

**Comment by JELCRAWFORD** [comment]
hm..  I was messing around with this this morning and changing from a decimal to a full digit to a decimal digit I can't reproduce the problem now - is working fine.  Will close.
