### ISSUE TITLE
Reporting functions

### ISSUE THREAD

**Issue by romulol** [nightscout/cgm-remote-monitor#289]
Would be nice to have included on a link like the care portal a link to various reports similar to the ones shown in the Nighscout Chromadex app reports tab.  While it's convenient and it's a nice tool the Chromadex uploader having integrated the reports into nightscout will really enhance it's value.  People who might be worried about privacy could decide not to enable it like the care portal and instead use the Chromadex app.  

Another feature that helps visualize things is having a timeframe option.  I have seen it on Chromadex, is native to Dexcom.    
##

**Comment by dbeasy** [comment]
This can probably be closed. I think the reports tab in Nightscout does cover what I could find of the Chromadex ( https://chrome.google.com/webstore/detail/nightscoutinfo-cgm-utilit/ffjaahelelfakhdpphligimoibajjlhl Chrome Uploader ) screen shots. There are daily and hourly average stats etc now in Nightscout's reporting tabs.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
