### ISSUE TITLE
Protect user from editing OpenAPS pump bolus treatments

### ISSUE THREAD

**Issue by tynbendad** [nightscout/cgm-remote-monitor#2909]
If you edit carbs on a treatment that came directly from the pump bolus wizard from OpenAPS, it will cause OpenAPS to see it as a new carb entry and can cause it to dose for the combined edited+original carbs.

Nightscout can protect users from this by warning when someone wants to edit an entry that came from a pump thru openaps, e.g., with "Entered By" starting with "openaps:".

I don't know if editing insulin treatments that come from openaps: should similarly be protected, I would guess so.

The issue stems from this fb post:
https://www.facebook.com/groups/cgminthecloud/permalink/1439709746150277/?comment_id=1439769216144330&reply_comment_id=1440066756114576&notif_id=1507595870361152&notif_t=group_comment_reply

**Comment by sulkaharo** [comment]
Is this a Nightscout or OpenAPS feature? If we implement entry locking, I'd prefer that to use a generic locking mechanism and not be OpenAPS specific. Alternatively, we could have logic in OpenAPS to detect the entry has been edited (given the downloaded event will also have the OpenAPS tagging / same timestamp as the event OpenAPS already has locally).
