### ISSUE TITLE
iOS 11 Temp Basal Entry Forces Numeric Keyboard

### ISSUE THREAD

**Issue by jwedding** [nightscout/cgm-remote-monitor#2916]
With only numeric keyboard, there is no option to manually log a negative temp basal.

**Comment by kmudd22** [comment]
I believe this has been logged elsewhere

**Comment by ELUTE** [comment]
I believe this has been logged elsewhere. I can't seem to find the issue about it though.

**Comment by sulkaharo** [comment]
This is fixed in the next patch release. I’ll probably release it today or tomorrow.
