### ISSUE TITLE
Feature request: Allow filtering of treatments by event type and note contains

### ISSUE THREAD

**Issue by bdr1177** [nightscout/cgm-remote-monitor#2948]
Currently, the "notes contain" and "event type" fields on the treatment report only filter by day, but do not filter to specific treatments.  This feature request is to add functionality to the treatment report to allow the treatments themselves to be filtered by "notes contain" and "event type."  

This would allow, for example, someone to filter the treatments to display only "pump site changes" over a specified period of time, which could be helpful for tracking site rotation.

**Comment by alimhassam** [comment]
Would be nice to be able to select multiple event types in the search, so we could request a report with all insulin treatments, snack bolus, correction bolus, meal bolus for example, but not other treatment types.

**Comment by robinsondan87** [comment]
This feature would be very useful especially for hospital appointments to show everything apart from "Temp Basal" under the treatments report.

At the moment this is basically unusable as the search options for event types (including meal bolus) always seem to include temp basals.
