### ISSUE TITLE
Feature Request: Ability to use different kinds of insulin simultaneously  

### ISSUE THREAD

**Issue by miguelkennedy** [nightscout/cgm-remote-monitor#2961]
It would be awesome if we could use different kind of insulins in NS. For instance, I use a rapid insulin (Humalog) and also use a regular one (Humulin-R). Both have different duration of insulin activity (DIA).

If I'm going to eat a very low carb meal with low GI or a meal of only protein and fat I use regular insulin, if I eat a moderate or high carb meal I use rapid. Sometimes I even use both rapid and regular insulin in the same meal (for instance: pizza).

The request is to have the ability to add various types of insulins in the profile editor and also their correspondent DIA. When adding a meal bolus or correction in Careportal the user should be able to choose the correspondent insulin used in that meal/correction (or multiple insulins if that's the case) and nightscout would calculate correctly the IOB for the insulin that was selected, or combine IOB of various insulins if the user inserted various insulins in Careportal for special meals (example: pizza).

Hope it makes sense. Right now I have all the features I need in NS. This is the only one missing. I hope someone can implement this feature.

Thanks in advance!

**Comment by tanja3981** [comment]
If I understand this feature request correctly, it's basically about being able to enter a custom DIA for some treatments, isn't it?

**Comment by miguelkennedy** [comment]
A bit more than that, being able to add various kinds of insulins with their correspondent DIA in NS profile and in treatments the user has the option to select which insulin to use... It would also be great to be able to use 2 or more insulins at the same time in the same meal... For instance: in the bolus screen of care portal a user might choose to bolus xIU of insulin A and yIU of insulin B in the same meal and nightscout should be able to calculate the IOB of the combined insulins...

**Comment by tanja3981** [comment]
Okay sorry, then that's much more what I intended to do. ;-)
