### ISSUE TITLE
Fix for AUTH_DEFAULT_ROLES

### ISSUE THREAD

**Issue by miguelkennedy** [nightscout/cgm-remote-monitor#2962]
When setting AUTH_DEFAULT_ROLES to "denied" or "status-only" watchfaces for pebble (and I assume for other smartwatches as well) can't read data from NS. Apps for pebble like Careportal or PinIt can't add treatments to NS.

It would be perfect if we had an option for AUTH_DEFAULT_ROLES that allows read and write access to the treatments API (both v1 and v2) but still blocks users from seeing the NS site in a browser unless the first login with the API secret.

Thanks in advance!

**Comment by PieterGit** [comment]
This is not a Nightscout issue, but a pebble app issue (e.g. urchin). Those apps should support tokenbased authentication, so it's possible to use a token with exactly the right permissions. Allowing the treatments to be changed and allowing reading stuff through the API does not comply with `AUTH_DEFAULT_ROLES ` set to `denied`.

**Comment by PieterGit** [comment]
If you're using openaps you might want to use pancreabble. I'm working on making that work with openaps out of the box, see https://github.com/openaps/oref0/pull/570 .
