### ISSUE TITLE
Add 4-hour DIA curve to wip/iob-cob

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/cgm-remote-monitor#301]
Currently the IOB curve for 3h duration of insulin action is defined at 
https://github.com/nightscout/cgm-remote-monitor/blob/wip/iob-cob/static/js/client.js#L1611

Before making IOB available outside of wip/iob-cob, we need to define and test the curve for 4h DIA as well.  The formulas look something like:

y = -0.1157x^2 + 0.1157x + 100
and
y = 0.0694x^2 - 4.2361x + 64.583

Cc @jasoncalabrese 
##

**Comment by oskarpearson** [comment]
Is this still a problem with the latest code?

From what I can tell the relevant piece of code is now https://github.com/nightscout/cgm-remote-monitor/blob/209cf03b1d298c21b5c387a058ca5e7b6737b211/lib/plugins/iob.js#L151-L185 rather than the blob URL referenced above.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
