### ISSUE TITLE
Nighscout plus or minus differences.

### ISSUE THREAD

**Issue by MJLewis30** [nightscout/cgm-remote-monitor#3020]
I am running NS 10.0.1 Xdrip + android/G4. Lately we have been seeing the BG number change. For instance it changed from 64 to 70 but showed plus 0 then about 2 minutes later it showed plus 6. We have been using this for a few years and this just started a few months ago. I just recently changed to NS 10.0.1 and Xdrip + hoping that would fix it. It did not. I have talked to Kate F and she suggested to create an issue. 
The plus or minus problem happens at every change. the arrow does not change until the plus or minus changes to the correct calculation. I have stopped and started azure as well. my NS site is https://coltenjl.azurewebsites.net.

**Comment by Kdisimone** [comment]
@MJLewis30 Has your issue resolved now?  Just checking in.  If it has resolved, can you please close this issue?  If it has not, please provide an update with the current issue.  thanks.

**Comment by PieterGit** [comment]
@MJLewis30 : can you give an update? Does this problem persist with Habanero Red (0.10.2)?
We are closing issues that are not updated.  If you have questions feel free to reopen or ask support at
https://gitter.im/nightscout/public
