### ISSUE TITLE
Default Intent for the alexa skill?

### ISSUE THREAD

**Issue by dhermanns** [nightscout/cgm-remote-monitor#3022]
I'm on V0.10.1. When I open the alexa skill with the utterance

"open nightscout"

I don't get a response. If asking

"ask nightscout how am i doing"

I get the NSStatus response. Wouldn't it be nice to have the nsstatus as the welcome response?

**Comment by winni67** [comment]
Perhaps a nice feature

**Comment by PieterGit** [comment]
@dhermanns and @winni67  Setting this to 0.11.0 milestone. I think we should first make sure basic Alexa works and is properly documented, see e.g. https://github.com/nightscout/cgm-remote-monitor/pull/3632 for Alexa work that is planned for the upcoming 0.10.3 release.

I don't have Alexa so I can't help with this PR/issue.

**Comment by dhermanns** [comment]
Hi! Still would be nice. But right now I don‘t have the time to provide a PR for this :-/.

**Comment by PieterGit** [comment]
@dhermanns @winni67 @veryfancy Please help test the refactored Alexa codebase at https://github.com/nightscout/cgm-remote-monitor/pull/4980 

If this PR is still relevant, please reopen or create a new (generic) implementation of the PR.

Closing this PR due to inactivity.
