### ISSUE TITLE
BG meter datapoint sometimes appears at radically wrong Y-location

### ISSUE THREAD

**Issue by mhaeberli** [nightscout/cgm-remote-monitor#3025]
BG meter datapoint sometimes at radically wrong Y-location. (BG Meter linked to Medtronic 723 pump).
For example, points that were around 232 or 251 showed up at y locations corresponding to 400 - just barely visible at the top of the screen. (but when floated over with the mouse, showed 'correct' 232 or 251.)
![cgm1](https://user-images.githubusercontent.com/556854/32454184-4f9ce720-c2d3-11e7-9a21-db36a121447a.png)

-note - some display problems were solved not by refreshing, but by restarting 'dynos' on Heroku instance.

**Comment by steve8x8** [comment]
Yet another "data point": When there's no CGM running (my sensor has expired, and I don't have a new one) and only meter bg values are uploaded (Contour BT, via xDrip) those end up as red un-clickable half-circles (*) at the top of the display area (there's also no scale in this case). Reports are OK in this respect.
Values of today and past days are happily mixed (perhaps using different circle sizes).
I admit that this is not the typical use case for Nightscout, but if there are no CGM values, IMHO a default scale should be used (40-400 seems reasonable).
