### ISSUE TITLE
Update to latest dev 0.10.2 on heroku failed

### ISSUE THREAD

**Issue by osodebailar** [nightscout/cgm-remote-monitor#3059]
Update on latest dev failed with following log entry:

-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  8.9.1
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.9.1...
       Downloading and installing node 8.9.1...
       Using default npm version: 5.5.1
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Installing node modules (package.json + shrinkwrap)
       
       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/build_9782e35936c1c3753b9cb2d5c2415d55/osodebailar-cgm-remote-monitor-1218b81/node_modules/uglifyjs-webpack-plugin
       > node lib/post_install.js
       
       
       > Nightscout@0.10.2-release-20171109 postinstall /tmp/build_9782e35936c1c3753b9cb2d5c2415d55/osodebailar-cgm-remote-monitor-1218b81
       > webpack --config webpack.config.js && npm run-script update-buster
       
       Production environment detected, enabling UglifyJsPlugin
       Hash: a7b09b7d474e72c01133
       Version: webpack 3.8.1
       Time: 31690ms
       Asset     Size  Chunks                    Chunk Names
       js/bundle.js  1.91 MB       0  [emitted]  [big]  app
       js/bundle.js.map  10.8 MB       0  [emitted]         app
       [23] (webpack)/buildin/module.js 495 bytes {0} [built]
       [25] ./lib/language.js 342 kB {0} [built]
       [40] ./lib/units.js 291 bytes {0} [built]
       [254] ./bundle/bundle.source.js 863 bytes {0} [built]
       [256] ./static/css/drawer.css 1.01 kB {0} [built]
       [259] ./static/css/dropdown.css 1.02 kB {0} [built]
       [261] ./static/css/sgv.css 1.01 kB {0} [built]
       [274] ./lib/client/index.js 36.6 kB {0} [built]
       [440] ./lib/client/boluscalc.js 26.7 kB {0} [built]
       [441] ./lib/client/chart.js 21.4 kB {0} [built]
       [443] ./lib/report_plugins/index.js 2.11 kB {0} [built]
       [444] ./lib/report_plugins/daytoday.js 34.9 kB {0} [built]
       [454] ./lib/admin_plugins/index.js 2.31 kB {0} [built]
       [455] ./lib/admin_plugins/subjects.js 7.91 kB {0} [built]
       [456] ./lib/admin_plugins/roles.js 7.68 kB {0} [built]
       + 444 hidden modules
       
       ERROR in ./node_modules/js-storage/js.storage.js
       Module parse failed: Unexpected token (421:59)
       You may need an appropriate loader to handle this file type.
       |     // Check if storages are natively available on browser and check is js-cookie is present
       |     var storage_available = _testStorage('localStorage');
       |     var cookies_available = typeof Cookies !== 'undefined';*
       |
       |     // Namespace object
       @ ./bundle/bundle.source.js 16:17-38
       npm ERR! code ELIFECYCLE
       npm ERR! errno 2
       npm ERR! Nightscout@0.10.2-release-20171109 postinstall: `webpack --config webpack.config.js && npm run-script update-buster`
       npm ERR! Exit status 2
       npm ERR!
       npm ERR! Failed at the Nightscout@0.10.2-release-20171109 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2017-11-17T09_11_08_773Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by PieterGit** [comment]
@osodebailar can you confirm is this issue has been fixed for you. I have no problems deploying dev to Heroku.

**Comment by Kdisimone** [comment]
deploying fine for me...
