### ISSUE TITLE
Missing files with a new installation.

### ISSUE THREAD

**Issue by ramjar** [nightscout/cgm-remote-monitor#3076]
Hi guys,

Got some issues with NS installation. I did a clone (master branch) and when I try to start the NS for the first time after the installation (npm install) I get follow error:
Error: ENOENT: no such file or directory, open '/root/cgm-remote-monitor/tmp/cacheBusterToken'

So I did 
`$ mkdir tmp ; node bin/generateCacheBuster.js > tmp/cacheBusterToken
`
`$ env $(cat my.env) PORT=1334 node ./server.js
`
When I then visit the NS address, the "loading" screen appears, and nothing else happens. However I can see that the web browser have some errors with the site:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bundle.js, line 0)
[Error] Did not load script at 'http://xxx:1334/js/bundle.js?v=kl24xs2qo8sl5n1k' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
[Error] ReferenceError: Can't find variable: $
	Global kod (client.js:3)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bundle.js, line 0)
[Error] Application Cache update failed, because http://xxx:1334/js/bundle.js?v=kl24xs2qo8sl5n1k could not be fetched.
```

Looks like I am missing a file /js/bundle.js which I guess refers to static/js/bundle.js

```
$ ls static/js/
client.js

```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
$ npm -version
5.5.1

```

```
$ nodejs --version
v6.12.0

```

Anyone have any ideas?

**Comment by sulkaharo** [comment]
Sounds like you’re using sudo to run npm? Npm de-escalates it’s privileges from root when run as root, which causes file permissioning issues. Chown the install directory to the web user and re-run npm as that user & it should work. 

Sulka

**Comment by ramjar** [comment]
Thank you @sulkaharo. Been trying to figure this out for 2 days now. =) 
Worked great!

**Comment by Kitekater** [comment]
Im not the Linux crack.
Have same Problems.
How must i do this wich the chown command on the npm folder?
