### ISSUE TITLE
Feature Request mmol for pushover bg check and eventual predicted eventual bg

### ISSUE THREAD

**Issue by ELUTE** [nightscout/cgm-remote-monitor#3111]
Would it be possible to set everything to mmol when DISPLAY_UNITS is set to mmol? Like pushover BG checks and predicted glucose in the Loop pill etc?
![screen shot 2017-12-02 at 3 55 00 pm](https://user-images.githubusercontent.com/7684327/33519663-706c37de-d779-11e7-86a3-69e58af494af.png)

**Comment by stavlor** [comment]
I believe the text here is coming directly from the data provided to devicestatus api so likely any change would need to be made on the Loop side but not certain of that.

**Comment by ELUTE** [comment]
SGV etc come in in mg/dL the conversion happens in NS.

**Comment by sulkaharo** [comment]
Nightscout used mg/dl as the internal data format to make sure all the math works. Plugins need to conver to the display units as needed, looks like Loop plugin is missing a line to do that

**Comment by dm61** [comment]
I've just updated the Loop plugin to display min-max and eventual predicted bg in units matching the user NS preference, see https://github.com/nightscout/cgm-remote-monitor/pull/3114

**Comment by ELUTE** [comment]
![img_5604](https://user-images.githubusercontent.com/7684327/33533666-a83a6670-d870-11e7-8466-9f745e1a4e6a.PNG)

Also the pushover notification?

**Comment by ELUTE** [comment]
ty @dm61 !

**Comment by dm61** [comment]
@ELUTE my guess is that the particular pushover is created when Contour Next Link meter sends bg to the pump, Loop reads the pump, and then uploads that bg value to NS? If so, I think the problem might be related to the fact that Loop is transmitting that Meter BG value as a treatment, which might then be lost in translation in the `treatmentnotify.js` plugin, specifically this line: 
https://github.com/nightscout/cgm-remote-monitor/blob/75e195a0cf6d4275237a474e819204a34ea26469/lib/plugins/treatmentnotify.js#L121
I'd try replacing `lastTreatment.glucose` with `sbx.scaleEntry(lastTreatment.glucose)` .  
I am not using pushover at all, so you may just give this a try when you get a chance.

**Comment by ELUTE** [comment]
ok will try this ty

**Comment by ELUTE** [comment]
It didn't seem to work for me. I realize now that treatments are logged in reports in mg/dL as well

**Comment by dm61** [comment]
Thanks for checking. I guess you may have already checked this: look at a Loop treatment (`ns-site/api/v1/treatments.json`) with `BG Check` as `eventType`. If the treatment is in mg/dL and does not contain the original meter unit, then it is impossible to fix this in Nightscout. This would then be a Loop issue.

**Comment by ELUTE** [comment]
{"_id":"5a25fa4536940ca0a433fcd2","glucose":221,"enteredBy":"loop://Sydney's iPhone","glucoseType":"Meter","eventType":"BG Check","created_at":"2017-12-05T01:44:45Z","units":"mg/dL","timestamp":"2017-12-05T01:44:45Z","carbs":null,"insulin":null}

So Loop issue? OpenAPS also uploads in mg/dL

**Comment by dm61** [comment]
I think  NS reports simply treatments as entered, which is why that sbx.scaleEntry attempt failed.  It should still be possible to fix this in NS by checking the user's preference and overriding the units provided with the treatment - I'll take another look at that. On a different note, I am not sure why Loop (or OpenAPS) are converting the meter BG values to mg/dL before sending them to NS.

**Comment by dm61** [comment]
@ELUTE,  in that same location in `treatmentnotify.js` as attempted earlier, you may try inserting the following line: 

`var displayBG = sbx.settings.units === 'mmol' ? 
            sbx.roundBGToDisplayFormat(sbx.scaleMgdl(lastTreatment.glucose)) : lastTreatment.glucose;`

followed by replacing `lastTreatment.glucose` with the new variable `displayBG` in the next line:  

`return (lastTreatment.glucose ? 'BG: ' + displayBG + ' (' + lastTreatment.glucoseType + ')' : '') +
`

**Comment by sulkaharo** [comment]
@dm61 Nightscout uses mg/dl as the internal data format for everything so it assumes the data is in mg/dl. This is largely due to the CGM systems actually doing the same and reporting the data in mg/dl even for mmol users, so the original decision was to use the same format as the devices and convert if needed. If the patch above works, wanna PR that in?

**Comment by ELUTE** [comment]
@dm61 tried it this morning and for some reason it causes my ns site to load asking for API_SECRET which it tells me is incorrect when entered. Bizarre

**Comment by dm61** [comment]
@ELUTE just one more try, wrap the scaling statement in an `if` statement:

`if(lastTreatment.glucose) {
           var displayBG = sbx.settings.units === 'mmol' ? 
           sbx.roundBGToDisplayFormat(sbx.scaleMgdl(lastTreatment.glucose)) : lastTreatment.glucose; 
}`

If this does not work, then I am not really sure what's going on - will work on the pushover issue at a later time, or someone else can take a look at it. Scaling in the Loop pill is fine, that's been corrected in #3114
