### ISSUE TITLE
Raw BG display problem - inconsistent data and Linear Y axis problems

### ISSUE THREAD

**Issue by bordeb** [nightscout/cgm-remote-monitor#3118]
Brief _**background info**_ about my setup:
Dexcom sensor/transmitter > Parakeet > google app engine > xDrip+ > Nightscout (on Azure) with Raw Data display enabled. One note: we have multiple azure Nightscouts portals for redundancy, so I reconfirmed my problems on v10.1 as well as v10.2. We are personally using mmol/L (we are in EU) but I will still report here in mg/dl for better understanding.
**_Browsers tested_**: IE 11, Firefox 57, 57.0.1, Firefox Mobile... All the same results.

**_The problems:_** I have two interconnected problems (at least I think so):

##**_problem 1)_**
At the very end time of one sensor (approx. 01 Nov 2017) the sensor was pretty "crazy" sometimes reporting very crazy values. One thing I noticed was that for the exact same measurement the **Nightscout showed different Raw BG value on one day (yesterday) compared to the next day (today)**, while in the same time BG value is always the same, luckily. This all happened with the old version (10.1) and also with the updated one (10.2).  
I cannot figure it out how this can happen? Can someone please help!

_Example, excerpt from the mlab database:_
"sysTime": "2017-12-01T14:19:31.119+0100",
    "unfiltered": 90032,
    "filtered": 85728,
    "direction": "Flat",
    "delta": 4.057,
    "device": "xDrip-WifiWixel",
    "rssi": 100,
    "sgv": 74,
    "dateString": "2017-12-01T14:19:31.119+0100",
    "type": "sgv",
    "date": 1512134371119,
    "noise": 1

_This was represented on Nightscout as:_
- yesterday it was  - BG: 74 ; Raw BG: 1207
- today it is           - BG: 74 ; Raw BG: 80
Screen shots are also here:
Yesterday:
![ssns1](https://user-images.githubusercontent.com/24623289/33524521-f0ba2b8a-d81e-11e7-8bda-b6cd6b272c89.png)
Today:
![ssns2](https://user-images.githubusercontent.com/24623289/33524525-0814e54a-d81f-11e7-9236-db2da5d5bedb.png)

## **_problem 2)_** 
In the same time the other interconnected problem is that yesterday while Raw BG data was displayed as sky rocketing HIGH level (Raw BG: 1207) this resulted in Nightscout chart using Linear Scale extremely flat (almost unusable, see screen shot) while Logarithmic and Logarithmic (Dynamic) was quite ok – Logarithmic just did not showed this high dot so the chart wasn’t flatted and eas usable! I think this is good approach, but it is not implemented while in Linear view, so it would be very useful to be able to apply the same approach also to Linear Scale. Are there any plans for that? Or maybe just to be able to set max value on Y axis in Linear view.

**Comment by sulkaharo** [comment]
Right - we should have filtering for obviously wrong values, but I'll check. @jamorham it might be worth filtering out data such as mentioned here (RAW BG > 1000) in  xDrip as well.

**Comment by bordeb** [comment]
@sulkaharo thank you very much on your responsive support and fast reply. I really appreciate your efforts!!
I have read about how to interpret and understand raw data in nightscout but still can not figure it out how nightscout calculates this, especially loking into my database mlab data. My example, excerpt from the mlab and corresponding raw value displayed in nightscout that is extremely high one day and than normal the next day is so confusing. I can not figure it out how this happened. Can someone please help me understand?
