### ISSUE TITLE
All buckets are empty

### ISSUE THREAD

**Issue by Lufo95** [nightscout/cgm-remote-monitor#3143]
Nightscout website works but BG not showing. 
Getting console output 'All buckets are empty'.

![f1c2a1f547196ae2519740bbe4737119](https://user-images.githubusercontent.com/12578230/33685016-8ab708ee-dad0-11e7-958c-579f5fd744e3.png)

**Comment by unsoluble** [comment]
Did you sort this out? Whatever your data source is — a Dexcom bridge, or an xDrip uploader, or something — isn't sending data to the Nightscout site (the site itself is working fine, from all appearances).

**Comment by Lufo95** [comment]
Hi! Yes I was able to fix this. The NodeJS plugin connects to the carelink.com website, which is carelink.eu for European people. I fixed this manually.
