### ISSUE TITLE
We are using Guardian Connect Medtronic. Is is possible to use nightscount to get data from their cloud

### ISSUE THREAD

**Issue by liuxuhan** [nightscout/cgm-remote-monitor#3145]
Hi
We are using Guardian Connect Medtronic. We want to use the data in our own app.
I know nightscount is working with MiniMed.
Is is possible to use nightscount to get data from cloud of Guardian Connect Medtronic.

Or anyone is using this device now?

Thanks

**Comment by Kdisimone** [comment]
Yes, you can use the following link below to setup a system to pull your CGM data from your Guardian Connect into a Nightscout site.

https://github.com/pazaan/600SeriesAndroidUploader/wiki

If this answers your question, can you confirm by closing this issue?  Thanks.  If it doesn't answer your question, let me know what else you are looking for.  Any questions about setup of that system can be addressed in the Nightscout for Medtronic facebook group too.  https://www.facebook.com/groups/NightscoutForMedtronic

**Comment by PieterGit** [comment]
@liuxuhan please let us know if the comment of @Kdisimone is useful for you. I'm closing this issue for now. Feel free to reopen if you have additional questions.

**Comment by szymjaw** [comment]
Please go with this tutorial http://nightscout.pl/medtronic/guardian-connect/

**Comment by shortanu** [comment]
Hello, is there a tutorial for Guardian Connect with Heroku?  I am new to this and don't know how to edit the source files of the app on Heroku...

**Comment by szymjaw** [comment]
This is for Azure, but you can do this.
Please deploy your heroku app from my github https://github.com/szymjaw/cgm-remote-monitor

**Comment by fozatay** [comment]
Hello same issue but even if I tried both Szymjaw' heroku github and Azure procedures , I could not manage to get the BG data to the Nightscout .

**Comment by PieterGit** [comment]
@szymjaw can you try to create a PR for https://github.com/szymjaw/cgm-remote-monitor/commits/carelink-dev-servers against the Nightscout `dev` branch? In that case we can include your code changes in the main repository. I'm reopening this issue so that we notice that there is a PR to merge in future (closed issued don't get our attention)

@fozaty I can't help with this issue, because I'm not a Guardian Connect user.

**Comment by szymjaw** [comment]
@PieterGit I will do it on Monday.

**Comment by norbicz** [comment]
@szymjaw Could you prepare info/tutorial how to update Heroku with Guardian Connect?

Probably you have done a cool guide for Azure (nightscout.pl page) but I would like to skip MS solution.
I hope it will be possible to prepare Heroku Guardian Connect version :)

I don't know how to update files on Heroku: carelink.js and transform.js
the way it is described for Azure. Not sure where I should edit them before deploying my app.

**Comment by pleinolijf** [comment]
> 
> 
> Hello same issue but even if I tried both Szymjaw' heroku github and Azure procedures , I could not manage to get the BG data to the Nightscout .

Same problem here. Used the carelink-dev-servers branch of @szymjaw repo on a Heroku setup (I'm in Belgium). No data coming through.

Can anyone enlighten us ?  When is the main Nightscout branch adapted for EU Guadian Connect users ? 
Really looking forward to building stuff on this...

**Comment by szymjaw** [comment]
> > Hello same issue but even if I tried both Szymjaw' heroku github and Azure procedures , I could not manage to get the BG data to the Nightscout .
> 
> Same problem here. Used the carelink-dev-servers branch of @szymjaw repo on a Heroku setup (I'm in Belgium). No data coming through.
> 
> Can anyone enlighten us ? When is the main Nightscout branch adapted for EU Guadian Connect users ?
> Really looking forward to building stuff on this...

@pleinolijf please fork cgm-remote-monitor from https://github.com/nightscout and use dev branch.
Please check if it's working.

**Comment by pleinolijf** [comment]
@szymjaw Using the dev branch of the Nightscout repo, I got it working now. Thank you !
