### ISSUE TITLE
Temporary target asks for values in mg/dL even when set to display in mmol/L

### ISSUE THREAD

**Issue by cascer1** [nightscout/cgm-remote-monitor#3168]
I've experienced this issue since starting to use Nightscout late October of this year. 

I am currently running version 0.10.2-release-20171109

**actual behaviour**:

1. Visit nightscout
2. Set display units to mmol/L if not already set this way
3. Open window to create a new temporary target
4. Observe target values display in mg/dL

**expected behaviour**: 

The range input should be in mmol/L when the displayed units for the rest of the system are also in mmol/L. 

![displayed units](https://ducohosting.com/screenshots/desk86ded7c4367711a1f5c70f7b8795a227.png)

![display setting](https://ducohosting.com/screenshots/desk9e845cbd870cc9b0d7e24cd09c55a45c.png)

![temporary target](https://ducohosting.com/screenshots/desk4da129730eca6c4e35f17689e45f7d48.png)

**Comment by awaxa** [comment]
In case it's worth noting, this is not precisely `0.10.2-release-20171109` after...
https://github.com/nightscout/cgm-remote-monitor/compare/awaxa:hours...cascer1:d46d06a2  via  https://github.com/cascer1/cgm-remote-monitor/pull/2
I certainly enjoy my crazy testing branch, do not recommend and can not support it, etc.  This is a quick rebase ... for one of my friends who'll soon also wear our NFHack shirts with the spirit they deserve!

**Comment by GlennCoco** [comment]
Just came across this, I am having the same trouble and wondering if there is a fix for this? @awaxa @cascer1

**Comment by ELUTE** [comment]
all targets and treatments are in mg/dL unfortunately and always have been. +1 on wishing this could be resolved

**Comment by cascer1** [comment]
@GlennCoco I haven't had a chance to look at this yet, I'm unfamiliar with the existing code so it might take a while if I were the one to fix this.

**Comment by lottainkeri** [comment]
Hi all, I also encountered this problem. Hope it will be fixed soon? Thanks in advance!

**Comment by PieterGit** [comment]
@lottainkeri This has been fixed with  
https://github.com/nightscout/cgm-remote-monitor/commit/0516c99e5a527bceabd4487ea3e2486e853e5965 and is available in 0.10.3.1. Please upgrade your Nightscout to latest master.

@cascer1 @awaxa @GlennCoco @ELUTE If you haven't upgraded to 0.10.3.1 or dev, please do and then temporary targets can be set in mmol/L

Closing this issue. Please open new issue and link to this issue, if you still have problems.
