### ISSUE TITLE
Treatment form issue with &lt;input type="number"&gt;

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#319]
Safari, MobileSafari and IE 10+ seem to have an unfortunate feature, where the number formatting validator for &lt;input type="number"&gt; is strongly tied to the device's locale, and any number that doesn't match the locale is ignored.

What this means is, if you're a computer / phone that uses a locale that expects period-based decimal separators but you enter a value using a comma (as expected in many European countries), the value will be ignored by the browser and not stored with the treatment. I found this when the treatment form lost data when my wife used it, where the iPhone default for Finnish users who choose to use English as the UI language seems to be to default to UK number formatting, causing numbers with Finnish formatting to fail. The symptom is, document.getElementById("glucoseValue").value returns null when "misformatted" numbers are entered, making it impossible to detect a number has been entered and reformat accordingly.

Unfortunately a lot of software is buggy with locale management and thus in my experience setting the Finnish locale for number breaks random software and makes working with people across different locales challenging (Excel notably is a horror with Finnish locale and importing data in US format), so I assume there's a lot of users who either have to use a non-native locale or have it set unknowingly as a default (many Europeans choose run their computers in English due to the terrible UI localizations).

So - I wonder if it's better to use &lt;input type="number"&gt; and teach users how to use the form, or refactor the form to use text fields and leniently parse both comma and period based formatting.
##

**Comment by jasoncalabrese** [comment]
Is this still a problem?

**Comment by PieterGit** [comment]
@sulkaharo This is the oldest issue in the issue tracker.  I just tested an can use a comma with setting a temp target without problems now. Closing this issue.
