### ISSUE TITLE
Warn or prevent creating a treatment event in the future

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#321]
I noticed I'd accidentally created a treatment event in the future, which caused all kinds of breakage with the predictions. Luckily I can delete items in the database but given users can't edit treatments right now, this probably needs looking at before iob-cob goes out.
##

**Comment by scottleibrand** [comment]
Future treatment events (particularly negative boluses to represent
scheduled temp basals to zero) should work. Can you detail what yours
looked like, and how it broke, so we can fix?

**Comment by sulkaharo** [comment]
The future event I found was probably an accidental marking, or at least I can't see any other reason for it. Last night 10 grams of carbs appeared as a future event by myself, where the only explanation I can think of for it was I'd changed the time and accidentally changed the hours as well. I could fortunately go into the database to delete the event but users won't have such an option through the UI.

**Comment by jasoncalabrese** [comment]
I put carbs in the future using the "Eating in" time select for pre-bolusing in 1 step

**Comment by sulkaharo** [comment]
Ok so found a clear issue with how the date change flow works. What's happened to us a number of times is, R is backfilling treatment log around midnight. The code for "other" time in treatments creates a new Date() to get the date part of edited timestamp in all cases, so creating a treament for 11:59 pm at 00:01 am is logged ~24 hours in the future.

How far in the future should users be able to add events? Should the code assume that if the event is more than say, 6 hours in the future, we can assume the event is actually meant for the past?

**Comment by sulkaharo** [comment]
Relevant code is in ui-utils.js, function treatmentSubmit(event):
```
    var eventTimeDisplay = '';
    if ($('#treatment-form input[name=nowOrOther]:checked').val() != "now") {
        var value = document.getElementById("eventTimeValue").value;
        var eventTimeParts = value.split(':');
        data.eventTime = new Date();   // here be dragons around midnight
        data.eventTime.setHours(eventTimeParts[0]);
        data.eventTime.setMinutes(eventTimeParts[1]);
        data.eventTime.setSeconds(0);
        data.eventTime.setMilliseconds(0);
        eventTimeDisplay = formatTime(data.eventTime);
    }
```

**Comment by jimsiff** [comment]
If date() is derived from and calculated in epoch, does this problem go away?

**Comment by jasoncalabrese** [comment]
I think I've seen this before, at 1 point I used a date/time type instead, but it in most cases it's more than you want.  If we had an edit it would help too.  How do you backfill from R?

**Comment by dbeasy** [comment]
I'm new to Nightscout, a couple days in and saw this issue too, I forgot to log an Omnipod change "site change" at 11:11pm (6/12) and when I remembered the real time of day was 12:53am (6/13), I changed the time of event back to 11:11pm (I think I used an iPhone so it was a scroller time picker, not important). I suspected that it might log into the future and didn't find it until the next day reading this thread it mentioned the db so I went to the mongolab site and found and fixed the json document (db row) with the invalid date, refreshed the azurewebsites page and it showed up on the right date.

I'm also seeing trouble logging events on Dolphin on Kindle, so I'll be looking at what's going on with that too, might be out of the scope of this issue.

With that in mind I'll be fixing this in my fork and, assuming my git jargon is right, make a pull request after testing the other scenarios mentioned on this issue, such as future food/insulin logging (via the "Eating in" X mins in the future dropdown).

**Comment by jasoncalabrese** [comment]
Think the solution is what @MilosKozak did in his fork, add an additional date input

It's part of lots of other changes, so maybe this 1 part should be ported over

![screen shot 2015-06-13 at 8 53 18 am](https://cloud.githubusercontent.com/assets/751143/8144965/bc65c328-11a9-11e5-8206-29bda0abdc9a.png)

**Comment by MilosKozak** [comment]
There is more improvements and fixed bugs in my branch like scrolling over hours and days while holding up/down key, fixed Now/Other behaviour etc. Once @jasoncalabrese says code refactoring is done i'll put it in treatment drawer too
