### ISSUE TITLE
timestamp issues in cookie monster uploader

### ISSUE THREAD

**Issue by kenstack** [nightscout/cgm-remote-monitor#322]
Hi guys,
Couple of timestamp issues Im finding.  I use the mongo data for my own push alarm system that I wrote in addition to my use of azure and the new ios app. I finally got around to getting off the old uploader today (circa september) and the upgrade broke my system.  Ill fix it on my end but thought other folks may run into similar issues

1. the text time stamp is wrong at least for EST - epoch time converts correctly but the dateString is an hour ahead - from a bit ago
"date": 1420434475000,
    "dateString": "Mon Jan 05 00:07:55 EST 2015",
the epoch was right on, I noticed because its still sunday in EST as Im typing this

2. the datestring format changed from pre cookie monster to cookie monster FYI (maybe you knew this - I was reading datestring and converting it myself - I have no idea why I did that :)  the old format was
"dateString": "09/03/2014 11:40:54 PM" - I very much like the timezone add btw so Im not complaining - just notice the format changed as well as the add of the timezone

3. the date in the devicestatus collection is in an entirely different format and there is no epoch 
"$date": "2015-01-05T05:35:08.099Z"  I assume the Z means zulu time, which I think should be 5 hours ahead of EST.   in this case its coming out 6 hours ahead so I think its wrong.

But, please let me know if I am messing something up.

small point - calling the name something different like devicedateString versus $date for device status might be a bit more user friendly but again not a big deal.  

As always, great job to all of you - nightscout is life changing for the parents of T1ds

**Comment by ktind** [comment]
This sounds like an uploader issue and specifically it looks like you are using the mongo vs REST. Is this the master branch? or the Dev branch?

1 -  According to [Epoch converter](http://www.epochconverter.com/epoch/timezones.php?epoch=1420434475) ``Mon Jan 05 00:07:55 EST 2015`` is the correct time for 1420434475000. The uploader currently uses the Dexcom display time as the reference point (see [here](https://github.com/nightscout/android-uploader/wiki/Time-and-the-Dexcom#solution-1---use-the-display-time) for more information). Did you update the Dexcom time updated during the last Daylight savings change?

2 - The date string was primarily added for debugging. I don't think any other components used the datestring.  Glad to hear you like it :smiley: . Sorry it broke your modifications. Our take away is that we need to be a little more clear on the changes we introduce. Thanks for the feedback.

3 - This is the [mongo date type](http://docs.mongodb.org/manual/reference/mongodb-extended-json/#date) that is a result the way we do an [upsert](https://github.com/nightscout/android-uploader/blob/master/app/src/main/java/com/nightscout/android/upload/Uploader.java#L393) with ``new Date()`` as the value in the mongo uploader. I believe the REST interface stores it as a string. We can change this to a string, but I think it better serves us as a Date object.

@jasoncalabrese @bewest @rnpenguin @trhodeos We should probably make the Mongo and REST interfaces store the record consistently.  Any thoughts/preferences as to how - $date object vs String?

**Comment by kenstack** [comment]
@ktind thanks for the quick reply!  Master branch.

1. Ill check the dex when my kid gets home late afternoon - we were just many timezones away from here - Im wondering if he reset the time along the way... maybe thats it !  

2. love the timezone - I have been burned many times on timezone issues... glad you added - Ill make the mods no worries to my stuff :)

3. I am fine with whatever the type is - I think you, if possible, should make them consistent between the collections and if possible add the epoch to the device collection 

I am rewriting my stuff to use the epoch directly - no idea why I used the string the first time!

Thanks!!!

**Comment by kenstack** [comment]
@ktind unclear but likely my issue...  I just checked a few records and they are correct right now to EST, so gotta have been my dex last night.  My kid said he changed some settings but wasnt specific before he went to practice so Im guessing this was us.  Sorry for the confusion! 

As I rewrite my code Ill let you know if I see anything else.  If you add the epoch to the device stuff or if you are going to change the date formats let me know if you remember.  Im excited to add a battery alarm to my code so it alarms if the phone gets below say 10% - Ill convert the date stamp for now.  

Again, many thanks for all the work!  

We can close this if you like
