### ISSUE TITLE
Profile editor - target BG not used?

### ISSUE THREAD

**Issue by fromorbonia** [nightscout/cgm-remote-monitor#3220]
It appears that setting the Profile Editor  target BG values are not being applied to the alarms. Is this due to not being implemented? 
I was expecting some code to load up the client settings.threshold, but can only find that being set based on server settings. Have I completely missed this in the app / code? Is this something I could look to add code wise?

Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier? New

Which device / browser version was used to reproduce the bug? Chrome / Firefox / iOS nightscout app

Does this happen every time you launch Nightscout, or sometimes? Always

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)
- edit profile
- set up target BG values against time
- neither graph nor alarms are influenced by target BG values

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong

**Comment by sulkaharo** [comment]
The alarms use the targets from the environment settings in Azure/Heroku. Should improve the documentation to indicate this more clearly. See https://github.com/nightscout/cgm-remote-monitor#alarms

**Comment by fromorbonia** [comment]
Hi,
I didn't phrase my post as clearly as intended! It seemed that a logical thing to occur, when you set the target BG values and times on the profile, is that would then change the alarm points. The documentation did not imply that - so not a problem with the documenation.
I suppose the phrase "some settings can be overridden per client" is slightly open, and I thought I might as well look at the code to see if I could re-use the profile value in the settings.
I've now see that xDrip & xDrip+ appear to have this functionality.
Thanks

**Comment by fromorbonia** [comment]
Should have closed this earlier - I was wondering if others were thinking about this as well (obviously not!).
