### ISSUE TITLE
Full screen UI for treatment entry in small screen devices

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#323]
When using iob-cob branch, the bg/prediction curve redraw/data processing is so CPU intensive, that the treatment form entry sometimes suffers from severe UI lag. We're testing on iPhone 6, which has 50% the Javascript benchmark speed of my Core i7 laptop, so this will probably be pretty severe on older phones. The form would probably be more usable full-screen and disabling the curve redraw while the form is open might solve the performance issues.
##

**Comment by jasoncalabrese** [comment]
1 think that really slows down rendering with iob-cob is the Retrospective lookback, if you set that to 0 the blue line goes aways and rendering is much faster

**Comment by sulkaharo** [comment]
I have it set to 0 on mobile, but still occasionally getting performance issues.

**Comment by jasoncalabrese** [comment]
yeah, still lags, but is unusable on a phone with lookback on, just wanted to make sure

**Comment by francescaneri** [comment]
![img_1408 1](https://cloud.githubusercontent.com/assets/9915825/5766011/6ab8d0d0-9cfe-11e4-958c-01b86beb6fb0.PNG)
![img_1407 1](https://cloud.githubusercontent.com/assets/9915825/5766031/7e41bb6c-9cfe-11e4-9be3-a8d36040b6a5.PNG)
given that on phones like iphone 3g and iphone 4 / 4s you can not see the screen nightscout.
does not work with Opera mini ios 3.1.3 message:(please enable cookies so you may customize your site nightscout).
wonder if it is possible to enlarge the vision to two hours instead of 1 hour. with screens smaller it gets really hard. thank you

**Comment by dbeasy** [comment]
I noticed the careportal/treatment screen lags a lot more on Android, even my newer phones with newer Chrome and traced it back to a big lag when switching form fields. When the keyboard shows/hides it hangs a few seconds. Android OS has a bug/feature that resizes the screen space when the keyboard appears, Chrome triggers the .resize event and our whole chart redraws all those dots. I am testing turning off the form redraw, it seems to help a lot, I just have to test again with the fix disabled.

I also agree with the original post, on mobile this would've been a lot easier if the careportal drawer was just a new tab (full screen) with nothing updating in the background.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
