### ISSUE TITLE
Azure - re-deploy NPM failing

### ISSUE THREAD

**Issue by fromorbonia** [nightscout/cgm-remote-monitor#3230]
Hi,
I was trying out some code changes on my repository (aftering merging with the latest). That resulted in a successful deployment on Azure to 0.10.2. 
I then changed on file, and Azure tried to redeploy, but kept on getting stuck on a permission / scan error (error below). Tried a whole number of things with no succcess. 
I then updated packages.json to also accept the latest NPM of 5.6.0, and it worked. I noticed that @sulkaharo had removed the >= 5.2.0 in Dec. Was there another issue with later NPM versions?

Thanks

Main error line:
Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\getpass\node_modules' 

Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier? I think new!

Which device / browser version was used to reproduce the bug? Azure deployment

Does this happen every time you launch Nightscout, or sometimes?

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong

**Comment by sulkaharo** [comment]
5.6.0 was release after the latest public release and has the fix for a bug with the earlier npm releases. Sounds like need to update master soon.

**Comment by PieterGit** [comment]
Note that https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.4 also includes npm 5.6.0 now.

**Comment by Kdisimone** [comment]
@fromorbonia just checking in...has your issue been resolved?  If so, can you please close this comment.  Thanks

**Comment by PieterGit** [comment]
Next 0.10.3 release will include nodejs 8.9.x (8.9.4 or later). That will include npm 5.6.0 (or later).
@fromorbonia : can you confirm that the `dev` branch works for you?

**Comment by fromorbonia** [comment]
Just mergeded the dev code and Azure successfully re-deployed site.  :-)
Thanks very much
