### ISSUE TITLE
Deployment of nightscout fails in Azure

### ISSUE THREAD

**Issue by lilagw** [nightscout/cgm-remote-monitor#3238]
Hello, I've been running an older version of NightScout and tried to upgrade to the latest. It fails on deployment. I've tried all the troubleshooting suggestions and nothing works. Please help!

Here is the Activity Log of the deploy:
Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Deleting file: 'hostingstart.html'
Copying file: '.bowerrc'
Copying file: '.dockerignore'
Copying file: '.gitattributes'
Copying file: '.gitignore'
Copying file: '.nvmrc'
Copying file: '.travis.yml'
Copying file: 'app.js'
Copying file: 'app.json'
Copying file: 'azuredeploy.json'
Copying file: 'bower.json'
Copying file: 'CONTRIBUTING.md'
Copying file: 'COPYRIGHT'
Copying file: 'database_configuration.json'
Copying file: 'Dockerfile.example'
Copying file: 'env.js'
Copying file: 'example-profiles.md'
Copying file: 'LICENSE'
Copying file: 'Makefile'
Copying file: 'npm-shrinkwrap.json'
Copying file: 'package.json'
Copying file: 'prep_repo_release.sh'
Copying file: 'Procfile'
Copying file: 'README.md'
Copying file: 'scm-commit-id.json'
Copying file: 'server.js'
Copying file: 'setup.sh'
Copying file: 'swagger.yaml'
Copying file: 'Vagrantfile'
Copying file: 'webpack.config.js'
Copying file: 'bin\create_svg.sh'
Copying file: 'bin\generateCacheBuster.js'
Copying file: 'bin\post-devicestatus.sh'
Copying file: 'bin\post-mbg.sh'
Copying file: 'bin\post-sgv.sh'
Copying file: 'bin\post-treatment.sh'
Copying file: 'bin\tsvtojson.sh'
Copying file: 'bundle\bundle.source.js'
Copying file: 'bundle\index.js'
Copying file: 'docs\issue_template.md'
Copying file: 'lib\aggregate.js'
Copying file: 'lib\booterror.js'
Copying file: 'lib\bootevent.js'
Copying file: 'lib\bus.js'
Copying file: 'lib\constants.json'
Copying file: 'lib\devicestatus.js'
Copying file: 'lib\entries.js'
Copying file: 'lib\food.js'
Copying file: 'lib\hashauth.js'
Omitting next output lines...
Using start-up script server.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3.
Selected node.js version 8.9.3. Use package.json file to choose a different version.
Selected npm version 5.3.0
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN invalid config scripts-prepend-node-path="--production"
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\8.9.0\node.exe but npm is using D:\Program Files (x86)\nodejs\8.9.3\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\home\site\wwwroot\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-01-06T08_24_19_474Z-debug.log
An error has occurred during web site deployment.
npm failed
npm WARN invalid config scripts-prepend-node-path="--production"\r\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\r\nnpm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\8.9.0\node.exe but npm is using D:\Program Files (x86)\nodejs\8.9.3\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.\r\nnpm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall scandir\r\nnpm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'\r\nnpm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'\r\nnpm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'scandir',\r\nnpm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }\r\nnpm ERR! \r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     D:\local\AppData\npm-cache\_logs\2018-01-06T08_24_19_474Z-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\70.10102.3204\bin\Scripts\starter.cmd bash deploy.sh

**Comment by sulkaharo** [comment]
Can you try to deploy the dev branch to see if it works?

**Comment by lilagw** [comment]
Actually, I tried the deployment again and it works now. It had been trying to deploy 'Merge branch 'dev', but it wasn't working in the middle of the night. Perhaps it was a timing issue?
