### ISSUE TITLE
Deployment to Azure fails

### ISSUE THREAD

**Issue by waltsteinchen** [nightscout/cgm-remote-monitor#3353]
Hi, trying to deploy to Azure results in an error: 
The resource operation completed with terminal provisioning state 'Failed'. at stage setting up source control.

Looking into Azure what happened I get the following: 

Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN invalid config scripts-prepend-node-path="--production"
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\8.5.0\node.exe but npm is using D:\Program Files (x86)\nodejs\8.9.4\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\home\site\wwwroot\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-02-12T09_30_57_437Z-debug.log
An error has occurred during web site deployment.
npm failed
npm WARN invalid config scripts-prepend-node-path="--production"\r\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\r\nnpm WARN lifecycle The node binary used for scripts is D:\Program Files (x86)\nodejs\8.5.0\node.exe but npm is using D:\Program Files (x86)\nodejs\8.9.4\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.\r\nnpm ERR! path D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall scandir\r\nnpm ERR! Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'\r\nnpm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\fsevents\node_modules\dashdash\node_modules'\r\nnpm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules\'',\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'scandir',\r\nnpm ERR!   path: 'D:\\home\\site\\wwwroot\\node_modules\\fsevents\\node_modules\\dashdash\\node_modules' }\r\nnpm ERR! \r\nnpm ERR! Please try running this command again as root/Administrator.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     D:\local\AppData\npm-cache\_logs\2018-02-12T09_30_57_437Z-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\70.10205.3242\bin\Scripts\starter.cmd bash deploy.sh

**Comment by oleksandrg** [comment]
Hello,
Has the same error

**Comment by PieterGit** [comment]
@waltsteinchen and @oleksandrg we've done quite some Azure fixes with the upcoming 0.10.3 release. Can you confirm that this issue has been resolved. Closing this issue for now. Feel free to reopen it if it persists.
