### ISSUE TITLE
Believe thresholds in settings.js should use profile data?

### ISSUE THREAD

**Issue by brentdur** [nightscout/cgm-remote-monitor#3410]
It seems odd that there is the ability to set thresholds for different times in the profile data but that the chart and alarms don't make use of this information?

**Comment by jacksutton22** [comment]
How do I stop getting these emails?

**Comment by sulkaharo** [comment]
@jacksutton22 you’re probably “following” the Nightscout repository? Click the link in the email to see the ticket in GitHub, log in and check the Repository following preferences in the top right of the web page
