### ISSUE TITLE
Document Steps for Connecting GitHub to Heroku

### ISSUE THREAD

**Issue by someoneAnyone** [nightscout/cgm-remote-monitor#343]
Heroku has released a way to connect github to your heroku deployment. Its beta so I guess it might change but, I used today without any issue to update my forked master to 6.0.

More info on the feature can be found here: https://devcenter.heroku.com/articles/github-integration

Here are the steps I took.

1. I updated my fork via GitHub to latest version of cgm-remote-monitor. My current branch is "master".
2. I logged into Heroku with my account.
3. Click on your deployment.
4. Click on the code tab.
5. Click on GitHub (you still probably overwrite your current heroku:git files)
6. Follow the onscreen instructions to connect your github account with heroku. (github will ask your to authorize this).
7. Pick a repo, and a branch.
8. Click deploy.
![benscgm_ _github___heroku](https://cloud.githubusercontent.com/assets/438049/5746567/6ec4c4dc-9bfe-11e4-9993-0b8c5b3612d1.png)

**Comment by jimsiff** [comment]
Nice!  I will look at this... we've been trying to figure out good ways to handle Heroku updates.  Other options like Dropbox sync, Codeship, etc have some disadvantages.

**Comment by jimsiff** [comment]
I updated all of my Heroku sites using this method.  Between the Deploy button and the new Github integration, Azure is becoming less compelling for me.  Heroku data caps aren't as low as Azure, and it uses AWS for Mongo by default rather than Azure.  @gregwaehner check out the new Github integration for Heroku.  It's easy peasy.  We should update the lab to use this rather than Dropbox or Codeship.

**Comment by gregwaehner** [comment]
Awesome… would love to update it… Jim and I were working on this and then I’ve been chasing other fires. I’ll take a look… if you are familiar with it, let me know if you are interested in updating the doc – would love additional input!

 

-          Greg

**Comment by jasoncalabrese** [comment]
very cool, I just setup an extra heroku app

**Comment by jimsiff** [comment]
I reached out to Heroku asking about pulling the GitHub integration into the Deploy button.  So far it's not possible, but they took it as feedback. 

Here's a condensed version of the email thread:

On 16 January 2015 at 08:58, Jim Sifferle wrote:

Is it possible to include Github integration with the Deploy to Heroku button?  It would be great if there was a way to integrate the process of authenticating the webhook into app deployment.  If it's possible, what changes need to be made to the app.json file?

On Jan 16, 2015, at 1:27 AM, Andrew Appleton wrote:

...I'm afraid it's not currently possible. I could see it being a feature we would consider adding, but I imagine there could be some difficulty with account permissions. We need to be authenticated to the source GitHub repo to install a webhook, but you're able to deploy a Heroku button app from any public repo, even one you don't own.

Thanks for the suggestion, it's great to get feedback like this!

**Comment by gregwaehner** [comment]
Updated Nightscout Labs deployed tonight covering the Heroku Github integration.

 

http://www.nightscout.info/wiki/labs/how-to-heroku

 

-          Greg

**Comment by jasoncalabrese** [comment]
This was resolved by http://www.nightscout.info/wiki/labs/how-to-heroku
