### ISSUE TITLE
[API] Treatments with invalid IDs can be uploaded successfully

### ISSUE THREAD

**Issue by mpangburn** [nightscout/cgm-remote-monitor#3468]
I'm working on a Swift wrapper around the Nightscout API and have encountered a bug with some odd consequences: a treatment can be uploaded with an invalid ID. However, upon querying the API to modify/delete by this ID, the API will return an error response, so the invalid treatment is effectively untouchable.

I haven't tested uploading an entry/profile record/device status/etc. with an invalid ID, but I suspect that this issue persists in those cases.

Here's a sample of some data that uploaded successfully. Note that the ID is most definitely not a 24-character-long string of hex digits.
```
{
  "_id": "-5",
  "notes": "NOT VALID",
  "eventType": "Note",
  "duration": 0,
  "created_at": "2018-03-24T03:15:38",
  "carbs": null,
  "insulin": null
}
```

**Comment by tanja3981** [comment]
This issue will be already fixed will pull request 
https://github.com/nightscout/cgm-remote-monitor/pull/3464
