### ISSUE TITLE
Profile editor times incorrect after daylight savings time change

### ISSUE THREAD

**Issue by Pogman** [nightscout/cgm-remote-monitor#3469]
version 0.10.2-release-20171201

Clocks went forward +1 hour at 1am on 25/3/2018

Opened profile editor at 2pm.

The profile shows blank times and the drop down time selection jumps between the +1 hour time change.

Expected behaviour is not to use TZ or daylight savings for time selections within profiles.

![ns-0 10 2-bug-profile-1](https://user-images.githubusercontent.com/7413594/37875706-051d5808-303b-11e8-971a-622a360aa52c.JPG)

Dropdown time menu:

![ns-0 10 2-bug-profile-2](https://user-images.githubusercontent.com/7413594/37875702-f4e2aeb6-303a-11e8-9652-20cfb8885445.JPG)

**Comment by triplem** [comment]
I do have the same issue. The total per day is not calculated as well. The whole profile cannot be edited anymore. No additional profile can be added nor deleted.

**Comment by tanja3981** [comment]
Stacktrace from dev console:
TypeError: time is null[Weitere Informationen]
profileeditor.js:628:9
toMinutesFromMidnight
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:628:9
timeDiffMinutes
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:205:20
refreshTotalBasal
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:219:16
initProfile
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:242:5
initRecord
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:199:5
initeditor
http://tanjascgms.herokuapp.com/profile/js/profileeditor.js:182:5
l
jquery.js:3187
fireWith
jquery.js:3317
i
jquery.js:8757
t/<
jquery.js:9123

**Comment by MilosKozak** [comment]
yes, 2 days every year it doesn't work ;)

**Comment by PieterGit** [comment]
@MilosKozak @Pogman @triplem @tanja3981 This bug is now fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4029

Closing issue.
