### ISSUE TITLE
Admin tool shows future treatments after daylight savings time change

### ISSUE THREAD

**Issue by Pogman** [nightscout/cgm-remote-monitor#3470]
version 0.10.2-release-20171201

Clocks went forward +1 hour at 1am on 25/3/2018

Opened Admin tool at 3:30pm.

The database is showing items as in the future to be removed.

![ns-0 10 2-bug-admin-1](https://user-images.githubusercontent.com/7413594/37876335-c11ad768-3042-11e8-8e3a-da06d94e87a4.JPG)
![ns-0 10 2-bug-admin-2](https://user-images.githubusercontent.com/7413594/37876336-c1359fe4-3042-11e8-9aed-1c188645040d.JPG)

**Comment by tim2000s** [comment]
I've had the same issue and am aware of other users seeing the same thing.
