### ISSUE TITLE
Feature request: Add Ketone reading

### ISSUE THREAD

**Issue by andyrozman** [nightscout/cgm-remote-monitor#3474]
Would it be possible to add "Add Ketone reading" in Nightscout. While I don't do the lot of this readings, it would be nice if this information could be there.

**Comment by jamorham** [comment]
xDrip has support for at least one meter that supplies ketone information and is ready to upload that to Nightscout whenever there is support there for it.

**Comment by PieterGit** [comment]
@andyrozman @triplem and @jamorham this indeed seems like a good new features. Now all we need is people that start working on implementing it for Nightscout and create a PR. We recently added activity endpoints to Nightscout and I don't mind additional endpoints for proper Ketone support in Nightscout. I don't have Ketone readers so can't help you with the implementation. Any volunteers? If you need help, please join https://gitter.im/nightscout/public

I'm setting this for the 0.11.x release. It can of course only be implemented in that release if there are volunteers to create/code this feature.

**Comment by TheDiabeticWay** [comment]
this would be very helpful if we can add it to nightscout!

**Comment by PieterGit** [comment]
No interest in creating PR's currently, so postponing to 0.12 release

**Comment by MahaFatehallah** [comment]
can i add more sensor reading to nightscout??
