### ISSUE TITLE
Browsers not staying current with Dreamsicle

### ISSUE THREAD

**Issue by denvergail** [nightscout/cgm-remote-monitor#348]
Several users are reporting that their websites are not keeping current with their computer's clock and are static until the next update or 2.  Some show "1 min ago" for 5 minutes, then switch to "5 mins ago" for 5 more minutes.  Back to "1 min ago".  They are not all 1 & 5 (mins ago).  Some are 4 & 12.
Seen in Chrome & Safari on Mac OSX, and on Windows with IE (v11).

**Comment by oamyoamy** [comment]
Observing this same "time" problem today using Chrome (Version 39.0.2171.99 m) on Windows 7. (Logging it here since this is a different browser/OS combination than reported so far.)  Seeing 1 minute... persistent as a persistent value.

**Comment by denvergail** [comment]
One minute persistency is a symptom of a different problem also.
Have you looked at the time stamps of your latest mongodb record?

from a browser type in websiteURL/pebble

convert the two time stamps to human time to see if they are reasonably close (within minutes) or if there is a larger discrepancy.

**Comment by jasoncalabrese** [comment]
My plan to fix this is to display the local time, not the time of the last broadcast.  With that we'll be able to calculate the time ago even if the network connection drops.

**Comment by jasoncalabrese** [comment]
Fix in progress, see https://github.com/nightscout/cgm-remote-monitor/pull/350

**Comment by sulkaharo** [comment]
Further improvement idea: measure the time between broadcasts and show a warning if the delay is very long.

**Comment by jasoncalabrese** [comment]
@sulkaharo currently the time ago will change from to yellow after 10 minutes and then red after 20 minutes, I could see adding an alarm for that, but probably best as a new feature

Were you thinking of something else?

**Comment by jonhunterbui** [comment]
I have 5 browsers opened (Windows 8, Mac OS X) displaying my NS main screens throughout the house.  If I hit refresh on just 1 of the 5 opened browsers (such as from my laptop)...it will instantly update "x min ago" on all 5 of my main screens up to that particular minute.
