### ISSUE TITLE
Automatically reset CAGE pill after pressing "Fill Cannula" on pump

### ISSUE THREAD

**Issue by sooperlooper** [nightscout/cgm-remote-monitor#3490]
I have a working prototype but it uses a roundabout method that requires IFTTT.  It would be great if someone could port it to Javascript so that everything could be done inside Nightscout instead of IFTTT. 

This is how I did it:
First I had to get my NS site to allow OpenAPS treatments to generate notifications. I added treatmentnotify to my enable line in Heroku and I also had to change one part of the code in cgm-remote-monitor/lib/plugins/treatmentnotify.js. I changed the the first zero to a 1.
![screen shot 2018-03-31 at 7 24 16 pm](https://user-images.githubusercontent.com/36587731/38175623-6d82f96c-3594-11e8-8db0-8ee1cf3c8436.png)

Then I created an IFTTT applet to create a google spreadsheet whenever my NS site had a “ns-event” The instructions are here: https://loopkit.github.io/loopdocs/nightscout/pushover/
  One thing I did differently than the instructions was to name the spreadsheet Value 2 instead of Value 1.
![screen shot 2018-03-31 at 8 31 40 pm](https://user-images.githubusercontent.com/36587731/38175703-9c295a3a-3595-11e8-8ddb-9925d3c65ca1.png)

This created a whole bunch of spreadsheets in my Google Drive like this.
![screen shot 2018-03-31 at 7 23 47 pm](https://user-images.githubusercontent.com/36587731/38175634-8fc780f6-3594-11e8-9929-96d2abb74e39.png)

The important spreadsheet that gets created when you press Fill Cannula is the one named: “Entered By openapsmedtronic554Notes Prime 554 ”. So the next step was to create a second IFTTT applet that reads this spreadsheet and then posts a “Pump Site Change” treatment to my NS site whenever a new row is added to the spreadsheet
![screen shot 2018-03-31 at 7 21 56 pm](https://user-images.githubusercontent.com/36587731/38175647-c56e46a4-3594-11e8-87b4-941e4dc3fe2f.png)
![screen shot 2018-03-31 at 7 22 02 pm](https://user-images.githubusercontent.com/36587731/38175648-c8771dd0-3594-11e8-88a9-279b54fe1267.png)

And after testing it works!
![screen shot 2018-03-31 at 7 56 08 pm](https://user-images.githubusercontent.com/36587731/38175651-d0ec5f20-3594-11e8-8b11-a7cf5057b68c.png)
![screen shot 2018-03-31 at 7 57 49 pm](https://user-images.githubusercontent.com/36587731/38175655-d7719748-3594-11e8-9ba8-478ed51acae2.png)

Also. Now we can reset the BAGE pill with this spreadsheet,
![screen shot 2018-03-31 at 8 28 27 pm](https://user-images.githubusercontent.com/36587731/38175660-ea86dfbe-3594-11e8-9119-a83bc68fe908.png)

And the IAGE pill with this spreadsheet,
![screen shot 2018-03-31 at 8 28 33 pm](https://user-images.githubusercontent.com/36587731/38175686-4fe1c98c-3595-11e8-9869-ba4f362c4669.png)

**Comment by sooperlooper** [comment]
I have also made the IAGE and BAGE pill automatically reset using the same method.  After further testing, one thing I did notice is that the IFTTT trigger "ns-event" is not reliable at creating a new row in the spreadsheet each time. I have starting using "ns-info" and having more success

**Comment by PieterGit** [comment]
@sooperlooper Nightscout is responsible for viewing CGM/pump data, but I don't see it as the concern/responsibility of Nightscout to act on pump signals. That should be implemented by the pump drivers in the APS'es. Can you create an issue for it with https://github.com/openaps/oref0 and/or https://github.com/MilosKozak/AndroidAPS
Closing this issue for now. Please reopen if you think something needs to be implemented at the Nightscout side.
