### ISSUE TITLE
Web page view leaks memory and eventually crashes

### ISSUE THREAD

**Issue by jimrandomh** [nightscout/cgm-remote-monitor#3499]
If you leave the web-page view of Nightscout open, memory usage of the tab it's in gradually increases until eventually the tab becomes unresponsive and dies.

The renderer seems to be creating duplicate SVG elements (or alternatively, not deleting old SVG elements) and this is at least part, maybe all of the problem. I am working on a pull request to address it.

**Comment by PieterGit** [comment]
@jimrandomh I assume https://github.com/nightscout/cgm-remote-monitor/pull/3500 fixed this issue? If not, please feel free to reopen this issue.
