### ISSUE TITLE
Alexa plug-in tutorial outdated for the updated Alexa development portal.

### ISSUE THREAD

**Issue by aaronjknox** [nightscout/cgm-remote-monitor#3512]
It appears that the Alexa development site has been changed significantly and the nightscout tutorial for the Alexa plug-in is now outdated.
Alexa Skills Kit Developer Console
https://developer.amazon.com/alexa/console/ask

**Comment by tanja3981** [comment]
Yes, the amazon developer site has changed a lot and the instructions are based on the old layout. However there wasn't yet any volunteering to rewrite the alexa skill instructions. ;-)

**Comment by jettechfsr** [comment]
Im not getting anywhere with this and the alexa development site format tottally lost

**Comment by aaronjknox** [comment]
Yes, a rewrite would definitely help. Sorry I can't be of help. I don't know how to set this up since the developer site was revamped.

**Comment by winni67** [comment]
I have to solve my connection problem with the latest developer version and AndroidAPS. Then I can test tanja3981 pull request and perhaps I can help to rewrite the tutorial. I have uploaded my alexa skill in german and english as a *.json file in the facebook group https://www.facebook.com/groups/nightscoutDE/ With this file, you save the steps 3-5 in the old tutorial.

**Comment by veryfancy** [comment]
Gonna have a crack at this one, unless someone tells me not to.

**Comment by veryfancy** [comment]
PR here: https://github.com/nightscout/cgm-remote-monitor/pull/3632

**Comment by PieterGit** [comment]
Closing issue, because https://github.com/nightscout/cgm-remote-monitor/pull/3632 has been merge.
@veryfancy thanks for the doc update
