### ISSUE TITLE
FoundationDB Compatibility nightscout

### ISSUE THREAD

**Issue by francescaneri** [nightscout/cgm-remote-monitor#3517]
Hi, is there the possibility to integrate this database with nightscout?
Thanks Matteo

https://github.com/apple/foundationdb

**Comment by PieterGit** [comment]
@francescaneri There is only support for Json files and MongoDB. Do you want to submit PR's to make it possible to use FoundationDB? Have a look at: 
https://github.com/nightscout/cgm-remote-monitor/tree/dev/lib/storage
