### ISSUE TITLE
bgnow: current blood glucose level is not displayed in NS --> can someone help me ????

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/cgm-remote-monitor#3525]
I have installed NS on heroku. The installation to azure leads to errors. Next month I will use the FGM freestyle libre and uses GLIMP to transfer the data to NS.

I am testing this by enter manual BG values in GLIMP. They are correctly transferred to Nightscout.

The BG values are shown on the curve.

However, no current BG value is displayed on the main monitor, but only 3 dashes. What do I have to do so that the last transmitted bg code value appears here?

By the way, if I insert a new BG value directly in NS it is although shown on the curve but the current BG value is missing.

To check this error I have installed NS on  https://ns.10be.de

Buit the same problem occurs. The current BG value is not shown !!!

The bug comes with the latest release! I'm using Chrome as brwoser an on my smartphone  samsung S8 the internet browser.

Does this happen every time you launch Nightscout, or sometimes? Yes, all the time on every device.

Steps how to reproduce: 
Please feel free to use this ns url:   

https://cgmtommy.ns.10be.de:14472

and here comes a screenshot:

![image](https://user-images.githubusercontent.com/37514390/39184267-196100ae-47c3-11e8-8fa8-14728bc4438c.png)

**Comment by thomasmenges** [comment]
Can anybody help me to solve the problem:
The problem is caused in bgnow.js  --> all buckets are empty. But that is not true.

![image](https://user-images.githubusercontent.com/37514390/39399575-893e8bd4-4b20-11e8-9abc-7167cb2d719b.png)


![image](https://user-images.githubusercontent.com/37514390/39399577-8f11948e-4b20-11e8-877e-76c6be9df31c.png)

**Comment by whooze** [comment]
Still have this problem?

Have you checked the data to see if there really is any cgm data there?

**Comment by sulkaharo** [comment]
The red dots on the timeline are calibration events, not BG values. BGNow doesn’t show manual calibrations, only CGM data entries

**Comment by PieterGit** [comment]
@thomasmenges as per @sulkaharo comment this doesn't look like a bug. If you need help please elaborate, or ask for help at https://gitter.im/nightscout/public. Please let us know if you solved your problem with testing.

**Comment by thomasmenges** [comment]
Yes problem is solved yet. I thought that manual BGs are also shown. Now I know that only cgm values are shown.
