### ISSUE TITLE
Configured default setting for variable "theme" not loaded.

### ISSUE THREAD

**Issue by deltaford** [nightscout/cgm-remote-monitor#354]
Wanted to use "colors" as default theme but doesn't seem to work.
Configured default setting for variable "theme" not loaded in function getBrowserSettings.
seems to work when adding "json.theme = setDefault(json.theme, defaultSettings.theme);"

**Comment by jasoncalabrese** [comment]
The theme is only stored locally now, so it's per browser using local storage

**Comment by deltaford** [comment]
Ok, thanks for clarifying this.
