### ISSUE TITLE
NS connection problem with AndroidAPS 2.0 RC1

### ISSUE THREAD

**Issue by winni67** [nightscout/cgm-remote-monitor#3540]
Please look at

https://github.com/MilosKozak/AndroidAPS/issues/941

**Comment by LongboatAline** [comment]
this seems to be resolved by https://github.com/MilosKozak/AndroidAPS/commit/8419f8d0e997aeb52322e1a2c43d4d6faab74830, see https://gitter.im/MilosKozak/AndroidAPS?at=5ae9eb685cf0b830044f2f58. 
With this change the connection so far has been running stable, and been reestablished quickly and reliably after some forced disruptions that would have unsettled it before.
So I think this can be closed.

**Comment by winni67** [comment]
Thanks to Milos.
