### ISSUE TITLE
README badges aren't uniform

### ISSUE THREAD

**Issue by dduugg** [nightscout/cgm-remote-monitor#355]
It's a pretty simple task to to unify the badge styles and improve the look of the page. I'm happy to submit a pull request that would change this: 

![image](https://cloud.githubusercontent.com/assets/697964/5793532/fe6f7e06-9efb-11e4-890b-b5b9384eefdd.png)

to this:

![image](https://cloud.githubusercontent.com/assets/697964/5793533/0c351c26-9efc-11e4-8ccb-56d72437414f.png)

You can also preview the changes to the README [here](https://github.com/dduugg/cgm-remote-monitor/blob/feature/badges/README.md).

Ditto for the other nightscout repos. Let me know what you think.

**Comment by jasoncalabrese** [comment]
looks good, a simple PR targeting the dev branch would be an easy merge
