### ISSUE TITLE
standardization of reports and adding measures of glucose variability

### ISSUE THREAD

**Issue by jllmostert** [nightscout/cgm-remote-monitor#3558]
I have a few suggestions to improve reporting in NightScout.
1) One-page reports, AGP style. NightScout already has a big chunck of the information that's given by AGP reports, but I would like to discuss to introduce a really good one-page overview like this: http://www.agpreport.org/agp/research It shows basic metrics and some metrics about Glucose Variability.

The main reason to do this, is because I believe it would be beneficial for all users if NightScout could take another step towards standardization of reports. I'll refer to this article for discussion and to explain in detail why that could be interesting. http://care.diabetesjournals.org/content/40/12/1631

2) In NightScout reports, I still miss a few measures of Glucose Variability, which are already available in AGP reports. (There is nothing wrong with the percentile or day-to-day reports we already have)

MAGE and MODD (and maybe also CONGA)
LBGI/HBGI low and high risk factors.
Counter for episodes of hypo/low/high/hyper: mean episodes per day, mean duration per episode.
In short:
MAGE (Mean Amplitude of Glycemic Excursions): measures the average distance between your lows and highs.
MODD (Mean of Daily Differences): compares day-to-day variation.
Conga (Continuous Overlapping Net Glycemic Action): CONGA(n) represents the variation of differences between a current observation and an observation (n) hours earlier.
LBGI/HBGI: Index (0 – 100) of how many and how low/high glucose readings there were.

More info about these variables:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4416329/
or
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3160264/
or
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3263307/

As far as I know, these metrics or algorithms aren't protected by copyright/patent, so we should be free to use them. 

This is an example of open source software that calculates these metrics, so there's no need to redo all this kind of research.
https://apps.konsta.com.pl/app/glyculator/ -> working app
https://git.konsta.com.pl/ZBiMT/GlyculatorApp/blob/master/scripts/calculator.R -> source code
Implementation of the functions/algorithms can be found in the Calculate1-class, to give you an idea.
The code is written in R.

Prof. Nathan Hill developed an excel tool (for Oxford University) to calculate these parameters.
https://www.phc.ox.ac.uk/research/technology-outputs/easygv
This code is written in Visual Basic or something like that.

So the good news is, most of what I suggest is already implemented in other tools. The bad news is, my knowledge of programming is very, very poor. I have been thinking about rewriting these functions to use them in NightScout, but I have no idea where to start, and it would take me a very, very long time. (I have no experience in writing code).

**Comment by PieterGit** [comment]
@learn2laugh would you like to try to contact these companies? Maybe they are willing to give a free license the open source project Nightscout. I'm affraid they won't but we might give it a try. Settting this to 0.11 milestone, but of course before implemting this we should know about the legal implications.

**Comment by learn2laugh** [comment]
@pietergit and @jllmostert, I have attempted to make contact with the licensing department from the link on their website. I am awaiting a response. 

On 6/27/2018 2:54:38 PM, PieterGit <notifications@github.com> wrote:
@learn2laugh [https://github.com/learn2laugh] or @jllmostert [https://github.com/jllmostert] would you like to try to contact these companies? Maybe they are willing to give a free license the open source project Nightscout. I'm affraid they won't but we might give it a try. Settting this to 0.11 milestone, but of course before implemting this we should know about the legal implications.

**Comment by hartlijn** [comment]
any news @learn2laugh ? I would love to get similar reporting out of Nightscout!

**Comment by hosamn** [comment]
Did this functionality suggestion die, or what??

**Comment by PieterGit** [comment]
@hosamn and @hartlijn:  I hope @learn2laugh can give a response if he/she received an answer from the licensing department. If there was no repsonse, I assume other people should re-ask the question (and post the answer or lack of answer here again).

**Comment by scottleibrand** [comment]
As discussed in Gitter, I don't think we need to worry about copyright (you can't copyright an algorithm, just actual code, so as long as we write our own code we're fine there.) And generally we should not go out of our way to worry about patents if we're not intending to engage in commercial activity.  If we haven't gotten a "no" response to  our initial queries, then I would be fine with just proceeding to implement any algorithms or designs we think would be best for users, as long as we obtained them legitimately (from published papers, etc.)  But IANAL, so if anyone is worried about whether patent exemptions apply to their own personal situation, feel free to opt out of any such efforts.
