### ISSUE TITLE
[API] Determining the active profile

### ISSUE THREAD

**Issue by mpangburn** [nightscout/cgm-remote-monitor#3567]
The profile record API (api/v1/profile) provides access to all records and includes the default profile. However, in the case that a user has entered a Profile Switch treatment, the default profile may not be the active profile. As far as I can tell, the API does not provide a way to access the active profile; it's not included in /status either.

If I'm missing something here and it is available, I'd appreciate the redirection.
If it's not available, this would be a really helpful API feature.

**Comment by PieterGit** [comment]
@sulkaharo can you answer @mpangburn question? Setting this to 0.10.3 milestone to make sure we triage this issue.

**Comment by MilosKozak** [comment]
agree. include it in status would be helpfull

**Comment by PieterGit** [comment]
@MilosKozak thanks for having a look. Is this something we can do quickly before the 0.10.3 release? Or should we postpone it to 0.11 release? I don't understand what you and @mpangburn want to do to the profile API, so can't help out on this issue.

**Comment by sulkaharo** [comment]
Given the AAPS profile switch event support, I have no idea how to fetch the active profile in a simple manner; the code in question looks like it needs refactoring. @MilosKozak ?

**Comment by PieterGit** [comment]
Didn't make 0.10.3. Let's look into this issue for Nihgtscout 0.11 release. @MilosKozak  can you share your thoughts on this issue?

**Comment by PieterGit** [comment]
@mpangburn  @MilosKozak do you think you will work on this item the next say 2-3 weeks? If not, I'll postpone this to 0.12 release or close this PR due to inactivity. I would like to clean out the open PR's for the 0.11 release.

**Comment by PieterGit** [comment]
@mpangburn @MilosKozak No response more than half a year. Postponing to 0.12 and I will close it in february due to inactivity.  If you are not interested in this PR anymore please close it. Perhaps it's good to check on Slack that the v3 API will support these use cases.

**Comment by viq** [comment]
Sorry, which slack do you mean?
