### ISSUE TITLE
setup.sh change for python

### ISSUE THREAD

**Issue by Dave2526** [nightscout/cgm-remote-monitor#3577]
Hello,
last week I´ve installed Nightscout on my Raspberry Pi 3 (Latest update & upgrade) and there I found an Issue in the setup.sh file: The Packet "python-software-properties" is now called "software-properties-common".

**Comment by PieterGit** [comment]
@Dave2526 Could you test https://github.com/nightscout/cgm-remote-monitor/pull/3683
I think that should solve the problem in a better way. If your quick it will be released with 0.10.3, otherwise we need to postpone it.

**Comment by Dave2526** [comment]
Sorry, but at the moment I can't test it. Perhaps anyone else?

**Comment by PieterGit** [comment]
@Dave2526 can you now test this PR? If not it won't be included in the 0.11 release.

**Comment by PieterGit** [comment]
This PR has been integrated with the https://github.com/nightscout/cgm-remote-monitor/tree/needs_testing 
branch. Please test that branch and report at this issue or at nightscout/cgm-remote-monitor#4169

**Comment by PieterGit** [comment]
Assuming fixed. @Dave2526 can you report if the fix works for you on RPI?
Closing issue.
