### ISSUE TITLE
Unauthorized glimp when using AUTH_DEFAULT_ROLES

### ISSUE THREAD

**Issue by sbalmer** [nightscout/cgm-remote-monitor#3599]
I've just set up Nightscout 0.9.3 on Heroku. When I set `AUTH_DEFAULT_ROLES=denied` Glimp says "unauthorized" when testing the connection. With `AUTH_DEFAULT_ROLES` unset the connection works.

I've tried adding a subject and entering the access token as "API Secret" in Glimp. Is Glimp just unable to work with tokens? Is there some kind of workaround?

Now I've set the permissions for group `denied` to `*` to make uploads work again. This defeats the purpose of the `denied` group obviously.

**Comment by PieterGit** [comment]
@sbalmer This isn't a Nightscout issue, but Glimp should support Nightscout token based authentication. Closing this issue. Can you inform the Glimp developers of your feature request?

**Comment by git-commit** [comment]
Somehow this is still an issue. Did you notify the glimp developers about this yet @sbalmer?

**Comment by sbalmer** [comment]
@git-commit no I have not contacted the glimp developers.
