### ISSUE TITLE
Revert "updatelanguage.js"(#3406)

### ISSUE THREAD

**Issue by rhdtv2002** [nightscout/cgm-remote-monitor#3604]
In Azure when selecting Deployment Options and syncing GitHub this starts to building and Failed is returned - does anyone know what this is?
I am using GoogleChrome on a Chromebook from Asus.

**Comment by rhdtv2002** [comment]
Please close out. I was able to resolve the issue

**Comment by TylerMitchell1** [comment]
How were you able to resolve this issue? I am having the same one.

**Comment by PieterGit** [comment]
@rhdtv2002 @TylerMitchell1 can you be more specific about which error you get?  
I don't have Azure, so can't help you with that.

**Comment by PieterGit** [comment]
If this is blocking Azure deployments it needs to be fixed in 0.10.3 release.

**Comment by PieterGit** [comment]
Closing this issue. Current dev must be deployed with Azure and see if that works.
