### ISSUE TITLE
[feature request] Average TDD reporting for last x days

### ISSUE THREAD

**Issue by typ1-brods** [nightscout/cgm-remote-monitor#3605]
For regulation of weight / managing basal it is really helpful to have an eye on the average TDD of last x days. NS actually can show each **single** TDD in the day-by-day report, so the data should be available in the database. AAPS also does.

I would love to see the **average** TDD in Distribution tab of NS reports, depending on the chosen period of time. Maybe like this: 

`sum of TDD from the days chosen / number of days chosen`

**Comment by PieterGit** [comment]
@typ1-brods setting this as a possible enhancement for the 0.11 release. 
Since @sulkaharo likes this idea I assign it to him 😄

**Comment by typ1-brods** [comment]
Maybe you can add average bolus and average basal of last 30 days as well. This information will make it easy to check the basal scheme :-)
