### ISSUE TITLE
show calibration records in pebble

### ISSUE THREAD

**Issue by bewest** [nightscout/cgm-remote-monitor#361]
From @ELUTE getting cal in pebble output.

**Comment by ELUTE** [comment]
Hoping we can get this out ;)

**Comment by jasoncalabrese** [comment]
Do you really want the cal record on the pebble or would you rather have the raw data converted to a BG?

**Comment by ELUTE** [comment]
We need the cal record for the calc. We have raw already.

**Comment by jasoncalabrese** [comment]
So you're doing the calc on the pebble?  I was thinking that would be done on the server and passed to the pebble pre-calc'd

**Comment by ELUTE** [comment]
Yes server side. Just need the cal record in the pebble.js for the calculation.

**Comment by jasoncalabrese** [comment]
This is done
