### ISSUE TITLE
Glucose distribution data in Dev is reporting incorrectly. 

### ISSUE THREAD

**Issue by tim2000s** [nightscout/cgm-remote-monitor#3660]
Running latest Dev branch, the values for  Mean Total Daily Change and Mean Hourly Change are coming back with incorrect values as in the screenshot. This is running in Chrome on both Windows and iOS. 
![c0e73801-dec0-4d3c-a52a-3f7fd6f0c711](https://user-images.githubusercontent.com/14833174/42151871-4d4f6498-7dd6-11e8-991c-c20b715db04d.jpeg)

**Comment by sulkaharo** [comment]
This is a bizarre problem, none of the code that does the calculation has changed

**Comment by sulkaharo** [comment]
Fixed
