### ISSUE TITLE
mLab updates MongoDB from 3.4 to 3.6, all Heroku installations using master branch won't fulfil the requirements

### ISSUE THREAD

**Issue by dideldum** [nightscout/cgm-remote-monitor#3668]
I received an email from mLab, that from Jul 20th on they will update the MongoDB of the Heroku sandboxes from 3.4 to 3.6.
A requirement for MongoDB 3.6 in node.js is the mongodb driver version >= 3.0
In the Nightscout master branch the driver version is only ^2.2.33, which means, that all people with master branch will not fulfil the requirements for the mLab update soon.
I fear, that the Nightscout installation will fail to communicate with the MongoDB instance then.
The master branch should be updated to use mongodb >= 3.0!

**Comment by PieterGit** [comment]
@dideldum fortunately Nihgtscout 0.10.2 still works with mLab. This issue will be fixed with the upcoming 0.10.3 release. The mongo client has been upgraded in that release.
