### ISSUE TITLE
IOB/COB branch prediction is off in mmol

### ISSUE THREAD

**Issue by ELUTE** [nightscout/cgm-remote-monitor#367]
![screen shot 2015-01-23 at 10 34 50 am](https://cloud.githubusercontent.com/assets/7684327/5877154/a6314f3c-a2eb-11e4-92be-39f4b13c1eca.png)

![screen shot 2015-01-23 at 10 35 14 am](https://cloud.githubusercontent.com/assets/7684327/5877157/aa46d93e-a2eb-11e4-81b4-b9bbb1d29b18.png)
##

**Comment by scottleibrand** [comment]
@sulkaharo: did you fix this already?  if so, which commit was that?

**Comment by sulkaharo** [comment]
Nope. I got stuck in manual merge hell and am waiting for someone to make a move on the code modularization so I know I can make pull requests that have a chance of making the builds and/or which are maintainable. 

—

**Comment by ELUTE** [comment]
BGI is not calculated in mmol. It is still in mg/dL.
![screen shot 2015-02-02 at 2 18 56 pm](https://cloud.githubusercontent.com/assets/7684327/6007287/037d1d80-aae7-11e4-9ba6-e63cb945513c.png)
![screen shot 2015-02-02 at 2 19 11 pm](https://cloud.githubusercontent.com/assets/7684327/6007292/06288e8e-aae7-11e4-9266-24e3ad4dc88d.png)

**Comment by jasoncalabrese** [comment]
Don't think this really should have been closed

**Comment by GrantKY** [comment]
Just loaded iob-cob fork to test new pebble software. This fork still doesn't appear to like mmol as a setting. When I added in the current iob you can see from pics the difference in prediction between the 2 settings.


 
![iob-cob in mgdl](https://cloud.githubusercontent.com/assets/7541222/6382306/56ac2df6-bd3f-11e4-9a44-645436c8a23d.png)
![iob-cob in mmol](https://cloud.githubusercontent.com/assets/7541222/6382307/56ae0428-bd3f-11e4-8a60-64c0bedc7b75.png)

**Comment by jasoncalabrese** [comment]
This is still a bug, or more likely multiple bugs

**Comment by sulkaharo** [comment]
I think this is now fixed in Funnel Cake. Someone wanna verify and close? :)

**Comment by jasoncalabrese** [comment]
Think this is for the purple line in iob-cob

**Comment by oskarpearson** [comment]
I've done some experimenting with the UI now on version 0.9.3-dev-20161212b, and the prediction graphs appear correct to me.

I don't have the "BGI" indicator in the same place as the uploaded images, but all pills on our system display the correct value.

I'm resolving this. Please re-open if required. Alternatively it might be worth trying to create individual issues for any specific items that you uncover.
