### ISSUE TITLE
COB pill disappeared from my NS last week

### ISSUE THREAD

**Issue by JoseeT1Bionique** [nightscout/cgm-remote-monitor#3676]
I have searched... I've read there's been trouble with it a while back, but I've found no solution as of yet.
My COB pill disappeared from my NS last week. See pictures before /after
It is "Enable" in Heroku, as it's been for months. See picture
It is selected IN my NS menu. See picture
I have disable/save, then enable/save & restarted All Dynos twice.
Any idea on how to fix this or trouble shooting section on the subject that I might of missed.
Thank you.

Is this a new bug with the latest release, have you seen this earlier?
NO.

Which device / browser version was used to reproduce the bug?
Chrome, as usual

Does this happen every time you launch Nightscout, or sometimes?
Yes, in the last week.

![cob ns](https://user-images.githubusercontent.com/30188775/42458231-7d56ac00-8367-11e8-968d-68425ddc8872.JPG)
![cob pill missing](https://user-images.githubusercontent.com/30188775/42458232-7d655ffc-8367-11e8-9730-2e5348e9e00e.JPG)
![36773769_10156256634582900_64264277095088128_n](https://user-images.githubusercontent.com/30188775/42458300-9f005cca-8367-11e8-9047-91bd20740fcb.jpg)
![36860773_10156256637532900_4514851127426023424_n](https://user-images.githubusercontent.com/30188775/42458301-9f0d8b66-8367-11e8-9884-17cd3faffb96.jpg)

**Comment by PieterGit** [comment]
@JoseeT1Bionique can you please give an update? If we don't have more info we cannot fix this issue, and I will need to close it due to inactivity.

**Comment by JoseeT1Bionique** [comment]
Hello Peter,

I apologize for forgetting to close this. It was resolve with the help of a Looped Group member. 

Regards,

Josée

**Comment by fozatay** [comment]
having exactly the same problem above. Any help is appreciated I am using the latest version of nightscout

**Comment by JoseeT1Bionique** [comment]
My problem was solved by rekeying values into the Carb Ratio fields of NS. I had removed them because they were irrelevant, but I guess they were required, in my case, for the COB pill to display. 

Hopefully this helps.

Josée
