### ISSUE TITLE
jquery.tooltips.css changes tooltip font from 14px to 10px

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/cgm-remote-monitor#3679]
With commit bd1db6e2b57f830a83c46e88b14eff9d2d3e64e5's switch from jquery.tipsy to jquery.tooltips, we inherited node_modules/jquery.tooltips/css/jquery.tooltips.css, which overrides our tooltips with:
```
.tooltip {
  position: absolute;
  font-size: 10px;
  padding: 3px 8px;
  opacity: 0.9;
  z-index: 9999;
}
```
The font size change in particular is problematic, as it makes the tooltips nearly impossible to read without squinting.  As a workaround, I changed my local copy of node_modules/jquery.tooltips/css/jquery.tooltips.css from 10px to 14px, which fixed the problem for me.  But I can't figure out the proper place to make the font size in main.css override that jquery default font size.

cc @PieterGit @danamlewis

**Comment by sulkaharo** [comment]
Woot Scott which tool did you use to find which css file had be 10px definition? Chrome didn’t show the jquery file when I tried to debug this over the weekend

**Comment by scottleibrand** [comment]
I saw the 10px override in the Elements tab of Chrome Dev tools, on the right bar under Styles, the second section had the text I pasted above.  I confirmed that was the problem by unchecking the override there, and confirming that changed the font size I was interested in.  I then ended up doing a `grep -r 'opacity: 0.9'` to find out what file that was from.

**Comment by sulkaharo** [comment]
Fix pushed to dev

**Comment by PieterGit** [comment]
Nice catch @scottleibrand @sulkaharo . Sorry for the regression.
