### ISSUE TITLE
speech plugin is always enabled on dev

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#3682]
Without adding `speech` to `ENABLE` I get speech messages with current dev. 

I think it's caused by these lines: 
https://github.com/nightscout/cgm-remote-monitor/blob/43e9301ac29a93aad83c702c61c547e5f85590a3/lib/client/index.js#L600

I think the server settings must be checked whether the `speech` plugin is enabled.

**Comment by PieterGit** [comment]
temporary fix added to dev. this will disable the complete plugin until @sulkaharo has had the time to add the proper code to only execute it when the plugin is enabled.

**Comment by sulkaharo** [comment]
Did it speak out even if you checked off the box in the client settings?

**Comment by PieterGit** [comment]
@sulkaharo we didn't add `speech` to the `ENABLE` var and then it would speak it out on page load. 
If I selected a Dutch anguage it spoke the English text with a dutch accent.
I could find a check box in the client settings (hamburger menu), even if I enable the `speech` plugin.
Are you sure you committed/pushed all the changes? 😄

**Comment by jaylagorio** [comment]
Can you also make this observe the `?mute=true` URL parameter so if that's set it doesn't talk?
