### ISSUE TITLE
After using Glimp / MiaoMiao all entries in nightscout (MLAB entries are existing) reports aren't shown anymore.

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/cgm-remote-monitor#3688]
I'm using Freestyle Libre (**Glimp**). The CGM-Information are automatically transfered to nightscout. (MLAB entries are existing).
Since yesterday I'm using **MiaoMiao** to get the CGM-information of freestyle libre automatically every 5 minutes.
Everything is working. Even in Nightscout the is shown correctly.
But if I'm starting any report for today or yesterday no result is  shown. No entries for the day are exisiting in the report,

This behavior can be found in MASTER as well in DEV.

What can I do to resolve the problem. 
![nightscout 1](https://user-images.githubusercontent.com/37514390/42634636-059d8650-85e4-11e8-9d14-94cb9589a54f.jpg)
Here you can see the Nightscout Overview --> everything is OK

![nightscout reports](https://user-images.githubusercontent.com/37514390/42634676-1ba67bfa-85e4-11e8-9f6c-421dc278363b.jpg)
Here you can see that the entries are missing

![mongodb entry](https://user-images.githubusercontent.com/37514390/42634705-3caa9caa-85e4-11e8-80c9-f4ac6fe1a842.jpg)
Here you can see that in MongoDB an entry exists

**Comment by thomasmenges** [comment]
The reason, why some values aren't shown is found (I think).
When I'm using GLIMP without connection to MiaoMiao (the CGM Reader for freestyleLibre)  everything is transfered correctly to nightscout.
Do I use Glimp connected to MiaoMiao then the values are transfered to nightscout but these entries seem to be different like the "normal" ones. 

But I'm still confused. On the overwiew of NS all values are shown correctly (screenshot 1). Only in the reports these GLIMP/MiaoMiao entries are missing

**Comment by PieterGit** [comment]
@thomasmenges Can you tell me which type of hosting (Azure, Heroku, self which OS), and what MongoDB version /hosting type you use.

Can you please check  if you're not hitting one of these issues:
- http://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Rig-NS-communications-troubleshooting.html
- http://openaps.readthedocs.io/en/latest/docs/Troubleshooting/Rig-NS-communications-troubleshooting.html#mlab-maintenance
- https://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/nightscout-setup.html?#all-of-a-sudden-nightscout-is-no-longer-showing-treatments-bolus-carbs-finger-bgs-on-the-graph-or-rendering-my-basals

**Comment by thomasmenges** [comment]
Hi Pieter,
I'm using heroku and mongoDB version 3.4.13.
I have checked the issues (interesting)  but nothing of this solved the problem.
I have now changed to XDrip+ and the problem is solved.
Ok, the problem is triggered by Glimp, but in my opinion if you see the BG curve in NS, the reports of NS should alhough show the entries correctly

**Comment by thomasmenges** [comment]
Hi Pieter,
I'm using heroku and mongoDB version 3.4.13.
I have checked the issues (interesting)  but nothing of this solved the problem.
I have now changed to XDrip+ and the problem is solved.
Ok, the problem is triggered by Glimp, but in my opinion if you see the BG curve in NS, the reports of NS should alhough show the entries correctly

**Comment by PieterGit** [comment]
@thomasmenges I agree that if it shows up in the BG curve it should be visible in the reporting. Current Nightscout API does not have a strict validation of records.  Can you compare the xdrip records to the Glimp records and see if you can spot a difference?

I can't help fixing if I cannot reproduce it and have neither xdrip or Glimp.

**Comment by thomasmenges** [comment]
Yes I asked the GLIMP community. But an answer is missing.
How can I do the comparison of the GLIMP and Xdrip values? 

Not the differences between GLIMP ans Xdrip is interesting but the GLIMP values with and without using MiaoMiao.
I tried to compare the values in MLAB but they seem to be identical ?? Do you have an idee, how I can check the differences ?

**Comment by sulkaharo** [comment]
Is the entry posted above one of the pieces of data that doesn't show up, or a working one?

**Comment by thomasmenges** [comment]
The entry postet above is an entry which isn't shown on the curve. But the problem is that all entries in MLAB looks like the one shown above regardless of whether using MiaoMiao or without MiaoMiao. (I don't know how I can see the complete information in the dataset of an MLAB Entry).

**Comment by rob-andy** [comment]
I have found the answer to this in [static/report/js/report.js]
line 637 which is
```javascript
var ok = (lastDate + ONE_MIN_IN_MS) < d.mills;
```
excludes any value that is exactly on a 1 minute boundary.  Using glimp with miaomiao uploads data is uploaded every one minute (even with a 5 minute scan rate set).  The problem could be fixed very simply changing the line to be
```javascript
var ok = (lastDate + ONE_MIN_IN_MS) <= d.mills;
```
which would allow values on the 1 minute boundary.  I think more thought needs to be put into when are cgm values considered a duplicate/ignored.

**Comment by rob-andy** [comment]
I should add, this fixes some of the reports but not the GVI calculation.  From what I can tell, the GVI calculation algorithm is assuming a 5 minute window for each sensor reading.

**Comment by GrantGam** [comment]
Hello,

I have this very problem but have absolutely no idea how to fix it... Could anyone kindly advise please?

Heroku hosting and MongoDB
Currently using a Mac

Thanks.

**Comment by sulkaharo** [comment]
@thomasmenges & @rob-andy can you test the latest DEV to see if the issues are now resolved?

**Comment by thomasmenges** [comment]
Sorry, I'm not able to do that anymore because I changed to Dexcom G6.
