### ISSUE TITLE
Duplicated entries on screen

### ISSUE THREAD

**Issue by CMartin7s5** [nightscout/cgm-remote-monitor#3699]
Which device / browser version was used to reproduce the bug? Chrome Version 68.0.3440.59 (Build officiel) beta (64 bits)/Personnal computer  and Chrome 67.0.3396.87 on my mobile device (Xiaomi Redmi 4G) 

 I am using Dev version of Nighscout, AndroidAPS and the latest version of XDrip. When I enter the carbs in APS calculator (and consequently receive insulin), from time to time, the information apears duplicated on NS screen . Please note  that i have not entered manually the BG though it mentions "BG Manual". 
It's not a consistant issue, i.e. it doesn't happen every time but happened also with previsous versions of NS/Xdrip. 

Thanks :)

![ns1](https://user-images.githubusercontent.com/39925891/42735523-031a10fa-8856-11e8-8c5e-d1d0ba016d39.jpg)
![ns2](https://user-images.githubusercontent.com/39925891/42735524-063fdb66-8856-11e8-9383-ff9a40a1f863.jpg)
![ns3](https://user-images.githubusercontent.com/39925891/42735600-3cfd3512-8857-11e8-873c-698e3a408d0b.JPG)

**Comment by parapenT1sta** [comment]
I also have the same "glitch".

**Comment by jasoncalabrese** [comment]
if you look at the treatment report do you see the duplicates?  Looks like a double upload

**Comment by CMartin7s5** [comment]
Yes, indeed but how to prevent this please? 
![capturetreatmentsns](https://user-images.githubusercontent.com/39925891/42738630-231d3568-8887-11e8-95f9-d5f583fdff1b.JPG)

**Comment by jasoncalabrese** [comment]
I think it's something with xDrip and AndroidAPS, may you have both uploading or something like that, check in those gitter channels, probably some setting to prevent this

**Comment by CMartin7s5** [comment]
Thank you @jasoncalabrese

**Comment by PieterGit** [comment]
@CMartin7s5 if you can also reproduce it also with the master branch it points at xdrip or AndroidAPS.  Please update this issue if you find more information. I'm not using xdrip and cant reproduce it so can't help fix this issue.

**Comment by CMartin7s5** [comment]
Solution has been given : "you can disable in xDrip under "settings, cloud upload, api-upload, extra options" the Option "treatment upload", then it will works fine again."
