### ISSUE TITLE
BG delta doesn't consider time or error codes

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#371]
on the pebble and web monitor

**Comment by hackingtype1** [comment]
How our web service handles it:
On insert, look for missing data, using last real EGV and new one being inserted, interpolate the missing data - marking a Boolean attribute "Interpolated" as true for these values.

On the view, I get the Interpolated field and follow the delta value with an "-i-" so I know it's not based on real EGV data.

**Comment by scottleibrand** [comment]
We also interpolate in #DIYPS, albeit without any extra indication that
we've done so.  Just think about it as a rate of change (mg/dL/5m) rather
than a delta from the last data point.

-Scott

**Comment by jasoncalabrese** [comment]
This part of #702 

<img width="536" alt="screen shot 2015-07-11 at 11 46 32 am" src="https://cloud.githubusercontent.com/assets/751143/8635124/6fe85cf4-27ca-11e5-9be4-70ece5f7868e.png">
