### ISSUE TITLE
Wrong device status

### ISSUE THREAD

**Issue by brutevinch** [nightscout/cgm-remote-monitor#3749]
i use only ONE samsung phone (androidaps) + xBridge Wixel.
i never use limitter.... it's xBridge battery status..
![2018-07-30 0 57 44](https://user-images.githubusercontent.com/12526597/43370199-43f2f8e6-9394-11e8-9dbf-abf9073a2fe7.png)

using dev branch nightscout

**Comment by PieterGit** [comment]
@brutevinch The cause of the duplicate entries is probably around here https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/upbat.js#L123-L139
Can you check your MongoDB for device statuses that cause this problem? We can use these for creating a unit test that will prevent a duplicate entry.

Nightscout doesn't create the labels like `LimiiTTer`. That's done by the uploader, so you should file a bug  there.

The `upbat.js` file has not been touched in the 0.10.3 release cycle, so this is bug is no regression from the 0.10.2 release.

**Comment by PieterGit** [comment]
@brutevinch can you still reproduce, and can you check your mongodb which records create this problem?
