### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by mdomox** [nightscout/cgm-remote-monitor#3750]
After a while (dev and 0.10.3 branch) crashes. What follows is an extract of the log. 

Jul 30 00:27:37 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:entries:read 
Jul 30 00:27:37 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:entries:create 
Jul 30 00:27:37 maria-cgm app/web.1: got data-received event, requesting reload 
Jul 30 00:27:37 maria-cgm app/web.1: If-Modified-Since: Invalid Date Last-Modified 2018-07-30T07:03:07.461Z 
Jul 30 00:27:37 maria-cgm heroku/router: at=info method=POST path="/api/v1/entries" host=maria-cgm.herokuapp.com request_id=82d31e49-42a5-4f3a-8857-5e67d32471e7 fwd="5.144.229.1" dyno=web.1 connect=0ms service=243ms status=200 bytes=1145 protocol=https 
Jul 30 00:27:38 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:devicestatus:read 
Jul 30 00:27:38 maria-cgm app/web.1: GRANTED:  5.144.229.1 api-secret api:devicestatus:create 
Jul 30 00:27:38 maria-cgm app/web.1: /app/node_modules/mongodb/lib/utils.js:132 
Jul 30 00:27:38 maria-cgm app/web.1:       throw err; 
Jul 30 00:27:38 maria-cgm app/web.1:       ^ 
Jul 30 00:27:38 maria-cgm app/web.1: TypeError: Cannot read property 'ops' of null 
Jul 30 00:27:38 maria-cgm app/web.1:     at /app/lib/server/devicestatus.js:13:20 
Jul 30 00:27:38 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 00:27:38 maria-cgm app/web.1:     at session.endSession (/app/node_modules/mongodb/lib/utils.js:399:27) 
Jul 30 00:27:38 maria-cgm app/web.1:     at ClientSession.endSession (/app/node_modules/mongodb-core/lib/sessions.js:72:41) 
Jul 30 00:27:38 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:397:17) 
Jul 30 00:27:38 maria-cgm app/web.1:     at /app/node_modules/mongodb/lib/collection.js:626:14 
Jul 30 00:27:38 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 00:27:38 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:404:25) 
Jul 30 00:27:38 maria-cgm app/web.1:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55) 
Jul 30 00:27:38 maria-cgm app/web.1:     at resultHandler (/app/node_modules/mongodb/lib/bulk/ordered.js:457:16) 
Jul 30 00:27:38 maria-cgm heroku/web.1: State changed from up to crashed 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=LdX3w04zLXZst8XjAAAD&transport=websocket" host=maria-cgm.herokuapp.com request_id=9de35cd3-dbf5-414f-9049-8bef23cfe5bf fwd="5.144.229.1" dyno=web.1 connect=0ms service=8121ms status=101 bytes=129 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/web.1: Process exited with status 1 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=cHk0djuM2zlq8mLYAAAB" host=maria-cgm.herokuapp.com request_id=ef652589-1fb4-4cbb-951b-73f6f1895d9d fwd="87.203.121.205" dyno=web.1 connect=1ms service=12299ms status=101 bytes=175 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/router: at=error code=H13 desc="Connection closed without response" method=POST path="/api/v1/devicestatus" host=maria-cgm.herokuapp.com request_id=4fbe7a75-03b3-4c40-a7a0-f11a35727be5 fwd="5.144.229.1" dyno=web.1 connect=0ms service=105ms status=503 bytes=0 protocol=https 
Jul 30 00:27:38 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=pF5KjkyyYOU7SuYlAAAE&transport=websocket" host=maria-cgm.herokuapp.com request_id=8134999b-02f6-4937-9bbc-3a07c341c24c fwd="31.152.26.140" dyno=web.1 connect=0ms service=5624ms status=101 bytes=129 protocol=https 
Jul 30 00:27:39 maria-cgm heroku/router: at=error code=H10 desc="App crashed" method=POST path="/api/v1/devicestatus" host=maria-cgm.herokuapp.com request_id=a3541034-f572-4021-92e8-779f4486284d fwd="5.144.229.1" dyno= connect= service= status=503 bytes=

**Comment by sulkaharo** [comment]
Ok that's a weird one - the ops parameter is null only if the API failed to insert a document into the device status collection in Mongo. Given there's no error handling for that, I don't think we've basically ever seen that before. What apps do you have that are reporting the device status data?

**Comment by mdomox** [comment]
@sulkaharo , AndroidAPS . BG data are uploaded by xDrip+

**Comment by mdomox** [comment]
@sulkaharo It happens only with dev and 0.10.3 branch. Loaded master branch and it has not crashed so far.

**Comment by sulkaharo** [comment]
@mdomox Can you pull https://github.com/nightscout/cgm-remote-monitor/pull/3751 and see what the logged error is

**Comment by mdomox** [comment]
@sulkaharo Died again 

ul 30 02:00:58 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=MJgQqxM&sid=OtodDoxPfyGCKo67AAAA" host=maria-cgm.herokuapp.com request_id=ef9aad93-dba9-4da1-903a-2b1fe032773f fwd="87.203.121.205" dyno=web.1 connect=0ms service=2ms status=200 bytes=301 protocol=https 
Jul 30 02:00:58 maria-cgm app/web.1: WS: Connection from client ID:  BkusYtcXHXNgX2kHAAAB  IP:  31.152.26.140 
Jul 30 02:00:58 maria-cgm heroku/router: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=MJgQqxL&sid=OtodDoxPfyGCKo67AAAA" host=maria-cgm.herokuapp.com request_id=a6636961-a00a-44bf-b9c6-9f66ecd4126b fwd="87.203.121.205" dyno=web.1 connect=0ms service=7ms status=200 bytes=208 protocol=https 
Jul 30 02:00:58 maria-cgm app/web.1: WS: Authetication ID:  BkusYtcXHXNgX2kHAAAB  client:  Android_OpenAPS  history: 48 
Jul 30 02:00:58 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=MJgQr08&sid=OtodDoxPfyGCKo67AAAA" host=maria-cgm.herokuapp.com request_id=62e00c9a-0709-4bc4-b41c-c6257effe1b4 fwd="87.203.121.205" dyno=web.1 connect=1ms service=98ms status=200 bytes=241 protocol=https 
Jul 30 02:00:58 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling" host=maria-cgm.herokuapp.com request_id=d083c3d2-82a6-4b39-8f1b-b7cad8b41eec fwd="31.152.26.140" dyno=web.1 connect=0ms service=28ms status=200 bytes=327 protocol=https 
Jul 30 02:00:58 maria-cgm heroku/router: at=info method=POST path="/socket.io/?EIO=3&sid=BkusYtcXHXNgX2kHAAAB&transport=polling" host=maria-cgm.herokuapp.com request_id=6419463f-eb38-45d2-8750-65acdbdae086 fwd="31.152.26.140" dyno=web.1 connect=0ms service=1ms status=200 bytes=208 protocol=https 
Jul 30 02:00:58 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=BkusYtcXHXNgX2kHAAAB&transport=polling" host=maria-cgm.herokuapp.com request_id=a00712b5-3d8d-40a4-9458-aa8e226e5207 fwd="31.152.26.140" dyno=web.1 connect=0ms service=2ms status=200 bytes=280 protocol=https 
Jul 30 02:00:58 maria-cgm app/web.1: Load Complete: 
Jul 30 02:00:58 maria-cgm app/web.1: 	 sgvs:537, treatments:235, mbgs:9, cals:8, profiles:1, food:64, sensorTreatments:9, profileTreatments:96, tempbasalTreatments:2 
Jul 30 02:00:58 maria-cgm app/web.1: OpenAPS Prefs: { fields: [ 'status-symbol', 'status-label', 'iob', 'meal-assist', 'rssi' ], 
Jul 30 02:00:58 maria-cgm app/web.1:   retroFields: [ 'status-symbol', 'status-label', 'iob', 'meal-assist', 'rssi' ], 
Jul 30 02:00:58 maria-cgm app/web.1:   warn: 30, 
Jul 30 02:00:58 maria-cgm app/web.1:   urgent: 60, 
Jul 30 02:00:58 maria-cgm app/web.1:   enableAlerts: true } 
Jul 30 02:00:58 maria-cgm app/web.1: OpenAPS hasn't reported a loop yet 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=BkusYtcXHXNgX2kHAAAB&transport=polling" host=maria-cgm.herokuapp.com request_id=c2735ec6-7e52-4908-aefc-3bf3b921ebe2 fwd="31.152.26.140" dyno=web.1 connect=0ms service=1ms status=200 bytes=241 protocol=https 
Jul 30 02:00:59 maria-cgm app/web.1: WS: running websocket.update 
Jul 30 02:00:59 maria-cgm app/web.1: WS: Connection from client ID:  rd9irQciOmRkLS54AAAC  IP:  87.203.121.205 
Jul 30 02:00:59 maria-cgm app/web.1: WS: Connection from client ID:  YcnZ3grHlWg7u9GhAAAD  IP:  5.144.229.1 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=MJgQr3R&sid=OtodDoxPfyGCKo67AAAA" host=maria-cgm.herokuapp.com request_id=bd378b4b-3de8-4ec9-a631-8f4be22ea560 fwd="87.203.121.205" dyno=web.1 connect=0ms service=93ms status=200 bytes=225 protocol=https 
Jul 30 02:00:59 maria-cgm app/web.1: WS: Connection from client ID:  sJjC4MpBrs7pjvveAAAE  IP:  5.144.229.1 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling" host=maria-cgm.herokuapp.com request_id=0d352baf-a149-4982-a6cc-e1370dda21af fwd="87.203.121.205" dyno=web.1 connect=0ms service=100ms status=200 bytes=327 protocol=https 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling" host=maria-cgm.herokuapp.com request_id=fd801283-7767-463e-b081-e59348f05375 fwd="5.144.229.1" dyno=web.1 connect=0ms service=1ms status=200 bytes=327 protocol=https 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=BkusYtcXHXNgX2kHAAAB&transport=polling" host=maria-cgm.herokuapp.com request_id=057a65be-cee2-48bb-95d9-1bdc3825f201 fwd="31.152.26.140" dyno=web.1 connect=1ms service=253ms status=200 bytes=241 protocol=https 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling" host=maria-cgm.herokuapp.com request_id=e2e0657e-54e7-4698-abc6-1a671a6b363f fwd="5.144.229.1" dyno=web.1 connect=0ms service=7ms status=200 bytes=327 protocol=https 
Jul 30 02:00:59 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=BkusYtcXHXNgX2kHAAAB&transport=polling" host=maria-cgm.herokuapp.com request_id=4a00b382-e0bc-4dc5-b83f-fccf8ec2b5c6 fwd="31.152.26.140" dyno=web.1 connect=0ms service=1ms status=200 bytes=259 protocol=https 
Jul 30 02:01:00 maria-cgm app/web.1: results.first size 3210 bytes 
Jul 30 02:01:00 maria-cgm app/web.1: results.rest size 16547 bytes 
Jul 30 02:01:00 maria-cgm app/web.1: WS: Authetication ID:  rd9irQciOmRkLS54AAAC  client:  Android_OpenAPS  history: 48 
Jul 30 02:01:00 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&sid=rd9irQciOmRkLS54AAAC" host=maria-cgm.herokuapp.com request_id=e97fceb8-8e2f-42f3-b2e6-d94b3f7f85fd fwd="87.203.121.205" dyno=web.1 connect=0ms service=1ms status=200 bytes=277 protocol=https 
Jul 30 02:01:00 maria-cgm heroku/router: at=info method=POST path="/socket.io/?EIO=3&transport=polling&sid=rd9irQciOmRkLS54AAAC" host=maria-cgm.herokuapp.com request_id=4c638880-ab18-4a11-8bfb-159777997dd5 fwd="87.203.121.205" dyno=web.1 connect=0ms service=1ms status=200 bytes=208 protocol=https 
Jul 30 02:01:01 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&sid=rd9irQciOmRkLS54AAAC" host=maria-cgm.herokuapp.com request_id=b7e9aa7b-088d-446c-ab85-67e395775139 fwd="87.203.121.205" dyno=web.1 connect=0ms service=7ms status=200 bytes=5057 protocol=https 
Jul 30 02:01:02 maria-cgm app/web.1: results.first size 3210 bytes 
Jul 30 02:01:02 maria-cgm app/web.1: results.rest size 16547 bytes 
Jul 30 02:01:02 maria-cgm app/web.1: WS: Authetication ID:  YcnZ3grHlWg7u9GhAAAD  client:  Android_OpenAPS  history: 48 
Jul 30 02:01:02 maria-cgm heroku/router: at=info method=POST path="/socket.io/?EIO=3&sid=YcnZ3grHlWg7u9GhAAAD&transport=polling" host=maria-cgm.herokuapp.com request_id=81ce1f83-ca7c-4416-8429-9a8ad5d31262 fwd="5.144.229.1" dyno=web.1 connect=0ms service=1ms status=200 bytes=208 protocol=https 
Jul 30 02:01:03 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=polling&sid=rd9irQciOmRkLS54AAAC" host=maria-cgm.herokuapp.com request_id=8edcb852-3ba3-4bbd-af61-28efe74e3d42 fwd="87.203.121.205" dyno=web.1 connect=0ms service=1171ms status=200 bytes=225 protocol=https 
Jul 30 02:01:04 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&sid=YcnZ3grHlWg7u9GhAAAD&transport=polling" host=maria-cgm.herokuapp.com request_id=f104dc49-06d2-4395-bea2-abe956b14c39 fwd="5.144.229.1" dyno=web.1 connect=0ms service=4ms status=200 bytes=5070 protocol=https 
Jul 30 02:01:05 maria-cgm app/web.1: GRANTED:  31.152.26.140 api-secret api:entries:read 
Jul 30 02:01:05 maria-cgm app/web.1: GRANTED:  31.152.26.140 api-secret api:entries:create 
Jul 30 02:01:05 maria-cgm app/web.1: got data-received event, requesting reload 
Jul 30 02:01:05 maria-cgm app/web.1: If-Modified-Since: Invalid Date Last-Modified 2018-07-30T09:00:59.545Z 
Jul 30 02:01:05 maria-cgm app/web.1: GRANTED:  31.152.26.140 api-secret api:devicestatus:read 
Jul 30 02:01:05 maria-cgm app/web.1: GRANTED:  31.152.26.140 api-secret api:devicestatus:create 
Jul 30 02:01:05 maria-cgm heroku/router: at=info method=POST path="/api/v1/entries" host=maria-cgm.herokuapp.com request_id=1e3e1a7c-f5f1-48d1-9a7b-dc9404ed6561 fwd="31.152.26.140" dyno=web.1 connect=0ms service=131ms status=200 bytes=527 protocol=https 
Jul 30 02:01:05 maria-cgm app/web.1: Error inserting the device status object quota exceeded 
Jul 30 02:01:05 maria-cgm app/web.1: WS: dbAdd client ID:  YcnZ3grHlWg7u9GhAAAD  data:  { collection: 'devicestatus', 
Jul 30 02:01:05 maria-cgm app/web.1:   data:  
Jul 30 02:01:05 maria-cgm app/web.1:    { device: 'openaps://LGE LG-D855', 
Jul 30 02:01:05 maria-cgm app/web.1:      openaps: { suggested: [Object], iob: [Object] }, 
Jul 30 02:01:05 maria-cgm app/web.1:      uploaderBattery: 92, 
Jul 30 02:01:05 maria-cgm app/web.1:      created_at: '2018-07-27T09:25:33Z', 
Jul 30 02:01:05 maria-cgm app/web.1:      NSCLIENT_ID: 1532683533945 } } 
Jul 30 02:01:05 maria-cgm app/web.1: /app/node_modules/mongodb/lib/utils.js:132 
Jul 30 02:01:05 maria-cgm app/web.1:       throw err; 
Jul 30 02:01:05 maria-cgm app/web.1:       ^ 
Jul 30 02:01:05 maria-cgm app/web.1: TypeError: Cannot read property 'ops' of null 
Jul 30 02:01:05 maria-cgm app/web.1:     at insertResult (/app/lib/server/websocket.js:371:26) 
Jul 30 02:01:05 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 02:01:05 maria-cgm app/web.1:     at session.endSession (/app/node_modules/mongodb/lib/utils.js:399:27) 
Jul 30 02:01:05 maria-cgm app/web.1:     at ClientSession.endSession (/app/node_modules/mongodb-core/lib/sessions.js:72:41) 
Jul 30 02:01:05 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:397:17) 
Jul 30 02:01:05 maria-cgm app/web.1:     at /app/node_modules/mongodb/lib/collection.js:626:14 
Jul 30 02:01:05 maria-cgm app/web.1:     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
Jul 30 02:01:05 maria-cgm app/web.1:     at executeCallback (/app/node_modules/mongodb/lib/utils.js:404:25) 
Jul 30 02:01:05 maria-cgm app/web.1:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:128:55) 
Jul 30 02:01:05 maria-cgm app/web.1:     at resultHandler (/app/node_modules/mongodb/lib/bulk/ordered.js:457:16) 
Jul 30 02:01:05 maria-cgm heroku/router: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=OtodDoxPfyGCKo67AAAA" host=maria-cgm.herokuapp.com request_id=7d872f9f-cb46-4a56-b446-06df8ff2e54d fwd="87.203.121.205" dyno=web.1 connect=0ms service=7453ms status=101 bytes=175 protocol=https 
Jul 30 02:01:06 maria-cgm heroku/web.1: Process exited with status 1 
Jul 30 02:01:06 maria-cgm heroku/web.1: State changed from up to crashed

**Comment by sulkaharo** [comment]
"Error inserting the device status object quota exceeded" -> Your Mongo database is full and probably all inserts are failing

**Comment by mdomox** [comment]
Nevertheless, my mongo db was 350 out of 500MB. It did not reach its 500MB quota. 
Now it is 290 MB.

**Comment by sulkaharo** [comment]
Can you try to repair the database as described in this link to see if the size goes down? https://www.google.fi/amp/s/davidburgos.blog/how-fix-quota-exceeded-mlab-mongolab/amp/

**Comment by mdomox** [comment]
Repaired the MongoDB. It eventually reduced the overall size by 100 MB and devicestatus collection now seems to grow in a reasonable rate.

**Comment by PieterGit** [comment]
Solution for this problem is being worked on by @jpcunningh . See PR https://github.com/nightscout/cgm-remote-monitor/pull/3751 . Closing this issue.
