### ISSUE TITLE
[Enhancement] Ability to store APS settings in Nightscout

### ISSUE THREAD

**Issue by Mackwe** [nightscout/cgm-remote-monitor#3760]
One of the biggest problems a (Closed or Open) looper can face is the loss or damage of their APS device. A (Loop or AAPS) phone can be stolen, an OpenAPS rig can be lost etc. Not to mention when you finally found the optimal settings for xDrip. Wouldn't it be really nice if these devices could store a settings backup in Nightscout? So if the worst happens, you could just type in the NS site & API secret, and all settings were restored onto a new hardware. Up and running again in seconds or minutes instead of hours and days.

Proposal:
* Create an empty DB collection called "apssettings" when NS is installed
* Create a receiving (POST) function i NS saving date (datetime), aps (string), device name (string), device type (short int), data (BSON or other suitable data storage), description (string) and verifiedcomplete (boolean)
* Create a backup management page for viewing what's there and possibility to delete single or multiple backups
* Create a (GET) function to request a certain type of backup "select * from apssettings where aps='aaps' AND devicetype=1 AND verifiedcomplete ORDER BY date DESC LIMIT 1" or similar to get the latest verified backup for the master phone. The aps string is to differ Loop from xDrip or AAPS. Device types/numbering can be chosen by the respective dev teams for the APSes i.e. 1 for AAPS master phone, 2 for NSClient follower etc.

Comments and suggestions apprechiated!  =)

**Comment by trixing** [comment]
I think this is a great idea.  Why wouldn't you store this in the existing profiles though?  Part of the APS settings are the correction factors, insulin type, etc after all.

**Comment by Mackwe** [comment]
Thanks!

To me profiles are already saved in NS. No need to save them again. And
separate them in order to save other apps' settings as well (xDrip an such).

// Marcus


Den ons 1 aug. 2018 14:09Jan <notifications@github.com> skrev:

**Comment by volkerrichert** [comment]
I also thinking about a good place to save APP configs (600Uploader) outside the app to easily restore them. NS could be a good place.
