### ISSUE TITLE
CAGE resets to N/A after more than 8 days

### ISSUE THREAD

**Issue by djzeratul** [nightscout/cgm-remote-monitor#3761]
Let me preface this with a caveat... This is a strange bug, and difficult to report since "nobody is supposed to leave their sites in for longer than 5 days, right?!?" There's like a stigma behind doing so and I don't need to hear any more lectures about lipos or infection risk. Sometimes you just... have to do it. Maybe you didn't reorder supplies on time. Maybe you're hard up and hurting for cannulas. Maybe the one you've had in for a week is still absorbing fine and your CGM can prove that. Please don't judge the context of the bug, but the actual bug itself. Anyway, I digress.

This happens any time a site change goes longer than 8 days. It appears to reset the cannula insertion date to Unix Epoch time = 0. I am UTC -8 so it says 4PM on 12/31/69.

To reproduce, have a site change logged that is older than approximately 8 days ago.

![image](https://user-images.githubusercontent.com/1778738/43552265-be1477c4-959e-11e8-86bf-7c7c960209c4.png)

**Comment by trixing** [comment]
This is due to the frontend only getting the last 8 days of history I believe. Try changing this line:

https://github.com/nightscout/cgm-remote-monitor/blob/881d3c6d4d42f1bb8fb156404ae1397514c156db/lib/data/dataloader.js#L149

**Comment by djzeratul** [comment]
hey thanks @trixing this fixed the issue!

![image](https://user-images.githubusercontent.com/1778738/43609672-84ce399e-9659-11e8-9c17-b2855f309db9.png)
