### ISSUE TITLE
Not possible to update

### ISSUE THREAD

**Issue by RayAmsterdam** [nightscout/cgm-remote-monitor#3838]
After updating my NS repository on Github to the latest version (v0.10.3) and restarting the dynos on Heroku, the app still stays on v0.10.2. Checking again for updates says I am up to date.
What can I do to effectuate the update?
![github update](https://user-images.githubusercontent.com/32841814/44100061-61eea938-9fe4-11e8-9152-3f28980e6b16.PNG)
![ns version](https://user-images.githubusercontent.com/32841814/44100133-9b90d148-9fe4-11e8-8a61-e0b86052b3fd.PNG)

**Comment by viderehh** [comment]
please clear your browser cache and try again

**Comment by RayAmsterdam** [comment]
Thanks viderehh. Unfortunately that doesn't help.

**Comment by sulkaharo** [comment]
Did you deploy the site in Heroku after updating the branch in Github?

**Comment by viderehh** [comment]
did you deploy it on heroku? i think you miss this part !?
please check your app activity > something with build ....
if not, you can deploy it manual or set it to automatic deploy.

**Comment by RayAmsterdam** [comment]
I indeed forgot to deploy.
Thanks!

**Comment by PieterGit** [comment]
Closing issue. User @RayAmsterdam forgot to deploy.  Good luck with 0.10.3.
