### ISSUE TITLE
editing or deleting treatments does not work with 0.10.3 and Chrome

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#3848]
page `/reports`, tab `treatments`:  When I edit or delete I see the following in the console. 

![image](https://user-images.githubusercontent.com/6500826/44370842-5b84f280-a4dc-11e8-8207-3bed3f8efe67.png)

The link redirects to https://www.chromium.org/developers/design-documents/create-amazing-password-forms
and on that page it's listed that `<input>`  should be in a `<form>`. 

I also saw a save username dialog. Don't know why the API_SECRET must be sent to the client. 
I'll look into this issue later. Saving it for future reference.

**Comment by unsoluble** [comment]
Also reported to fail in Firefox/Win.

**Comment by jpcunningh** [comment]
I checked both Firefox 63.0.3 and Chrome 70.0.3538.110 on Windows 10 and was unable to duplicate the issue. I don't mind digging into this one if you have some thoughts on how I can duplicate the issue.

**Comment by PieterGit** [comment]
Works with `dev` and Chrome version 70.0.3538.110 (Officiële build) (64-bits). 
Don't see the message in the console anymore. Closing issue.
