### ISSUE TITLE
To get the stats of today I need to put the day of tomorrow

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/cgm-remote-monitor#3852]
Is this normal? What Do I need to do to fix it?

![image](https://user-images.githubusercontent.com/608650/44425243-30a1a980-a583-11e8-9a42-5e9172816671.png)

**Comment by MilosKozak** [comment]
wrong timezone in profile

**Comment by parapenT1sta** [comment]
@MilosKozak Where Can I setup the timezone? I just can't find it :( Sorry
