### ISSUE TITLE
Day of Week & Date Mismatch on Reports

### ISSUE THREAD

**Issue by briandlucas** [nightscout/cgm-remote-monitor#3867]
**Is this a new bug with the latest release, have you seen this earlier?**
only version I've worked with - new user/install

**Which device / browser version was used to reproduce the bug?**
Firefox, Safari (iOS)
Firefox (Ubuntu)
Firefox (Win) 

**Does this happen every time you launch Nightscout, or sometimes?**
every time

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)
"Day to Day" and "Daily Stats" reports seem to have day of week and date mismatch.  For example, today is Sunday, August 26th but both reports show Sunday 8/25/2018, Saturday 8/24/2018 and so on.

"date" command on server (Ubuntu 18.04.1" reports "Sun Aug 26 17:12:07 UTC 2018"

![file-2](https://user-images.githubusercontent.com/14844635/44630937-16751c00-a933-11e8-87c7-9079107c18a8.jpeg)

**Comment by PieterGit** [comment]
@briandlucas what node version are you using?

**Comment by briandlucas** [comment]
just noticed time is off by 4 hours on the day to day report.  here in Florida, we are GMT-4 currently, so the 4 hour offset is clearly related.  However, server and client both report date/time/timezone correctly (see above for timdateclt output).

running console.log(new Date().toLocaleString()); in node gives me correct date/time:
2018-9-16 10:08:51

![screenshot_2018-09-16 97 -1](https://user-images.githubusercontent.com/14844635/45597352-eac8dd00-b998-11e8-9810-19b037e79b66.jpeg)

**Comment by briandlucas** [comment]
i've been running nightscout inside pm2 process manager - ran above date/time code inside pm2 and do get same/correct local time.

**Comment by steve8x8** [comment]
Living in CET, I also initially had the profile TZ set to UTC, and ended up with an apparent 23-hour shift. Report showed today with yesterday's values.

To me it seems that UTC ist handled wrong...
