### ISSUE TITLE
Display blue AR-based uncertainty cone when there are no recent treatments

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/cgm-remote-monitor#387]
Tirzah Heide Thank you, my son's did that this morning too. I have the iob branch now and dex drip, love being able to see what's really happening....

But, we really are not able to use care portal well, so would really prefer the blue prediction cone to the purple, so excited to see raw data more available
11 minutes ago · Like · 1

Scott Leibrand Hmm, good point Tirzah. Maybe we should update iob-cob to display the blue cone when no recent treatments have been entered...
a few seconds ago · Like
##

**Comment by Kdisimone** [comment]
@scottleibrand this issue can be closed now, correct?  the AR2 forecast can be shown regardless of whether there were recent treatments now....

**Comment by scottleibrand** [comment]
Sure.  Also, it's 3 years old, and we'd all forgotten about it.  ;-)
