### ISSUE TITLE
Target BG settings are not intuitive

### ISSUE THREAD

**Issue by bert1973** [nightscout/cgm-remote-monitor#3895]
Hi
As I'm new to Nightscout, doing a deploy to Heroku was a bit of a challenge.
You have to fill a lot of options before you are able to do a deploy.

Something I overlooked was the warning:  'Must be set in mg/dL (multiply with 18 if you have a value in mmol/L) for BG_HIGH/ BG_TARGET_TOP/ BG_TARGET_BOTTOM/ BG_LOW", resulting in reports with a very small green target rectangle.

As there's a lot of text to read the first time, isn't it better to convert the supplied BG values automatically by 18 if DISPLAY_UNITS = 'mmol'? or check if the values < 22? Or stop the deployment otherwise?

Next to that you are able to fill in the profile BG target, but that's standing apart from the variables used in the reports (the environment variables)? That's something that took me a while in hunting for the reason.

**Comment by unsoluble** [comment]
Yeah, I totally agree with this concern; it's a very common error in new setups. I'm sure it wouldn't be that onerous to get the app to treat values in those variables as mmol if the profile is set to mmol, but this would likely require digging through all the code and making sure we cover every instance.
