### ISSUE TITLE
Pebble MMOL settings issues

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#396]
http://www.nightscout.info/wiki/welcome/website-features says DISPLAY_UNITS = mmol doesn't apply to the Pebble and that seems to be the case.

The Pebble watchface has a units setting, but it doesn't actually change the units that are displayed, only the units used to configure the warnings. How the units are actually configured is not documented.

The undocumented way to get the data in mmols is by appending ?units=mmol to the end of the data source URL.

Things to do (?):

* Have DISPLAY_UNITS actually affect Pebble
* Have the API send over the units used for the data
* Have the setting in the watch face config actually change the units shown if changed to be different from the default

**Comment by ELUTE** [comment]
Appending ?units=mmol is documented. Both in the pebble config itself and nightscout.info site.

**Comment by sulkaharo** [comment]
I guess there's multiple pebble pages for the watchface in that case? The page linked to from the docs, which I used as reference, doesn't mention this.



—

**Comment by jasoncalabrese** [comment]
We should fix the pebble to use the `DISPLAY_UNITS` setting, the units parameter could be an override

**Comment by YYGIRL** [comment]
It would break backwards compatibility. Many people still use versions that
don't have a config file. Plus we don't have room in the message going down
to the watch.

On Tue, Feb 3, 2015 at 7:25 PM, Jason Calabrese <notifications@github.com>
wrote:

> We should fix the pebble to use the DISPLAY_UNITS setting, the units
> parameter could be an override
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/issues/396#issuecomment-72766426>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by jasoncalabrese** [comment]
Think a typo in my comment confused things, the pebble **endpoint** should use the `DISPLAY_UNITS` setting, for backwards compatibility we can still support the `units` parameter.

**Comment by YYGIRL** [comment]
Got it, thanks.

On Tue, Feb 3, 2015 at 7:55 PM, Jason Calabrese <notifications@github.com>
wrote:

> Think a typo in my comment confused things, the pebble *endpoint* should
> use the DISPLAY_UNITS setting, for backwards compatibility we can still
> support the units parameter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/issues/396#issuecomment-72769648>
> .
>



-- 
*Join the Jack Attack!*
*Fight Type 1 Diabetes*
*Give to the JDRF - **www.jdrf.org* <http://www.jdrf.org>

**Comment by jasoncalabrese** [comment]
Think this is done, but we should verify

**Comment by jasoncalabrese** [comment]
I verified that this is done, the `DISPLAY_UNITS` env is used in `/pebble` now so your don't need to use `?units=mmol` anymore.   If it's set it will work as an override.

@ELUTE, @jimsiff, can we update the docs to remove `?units=mmol` and have users set `DISPLAY_UNITS`.
