### ISSUE TITLE
Delta not showing up on Fitbit watch faces 

### ISSUE THREAD

**Issue by philabetes** [nightscout/cgm-remote-monitor#3962]
I’m using my Dexcom g5 app on iOS to upload to heroku for my Nightscout site.  On my Fitbit, the delta isn’t showing. But BG values and trend line work fine. Delta shows up on Nightscout fine.  

Essentially, My sgv.json endpoint is not including a "delta" output even though a delta is showing up on my nightscout site. 

Not sure if this is related to a new release, just got the Fitbit versa this weekend. 

Fitbit watch faces include glance and marclock. 

See screen shots attached.  Wait. Now do I upload screenshots to this post?

**Comment by cramis1** [comment]
Hi Phil, did you ever find a solution to this problem?

**Comment by sulkaharo** [comment]
This would be a missing feature on the Fitbit watchface and not a Nightscout bug. The recent delta information calculation is available over REST at /api/v2/properties - you might want to pass this information to whomever has made the Fitbit watchface implementation.

**Comment by philabetes** [comment]
Hey, I forget how it was fixed, but I don't have this problem anymore!

*Phil*

**Comment by PieterGit** [comment]
Rerporter @philabetes says issue is fixed. The issues wasn't a Nightscout issue, but a Fitbit watchface issue. Closing issue.
