### ISSUE TITLE
Color of dots

### ISSUE THREAD

**Issue by BartoszJedynak** [nightscout/cgm-remote-monitor#3984]
Hi, 
i'll try edit theme colors of dots, in earlier versions that was in lib\client\index.js now when i'll edit this file nothing happend. 
I will be grateful for any help
Best regards 
Tom

**Comment by BartoszJedynak** [comment]
i'm not editing color names, only color of mediana, after Deploy nothing changing

**Comment by unsoluble** [comment]
Can you be more specific about what exactly you’re changing in the code?

**Comment by BartoszJedynak** [comment]
function sgvToColor(sgv) {
    var color = 'grey';

    if (client.settings.theme !== 'default') {
      if (sgv > client.settings.thresholds.bgHigh) {
        color = 'red';
      } else if (sgv > client.settings.thresholds.bgTargetTop) {
        color = 'yellow';
      } else if (sgv >= client.settings.thresholds.bgTargetBottom && sgv <= client.settings.thresholds.bgTargetTop && client.settings.theme === 'colors') {
        color = '#4cff00';
      } else if (sgv < client.settings.thresholds.bgLow) {
        color = 'red';
      } else if (sgv < client.settings.thresholds.bgTargetBottom) {
        color = '#0016c3';
      }


this is from my 0.9.2

**Comment by unsoluble** [comment]
Just made that exact change on a clean 0.10.3-master deployment, and it worked as expected:
![screen shot 2018-10-26 at 7 19 02 am](https://user-images.githubusercontent.com/801582/47572295-7bc39a00-d8ef-11e8-84fb-f4df08c4b84d.png)

Something else must be going on with your particular setup.
