### ISSUE TITLE
double measurements?

### ISSUE THREAD

**Issue by oliwierkobiak** [nightscout/cgm-remote-monitor#3994]
can anyone help?
for 2 days, nighwcout shows me double measurements (as if some have been broken). I use Freestyle Libr + had a + xdrip
![img_0525](https://user-images.githubusercontent.com/13902431/46908158-c53edd00-cf1e-11e8-9af5-58b3221741b9.PNG)
![img_0524](https://user-images.githubusercontent.com/13902431/46908159-c53edd00-cf1e-11e8-96bf-e278d6c69b58.JPG)

**Comment by PieterGit** [comment]
@oliwierkobiak please check if they aren't xdrip+ cgm's that re-uploads cgm values.
You can also use mlab UI or Robo 3T (formerly Robomongo) https://robomongo.org/ to see which device is uploading these values.

**Comment by oliwierkobiak** [comment]
OK, i see the dots are from glimp

 

 Krzysztof Kobiak
gsm: 
email:
www:500 045 889
k.kobiak@tukobi.pl
tukobi.pl

 

 
 

 

Od: PieterGit <notifications@github.com>
Odpowiedź do: nightscout/cgm-remote-monitor <reply@reply.github.com>
Data: sobota, 13 października 2018 23:41
Do: nightscout/cgm-remote-monitor <cgm-remote-monitor@noreply.github.com>
DW: "admin@tukobi.pl" <admin@tukobi.pl>, Mention <mention@noreply.github.com>
Temat: Re: [nightscout/cgm-remote-monitor] double measurements? (#3994)

 

@oliwierkobiak please check if they aren't xdrip+ cgm's that re-uploads cgm values.
You can also use mlab UI or Robo 3T (formerly Robomongo) https://robomongo.org/ to see which device is uploading these values.

**Comment by PieterGit** [comment]
@oliwierkobiak can you post two records with the same timestamp? If they are from the same Glimp uploader, then I assume it's not a Nightscout issue, but a glimp uploader issue and you should ask the Glimp devs.
