### ISSUE TITLE
Grammar/Syntax

### ISSUE THREAD

**Issue by Trusties13** [nightscout/cgm-remote-monitor#400]
This is probably one of the easiest 'issues' that you can be given. Being the self-professed 'grammar nazi' I've located a minor syntax error that can be easily resolved.

On the 'settings' sidebar that appears on the right hand side of the page, when hovering over the question mark next to "Enable Alarms" the following text is readable: "When enabled the an alarm may sound."

Minor thing, I know! Caught my attention and thought I'd share.

Thanks for such an awesome solution to remote monitoring. Cheers.

![screen shot 2015-02-08 at 21 47 53](https://cloud.githubusercontent.com/assets/10569958/6096269/85796f38-afdc-11e4-84a1-c686a0557e63.png)

**Comment by scottleibrand** [comment]
Sounds like the perfect thing for your first code commit and pull request. :-)

Your mission, should you choose to accept it, is to go into GitHub, find that string in your personal copy (fork) of the cgm-remote-monitor repo, and edit it right there in the web interface. Then save the changes, do a comparison to the Nightscout code, and submit a pull request to incorporate your change. 

Let us know if you run into any trouble. 

Scott

**Comment by Trusties13** [comment]
Thanks Scott.

Wow! That was totally different to anything I have ever done before! Interesting experience - thanks for pointing me in the correct direction. I've submitted a pull request and will see what happens from here.

Cheers,
David
