### ISSUE TITLE
Time zone list problems

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#4003]
The timezone list in the profile editor is a mess, and should be replaced with a simplified list that is known to work. I don't know the history behind where this list came from, or why it was incorporated — am assuming it's just been grabbed wholesale from another source — but we should probably look into finding a better one.

Two major issues:
1. It's way too long. There are 38 distinct time zones in the world at the moment, and over 600 in this list.
2. Some of the common zones don't work as users assume they will. "EST" and "MST", for example, don't actually work as expected; users must choose "US/Eastern" or "US/Mountain" instead.

If anyone close to the original implementation of this would like to comment on the history and rationale of the existing list, I'm all ears. Willing to investigate alternatives though, if there's no good reason to keep this set.

**Comment by PieterGit** [comment]
@unsoluble I don't know about the history of the time zone list and making it a cleaner implementation is always a good idea. I assume the current list is based on `moment-timezone`, https://github.com/nightscout/cgm-remote-monitor/blob/master/package.json#L81-L82. 

That packages uses the standard is the IANA time zones (see https://www.iana.org/time-zones or https://en.wikipedia.org/wiki/Tz_database).  According to the `moment-timezone` source it's IANA version 2018e (see https://github.com/moment/moment-timezone). This is the latest official version.

Perhaps there is a better TimeZone picker, e.g. http://timezonepicker.com/ that we can use. Please search for a well-maintend package on https://www.npmjs.com/search?q=keywords:timezone

**Comment by unsoluble** [comment]
Hmm. The `moment-timezone` library looks good, we'd just need to either find a smaller data source that it can import or do our own work to build a custom subset before passing it to the UI. Can't see an easy solution right now, but will keep poking around.

**Comment by PieterGit** [comment]
@unsoluble I think it would be best to change the UI to first select a country, and then the timezones within that country, similar to the pulldown box implementation of http://timezonepicker.com/  . I don't think the map view in that example has a lot of added functionality for us.

**Comment by PieterGit** [comment]
Postponing to 0.12.0.
@unsoluble still interested in improving the UI as suggested at https://github.com/nightscout/cgm-remote-monitor/issues/4003#issuecomment-430805353 ?

**Comment by unsoluble** [comment]
Yeah I'll take another look at this eventually.

**Comment by 4gra** [comment]
I'll note that it's not just "esoteric" time zones that are broken - I've been having odd problems while set to UTC, including silently broken reporting output (unrecognisable data presented in reports, presumably from other dates / times).  This is with an entirely self-hosted nightscout & mongodb.

Given than UTC is, well, the UTC, it should surely work correctly even with limited or no working timezones ...
