### ISSUE TITLE
Prediction cone values are different in MMOL setting

### ISSUE THREAD

**Issue by baswieb** [nightscout/cgm-remote-monitor#402]
The prediction cone looks different in MMOL setting because the BG values are rounded to integer values. When the values are rounded to 1 decimal the prediction values look better in MMOL setting.

**Comment by jasoncalabrese** [comment]
@baswieb I think I have a fix, do you know how to test with different branches?  I opened a PR with the fix #405

**Comment by jasoncalabrese** [comment]
Will be part of the 0.6.3 release that will hopefully be out very soon

**Comment by baswieb** [comment]
@jasoncalabrese Thanks! It's fixed
