### ISSUE TITLE
Add a report with just the numeric values of the sensor readings.

### ISSUE THREAD

**Issue by kusuriya** [nightscout/cgm-remote-monitor#4041]
---
name: "Feature request"
about: Add a report with just the numeric values of the sensor readings.

---

One of my providers is not a huge fan of charts and graphs and would prefer to be drowned in the displayed BG value that makes up the datapoint on the graph, and would like just a basic chart of them.

**Describe the solution you'd like**
The basic gist of the solution is to have a tab that lets me create a chart that looks something like

| Date/Time | Blood Glucose Value |
| --- | --- |
| 10/19/2018 13:03 | 230 |
| 10/19/2018 13:07| 242 |

**Describe alternatives you've considered**
I tried to just extract the data straight from mongodb but its a bit cumbersome to try and teach my provider how to do that and could be dangerous.
If there was an API or advanced search functionality that I could feed raw mongodb queries too I could make that work as well

**Comment by sulkaharo** [comment]
There's already an API for this - try loading http://localhost:1337/api/v1/entries.csv?find[dateString][$gte]=2015-08-28&find[dateString][$lte]=2015-08-30 (replace csv with tsv if tab separated files are better)

**Comment by kusuriya** [comment]
Nice, any reason we couldn't expose this on the reports page?

**Comment by sulkaharo** [comment]
Sure, wanna PR in a feature? ;)

**Comment by kusuriya** [comment]
Funny enough i've been looking at just that and am trying to figure out the codebase to do it. I'm not that awesome at webdev
