### ISSUE TITLE
Remove sgvdata and mqtt or upgrade and maintain it

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4046]
Follow up on: https://gitter.im/nightscout/public?at=5bde0b3a5905a919554c36e3

Current sgvdata module has the following issues:
- it has a small security issue with protobufjs that needs to be upgraded
- it's not a npm package, but uses git://github.com/ktind/sgvdata.git#wip/protobuf
- it's not maintained
- the code is hard to grasp

I tried upgrading it and integrated it back into Nightscout. If integrated with Nightscout it fails on a mqtt test of Nightscout that uses the possibility to use dexcom hexcoded string into json. See code at 
https://github.com/ktind/sgvdata/pull/1

```
  it('should parse protobuffers', function () {
    // based on Nightscout tests/mqtt.test.js
    var pb = require('../').sync.protobuf;
    var payload = new Buffer('0a1108b70110d6d1fa6318f08df963200428011a1d323031352d30382d32335432323a35333a35352e3634392d30373a303020d7d1fa6328004a1508e0920b10c0850b18b20120d5d1fa6328ef8df963620a534d34313837393135306a053638393250', 'hex');
    var result = pb.parse(payload);
    result.direction.should.equal('NONE');
  });
```

it fails with:

```
$ make
NODE_ENV=test node_modules/.bin/mocha --require blanket  -R 'travis-cov' tests/*test*.js
Tests failed.

Error: Illegal wire type for field Message.Field .Practical8601.direction: 2 (0 expected)Error: Illegal wire type for field Message.Field .Practical8601.direction: 2 (0 expected)
    at Field.ProtoBuf.Reflect.FieldPrototype.decode (node_modules\protobufjs\dist\protobuf.js:3704:23)
    at Message.ProtoBuf.Reflect.MessagePrototype.decode (node_modules\protobufjs\dist\protobuf.js:3263:45)
    at Function.Message.decode (node_modules\protobufjs\dist\protobuf.js:2952:37)
    at Function.parse (lib\protobuf.js:49:19)
    at Context.<anonymous> (tests\test_protobuf.js:46:21)
make: *** [Makefile:6: travis-cov] Fout 1
```

If nobody uses the `text` and `csv` uploads for entries (see https://github.com/nightscout/cgm-remote-monitor/blame/7c272ec67a7795e0f4edf7ff9abdfac1bd1308a0/lib/api/entries/index.js#L169-L202 ), I would like to propose to remove that code and force uploaders to use `json` starting with Nightscout 0.11. This way we can completely remove the `sgvdata` dependency (and do not worry about the other issues).

According to @ecc1 it's not used for Loop and Openaps.

Thoughts?

**Comment by sulkaharo** [comment]
AFAIK we don't have any users who use MQTT - if this is only used in for MQTT, we should be able to remove both this and MQTT support to make the system more maintainable. @bewest and @jasoncalabrese might have some insight on whether the subsystem is actually used at all?

**Comment by jasoncalabrese** [comment]
I think it was only Ben and Kevin that used MQTT, and that support for it could be dropped, and then remove the dependency on sgvdata

**Comment by bewest** [comment]
Sorry for the legacy code, I suppose!  A few notes:

* the text and csv modules, I believe *are* used by Nightscout.  The Nightscout API has a feature that can negotiate content-types, and can produce valid CSV, and TSV values for the core glucose API.

There's a lot of value in simple text export; for awhile it made it trivial to copy/paste directly from browser into a spreadsheet.  In addition it's easier to import into spreadsheets using the built-in functions using these features.  As the de facto API for diabetes data, I whole point of REST, REpresentational State Transfer, is the ability to negotiate among many potential content-types to automatically find the best fit for the use case at hand.

I won't argue that the code is hard to read; I was in love with streams at the time, and the content-type behavior could probably be refactored to work better and be more clear.  There's a hacky feature that allows co-ercing content-types based on extension... try adding `.txt`, `.tsv`, `.csv` to different API endpoints versus feeding them a `content-type` header.

### MQTT, Long Live distributed pub-sub
@rnpenguin, @ktind and I added MQTT as an android-uploader feature.  I used it exclusively for almost two years.  The MQTT infrastructure has things like decentralized backups and co-ordinated event responses that provide a lot of leverage in the ecosystem Nightscout participates in.  https://jamorham.github.io/ describes "mesh" networking that an MQTT foundation makes easy.  For example, MQTT could be used to coordinate between several local openaps rigs running NS locally and a cloud-backed NS.  Of course, websocket clients, already built into NS could perform the same purpose, but MQTT allows outsourcing this logic to a third party broker which offers additional failover logic.

The core technology is not nearly as important as the impact to its users.  If MQTT is considered harmful to the codebase or to its users, remove it.  When I used a custom MVNO cell service, I found usage of protobuf+MQTT turned 60+MB/month into < 10, and found that it made more sense when architecting a potential multi-tenant, hosted version of NS.  For individual installs, it's conceptually interesting in setups like @jamorham's where a broker can coordinate responses from many agents.  However, it does require some technical burden to support questionable for most single-tenant use cases unless cost is a major issue.

Much ❤️ !

**Comment by PieterGit** [comment]
@sulkaharo If we want drop mqtt but keep .txt, .tsv and .csv support (I didn't use it ever but I agree it's a nice REST feature), we should work on minimizing https://github.com/ktind/sgvdata/pull/1 or reimplement the other formats without the old prototypejs version. I tried to fix/upgrade sgvdata, but failed. If others want this, please help (e.g. by forking the PR into a minimized version). I think we all can agree that raw dexcom hex uploads for entries can be removed for now. Other dexcom parsing modules are maintained, and I don't see a volunteer for maintaining dexcom format in prototypejs for now.

**Comment by bewest** [comment]
@PieterGit, many thanks for driving change here.  You/someone should prepare a pull request you wouldn't mind maintaining.

MQTT isn't being used: I'm fairly certain I was the only one taking advantage of this.  It's safe to remove.
Multi-tenant aspirations are better served by through explicit support.  Given @howardlook's and Insulet's recent announcements, I remain more hopeful than ever on opportunities here.

If you submit a pull request simply ripping out sgvdata, leaving json functions, this leaves two feature requests from the glucose-specific legacy API:
  * negotiate content-type according to header
  * coerce content-type according to extension

When we look at this decision in 2018, with a prospectus towards 2019, if CSV and TSV export is allowed, it makes sense to make it consistent across as many data types as possible.  My recommendation is to ensure that copy/pasting into a spreadsheet and using command line tools remains "easy" and consistent across the API with text and csv exports if possible.  However, `sgvdata` is not needed to accomplish this, appropriate middleware and versioning schemas can go a long way here.  In fact some of my work here in our API was informed by my time at Tidepool: is there anything in data formatting that can be leveraged from Tidepool?

You've provided excellent maintenance of Nightscout.  If I were in your shoes, I might rip out sgvdata, and work on REpresentating State Transfers as separate feature requests, more focused on data modeling across the board and making "standardized" treatments available as CSV and TSV and JSON as well as "core glucose."  Ripping out sgvdata means we can tackle these problems through middleware and formatting without the complicated code and dependency on MQTT.

Great job! You have plenty of support to do whatever you must.

**Comment by PieterGit** [comment]
See PR https://github.com/nightscout/cgm-remote-monitor/pull/4091 for the implementation. I first started ripping out mqtt and svgdata. The CVS/TSV export stuff still must be reimplemented without a call to `svgdata`.

**Comment by PieterGit** [comment]
Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4091
