### ISSUE TITLE
Hyperlink to GVI and PGS explanations doesn't work anymore

### ISSUE THREAD

**Issue by Kywalh** [nightscout/cgm-remote-monitor#4050]
**Describe the bug**
Link to GVI explanations doesn't work anymore
![screenshot_20181105-232216_1](https://user-images.githubusercontent.com/28366579/48030644-0c04a900-e152-11e8-98e9-fa446384ddd7.jpg)

**Comment by PieterGit** [comment]
Fortunately the Internet Archive has stored a copy of the healthline.com page. 
It can be found        https://web.archive.org/web/20160523152519/http://www.healthline.com/diabetesmine/a-new-view-of-glycemic-variability-how-long-is-your-line

**Comment by PieterGit** [comment]
Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4052 and merged to dev.
Will be part of the Nightscout 0.11 release.
@Kywalh Thanks for reporting.

**Comment by Kywalh** [comment]
I found it too.... Only reporting this as a "bug"...
 Very small one...

**Comment by PieterGit** [comment]
@Kywalh Small bugs must also be reported and also be fixed. Fixing it was more work than I expected because the URL was part of all the translations. Refactored that.

**Comment by Kywalh** [comment]
Thanks !!!
