### ISSUE TITLE
Use share2nightbridge npm module instead of git URL and maintain share2nightbridge

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4051]
**Describe the bug**
Current share2nightbridge does not use an npm module, but a git-style URL.
This is a (minor) security issue, because changes to Git will deploy a new version to users.
Npm best practices is to release/publish a npm module and use semver versioning for new versions.

**To Reproduce**
see `package.json`, which links to 
`share2nightscout-bridge` to `git://github.com/nightscout/share2nightscout-bridge.git#wip/generalize`
see https://www.npmjs.com/package/share2nightscout-bridge for older share2nightscout-bridge version.

**Expected behavior**
All Nightscout dependencies in `package.json` should link to npm modules that are maintained.
Options are:
1. I hope @bewest is willing to transfer share2nightscout-bridge to a npm Org account for Nightscout.  Then we can release/publish `share2nightbridge` to npmjs.com from https://github.com/nightscout/share2nightscout-bridge
2. Fork/rename to another name and release/publish that to npmjs.com. For example, rename to share-to-nightscout-bridge in 0.11

**Additional context**
- The code has been migrated from https://github.com/bewest/share2nightscout-bridge  to https://github.com/nightscout/share2nightscout-bridge
- I sent several emails and gitter message to @bewest for several months  but didn't get a response yet.
- As far as I know none of the core comitters of Nightscout use share2nightscout-bridge, so looking for a new maintainer of this part of the code and looking for testers that can test PR's that use this module. Please reply if you're interested.
- I'm not currently using share2nightscout-bridge, but might be a user quite soon with a Dexcom G6.

**Comment by bewest** [comment]
Transferred.

**Comment by PieterGit** [comment]
@bewest Great. Thanks. I will publish a new version of share2nightscout-bridge and integrate it into Nightscout 0.11 later. Thanks! Closing this issue.
