### ISSUE TITLE
Profile edit not working

### ISSUE THREAD

**Issue by vickster1** [nightscout/cgm-remote-monitor#4056]
**Describe the bug**
I open my profile edit page. It takes 30s to load. Sometimes the drop down option to choose a different profile to edit is shown, other times it is missing (pic where it is missing attached).

Scroll down the page, and it is a blank, black screen, which loads after another 30-60secs.
I choose a feature to edit, and click on it. I get no response. I wait, and usually the cursor shows after a while. 
However, editing remains very difficult - either the page doesn’t respond, or I make a change and it immediately reverts to the original page shown when I opened it.
If I keep trying I can generally get to make a few changes over 15 minutes- at most 3 or 4 in this time, and sometimes none.

**Your setup information**
- What version of Nightscout: dev 0.11.0, but I’ve had this with 0.10.3 & older versions. I saw it in 2016 & 2017, but then it was occurring on my Samsung phone & worked mostly OK on desktop & Apple devices.
- What type of CGM, and how do you get your data there? Dexcom G5 & xdrip+ on Sony mobile phone
- Is your issue specific to a browser: see above - previously it was but now affects all browsers

I have ensured my mlab database is compressed on disk & deleted device status entries.

![ffbb72cd-ced8-4582-9632-42efb022b064](https://user-images.githubusercontent.com/38795035/48199687-cebc3900-e354-11e8-970c-f5ede2686867.jpeg)

**Comment by DigitalDan1** [comment]
I've had the same problems.  I'm pretty sure my change (https://github.com/nightscout/cgm-remote-monitor/pull/4074) will fix it.

**Comment by vickster1** [comment]
Also fixed in latest Dev from today 😀

**Comment by PieterGit** [comment]
Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4074
