### ISSUE TITLE
Broken link on report

### ISSUE THREAD

**Issue by whooze** [nightscout/cgm-remote-monitor#4059]
The link http://www.healthline.com/diabetesmine/a-new-view-of-glycemic-variability-how-long-is-your-line#2 is broken.

Can be found on <yournightscouturl>/report the Distribution-tab

**Screenshots**

![image](https://user-images.githubusercontent.com/4024639/48233016-ed055180-e3b3-11e8-895e-b1659d4387c0.png)

**Your setup information**
Should be the same problem on earlier versions too

**Comment by nealgriffin** [comment]
Hi there - I'm actually interested in helping out on this repository and this is a pretty straightforward change - I'll submit the required PR to the maintainers, but wanted to ask if there was / should be a different link referenced here, if so can you paste the link needed? Thanks

**Comment by PieterGit** [comment]
@whooze @nealgriffin I already fixed this with https://github.com/nightscout/cgm-remote-monitor/pull/4052

@sulkaharo suggested to use this link https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5467104/
I think the healtline article is easier readable, but of course the ncbi article is more scientific approach. 

@nealgriffin If you want to PR a change that includes both links, please do.

**Comment by nealgriffin** [comment]
@PieterGit beauty! I'll do that - let me get myself setup - thnks

**Comment by PieterGit** [comment]
@nealgriffin Are you still interested in fixing/improving this PR? This is a nice beginner task to improve the docs in the code. If you need help, please visit https://gitter.im/nightscout/public
Postponing to 0.12.x release for now.
