### ISSUE TITLE
API bug: DELETE devicestatus and treatsments

### ISSUE THREAD

**Issue by VladislavLasmann** [nightscout/cgm-remote-monitor#4080]
Using the Nightscout-API to delete the types **devicestatus** and **treatsments** we noticed that the function remove(_id, fn) doesn't work properly. The delete seems to have no effect.

------------------------------------------
**Treatments:** 
 _[https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/server/treatments.js](url)
Line: 100_
The original code looks like this:
`function remove (_id, fn) {
    api( ).remove({ '_id': new ObjectID(_id) }, fn);
    ctx.bus.emit('data-received');
}`

Our solution:
`function remove (_id, fn) {
    api( ).remove({ '_id': _id }, fn);
    ctx.bus.emit('data-received');
}`

**Devicestatus:**
 _[https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/server/devicestatus.js](url)
Line: 62_
The original code looks like this:
`function remove (_id, fn) {
    var filter;
    if (_id === '*') {
      filter = {};
    } else {
      filter = { '_id': new ObjectID(_id) };
    }
    return api( ).remove(filter, fn);
  }`

Our solution:
`function remove (_id, fn) {
    return api( ).remove('_id': _id , fn);
  }`

------------------------------------------
Using this fix, the delete function works.

**Comment by jpcunningh** [comment]
@VladislavLasmann, I believe that would break the ability to delete all of the devicestatus records as used in the admintools.

**Comment by jpcunningh** [comment]
#4088 should correct this issue.

I'm not sure why it doesn't work as it was written. I don't believe the PR should cause a different result, but it works and preserves the benefits of using ObjectID and the '*' option for devicestatus.
