### ISSUE TITLE
Add an option to delete a set number of days of treatments in NS Admin Tools

### ISSUE THREAD

**Issue by DrVoles** [nightscout/cgm-remote-monitor#4095]
Hi there.

Quick query.

I have a Nightscout site, hosted by Heroku.

I use AndroidAPS. This results in A LOT of data.

Every now and then I have to clear devicestatus using admin tools of NS. This often helps and then I can compact my database. 
If i don't do this from time to time, I can't upload my data to nightscout.

Unfortunately, it didn't work this weekend, and on looking into the issue further - it was because my treatments collection was too large....

As far as I can tell, the only way to delete only a portion of this data would be to learn gui or shell or something I don't have the spare time to learn....

I was wondering if in the next version, the Devs would be willing to put an admin tool to delete x number of days of treatments (just as they have for device statuses) - there are plenty of people using NS with androidAPS who would benefit a lot from this small change.....

**Comment by DrVoles** [comment]
Or even better: a checkbox to auto-purge all data older than 90 days.

**Comment by DrVoles** [comment]
Yep, that would be a good way of doing. Anything which makes it easy to clear old data without touching the relevant, new data.

**Comment by jpcunningh** [comment]
PR #4090 adds treatments and entries sections to delete all but a user provided number of days.

They are separate sections so the user can choose to retain a different number of days for treatments, devicestatus, and entries.

**Comment by DrVoles** [comment]
I can only assume I'm being a little bit dense - how do I select the PR #4090  to try out?

**Comment by jpcunningh** [comment]
@DrVoles, it's not trivial.  I have a cloned of my github account cgm-remote-monitor fork on a Linux VM that I can checkout PRs to (google `git checkout pr locally`).

Once it's checked out, I can create a local branch from it and push the new branch to my github account's fork.  After the branch is in my cgm-remote-monitor, I can selected it on the Heroku deployment page.

There may be an easier way to get there, but I haven't found it, yet.
