### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by jweismann** [nightscout/cgm-remote-monitor#4098]
Please see https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream. I just downgraded to 3.3.4 and deployed to two heroku dev sites with success. Please do the same for the upstream version (I can create a PR but seems like overkill).

**Comment by viq** [comment]
`master` is not affected, and `dev` was fixed with f47c6c3979a9fe053e98f841a769381f26dbd777

**Comment by jweismann** [comment]
@viq Thanks. Closing this. 
@bewest Interesting ideas and thoughts. Thanks for sharing.
