### ISSUE TITLE
Incorrect day graph on Day to day

### ISSUE THREAD

**Issue by LubomirKovalcik** [nightscout/cgm-remote-monitor#4103]
**Describe the bug**
Day to day shows graph for incorrect day - one day off 
![image](https://user-images.githubusercontent.com/15881431/49235693-f1dd8400-f3fa-11e8-88ca-3faadc14c17c.png)

**To Reproduce**
1. Go to 'Day to Day stats'
2. Apply From Date and To Date filter
3. Apply target range filter
4. Click on show

**Expected behavior**
Should show graph for 28.11., but shows graph for 27.11.

**Your setup information**
- version 0.10.3-master-20180805
- Xdrip+ (libre with miaomiao) to nighscout hosted on heroku

**Comment by sulkaharo** [comment]
Can you check what time zone you have in your treatment profile store in Nightscout and verify the uploader and your computer are on the same time zone

**Comment by LubomirKovalcik** [comment]
Thank you,
 there was incorrect time zone set in profile, so that fixed the problem. 

Only thing I was not able to find easily was profile editor, but its under link "yournighscoutpage.herokuapp.com/**profile**"
