### ISSUE TITLE
Heroku deploy failed with "Archive URL not found" message

### ISSUE THREAD

**Issue by lashto** [nightscout/cgm-remote-monitor#4112]
Failed to deploy to heroku using the button

**To Reproduce**
Click the "Deploy to Heroku" button.

Worked few days ago , now fails with "Archive URL not found" message

**Your setup information**
Current version , tried different browsers, tried PC/tablet
Tried direct , tried fork 

![heroku](https://user-images.githubusercontent.com/8645338/49334816-de434080-f5e7-11e8-84ea-c821a68bfeec.png)

Thanks in advance,

**Comment by unsoluble** [comment]
This was a Heroku-side issue that has now been resolved. Try the deployment again, should work.

**Comment by sulkaharo** [comment]
Given Heroku says this is resolved and reporter not coming back, assuming this is resolved.
