### ISSUE TITLE
Alexa Spanish translations

### ISSUE THREAD

**Issue by x3nr1qu3x** [nightscout/cgm-remote-monitor#4121]
Hi!

I'm newbie here, and I do not know if I'm writing this in a good place

I got a Amazon Echo (Alexa), and i had tried the alexa plugin in my nightscout, but there are some answers that it says in English

Can someone help me for explain me how i can translate these answers? I can do it but i need someone that explains me how do it.

Thanks.

**Comment by nmorande** [comment]
Looking for the same: trying to have a translated skill for nightscout in Alexa. Any manual on how to do it?

**Comment by PieterGit** [comment]
@x3nr1qu3x @nmorande Have a look at the other `speech-alexa` issues/PR's (both open and closed). The Alexa plugin not only needs translations but also quite some refactoring unfortuately. So improvements are postponed until 0.12 for now.

**Comment by PieterGit** [comment]
@x3nr1qu3x  @nmorande Please check https://github.com/nightscout/cgm-remote-monitor/pull/4980 and help test the new Alexa codebase.

Closing this PR. Feel free to reopen if Alexa is maintained.
