### ISSUE TITLE
Nightscout crash on profile data upload

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#4126]
See last comments on https://github.com/openaps/oref0/issues/965

This is a strange error, since the crash can only occur if the profile insert failed silently (the created data object is null, but also no error was returned).

**Comment by philipgo2** [comment]
Thank you for looking into this and creating a new ticket @sulkaharo 

I found the cause of the error: My prior profile names contained special characters (`.`, e.g. `Basal rate red.`) leading to strange behavior. 

When using the Nightscout profile editor there was no problem at all, but I was unable to upload any profile using the `oref0-upload-profile`command. 

When trying to copy the profile collection to another database in 3T Studio the program threw an error. After manually removing all special character using the Nightscout profile editor I can now copy the collection and also upload profiles using the `oref0-upload-profile` command. (I self-host my MongoDB, but I could recreate the same behavior using the free MLab database).

Should there be a mechanism in Nightscout to prevent using special characters in profile names or could the way they are saved be changed to allow special characters?

**Comment by sulkaharo** [comment]
Aaah right, yes that sounds like there's some code somewhere that doesn't properly escape the strings. Preventing dots shouldn't be necessary. Do you know at which point the profile breaks? Is it that the profile works inside Nightscout with dots, but breaks during the OpenAPS import/export process?

**Comment by philipgo2** [comment]
It works flawlessly within Nightscout, but there already seems to be an error in the database at that point since I am unable to copy the profile collection using 3T Studio as soon as a profile name contains dots. `oref0-upload-profile` never works when an existing profile name contains dots.
