### ISSUE TITLE
Feature request:  Add Carbs, Bolus, and Total Insulin Consumed on Daily Stats report

### ISSUE THREAD

**Issue by msinkovich** [nightscout/cgm-remote-monitor#4132]
Based on my recent visit with my endo he asked if this was available and I cannot see it via the canned reports.  Would it be possible to add these as columns to the Daily Stats report?

**Comment by marionbarker** [comment]
I was also looking for this.  I typed things from the Day-To-Day with Insulin Distribution checked because I was in a hurry.

**Comment by DougKremer** [comment]
Agree,  would love to see daily totals for carbs, insulin units (bolus, basal, and total) in the daily stats tab.

**Comment by DonaldBough** [comment]
Is this something in progress yet? I'd love to add it in, wanted to make sure I wasn't stepping on someone's toes who already started

**Comment by AlexJGoodwin** [comment]
Hi. I see form the timeline that I've come to this party a bit late!
Firstly - superb job on the product it's simply cracking and so customisable. Truly great job!
Agree that total insulin would be really helpful - it's a stat that's often discussed in clinic.

One of my son's health team said "so strange not to have TDD and a basal total when this is so important ! Especially in growing children and young people but also in pregnancy and managing illness etc etc. Are you able to feed that back and ask the question?".

...so here it is!

**Comment by AlexJGoodwin** [comment]
Since my last post, I've discovered that at least some (non-aggregated) Total Daily Insulin data is available in the 'Day to day' section:
          - Bolus insulin
          - Base basal insulin
          - Positive temp basal insulin
          - Negative temp basal insulin
          - Total basal insulin
          - Total daily insulin
          - Total carbs
          - Total protein
          - Total fat

I've run an update since my last post, so not sure TBH whether I just missed it previously or it was an update feature. Suspect I'd missed it previously so thought I'd post here to save anyone else the red face!

Thanks everyone!!

**Comment by bjornoleh** [comment]
I was just going to make a request, and found this issue now.

While I appreciate that the Day to day report has the daily doses and also the averages for the selected time period, it would be nice to have a better representation of the changes over time. I think either a dedicated report for insulin, carbs etc would be nice, or, have insulin added to some of the other reports.

If adding to other reports, perhaps the **Daily Stats** report could accomodate insulin as well (as suggested in this issue report).

A dedicated table and/or chart which could display insulin doses  and carbs together with average BG, TIR and perhaps something else would be super nice!

![image](https://user-images.githubusercontent.com/63544115/102621007-3e5d9e80-413f-11eb-982e-37ccd4ebe5ef.png)
