### ISSUE TITLE
BG_* variables don't use DISPLAY _UNITS settings making it confusing for mmol users.

### ISSUE THREAD

**Issue by daktau** [nightscout/cgm-remote-monitor#4135]
I am seeing an urgent high status/alarm when I am in range. Can anyone explain why I am seeing this or if this is a bug?

<img width="470" alt="screen shot 2018-12-12 at 20 42 32" src="https://user-images.githubusercontent.com/9610778/49897632-9fff1a00-fe4e-11e8-905d-23861f6d14d4.png">

<img width="1678" alt="screen shot 2018-12-12 at 20 42 02" src="https://user-images.githubusercontent.com/9610778/49897669-b2795380-fe4e-11e8-8b04-7e966a740069.png">

**Comment by sulkaharo** [comment]
Have you set the DISPLAY_UNITS variable to “mmol”? What value do you have in the environment targets? The profile doesn’t affect the alarms

**Comment by daktau** [comment]
Is this what you mean?

<img width="214" alt="screen shot 2018-12-12 at 20 51 59" src="https://user-images.githubusercontent.com/9610778/49898068-da1ceb80-fe4f-11e8-8eb5-c43bf7259322.png">

**Comment by daktau** [comment]
<img width="183" alt="screen shot 2018-12-12 at 20 53 31" src="https://user-images.githubusercontent.com/9610778/49898137-10f30180-fe50-11e8-8375-c2191c3571ec.png">

**Comment by daktau** [comment]
Is this because the environmental variables ONLY work in mg/dl units?

**Comment by daktau** [comment]
Yep, where there is a mod right there.

1. Establish whether molar or mass concentrations are to be used
2. Indicate that all measurements are in mmol/L or mg/dL 
- Use variable variables? eg.
BG_HIGH [mmol/L]   ||   BG_HIGH [mg/dL]
BG_LOW [mmol/L]   ||   BG_LOW [mg/dL]  

Alternatively place a large warning that step 1. will mean all the other values need to adhere to the option taken in step 1.

3. Use the value in step 1 to establish the values in the app.

Alternatively, strongly indicate somewhere that the app variables are only available as mass concentrations (mg/dL)

**Comment by daktau** [comment]
See last comment

**Comment by PieterGit** [comment]
I agree this is confusing, but it is documented, see
https://github.com/nightscout/cgm-remote-monitor#alarms

```
BG_HIGH (260) - must be set using mg/dl units; the high BG outside the target range that is considered urgent
BG_TARGET_TOP (180) - must be set using mg/dl units; the top of the target range, also used to draw the line on the chart
BG_TARGET_BOTTOM (80) - must be set using mg/dl units; the bottom of the target range, also used to draw the line on the chart
BG_LOW (55) - must be set using mg/dl units; the low BG outside the target range that is considered urgent
```

Reopening. I think for Nightscout 0.12 we must implement that the `BG_*`  must comply to the `DISPLAY_UNITS`  setting.  All user facing variables should follow `DISPLAY_UNITS` style.

**Comment by unsoluble** [comment]
I'd love to see this change. There's sense to the logic of keeping the internal references to a single unit type, but the config vars _are_ user-facing and do end up causing consistent confusion.

**Comment by unsoluble** [comment]
(And things like the "Target BG range" UI in the screenshot at the top of this thread should reflect the DISPLAY_UNITS setting as well — instead of indicating either/or like they do currently.)
