### ISSUE TITLE
The BG_high value is not being picked up correctly

### ISSUE THREAD

**Issue by daktau** [nightscout/cgm-remote-monitor#4139]
Apologies if I am not seeing something obvious here but I cannot see why I only have 1 "line" (which seems to be both doubled up) to indicate the bg_high and bg_target_top whereas I have 2 for each teh bg_low and bg_taget_low.

Could someone explain this please?

<img width="736" alt="screen shot 2018-12-14 at 16 36 12" src="https://user-images.githubusercontent.com/9610778/50015589-da87c480-ffbe-11e8-8a39-fe82aebbd48f.png">

<img width="165" alt="screen shot 2018-12-14 at 16 34 44" src="https://user-images.githubusercontent.com/9610778/50015605-e3789600-ffbe-11e8-9542-391cb70ab82e.png">

**Comment by unsoluble** [comment]
This is because your TARGET_TOP is currently _higher_ than your HIGH, which conflicts with the logic of the two settings; HIGH is the "urgent" value, and needs to be set higher than your TARGET.

**Comment by daktau** [comment]
Many thanks!

**Comment by jakobsandberg** [comment]
@daktau it appears you issue was resolved, can we close this ticket?

**Comment by daktau** [comment]
Yes, many thanks again. Totally resolved 😀
