### ISSUE TITLE
Wrong "Bolus insulin" sum in NS Report

### ISSUE THREAD

**Issue by xafour** [nightscout/cgm-remote-monitor#4142]
**Describe the bug**
Bolus Insulin Sum is wrong, when there is a extended bolus reported. On attached picture you can see an example:
On Monday 3.12.2018 there are 7 boluses - in total 14,5U (4+1,2+4+3,3+0,9+0,6+0,5). Additionally there has been one extended bolus 7U (14U/hour, duration 30min) applied.
So the total bolus is 14,5+7=21,5U. In the insulin distribution overwiev are 56,5U reported. This is wrong.

**To Reproduce**
1. Apply extended bolus on AAPS V.2,0,
2. Make NS report and check "insulin distribution" checkbox
3. Verify the Bolus insulin Sum

**Expected behavior**
In case described the bolus insulin should be 21,5U instead of 56,5U.

**Screenshots**
![snapshot](https://user-images.githubusercontent.com/42938102/50044635-aaa3f400-0086-11e9-9920-2a2782ae3865.JPG)

**Your setup information**
- version of Nightscout: 0.11.0-dev-20180805
- Using Dexcom G5, Dexcom app, AAPS V2.0., NS on Heroku 
- Is your issue specific to a browser - no ?

**Additional context**

**Comment by unsoluble** [comment]
Have you determined that this happens with every extended bolus entry? We've only got one data point here to consider.
Also if you could provide the raw entries as a list for that day, would really help with analysis.

**Comment by PieterGit** [comment]
@xafour what pump do you use. Can you see if you can find the JSON entries in the MongoDB? Might look at the treatments tab if you spot duplicate treatments. What timezone are you in?

**Comment by xafour** [comment]
> Have you determined that this happens with every extended bolus entry? We've only got one data point here to consider.
> Also if you could provide the raw entries as a list for that day, would really help with analysis.
It happens with every extended bolus entry, every day. The picture above is just one example.
I will try to get the raw data and send it.

**Comment by xafour** [comment]
> @xafour what pump do you use. Can you see if you can find the JSON entries in the MongoDB? Might look at the treatments tab if you spot duplicate treatments. What timezone are you in?

I use Dana R with updated firmware v2. I will try to export the data from MongoDB and send it. There are no duplicate treatments on the tab. Timezone Europe, Vienna.

**Comment by sulkaharo** [comment]
Just to make sure - is the list in the ticket comprehensive? You're not using xDrip or any other app? We've discovered that if you at least run AAPS and xDrip on the same phone and have configured both to upload data to NS, it'll create duplicated records and lead to this report showing extra insulin and carbs based on the duplicated data.
