### ISSUE TITLE
BG alarms not working as expected

### ISSUE THREAD

**Issue by ireneusz-ptak** [nightscout/cgm-remote-monitor#4154]
Here is my setup for alarms:

(X) Urgent High Alarm (240)
() High Alarm (160)
(X) Low Alarm (90)
() Urgent Low Alarm (70)

The issue is I'm getting the alarm when the BG is going over 160. That doesn't seem to be a correct behavior.

I thought this is Android specific, but I got the same issue on my desktop. The alarmUrgentHigh, alarmUrgentLow, alarmHigh and alarmLow variables are set correctly.

Nightscout
version 0.10.3-master-20180805
Android 6.0 & Chrome, Win10 & Opera

**Comment by unsoluble** [comment]
What is your ALARM_TYPES set to? Also, do you have "bwp" in your ENABLE?

**Comment by ireneusz-ptak** [comment]
ALARM_TYPES was empty, bwp was not in ENABLE.
Changed the first to simple, added 2nd one, we'll see if that changes anything.

**Comment by unsoluble** [comment]
Sorry, should have elaborated — best to *not* have bwp enabled, unless you specifically need it.

**Comment by ireneusz-ptak** [comment]
OK, as the simple ALARM_TYPES is the default, nothing should change, right?

**Comment by ireneusz-ptak** [comment]
Nothing extraordinary, I think.

basal cage iob sage pump careportal

**Comment by ireneusz-ptak** [comment]
No, it's set to off.
I was able to get some information from JS console, but it doesn't look helpful.

index.js:1014 alarm received from server
index.js:1015 notify: {level: 1, title: "Warning HIGH", message: "BG Now: 161 +3 → mg/dl↵IOB: 0.15U", eventName: "high", plugin: {…}, …}debug: lastSGV: 161thresholds: {bgHigh: 240, bgTargetTop: 160, bgTargetBottom: 90, bgLow: 70}__proto__: ObjecteventName: "high"group: "default"key: "simplealarms_1"level: 1message: "BG Now: 161 +3 → mg/dl↵IOB: 0.15U"plugin: {name: "simplealarms", label: "Simple Alarms", pluginType: "notification", enabled: true}pushoverSound: "climb"title: "Warning HIGH"__proto__: Object
index.js:1018 Alarm raised!
index.js:608 Asking plugins to visualize alarms
index.js:164 visualizeAlarms

And some local variables:

alarmHigh	false	
alarmLow	true	
alarmTimeagoUrgent	false	
alarmTimeagoUrgentMins	30	
alarmTimeagoWarn	false	
alarmTimeagoWarnMins	15	
alarmUrgentHigh	true	
alarmUrgentLow	false	
basalrender	default	
customTitle	xxx
editMode	true	
focusHours	3	
language	en	
nightMode	true	
scaleY	log	
showPlugins	iob careportal pump cage sage basal	
showRawbg	undefined	
storageVersion	1	
theme	colors	
timeFormat	24	
units	mg/dl

**Comment by ireneusz-ptak** [comment]
No luck :(

**Comment by RyRyCeratops** [comment]
I have this exact same problem as well. My settings match all of these too.  Did you ever find a resolution?

**Comment by ireneusz-ptak** [comment]
Only a workaround - started using xDrip+ ;)

I went through the code before and I think the same method is used to check if alarm is raised regardless  of the alarm level, but had no time to confirm it.

**Comment by st0ber** [comment]
Same problem here :-( the high alarn is always here. What can i do? I dont use xdrip.

**Comment by jwedding** [comment]
Add me as a +1. The High Alarm toggle in NS doesn't work. Hasn't for a very long time, if ever.

**Comment by unsoluble** [comment]
This continues to be strange. Whenever I’m troubleshooting someone else’s site and they’re high, the high alarm will always go off in my browser. Can’t figure out what’s causing it to fail for seemingly everyone else.

**Comment by sulkaharo** [comment]
Yup it’d be great if you can post all your settings except for the api secret and mongo URL exactly as they are and describe exactly what the wrong behavior is. What makes debugging this really hard is “alarms don’t work” seems to mean about 20 different things and it’s very hard to tell what’s going on exactly, especially since I’m unable to reproduce issues.

**Comment by diabeticpilot** [comment]
I get this all the time and it drives me crazy. The "high" alarm goes off at 180 no matter what settings I have set in the config or from the browser.

**Comment by tiiladibe** [comment]
I have this problem too. I tried even deleting the ALARM_HIGH var completely as setting it off didn't help, but still no change. Otherwise essentially same settings as above.

I'm now thinking of setting the value of BG_TARGET_TOP to be the same as BG_HIGH in order to get alarms when and only when needed. That obviously will make the graphics less informative but I think I can live with that if the alarms then work.

**Comment by ville-juhani-honka** [comment]
Same thing here: no matter what I do or what settings I have ALARM_HIGH wants to trigger. My settings are here attached, if anyone wants to take a look.

Like mentioned above, the only "solution" to avoid these non-urgent high alarms is to set BG_TARGET_TOP to the same (or close) value as BG_HIGH, but like said, it does mess up the graphics and colors.
![config_vars](https://user-images.githubusercontent.com/72121861/95964030-0f5e4000-0e11-11eb-8aff-a1f5dc1e087d.png)

**Comment by sulkaharo** [comment]
Found the bug involved here, will fix soon
