### ISSUE TITLE
Improvement: Sound an alarm when data hasn't been received in n minutes

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#418]
Especially for nighttime use, it'd be good if an alarm was raised if the monitoring client hasn't received new CGM measurements in n minutes. We've had a couple occasions where the uploader phone has had some issue with the wifi router and didn't notice until a couple hours later, where such an alarm would have been very useful.

**Comment by jasoncalabrese** [comment]
I'd like this too, the time ago is already calculated on the client, acking the stale data alarm would be different and we might need an option to enable/disable the new alarm.

**Comment by jasoncalabrese** [comment]
working on this in #554
