### ISSUE TITLE
moment-timezone/data/packed/latests.json adds 901Kb to the bundle

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4208]
Current bundle has 900kb of moment-timzone data. See webpack bundle analyzer screenshot below.
![image](https://user-images.githubusercontent.com/6500826/51281380-84090e00-19e2-11e9-8e43-8d344608d2c5.png)

There is an interim fix available at: 
https://github.com/iamakulov/moment-locales-webpack-plugin/issues/17#issuecomment-452148122
but then we need to specify all timezones Nightscout is used in.

Question: 
Do we need all this timezone data or can we somehow manage to minimize it or remove it from the bundle.

**Comment by sulkaharo** [comment]
Nightscout is basically used in all time zones, so predefined locales is probably not an option.

**Comment by sulkaharo** [comment]
#4211 might actually fix this
