### ISSUE TITLE
Add the ability to delete/remove CGM readings

### ISSUE THREAD

**Issue by jennysloan** [nightscout/cgm-remote-monitor#4210]
In the Nightscout UI, the edit button does not allow the user to delete CGM readings.

This feature would be desired because when CGM device needs to be calibrated, the readings are not accurate. This is problematic if using NS reporting and erroneous high/low readings are included.

The edit button could be written to allow all data to be editable.

**Comment by DonaldBough** [comment]
I believe this already exists. If you enabled edit permissions, you can click the pencil button, then drag a reading to the delete box that appears.

**Comment by unsoluble** [comment]
Can currently only do that with treatment entries, not CGM data.

**Comment by DonaldBough** [comment]
Is that an architectural decision? Could this be done from a separate plug-in then?

**Comment by CoreISP** [comment]
Old request, just necromancing to utter my agreement. This is a much needed feature for when things went wrong with readings.

**Comment by manyyellowbirds** [comment]
Also agree that this would be a really useful feature, the readings on the libre are garbage data for the first 12-18 hours

**Comment by lucasvreis** [comment]
@Tornado-Tim since you closed this, could you clarify if it is now possible and how to do it?
