### ISSUE TITLE
ar2 Alexa integration doesn't do mmol

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#4214]
When an ar2 response is given to an Alexa query, it should honor DISPLAY_UNITS. Currently does not.

**Comment by unsoluble** [comment]
(I don't have a proposed fix at this point, just ticketing to put it on the radar. If anyone actually familiar with the ar2 plugin or alexa stuff in general could take a look, that'd be great.)

**Comment by PieterGit** [comment]
Unfortunately both the `ar2` and `alexa` plugins are currently unmaintained, see https://github.com/nightscout/cgm-remote-monitor/blob/dev/CONTRIBUTING.md#plugin-contributors

**Comment by PieterGit** [comment]
@unsoluble Is this issue still relevant? Did you test https://github.com/nightscout/cgm-remote-monitor/pull/4980 . Closing issue. If it's still relevant, please reopen.
