### ISSUE TITLE
Still have an issue with clock

### ISSUE THREAD

**Issue by SargentChris** [nightscout/cgm-remote-monitor#4220]
I have updated to the latest version (or at least I think I have -0.10.3-master-20180805 ) but I still have an issue when using clock mode in that it only shows in mg/dl rather than mmol/l

**Comment by unsoluble** [comment]
The clock views pull your preferences from your Config Vars; need to have DISPLAY_UNITS set to "mmol".

**Comment by PieterGit** [comment]
@SargentChris Latest released version is 0.11.1. That version is recommended.
Did @unsoluble comment help you fix the clock issue?
