### ISSUE TITLE
Update UI color schemes similar to xDdrip/Spike 

### ISSUE THREAD

**Issue by DonaldBough** [nightscout/cgm-remote-monitor#4249]
**Is your feature request related to a problem? Please describe.**
While the hacker in me understands the web client's 80s terminal color scheme, with apps like xDrip and Spike I know the web client can have a pleasant UI color scheme. The black, grey, and neon colors were intimidating to me when I first began using nightscout.

**Describe the solution you'd like**
I want to add a new "Theme" to change some styling colors. Similar to xDrip and Spike, I'd like to have a less black and white app and add in some color without sacrificing usability.

**Describe alternatives you've considered**
While the existing "Theme" colors are an improvement, I would like more changed.

**Additional context**
Just looking over the source, I believe I would be making a seperate css file other than ui-darkness. I'm not sure how the "Theme" option changes the css yet.

**Comment by unsoluble** [comment]
If you're into making up a new theme option and PRing it, will happily review.
