### ISSUE TITLE
when ns is set to use mmol/l the Target bg range values in config file cannot be set in mmol/l

### ISSUE THREAD

**Issue by wootmasterslick** [nightscout/cgm-remote-monitor#4255]
**Describe the bug**
See title

**To Reproduce**
1. Go to config file
2. Set NS to use mmol/l for displaying and entering data
3. set tgt bottom range to 4 and top range to 10
4a. in the overview screen the 4 and 10 are assumed to be input in mg/dl and converted to mmol/l resulting in tgt lines set to 0.1 mmol/l and ending up in bottom of graph
4b. in the reports section the auto filled BG values are also going through mg/dl to mmol/l conversion

**Expected behavior**
Values entered in config files are not converted and used as in in overview screen and report screen

**Your setup information**
- What version of Nightscout 0.11.0-dev-20181231

**Comment by unsoluble** [comment]
This is being discussed in #4135
