### ISSUE TITLE
/swagger.yaml not working on 0.10.3-master-20180805

### ISSUE THREAD

**Issue by roppenheimer** [nightscout/cgm-remote-monitor#4264]
https://<My-Site>/swagger.yaml is not working on 0.10.3-master-20180805 it simply give an error that the page cannot be found

=======

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your setup information**
- What version of Nightscout (e.g. 0.10.3)
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?

**Additional context**

**Comment by zehnBE** [comment]
in app.js in Line 104 (master) and Line 138 https://github.com/nightscout/cgm-remote-monitor/blob/85e6916dda95e362ae78ba296ca47894087e9025/app.js#L138 there is swagger.json already exempted and works. This is needed for "swagger.**yaml**" too or it is possible, to make filename dynamic like this (i dont know, if it will work)?:
`

    app.get('/swagger.'+(json|yaml), function(req, res) {

        res.sendFile(__dirname + '/swagger.'+(json|yaml));

    });
`

**Comment by roppenheimer** [comment]
I have raised an issue on Github.

**Comment by roppenheimer** [comment]
This issue is now resolved.
