### ISSUE TITLE
Show Raw BG Data controls should be conditional on ENABLE=rawbg

### ISSUE THREAD

**Issue by scottleibrand** [nightscout/cgm-remote-monitor#428]
In order to enable Raw BG Data display, users must set ENABLE=rawbg and choose "Always" or "When there is noise" under "Show Raw BG Data" in the UI settings dropdown.  However, it is not clear (even to me, and I knew this) that setting "Show Raw BG Data" in the UI settings dropdown is not sufficient by itself.

We should make the wip/iob-cob behavior consistent with the behavior in mainline, where the Raw BG controls don't show up without ENABLE=rawbg.
##

**Comment by ELUTE** [comment]
I thought it doesn't appear in the ui unless it is enabled?

**Comment by scottleibrand** [comment]
It does in wip/iob-cob.  I'll go check whether it does the same in mainline.

**Comment by jasoncalabrese** [comment]
Meant to make it so that you didn't need to enable raw for iob-cob, should be a really easy fix.

**Comment by scottleibrand** [comment]
Ah, ok.  That would work too.

**Comment by Kdisimone** [comment]
I believe this issue can be close, correct? @scottleibrand 

the most recent deployments I've seen do not show the dropdown menus for rawBG unless rawbg is on the ENABLE line.
