### ISSUE TITLE
0.11 is rejecting API secret after upgrade

### ISSUE THREAD

**Issue by KheldarUK** [nightscout/cgm-remote-monitor#4280]
**Describe the bug**
When entering API secret, error messaged is displayed - wrong secret

**To Reproduce**
1. Update using updater to 0.11
2. Load site
3. Enter API secret

**Expected behavior**
After entering API secret, log in succesful

**Additional**
Have restarted dynos, re-deployed, changed secret, various combinations of these three. API is not accepted by 0.11

**Comment by PieterGit** [comment]
@KheldarUK we just fixed a problem with 0.11, and are working on releasing 0.11.1.
Can you deploy master again, and confirm that that fixes your problem?

**Comment by KheldarUK** [comment]
0.11.1 resolved - thank you all <3

**Comment by auxlife** [comment]
I'm having the same issue..
