### ISSUE TITLE
Site not defaulting to HTTPS in Chrome

### ISSUE THREAD

**Issue by live4sw** [nightscout/cgm-remote-monitor#4307]
When I attempt to open my site without specifying "https://" in Chrome Version 71.0.3578.127 (Official Build) (64-bit), I receive the message "Connecting to Nightscout server failed, retrying every 2 seconds"

As long as I include https:// in the URL, it loads fine. It also loads correctly in Safari without entering "https://"

Developer Console in Chrome states:

[Deprecation] Application Cache is restricted to secure contexts. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
bundle.source.js:33 Nightscout bundle ready
client.js?v=d1x1465vg9kk8kkr:9 Application got ready event
(index):1 Access to XMLHttpRequest at '[NS URL]/api/v1/status.json?t=1549722546175' (redirected from 'http://[NS URL]/api/v1/status.json?t=1549722546175') from origin 'http://[NS URL]' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.js:67 Application appears to be OFFLINE

**Comment by OpossumGit** [comment]
I had this problem until clearing browser data. Probably cookies. This fixed Chrome problem both on iPhone and Android.

**Comment by live4sw** [comment]
Clearing browsing history didn't fix this for me, but clearing cache and cookies did. Anyway, that was a simple fix. I am going to close this issue.

**Comment by PieterGit** [comment]
@live4sw Thanks for filing the issue. We should find a way that clearing the cache or cookies should not be necessary. I don't understand why the server redirect does not work in these cases. @sulkaharo @jpcunningh  any idea?
