### ISSUE TITLE
App Lockup in Browser

### ISSUE THREAD

**Issue by rogue-bryan** [nightscout/cgm-remote-monitor#4322]
**Describe the bug**
Ever since I've started using nightscout on heroku, I've had to restart my browser and/or the app on iOS on a daily basis because it locks up. I was hoping with the new release of Ice Cream that this would be fixed, but its not. 

**To Reproduce**
Its very consistent:
1. let the app run in browser for at least 12 hours in (web browser or iOS)

**In browser after more than 12 hours:**
- the current (correct) glucose read is displaying on the tab
- the web site itself has not updated in quite some time or the browser tab itself has crashed (I'll update this post as I gather more information)

**On iOS app after more than 12 hours:** 
- the app has locked up 
- or crashed to home screen

**Expected behavior**
App continues to run throughout a 24 hour period on either iOS or browser

**Screenshots**
n/a

**Your setup information**
- What version of Nightscout: version 0.11.1
- What type of CGM, and how do you get your data there? G6, with Loop on iOS (though this situation was also showing itself when I was using Medtronic Enlite with Loop as well as MiniMed Connect previously)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?
Both Chrome and iOS apps (official nightscout iOS app)

**Additional context**
It seems like a memory leak. I was doing some benchmarking of the memory using Chrome tools at one point a few months ago and seemed like the browser tab just kept grabbing memory.

**Comment by unsoluble** [comment]
Do you have an Uptime Robot (or similar) running? Wondering if it's just that your app is sleeping.

**Comment by rogue-bryan** [comment]
Hmm, is this something we'd need? I hadn't read anything about that (I probably missed it) I can certainly set one up, any recommendations?

**Comment by unsoluble** [comment]
Depending on how your data is getting into Nightscout, it may be necessary in order to keep the app from sleeping. Typically required for bridges, but I'm not entirely sure whether a Loop setup needs it. No harm in setting it up, anyway; might as well. Instructions are near the bottom of [this guide](http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku), in the "Dexcom Share bridge users" section.

**Comment by rogue-bryan** [comment]
Doh! I definitely didn't read the full docs! If its ok, I'll keep this open for a couple more days. Definitely will know if it was user error at that point.

Thanks!

**Comment by rogue-bryan** [comment]
Seems to be working as designed. My lesson? RTFM!  Thanks for the help @unsoluble!
