### ISSUE TITLE
Incorrect version of nodejs in docker.example file in actual master

### ISSUE THREAD

**Issue by maskac** [nightscout/cgm-remote-monitor#4357]
In actual docker.example file si nodejs 8.9.1, but 11.1 not functional with it. 
Version 11.9 not functional too (message you must upgrade).
Version 10.15.1 see functional.

**Comment by PieterGit** [comment]
@maskac The docs only allow latest Node 8 or Node 10 LTS. Can you PR the file https://github.com/nightscout/cgm-remote-monitor/blob/dev/Dockerfile.example to use the Node 8.15.0 or Node 10.15.1 version and test to see if that make is work again?

**Comment by maskac** [comment]
Yes, i am allready tests with

"FROM node:10.15.1"

and works fine.

**Comment by m-a-v** [comment]
I'am running Nightscout for several days with "FROM node:10.15.1". I think the best option would be to use the Alpine image. I will do some tests with Alpine and if successful create a PR.

**Comment by m-a-v** [comment]
I have added a PR.

https://github.com/nightscout/cgm-remote-monitor/pull/4392

**Comment by PieterGit** [comment]
Fixed by merging https://github.com/nightscout/cgm-remote-monitor/pull/4409
Closing PR. Thanks @m-a-v

**Comment by m-a-v** [comment]
Thanks for the merge :-)
