### ISSUE TITLE
Link to alexa documentation is broken

### ISSUE THREAD

**Issue by tanja3981** [nightscout/cgm-remote-monitor#4422]
The link to the alexa documenation from https://github.com/nightscout/cgm-remote-monitor to "detailed (alexa) setup instructions)" is broken, currently leading to https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/plugins/alexa-plugin.md, which seems to have gone missing.

**Comment by jakobsandberg** [comment]
We can close this issue as it was resolved via #4423
