### ISSUE TITLE
Infinite redirects on 0.11 upgrade

### ISSUE THREAD

**Issue by thecubic** [nightscout/cgm-remote-monitor#4427]
**Description**
On upgrade to 0.11, a setup stopped working as a web endpoint.

**To Reproduce**
1. Create a 0.10.3 setup using a https URL and custom port
e.g.
PORT=1234
BASE_URL=https://my.cloud.server:${PORT}
2. Upgrade to Node 10.15.1 and version 0.11
3. Reload base URL
4. Page displays "Connecting to nightscout server failed..."
5. Previously-loaded pages continue to work

**Expected behavior**
Nightscout loading page

**Your setup information**
Fedora 27
Node 10.15,1
Nightscout 0.11 (pulled master)

CGM Dexcom G5, + iOS Loop (nothing indicating those do not function)
Tried on:
- Chrome
- Brave
- Direct cURL shows infinite redirects
```
$ curl -L https://my.cloud.server:1234/
curl: (47) Maximum (50) redirects followed
```
**Additional context**
I've tried removing the port from BASE_URL and it does not resolve the issue.
I've rewound the release to the `release/0.10.3` branch and it returned to function in the same setup

**Comment by PieterGit** [comment]
@thecubic please clean your cache before accessing the upgraded Nightscout. That should solve the issue. Please confirm that clearing the cache fixes the problem for you.

**Comment by sulkaharo** [comment]
How have you setup ssl? Check the release notes for how to disable https forwarding if this is through a proxy

**Comment by thecubic** [comment]
`curl` does not have browser cache or cookies or anything of that nature.  I started a second instance on a different port with the only difference being the release version.   I accessed this through an incognito browser session, and it yields `ERR_TOO_MANY_REDIRECTS`, whereas in the same session `release/0.10.3` loads fine.

I am using SSL directly through Node's listener by setting `SSL_KEY` / `SSL_CERT` and an `https` `BASE_URL` (and a public-trust certificate - Let's Encrypt)

**Comment by jweismann** [comment]
@thecubic . This issue is not clear to me so please help me understand your findings. First off, I would like to know your INSECURE_USE_HTTP settings and whether or not you can reproduce the problem with INSECURE_USE_HTTP=false.

@PieterGit @sulkaharo Maybe we should consider to have another default for INSECURE_USE_HTTP since it seems to cause confusions for non-heroku deploys. Alternatively we could have the current default setting activated only on heroku deploys. I don't think its a good idea to force redirections on setups that we cannot test.

**Comment by thecubic** [comment]
Here's some interesting signal - `INSECURE_USE_HTTP` was defaulted to `false` (not set)

with `INSECURE_USE_HTTP=true` it works again.  When setting explicitly to `false` again, it stops working again.  Reading up, that does seem to be a Herokuism, and I think there's a quick fix I'll take a stab at (which makes that envvar moot on a pure-HTTPS setup)
