### ISSUE TITLE
Battery Reading only shows one of each phone type even if multiple phones are used

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#4455]
**Issue Description**
Battery pill shows the lowest phone using xDrip+, not just the master.

Battery pill hover shows battery level of all phones using xDrip+ per device type. Only one line item is showing for the LGE Nexus 5X that has the lowest battery percentage. We are using 2 LGE Nexus 5X devices, so there should be 2 lines.

**To Reproduce**
1. Setup 2 phones with the same model on xDrip+ and upload to Nightscout. 
2. Hover over the Battery Pill to reveal the hover details

**Expected behavior**
- Battery Pill should show the % of the master/primary device directly connected to the CGM. In this case, the LGE Nexus 5X that is not visible in the hover menu.
- Hover menu should show one line per phone.
- Hover menu should show the Phone Name instead of the model. Ex: Tracy's Phone instead of "LGE Nexus 5X"

**Screenshots**
![image](https://user-images.githubusercontent.com/46848705/53982080-d43e4b80-40c8-11e9-9666-8fac63b0d12a.png)

**Your setup information**
- What version of Nightscout: 0.11.1
- What type of CGM, and how do you get your data there? G6 using bluetooth to xDrip+ that uploads to Nightscout
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No. Checked in Chrome desktop and Android

**Comment by sulkaharo** [comment]
Sorry for long response time - you should create a ticket to the developers of the application you're using. The uploader name used by Nightscout is simply the one the uploader is sending, so there's no way for Nightscout to actually know there's two separate uploaders if two phones are sending the same name.
