### ISSUE TITLE
Week to week report doesn't add up

### ISSUE THREAD

**Issue by KheldarUK** [nightscout/cgm-remote-monitor#4470]
**Describe the bug**
Running my weekly successes report I get 101% adding up Low, In Range and High for last week.

**To Reproduce**
Run the weekly successes report over the previous month

**Expected behavior**
Total of these values is 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/29229592/54195875-bbaea680-44b7-11e9-970c-2e1b1b1341ab.png)

**Your setup information**
- What version of Nightscout (0.11.1)
- What type of CGM, and how do you get your data there? (Libre, MiaoMiao, Spike)
- Is your issue specific to a browser (Browser / device agnostic)

**Additional context**
Feel free to use my site https://kheldaruknightscout.herokuapp.com/report

**Comment by unsoluble** [comment]
This is clearly just a result of each individual value being rounded (up, in this case), leading to an implied false total. I don't think it's really a bug, per se, unless the total was subsequently being used in another calculation.

**Comment by KheldarUK** [comment]
Fair play John, I just thought I’d mention it :)
