### ISSUE TITLE
Reporting fails to render for Libre users pushing 1 CGM entry / minute into Nightscout

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#4496]
If a user has set a Libre / MiaoMiao to send in 1 reading / minute into Nightscout, the reporting fails to render anything. On first look, this seems to be caused by a bug in the reporting REST client, where the large amount of data from the 1 min users causes the REST call to do a chunked load, but the script expects the data to be loaded in one go, so the multiple calls to the REST loaders from the chunks resets the BG data along the way. Sadly the code is a bit of a jumble so refactoring is needed...

**Comment by rob-andy** [comment]
I posted this in  #3688   . It's a pretty simple fix to get most of the reporting working.

The GVI calculation will be wrong but that's not overly difficult to fix either.

**Comment by rob-andy** [comment]
I've created a reporting-fixes branch in my github repo with my current work.  Happy to hear thoughts/feedback...

**Comment by sulkaharo** [comment]
@rob-andy wanna add the GVI fix too?

**Comment by rob-andy** [comment]
It's in there as well.. Currently my calculated value is very different to what was originally being calculated so need some more testing to make me feel confident it's right

**Comment by rob-andy** [comment]
Added some fixes to minor errors in the existing code tonight.  After unit testing using some basic sample data, I'm happy with the results.

**Comment by rob-andy** [comment]
@sulkaharo no thoughts?
