### ISSUE TITLE
MiniMed Connect error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by LubomirKovalcik** [nightscout/cgm-remote-monitor#4526]
**Describe the bug**
I am trying to get my bolus/basal data from pump to my nightscout. I am not using Medtronic CGM, but other which is already uploading data via Xdrip to nightscout. I just need bolus/basal data synchronized from pump to nightscout. 

I am using latest version 0.11.1 with "careportal basal mmconnect" enabled.
I have MMCONNECT_PASSWORD and MMCONNECT_USER_NAME set an double verified. 
I have MMCONNECT_SERVER set to EU. 

**To Reproduce**
1. Enable mmconnect and add config vars.
2. Open log to see:
MiniMed Connect error: SyntaxError: Unexpected token < in JSON at position 0

**Expected behavior**
Basal and bolus data are synchronized from carelink to nightscout. 

**Your setup information**
- What version of Nightscout:  0.11.1 
- What type of CGM, and how do you get your data there? MiaoMiao with Xdrip , pump 640g
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? no

**Comment by unsoluble** [comment]
The mmconnect plugin does not support EU accounts in 0.11.1 (this is pending release in 0.11.2).
