### ISSUE TITLE
Profile incorrect on main screen after a period of time

### ISSUE THREAD

**Issue by Pogman** [nightscout/cgm-remote-monitor#4538]
Using a profile group with several profiles set up within it.

A profile switch changes from 'Basal 2' to 'Day Off'.

This initially works as intended but after a period of time (I noticed the bug after around 7 days) the main screen then shows the old profile and the reports screen shows the correct profile.

The incorrect 'Basal 2' profile is the default profile as set in the profile editor and the main screen is using this when it should be using the 'Day Off' profile.

![profile-bug-reports](https://user-images.githubusercontent.com/7413594/56422559-fc13f800-629f-11e9-9b22-cb0d028f97dc.jpg)
![profile-bug-main](https://user-images.githubusercontent.com/7413594/56422560-fc13f800-629f-11e9-875f-ab9df1f4d685.jpg)
![profile-bug-profiles](https://user-images.githubusercontent.com/7413594/56422561-fc13f800-629f-11e9-8964-1302370f42a7.jpg)

**Comment by yeagerm** [comment]
I can confirm the same or similar behavior: My Basal pill always shows the same old profile name now matter what I select and save in the Profile editor. I see the problem in both cgm-remote-monitor -master and -dev.

The correct profile is retrieved if using a service like AutotuneWeb.

To get the pill to match the actual profile, use a manually entered profile switch entered via the NS treatments menu (thanks @pogman)
