### ISSUE TITLE
Firefox doesn't open "Admin" in new tab

### ISSUE THREAD

**Issue by mastacheata** [nightscout/cgm-remote-monitor#4539]
**Is your feature request related to a problem? Please describe.**
In Chrome all menu items open in a separate tab.
In Firefox the Admin link opens in the very same tab.

**Describe the solution you'd like**
Honestly: I got no idea how to solve this.
You could use _blank as the target, but I get that you assigned names to the tabs so only one of each kind will open. I couldn't find out why Firefox thinks the "main" NightScout tab is actually the admin tab.

**Describe alternatives you've considered**
An alternative would be not to use new tabs at all and instead provide a way to navigate back and forth within the app.
A very simple solution would be to drop the target parameter on all links and instead provdie a back button somewhere at the top.
Also it would be great to have the NightScout logo/Custom Site Title to work as some kind of Home button, but that definitely blows the scope of a Bug report and is better suited for a separate feature request issue.

**Additional context**
I can see this problem in both Firefox Developer Edition 67.0b3 and the current stable Firefox 66.
It does not occur in Google Chrome or Firefox Mobile. 🤷‍♂️

**Comment by davebrothers** [comment]
What OS? Using Firefox stable 66.0.3 on Windows 10 1803, I saw the following behavior: 
If only one NS tab is open and it isn't the admin tools, admin tools opens in a new tab. If there is an admin tools tab open, FF focuses and refreshes that tab.

**Comment by mastacheata** [comment]
Seems to have resolved by itself with the next nightly update of Firefox.
Sorry for not responding earlier, this somehow slipped through.
