### ISSUE TITLE
Nightscout doesn't reflect Combo Bolus cancelation

### ISSUE THREAD

**Issue by pdewaha** [nightscout/cgm-remote-monitor#4558]
It is not possible to cancel a combo-bolus in Nightscout. This seems to be by design, as there is no such even-type defined. The problem is, that the representation of Nightscout is wrong, in case of a combo bolus cancellation, and maybe impacts openaps through wrong iob.

**To Reproduce**
Create combo bolus in Nightscout through care portal. Then try to end the combo bolus somehow, so that the graph reflects the cancellation.  The API obviously reflects this in its devicestatus, in the extended section, the combobolus goes on, until deadline reached.

**Expected behavior**
As cancellation of a combo bolus happens, it should be possible to reflect this in Nightscout, I submitted it as a bug, as it seemed obvious that it should be possible, and it leads to potential errors in iob.

Nightscout (e.g. 0.11.1 latest)

AAPS feeds Nightscout, CGM g6, pump is Insight, my use case would be cancellation through sms.

**Comment by sulkaharo** [comment]
The data model expects the uploader to edit the original item duration to match the actual length of the bolus if it was cancelled. If this was entered manually, we sadly don't have a very user friendly UI to do this by hand (you can go to reports and edit the event there).
