### ISSUE TITLE
Nightscout app crashes after heroku installation

### ISSUE THREAD

**Issue by buessow** [nightscout/cgm-remote-monitor#4569]
I followed the setup instructions (here: http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku) to create a new instance on Heroku. The app doesn't start with the error below. Any idea what might be the problem?

Apr 29 11:48:32 rmb-cgm app/web.1: Setting up new connection to MongoDB 
Apr 29 11:48:32 rmb-cgm app/web.1: GIT HEAD  
Apr 29 11:48:32 rmb-cgm app/web.1: Successfully established a connected to MongoDB 
Apr 29 11:48:32 rmb-cgm app/web.1: Mongo Storage system ready 
Apr 29 11:48:33 rmb-cgm app/web.1: Pushover was NOT configured 
Apr 29 11:48:33 rmb-cgm app/web.1: Ensuring indexes 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: date 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: type 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: sgv 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: mbg 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: sysTime 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: dateString 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: created_at 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: eventType 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: insulin 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: carbs 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: glucose 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: enteredBy 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: boluscalc.foods._id 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: notes 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: created_at 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: startDate 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: type 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: position 
Apr 29 11:48:33 rmb-cgm app/web.1: ensuring index for: hidden 
Apr 29 11:48:33 rmb-cgm app/web.1: Dexcom bridge not enabled 
Apr 29 11:48:33 rmb-cgm app/web.1: /app/node_modules/minimed-connect-to-**nightscout/node_modules/request/node_modules/tough-cookie/node_modules/ip-regex/index.js:3 
Apr 29 11:48:33 rmb-cgm app/web.1: const v4 = '(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(?:\\.(?:25[0- 
Apr 29 11:48:33 rmb-cgm app/web.1: ^^^^^ 
Apr 29 11:48:33 rmb-cgm app/web.1: SyntaxError: Use of const in strict mode. 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Module._compile (module.js:439:25) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Object.Module._extensions..js (module.js:474:10) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Module.load (module.js:356:32) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Function.Module._load (module.js:312:12) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Module.require (module.js:364:17) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at require (module.js:380:17) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Object.<anonymous> (/app/node_modules/minimed-connect-to-nightscout/node_modules/request/node_modules/tough-cookie/lib/cookie.js:34:15) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Module._compile (module.js:456:26) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Object.Module._extensions..js (module.js:474:10) 
Apr 29 11:48:33 rmb-cgm app/web.1:     at Module.load (module.js:356:32) 
Apr 29 11:48:33 rmb-cgm app/web.1: error: Forever detected script exited with code: 8**

**Comment by unsoluble** [comment]
Sure your repository is up to date? There was a bug in an older version that could cause this crash.

**Comment by unsoluble** [comment]
Your repository is significantly out of date. Make sure you're logged in here on GitHub, then head [here](http://nightscout.github.io/pages/update-fork/) to begin the update process. Once that's done, go to your Deploy page in Heroku and manually deploy your master branch one more time.

**Comment by buessow** [comment]
Many thanks. Didn't realize that I've created it a long time ago.
