### ISSUE TITLE
Need to gracefully handle nulls in uploaded data

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#4570]
We should make sure that null entries are handled gracefully, and don't cause the whole stack to crash.

Re: [https://github.com/openaps/oref0/issues/1228](https://github.com/openaps/oref0/issues/1228)

**Comment by sulkaharo** [comment]
So, this is non-trivial to solve comprehensively. Things that need doing is:

1) Better overall validation of data on upload so data that's made it into the database is guaranteed better overall integrity - records that are missing required fields or have clearly misformatted data should be rejected and an error should be returned to the REST API caller. Implementing comprehensive validation is somewhat difficulty / time intensive, but we could easily do a better job at this. Note this would probably break some uploader apps, but this would be solved in time through users reporting the issues to the developers (and we could proactively have the dev community fix most uploaders; whether users upgrade to the fixed versions or not is another discussion).

2) Implement better isolation of error states in the codebase, so one part of the app crashing doesn't cause the rest of the app to crash; note users would not necessarily understand what happened in this instance and would just see parts of the application not work with no understanding how to fix things. And this being an error state, it'd by definition be something unexpected happening and thus it's hard to message to the user what exactly went wrong.

What's _not_ the right solution here is so called defensive programming where we add null checks to everywhere in the code to deal with broken data - the most graceful solution would be a full implementation of #1 with full reporting, where user would be told a clear error report on which app tried to inject broken data, with instructions how to report the bug.
