### ISSUE TITLE
HTTP 500 when xDrip+ calls entries REST-API to upload a new BG reading

### ISSUE THREAD

**Issue by renegadeandy** [nightscout/cgm-remote-monitor#4585]
xDrip+ starts to report : 

NightscoutUploader Unable to do REST API upload: Internal server error url: <my nightscout url> marking record failed - out of nowhere.

Nightscouts log at that exact moment looks as follows:

```
GRANTED:  92.239.205.226 api-secret api:entries:read
GRANTED:  92.239.205.226 api-secret api:entries:create
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2019-04-27T21:02:19.421Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:535, treatments:287, mbgs:3, cals:2, profiles:1, devicestatus:29, profileTreatments:1, tempbasalTreatments:170
reloading sandbox data
WS: running websocket.update
delta changes found on treatments
lastData full size 435356 bytes
WS: running websocket.emitData 1557090139421
tick 2019-05-05T21:02:22.748Z
searching treatments q { find: { created_at: { '$gte': '2019-04-27T21:02:27.748Z' } },
  sort: { created_at: 1 } }
```

No problems are obvious here.

I recreated the issue by using the api-docs.html and calling the entries POST API. I found that I also got an HTTP 500, with these specific errors:

```
{
  "status": 500,
  "message": "Mongo Error",
  "description": {
    "driver": true,
    "name": "MongoError",
    "index": 0,
    "code": 12501,
    "errmsg": "quota exceeded"
  }
}
```
I then looked at my mlab mongodb hosting, and found that devicestatus was full. I cleared that but the problem maintained.

I eventually fixed it by clearing the devicestatus collection and then did a `db.repairDatabase()`.

Then nightscout was able to perform the upload.

Perhaps nightscout could perform this repair, or better log the quota exceeded or mongodb error to the running console - there was literally no way for me to know the details of the problem without manually executing the API call.

**Your setup information**
Nightscout version is : version 0.11.1
Libre with MiaoMaio

**Comment by PieterGit** [comment]
@renegadeandy thanks for the report. Gitter discussion is at https://gitter.im/nightscout/public?at=5ccf5f80a4ef09747155f0dd . 
@jpcunningh do you known  why we don't log something on the Nightscout console in this case? Can we detect that the mongodb has enough space again and automatically call `db.repairDatabase()`?
@jamorham I think the remote client (xdrip plus in this case) should also show the `errmsg`  or `message` to the user.

**Comment by jpcunningh** [comment]
@PieterGit, better logging on the console and a user level alert is on my backlog that I just haven't gotten to, yet.

Adding a repairDatabase call is on my backlog as well. I'm not sure if it makes more sense to try to have it called automatically whenever the user uses the admin tool to delete old records, or if it should be a separate admin tool button. Thoughts?

**Comment by renegadeandy** [comment]
I think there should be a message suggesting people check their quota for the mongodb, and then perhaps perform a db.repairDatabase() by default, incase somebody clears space but doesn't realise the repair is required (which was my use case). 

Also perhaps have a button which will also call the repairDatabase when the user wants to drive it manually.

**Comment by sulkaharo** [comment]
@PieterGit Mongo doesn't have a quota system by default and when I asked about this from mLab, they don't seem to have a clear API for checking how much quota is left. Needing to run db.repairDatabase() is a bad sign as well - this should only be needed if there's table corruption on the database or if the table index is somehow badly out of whack. We could add a tool in the admin section to run this though? The repair takes some time, so probably can't add this to app start.

**Comment by sulkaharo** [comment]
@Midgeyran It's likely your MongoDB is full. Assuming you're on Atlas, you need to go to to the Mongo service and clear up space in the database.
