### ISSUE TITLE
Add tests to c-r-m for better end-user troubleshooting

### ISSUE THREAD

**Issue by jimsiff** [nightscout/cgm-remote-monitor#463]
It would be nice to have some tests in c-r-m for Mongo database access and data integrity, then report problems to remote monitor clients and /pebble.  These are just concepts... I have no idea whether they would require huge changes or just some simple tests.
- Always load web page to time and dashes, even when Mongo database is unavailable.  Never display a white page when Mongo server is down.  A white page makes it harder for users to differentiate between a web server and back end issue.
- Check for valid MONGO_CONNECTION URI syntax.  Report "syntax error or no variable set" via web monitor and /pebble.  This is mostly helpful during new setups where users don't follow the setup guides.  Value is debatable after initial setup.
- Test access to Mongolab server via URI.  If no access, report "Mongo down status" via web monitor and /pebble.  This is more helpful than a white page.
- Test for valid data from Mongo collection.  If none, report "no data" via web monitor and /pebble.
- Test for enough data to display a trend... (three values?).  If not enough, report "need more data" via web monitor and /pebble.
- Test latestSGV date / time against server and/or remote monitor date / time.  If latestSGV is in the future relative to server or remote monitor, report "date / time mismatch" via web monitor and /pebble.

What do you think?  Is this a good idea and doable?
##

**Comment by jimsiff** [comment]
Re the SGV date / time test... I realize that any data point in the future will cause the same issue... but at least a latestSGV test would flag ongoing issues rather than an issue with past data.

**Comment by jasoncalabrese** [comment]
@bewest has a couple open PR's that need a little clean, but should let us handle the mongo connection issue better.  A diagnostics page would be nice, but maybe we can just extend the status endpoint.
