### ISSUE TITLE
Meal / Correction Bolus do not display on Firefox

### ISSUE THREAD

**Issue by declan-wade** [nightscout/cgm-remote-monitor#4646]
Upon loading the Nighscout dashboard / home page on Firefox, it does not correctly display any Meal or Correctional Bolus data points. Loading the same dashboard on the same computer, but in a different web browser shows the bolus data correctly.

Screenshots: https://imgur.com/a/rPigX6J

This is running on Nightscout 0.11.1, with data being collected by Spike on iOS and hosted on Heroku. Version numbers of the web browsers are in the Imgur captions.

**Comment by unsoluble** [comment]
Not sure what's causing the rendering errors, but total aside: Make sure your BG thresholds in Heroku are set in mg/dl values — that's why your graph is all red. :)

**Comment by seanknox** [comment]
Confirming this—appears the bolus pills don't show up in Firdfox. 

Here's my NS instance in Chrome 74.0.3729.169:

### Chrome
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1231630/59123747-dd7ec480-8912-11e9-9698-decf4c1a3268.png">

And here's the same screen in Firefox Quantum 67.0:

### Firefox Quantum
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1231630/59123845-16b73480-8913-11e9-833f-85715b68611f.png">

**Comment by seanknox** [comment]
Perhaps relatedly, there are a number of JS errors in Firefox.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/1231630/59124094-9fce6b80-8913-11e9-85f7-0d9f2ac4cd03.png">
