### ISSUE TITLE
Open APS Bolus wizard treatments don't appear in NS

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/cgm-remote-monitor#4685]
When I use the bolus wizard on my 722, the carb and bolus treatment don't appear in NS. The same thing happens for Easy Bolus. Quick bolus DOES get displayed..

The odd thing is... they all DO appear in NSClient downstream.

Here is an example which does appear in mlab at ~Jun 14 3pm NZST...

```
"_id": {
        "$oid": "5d030edadab7d271c3267a16"
    },
    "duration": 0,
    "bolus": {
        "_type": "Bolus",
        "_description": "Bolus 2019-06-14T15:01:00 head[4], body[0] op[0x01]",
        "timestamp": "2019-06-14T15:01:00+12:00",
        "_body": "",
        "appended": [
            {
                "_type": "UnabsorbedInsulinBolus",
                "_description": "UnabsorbedInsulinBolus unknown head[5], body[0] op[0x5c]",
                "_body": "",
                "_head": "5c0528ef44",
                "data": [
                    {
                        "amount": 1,
                        "age": 239
                    }
                ],
                "_date": ""
            }
        ],
        "programmed": 0.5,
        "duration": 0,
        "amount": 0.5,
        "_head": "01050500",
        "type": "normal",
        "_date": "40814f0e13"
    },
    "timestamp": "2019-06-14T15:01:00+12:00",
    "created_at": "2019-06-14T03:01:00.000Z",
    "carbs": 4,
    "ratio": "8",
    "bg": "48",
    "glucose": 48,
    "glucoseType": "BolusWizard",
    "wizard": {
        "unknown_byte[8]": 0,
        "_type": "BolusWizard",
        "bg": 48,
        "_byte[5]": 0,
        "unknown_byte[10]": 0,
        "_description": "BolusWizard 2019-06-14T15:01:00 head[2], body[13] op[0x5b]",
        "timestamp": "2019-06-14T15:01:00+12:00",
        "_body": "04900814300005000002000582",
        "bg_target_high": 130,
        "sensitivity": 20,
        "carb_ratio": 8,
        "food_estimate": 0.5,
        "unabsorbed_insulin_total": 0.2,
        "correction_estimate": 0,
        "carb_input": 4,
        "_head": "5b30",
        "unabsorbed_insulin_count": "??",
        "_byte[7]": 0,
        "bolus_estimate": 0.5,
        "_date": "40810f0e13",
        "bg_target_low": 48
    },
    "eventType": "Meal Bolus",
    "insulin": 0.5,
    "notes": "Normal bolus with wizard.\nCalculated IOB: 0.441\nProgrammed bolus 0.5\nDelivered bolus 0.5\nPercent delivered:  100%\nFood estimate 0.5\nCorrection estimate 0\nBolus estimate 0.5\nTarget low 48\nTarget high 130\nHypothetical glucose delta -10\nGlucose was: 48",
    "medtronic": "mm://openaps/mm-format-ns-treatments/Meal Bolus",
    "enteredBy": "openaps://medtronic/722",
    "timeZoneOffset": -720
}
```
I'm on this branch
https://github.com/nightscout/cgm-remote-monitor/pull/4658
Which addressed this issue
https://github.com/openaps/oref0/issues/1263

Unsure if this new issue is a result of that, or if it's a separate manifestation of the same problem.

**Comment by sulkaharo** [comment]
Reading that data, there's nothing in it that obviously jumps at me as a reason why this would not show up in the Nightscout visualization, if this is in the treatments collection. FWIW OpenAPS Wizard entries from our 554 work as expected? What's the symptom you're seeing?

**Comment by sulkaharo** [comment]
Oh also, that negative timeZoneOffset looks like you're running an older version of the branch, can you update to latest?

**Comment by old-square-eyes** [comment]
Yes it's in treatments. OK will do another bolus Wizard before and after the branch update deploy. I actually think this was present prior to the date normalize work.

Other notes:
:: It's the main NS visual I'm not seeing these bolus wizard treatments. Not too sure where else they might be expected to appear (per your question on Gitter)
:: I reduced DB size and repaired prior to validating this

**Comment by old-square-eyes** [comment]
Here are screen shots...
**NS**
![image](https://user-images.githubusercontent.com/25760491/59639365-28b89300-91af-11e9-9f43-b3e5045d5f9b.png)
**NSClient**
![image](https://user-images.githubusercontent.com/25760491/59639430-5ef61280-91af-11e9-8a65-9a21025e7ba7.png)
**mLab**
![image](https://user-images.githubusercontent.com/25760491/59639490-8baa2a00-91af-11e9-99bc-cba091674e7b.png)

**Comment by old-square-eyes** [comment]
Same again after updating the Normalization branch

**Comment by sulkaharo** [comment]
With that Nightscout screenshot, note how the OpenAPS predictions haven't yet updated to the latest CGM point, which indicates the Nightscout UI hasn't yet updated with all the data. NSClient uses a different way to update the interface, so there's a short time window during which it's possible NSClient will show a treatment but Nightscout doesn't. Is it that the treatment never appears? Also, the next time you see this, if the treatment is taking >60 seconds to appear, can you 1) check if you can see the treatment in the Treatments report, and 2) then try restarting the Nightscout dynos in Heroku and reloading the site, to see if that makes the treatment to appear?

**Comment by old-square-eyes** [comment]
No it never appears. OK I'll test the report and dyno restart. Thanks for
looking at this :)

**Comment by old-square-eyes** [comment]
Restarting dynos and reloading doesn't help.

Bolus wizard treatment has shown in the report though...

![image](https://user-images.githubusercontent.com/25760491/59752379-416f9880-92d6-11e9-9887-ef0a0362c509.png)

**Comment by old-square-eyes** [comment]
Leaving a comment from Gitter that the BG entered was 6.3, not 63 as shown, so there may be a smoking gun, or another issue present.

**Comment by old-square-eyes** [comment]
Manually edited a record in mlab and it shows up in NS so it seems the loss of the decimal point is the cause. Looking at the data, a lot of the numeric mmol/L values are the same (target BG, BG and sensitivity)

**Comment by old-square-eyes** [comment]
Raised in Open APS https://github.com/openaps/openaps/issues/142

**Comment by sulkaharo** [comment]
So noting here, the issue is caused by the data bug in the treatment record, where the BG value recorded is 10x higher than the real BG, which caused the treatment to be rendered outside the screen. The issue is mitigated by #4697 by clamping the BG value for rendering purposes, so treatments with buggy CGM data are now visible on screen.
