### ISSUE TITLE
Wrong CAGE label on Spanish

### ISSUE THREAD

**Issue by nfontan** [nightscout/cgm-remote-monitor#4689]
On cgm-remote-monitor/lib/language.js
line 12185
      ,es: 'Carb.desde'
is wrong

Correct traduction is
     ,es: 'Cánula desde'

I also change the following line to reduce the size of the label
line 12207
      ,es: 'Carbohidratos activos'
      ,es: 'Carb. activos'

https://github.com/nfontan/cgm-remote-monitor/blob/master/lib/language.js

**Comment by unsoluble** [comment]
Don't really need to make an issue to accompany a PR — just put your notes in the PR's description. :)

(Fixes are in #4690)

**Comment by sulkaharo** [comment]
Soon to be fixed in dev
