### ISSUE TITLE
loading stuck

### ISSUE THREAD

**Issue by shailoantz** [nightscout/cgm-remote-monitor#4694]
**Describe the bug**
When no BG available - loading the client takes a lot of time and sometimes getting entirely stuck.
This error makes it harder to know if I have internet issues or a CGM error

**To Reproduce**
1. Have a working nightscout instance with BG and all
2. Have a CGM error (or xdrip error or any way to not feed BG to NS)
3. Refresh my NS instance

**Expected behavior**
I would expect that at least a message will be displayed. That way I can understand that my internet or device is not the issue

**Your setup information**
- What version of Nightscout - 0.11.1
- What type of CGM, and how do you get your data there? Dexcom G5 + xdrip

**Comment by sulkaharo** [comment]
Do you mean a single record is missing, or that a large amount of data is missing? Are you loading nightscout over the same data connection as what's used for uploading the data (so issues in Internet connectivity can cause both to fail)?

**Comment by shailoantz** [comment]
no. I am talking about a situation when the CGM has an unrelated error (e.g
bad connection to the body) and it does not transmit any data because it
does not have any current data. About the internet connection - I'm
maintaining the loop of my brother so usually when this error happens we do
not share the same internet network. Anyway, this happens a lot when I have
a good connection...
