### ISSUE TITLE
CAGE displays n/a if over 8 days old

### ISSUE THREAD

**Issue by tynbendad** [nightscout/cgm-remote-monitor#4718]
**Describe the bug**
The cage pill displays n/a when the cage reaches 8 days old.  It doesn't have the right insertion date when you hover over it either.  Believe it or not my son has been reaching this a few times now.

**To Reproduce**
Erase all your cannula insertion treatment events on Nightscout.
Insert one 7 days and 23 hours or so ago.
Refresh for a while and watch cage turn from correct time to n/a.

**Expected behavior**
I would expect it to show cage for longer than 8 days, similar to sage.

**Screenshots**

**Your setup information**
- 0.11.1

**Comment by sulkaharo** [comment]
Fixed in dev, the data loader now loads the latest site change event from the last 32 days.
