### ISSUE TITLE
Nightscout API Secret doesn't work through reverse proxy

### ISSUE THREAD

**Issue by rkoshak** [nightscout/cgm-remote-monitor#4721]
One other interesting behavior I notice is that when accessing Nightscout locally or through the VPN I can see the graph and everything without entering an API key. But if I access the site through the reverse proxy it demands I enter the API key or it won't show anything.

I'm using the following environment variables:

```
MONGO=mongodb://nightscout:password@localhost:27017/nightscout
API_SECRET=LONGAPISECRETSTRING
ENABLE=careportal%20basal%20bwp%20iob%20cob%20cage%20sage%20iage
DISPLAY_UNITS=mg/dl
PORT=80
INSECURE_USE_HTTP=true
```
xDrip is successfully publishing readings to Nightscout through the reverse proxy. It is only bringing up the web page through the reverse proxy that is showing problems.

I've left the HOSTNAME as the default so it should be listening on any URL path I use to get to it, and that appears to be the case. I'm also using the default value for AUTH_DEFAULT_ROLES which should allow readable for all users. 

It seems that when accessing through the reverse proxy it is both setting AUTH_DEFAULT_ROLES to denied or status-only and it's not accepting the API secret at all.

**To Reproduce**
1. Configure HAProxy (any reverse proxy?) with basic authentication.
2. Access Nightscout locally with the API Secret, it works
3. Access Nightscout through the reverse proxy with the API Secret, it says wrong API Secret.

**Expected behavior**
I expect the same API Secret to work whether I'm accessing Nightscout directly or through a reverse proxy.

**Your setup information**
- Nightscout 0.11.1
- Dexcom G6 using xDrip as the collector. xDrip is configured to publish the data straight to Nighscout's REST API and it is successfully publishing through the reverse proxy.
- I've tested on Chrome on both my phone and on a Chromebook.

**Comment by mastacheata** [comment]
Set the INSECURE_USE_HTTP environment variable to true and it will start working again. Otherwise it will try to perform an HTTP 301/302 redirect that looses all POST and authentication data during the redirect.

**Comment by mastacheata** [comment]
What's the output of Nightscout on the commandline (The node/expressjs process)?
In my case it didn't work unless I set INSECURE_USE_HTTP explicitly to true (despite the code in app.js checking for the presence of an X-Forwarded-Proto header, which should be set on an TLS termination reverse proxy)

Can you open the web browser dev tools on the network tab and see if there is a 302 status code when entering the API secret? If so, your app isn't properly capturing the environment variable nor is it identifying the X-Forwarded header set by your reverse proxy. 

You submit the API secret dialog using a POST request and when the browser receives a 302 redirect, it will move to the redirected site, but using a GET request and thus losing all the information previously sent along.
