### ISSUE TITLE
Split language.js file to separate languages

### ISSUE THREAD

**Issue by michalterbert** [nightscout/cgm-remote-monitor#4723]
**Is your feature request related to a problem? Please describe.**
Now JS file with languages has 527 KB, maybe a good idea is to split that file. 

**Describe the solution you'd like**
Separate JS language file, one per every language.

**Comment by PieterGit** [comment]
@michalterbert thanks for your suggestion.
This is a duplicate of https://github.com/nightscout/cgm-remote-monitor/pull/4209
Might be a candidate for 0.13.x release.
