### ISSUE TITLE
Alexa seems no longer to work

### ISSUE THREAD

**Issue by mhaeberli** [nightscout/cgm-remote-monitor#4731]
**Describe the bug**

Followed the Alexa setup.
Tested; nothing happened.

**To Reproduce**

**Expected behavior**
I expected to get Alexa test responses (or real responses)

**Screenshots**

**Your setup information**
- What version of Nightscout (e.g. 0.10.3)
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?

**Additional context**

**Comment by PieterGit** [comment]
@mhaeberli Can you please test https://github.com/nightscout/cgm-remote-monitor/pull/4980 and report if that fixes your Alexa problem. Please check with @inventor96  if he can help you fix your Alexa problem.

**Comment by PieterGit** [comment]
Closing due to long inactivity. Please use new refactored 4980 Alexa PR if you still have problems with Alexa integration.
