### ISSUE TITLE
Clock view - only black screen

### ISSUE THREAD

**Issue by maskac** [nightscout/cgm-remote-monitor#4750]
Is this a new bug with the latest release, have you seen this earlier?
Is only in 0.12 . 11.1 work corectly.

Which device / browser version was used to reproduce the bug?
Anybrowser (chrome/firefox/ie) , using docker + alpine node 10 image

Does this happen every time you launch Nightscout, or sometimes?
Every time.

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)
Switch to clock view - screen is black or white with no text.
URL si  clock/bgclock

![download](https://user-images.githubusercontent.com/16052233/61581543-f688b100-ab1f-11e9-86b1-023decba19ac.png)

**Comment by unsoluble** [comment]
This was fixed in 0.12.1 — update your fork again. :)

**Comment by maskac** [comment]
It's working. Thx.
