### ISSUE TITLE
mmconnect plugin is failing on bad date data for some users

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#4753]
(Filing this on behalf of @LynneRB and a couple others)

Something's happening with some users' data coming into NS via the `mmconnect` plugin — looks like a bad datestamp in some part of the chain. Users report that date/time is correct on all the devices involved.

Have tried reaching out to @szymjaw and @mddub on Gitter, but didn't get a response there.

Relevant log section:

```
Jul 20 12:55:19 lynne app/web.1: Sat Jul 20 2019 19:55:19 GMT+0000 (Coordinated Universal Time) Guessed pump timezone -NaN00 (pump time: "2019-07-20T14:50:42-05:00"; server time: Sat Jul 20 2019 19:55:19 GMT+0000 (Coordinated Universal Time)) 
Jul 20 12:55:19 lynne app/web.1: /app/node_modules/minimed-connect-to-nightscout/transform.js:50 
Jul 20 12:55:19 lynne app/web.1:   return new Date(timestamp).toISOString(); 
Jul 20 12:55:19 lynne app/web.1:                              ^ 
Jul 20 12:55:19 lynne app/web.1: RangeError: Invalid time value 
Jul 20 12:55:19 lynne app/web.1:     at Date.toISOString (<anonymous>) 
Jul 20 12:55:19 lynne app/web.1:     at timestampAsString (/app/node_modules/minimed-connect-to-nightscout/transform.js:50:30) 
Jul 20 12:55:19 lynne app/web.1:     at /app/node_modules/minimed-connect-to-nightscout/transform.js:144:21 
Jul 20 12:55:19 lynne app/web.1:     at Array.map (<anonymous>) 
Jul 20 12:55:19 lynne app/web.1:     at sgvEntries (/app/node_modules/minimed-connect-to-nightscout/transform.js:138:6) 
Jul 20 12:55:19 lynne app/web.1:     at Object.module.exports [as transform] (/app/node_modules/minimed-connect-to-nightscout/transform.js:176:26) 
Jul 20 12:55:19 lynne app/web.1:     at handleCarelinkData (/app/lib/plugins/mmconnect.js:55:33) 
Jul 20 12:55:19 lynne app/web.1:     at next (/app/node_modules/minimed-connect-to-nightscout/node_modules/common/index.js:138:6) 
Jul 20 12:55:19 lynne app/web.1:     at Object.parseData (/app/node_modules/minimed-connect-to-nightscout/carelink.js:142:5) 
Jul 20 12:55:19 lynne app/web.1:     at next (/app/node_modules/minimed-connect-to-nightscout/node_modules/common/index.js:138:6) 
Jul 20 12:55:19 lynne heroku/web.1: State changed from up to crashed
```

**Comment by sulkaharo** [comment]
We need access to someone's data / a data sample in order to fix. Ideas how to get this?

**Comment by szymjaw** [comment]
@sulkaharo 
I need data from US carelink site. 
I think, today I will fix it.
But I need pump data from both carelink sites (US and EU).

**Comment by szymjaw** [comment]
I created pull request
[https://github.com/mddub/minimed-connect-to-nightscout/pull/13](https://github.com/mddub/minimed-connect-to-nightscout/pull/13)

**Comment by leftyg** [comment]
Question, do I have to run two NS instances to get this workaround implemented? One for minimed-connect-to-nightscout and the other for cgm-remote-monitor?

**Comment by unsoluble** [comment]
You’ll need to wait for this fix to be merged (or for a fix coming from another angle), and then update your NS site. Forking the mmconnect repo isn’t going to get you anywhere.

**Comment by PieterGit** [comment]
@leftyg @unsoluble @LynneRB 
Implemented a fix for this by Integration of minimed-connect-to-nightscout v1.3.1 into Nightscout. 
I can't test this myself. Please help test this PR: https://github.com/nightscout/cgm-remote-monitor/pull/4915 and report your findings there.

**Comment by szymjaw** [comment]
I test with success. Both US with login data from @LynneRB and my, EU.

**Comment by PieterGit** [comment]
fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4915 . Closing this issue
