### ISSUE TITLE
you don't see override in NS when you activate it in a loop.

### ISSUE THREAD

**Issue by francescaneri** [nightscout/cgm-remote-monitor#4761]
**Your setup information**
- version of Nightscout 0.12.2
- all browser (Safari/Chrome) 
- Latest commit 6191ccf LoopKit/loop "dev"  

Thanks Matteo

**Comment by sulkaharo** [comment]
Can you please answer all the questions in the issue template - I bet most people here don’t have enough context to do anything about this.  Is this a feature request or a bug?

**Comment by francescaneri** [comment]
<img width="1275" alt="Schermata 2019-07-21 alle 14 27 21" src="https://user-images.githubusercontent.com/9915825/61591176-b4b14680-abc3-11e9-8564-28450afff11b.png">
<img width="351" alt="Schermata 2019-07-21 alle 14 29 16" src="https://user-images.githubusercontent.com/9915825/61591196-f93ce200-abc3-11e9-9d04-4bcaeffa125b.png">

I think it's a bug

**Comment by francescaneri** [comment]
![image](https://user-images.githubusercontent.com/9915825/61591291-4a010a80-abc5-11e9-9df6-3ab1af6905ce.png)
 This is the situation in the loop.

**Comment by sulkaharo** [comment]
I still don't understand what this ticket is about. Can you please clearly describe if this is a bug (something used to work and now doesn't) or a feature request (something that hasn't existed but you'd like to see), along with a clear description of what you expected to happen

**Comment by francescaneri** [comment]
I thought it should work as reported in this issue. Override mode plugin #4587

**Comment by francescaneri** [comment]
solved with the latest versions of loop v.1.10.1 thanks @ps2 @Kdisimone
