### ISSUE TITLE
Menu-button and careportal+ to much to the left

### ISSUE THREAD

**Issue by whooze** [nightscout/cgm-remote-monitor#4762]
**Screenshots**
![Screenshot_20190721-133937_Chrome](https://user-images.githubusercontent.com/4024639/61590744-c859ae80-abbd-11e9-8880-82a75a4b555d.jpg)

**Your setup information**
- What version of Nightscout 0.12.2
- What type of CGM, and how do you get your data there? Medtronic 600 series uploader
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? Chrome on Android-phone

**Additional context**
Seen it on iOS with Nightscout X as well

**Comment by antiann** [comment]
Ooh, I just noticed this https://github.com/nightscout/cgm-remote-monitor/pull/4748

**Comment by unsoluble** [comment]
Fixed in 0.12.3.
