### ISSUE TITLE
curl request using date -Ihours gives error with v0.12.2

### ISSUE THREAD

**Issue by efidoman** [nightscout/cgm-remote-monitor#4797]
**Describe the bug**
Two Logger users who upgraded to NS 0.12.2 noticed errors in the Logger logfile that were associated with curl statements to NS that use a where clause for create_at that use a unix "date -d -Ihours got an error returned after upgrading to 0.12.2.

**To Reproduce**
1. Go to unix command line and run the following curl statement:
2. curl --compressed -m 30 -H "API-SECRET: ${API_SECRET}" "${NIGHTSCOUT_HOST}/api/v1/treatments.json?find\[created_at\]\[\$gte\]=$(date -d "100 days ago" --iso-8601=seconds $UTC)&find\[eventType\]\[\$regex\]=Sensor.Start&count=1"
 
  replace ${API_SECRET} with your API_SECRET and ${NIGHTSCOUT_HOST} with your NS url if necessary.

3. See error
{
"error": {
"message": "Invalid time value",
"stack": "RangeError: Invalid time value\n at Date.toISOString (<anonymous>)\n at /app/lib/server/query.js:65:47\n at Array.forEach (<anonymous>)\n at enforceDateFilter (/app/lib/server/query.js:61:28)\n at create (/app/lib/server/query.js:110:5)\n at query_for (/app/lib/server/treatments.js:98:12)\n at Function.list (/app/lib/server/treatments.js:92:13)\n at /app/lib/api/treatments/index.js:39:24\n at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n at next (/app/node_modules/express/lib/router/route.js:137:13)"
}

**Expected behavior**
Before version 0.12.2, this curl statement returned "[]" if no records exist or something like the following if a Sensor Start treatment was done in last 100 days. 

[{"_id":"5d180d4f2a178166ab5c4041","enteredBy":"","eventType":"Sensor Start","reason":"","duration":0,"notes":"9311","created_at":"2019-06-30T01:15:59.043Z","carbs":null,"insulin":null}]Add any other context about the problem here.

**Screenshots**
N/A

**Your setup information**
- What version of Nightscout (e.g. 0.12.2)
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.) 
Dexcom G6 --> Logger (OpenAPS)

- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?
No

**Additional context**
Logger has been modified in both master/dev branches to change to use -Iseconds instead of -Ihours and the Logger issue is no longer occuring.

**Comment by efidoman** [comment]
Researching the issue helped further clarify the problem. There **is not** an issue with NS 0.12.2 curl statements using -Iminutes. There **is** an issue with 0.12.2 curl statements using -Ihours. I checked oref0 again and I don't see anywhere -Ihours are being used in curl statements to NS. This is good and therefore the priority of this issue may be a bit lower than earlier expected (unless there are other implementations that use hours for the date in curl/web requests. Logger has already been modified to use -Iseconds. I also searched through Lookout code and do not see where this will cause a problem for users of Lookout.

**Comment by sulkaharo** [comment]
@efidoman does this happen for all users, or just some? Can you get the request URL sent to Nightscout? Looks like the `date` utility works differently across different operating systems, so it's really hard to tell exactly what the dates are that are being sent.

At least what might be going on is the issued ISO date has to be properly URL encoded as it contains a plus sign, which is a reserved character in URLs and from what I can see, this script doesn't do the encoding, leading to hard to predict behavior.

Also I wouldn't necessarily call this a regression as Nightscout has only ever officially supported full ISO-8601 dates and any other date formats have just incidentally returned results, but probably not the results you were expecting (as the dates were just considered string, not dates).

**Comment by bewest** [comment]
Also be aware you may need to use `curl -g` to turn "globbing" off.  Syntax like `{...}` and `[...]` get turned into glob patterns in curl by default.  https://ec.haxx.se/cmdline-globbing.html.  We use a similar syntax (compatible with [php's `parse_str`](https://www.php.net/manual/en/function.parse-str.php), ) to build up the query json object to pass to mongo's query interface.

**Comment by sulkaharo** [comment]
Lol @bewest yes and getting the globbing to work for the latest release on a new library that's still maintained and didn't have years old dependencies with terrible security issues was interesting :D

**Comment by sulkaharo** [comment]
@efidoman can you try https://github.com/nightscout/cgm-remote-monitor/pull/4806 if that changes the API behavior for you

**Comment by sulkaharo** [comment]
Now running #4806 in production, works with our OpenAPS 0.6.3 install (but not using Logger).

**Comment by PieterGit** [comment]
@efidoman Can you give an status update on this issue? 

Does https://github.com/nightscout/cgm-remote-monitor/pull/4806 (merged with 0.12.3? ) fix this issue?

**Comment by PieterGit** [comment]
@efidoman @sulkaharo Please let me know if this issue is fixed with 0.12.3 or not. This issue is still open, but the 0.12.3 release is out of the door.

**Comment by PieterGit** [comment]
Did not make the 0.12.x releases. Postponing to 0.13.x

@efidoman @sulkaharo @jpcunningh Can you enlighten me with if this is still needed?
