### ISSUE TITLE
Completely drop Azure support (or not)

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4798]
**Is your feature request related to a problem? Please describe.**
Yes, Azure deploy does not seem to work for Nightscout 0.12.x (x=[0,1,2] ) and current `dev`
Up to Nightscout 0.11.x Azure worked, but was (strongly) discouraged.

**Describe the solution you'd like**
A clear choice:
1) do we or do we not support Azure. If we do, who is taking ownership for Azure deployment testing (and possibly development)?
2) if Azure support does not work, do we remove Azure specific code or not?

**Reasons to drop Azure support**
- Azure's node support is out of date and non-standard. 
- Node versions are often out of date, so users might use Node versions with security issues
- Deployment is not standard, and requires specific code and environment variables
- Azure's free-tier quotas are too low to support NS, 
- Userinterface for deploying is quite hard to grasp
- None of the (core) developers use Azure
- Nobody wants to test Azure deployments before a release

**Reasons NOT to drop Azure support**
- We should not be dependent on 1 SaaS platform like Heroku

**Describe alternatives you've considered**
Other alternatives:
- Somebody steps up and take ownership for at least testing Azure
- @jansche has offered support from the engineering folks from Azure
- Higher default (CPU) quota's for free use of Azure
- Things we can do is to do the `webpack` and package the files with a npm release. That would limit the amount of CPU needed. That would require somebody to step up and make that work.
- Make Nightscout deployment less CPU-hungry. That would require somebody to step up and make that work.

**Additional context**
Relevant Gitter links:
- https://gitter.im/nightscout/public?at=5d381ba0be916e76e2295288 (report of not working Azure)
- https://gitter.im/nightscout/public?at=5d38db1fd1cceb1a8db71855 (Microsoft employee @jansche will see if he can help us. Perhaps also via @shanselman  )

I would like a clear choice of at least the core developers, before we proceed to drop Azure specials from the code and adjust the docs. If we do support it or drop support. If we drop support do we drop it for Nightscout 0.12.3 and remove the code with Nightscout 0.13.x?
@jasoncalabrese @MilosKozak @sulkaharo:  may I have your 👍 or 👎  on dropping support?

@pogman Did you have a change to retry if Nightscout 0.12.2 on Azure is broken or not?

My vote:
👍 on documenting no Azure support in 0.12.3 and drop it completely for 0.13.x. That is unless somebody takes ownership for testing future Nihgtscout releases with Azure, then we should do that. I don't mind helping people, but I won't spend time in getting Nightscout to run on Azure myself (spent way to much time, and charged my own credit card for the community sake).

**Comment by unsoluble** [comment]
For what it's worth, I've taken a brief look at a bunch of current Saas alternatives — Google App Engine, Digital Ocean, LiquidWeb, Back4Web, and none of them seem to fit our needs (none are free, primarily).

**Comment by bewest** [comment]
Howdy all! Thanks for the continued support and maintenance.  I wanted to share some important requirements I had in mind when originally developing the distribution channels for Nightscout.  Early on, (May 2014) I had done some research into regulations surrounding quality control, theory and practice of regulatory oversight.  One of the things that became clear was that one of FDA's concerns was that the versioning of software was uncontrolled.
* Is everyone is using a different version from one another... exacerbated by possibility (required in initial version) of changing the code before deploy.
* If a problem is found in a version of Nightscout, is there any possibility of letting everyone affected know?

I want to highlight how forking the code, and then forcing a deployment engine to match 1:1 to what is in a user's github was crucial to providing the Nightscout community with needed controls to ameliorate both concerns of industry and regulators.  The forking model essentially gives us a database in which we can query via github API who is using which version of the code.  It also allows us a mechanism to to notify everyone affected by a problem in a specific version of Nightscout as well as monitor the distribution of different versions of Nightscout.  These abilities were crucial in convincing industry and regulatory agencies alike to give us some breathing room, essentially allowing Nightscout freedom to operate.  It's hard to underscore this enough.

It is important that Nightscout and related projects provide regulatory bodies such as FDA with controls for oversight that comply with regulations, and ability to monitor who is affected by a problem in a specific version of Nightscout is one of the chief concerns. 
What is the relationship to Azure?  As @unsoluble ble mentions across the cloud providers, they have all adjusted their freemium usage tiers and quotas as Nightscout has intensified usage and consumption of resources such that none are ideal candidates for continuously operated and free usage models.  However, I would point out that the "deploy tarball" mechanism used by Heroku does not allow tracking Nightscout usage while "deploy github repo" mechanism used by Azure does and that this is an important part of the distribution design.  So while giving up on a specific cloud provider, such as Azure, might seem tolerable or even desirable to folks, I strongly encourage replicating another way to track and address who is using Nightscout.

It's possible that Heroku's updates since 2016 allow tracking actual github repos.  This should be the standard way for the reasons I outline above, as the "unversioned tarball deploy" traditionally done by Heroku actually seems somewhat irresponsible.

In 2015 we had some special support from Microsoft including donated compute resources to developers.  I'm not sure what's happened on that front since then.  Someone could ask James Wedding or Wes Ton. Ali M was our contact at that time.
Hopefully, regardless of decision to drop or maintain Azure, we can agree that tracking who is affected by a problem in a version and maintaining some mechanism to reach out to them is a requirement to keep in the "possible-even-if-never-used" category rather than the "make-it-impossible" category.  This requirement is just subtle enough that I've noticed the community as a whole doesn't fully appreciate it, I'd be happy to continue to explain the requirement if needed.

**Comment by unsoluble** [comment]
Wow, that's a fascinating angle, thanks for elaborating. Practical question: Has anyone actually been _doing_ this kind of analysis on deployed versions since it was conceived? I've never heard it mentioned in the three years I've been involved.

**Comment by bewest** [comment]
As I mention, it's been oft maligned and unappreciated.  Shortly after my initial meetings with FDA I actually did register us via Nightscout Foundation as a registered entity with FDA, which additionally bought us some discretion and freedom to operate.  I did experiment with using the github API to list out and query who was using which version.  The need to use a tool like this, thankfully, never quite rose to a priority above all the other things I was working on at the time.  In addition, when I spoke to community about these concerns, the number in support of working with FDA and industry were a small minority and I received pressure to work on other things.

To my knowledge we've never actually done this kind of analysis... I was satisfied as a matter of MVP and priorities that it would be possible to do if needed.  The ability to perform these kinds of post-market surveillance capabilities are table stakes among industry and regulators, and at the time, it was also enough for them that is was "possible" to do, having assumed it was impossible.

**Comment by Pogman** [comment]
@PieterGit I retried the current dev branch in Azure and it still fails for me. CPU quota seems to be getting used up during deploy.

**Comment by unsoluble** [comment]
> tracking who is affected by a problem in a version and maintaining some mechanism to reach out to them is a requirement
Considering the making-oversight-bodies-happy angle, this does seem like something we should stay on top of. But right now it's kind of like having a backup system that you've never actually tried restoring data from — if we aren't actively checking to see if it works, it's not really a system at all.

**Comment by shanselman** [comment]
Hey friends. I worked on some of the early Azure support and I had a call with @anthonychu today from the Azure team today and he's volunteered to do some analysis here. There's a number of ways we can run NightScout on Azure - Azure Websites being just one of them. There's also a number of improvements that have happened with Docker containers and deployment from a Container Registry that haven't been revisited in a while.

Additionally, there's Mongo support in CosmosDB now and I've been talking to them about free or highly discounted NightScout support.

I'd ask that you let @anthonychu take a stab at some analysis and report back. He and I and @jansche and perhaps @amazaheri can make a little v-team/strike team and return back soon with the analysis. 

I also agree strongly with @bewest that we should avoid making a "new way" to deploy NS someone that bypasses the forking system. 

In my eyes, ideally, regardless of cloud, one should 

* fork
* press a button
* be happy

If that's not possible on Azure or any other cloud, then it's too hard.

Azure's issues today are largely a problem with *Kudu* not Azure. We are going to meet with the https://github.com/Microsoft/Oryx team and see how NightScout deploys that way. Before we drop Azure or any cloud we should to the analysis.

Finally, 4 years ago we deployed NightScout on Windows App Services, while today we have Linux App Services and Linux Container App Services available. Deploying from a fork *where that Fork has  valid Dockerfile (that isn't marked example)* would be ideal and would avoid "building in production"

Does this seem reasonable?

**Comment by PieterGit** [comment]
@shanselman @bewest Thank for your quick answers (and welcome back here at Nightscout Github 😄  ).

I hope @shanselman actions and calls will have success. I personally have tried to support Azure users in the past (e.g. 0.10.x cycle), and spent too much time fighting Azure and I gave up. I am no Azure users (privately, my company is). I think it's important to have working and maintainable code. If nobody is willing to test or develop for Azure, we should not support it and remove it.

About the forking stuff. I understand the regulators requirement. Better than forking would be to have our own notify-users/update-is-available mechanism and use npm packaging as it's designed, i.e.  https://docs.npmjs.com/cli/publish and have it published on https://www.npmjs.com/ . I don't have the time to do that currently,but I prefer "press a button" and "be happy" over the forking part. The forking part also has quite some disadvantages, such as https://github.com/nightscout/cgm-remote-monitor/labels/git-spam

**Comment by shanselman** [comment]
Cool. We'll do some work and report back. I'll defer to @bewest and @sulkaharo and friends to determine the regulatory benefits or not of the forking thing (which is useful, but also historical). If there's a better way to let folks know about updates, that's outside the scope of Azure vs Heroku vs SomeCloud.

For now, I'm hearing:

* Given a fork on NS on GitHub
* Make it "falling of a log easy" to deploy to Azure with 100% success
* Assuming the user wants to spend minimal $, if any

**Comment by PieterGit** [comment]
@shanselman I agree the forking stuff is another discussion, and far less important than choosing a solution for Azure support. I just mentioned it as a technical solution to use less CPU-power. It's fine if  we keep the forking because of regulatory benefits in future, and because we don't have notify-users/update-is-available feature available. @sulkaharo and I will clear the git-spam cluttering our PR's from time to time.

One thing I would like to add is that I would like to make sure that Azure support keeps working with newer versions of Nightscout. Either because there are volunteers to test release candidates and report back, or that we automate it with CI/travis/....

**Comment by sulkaharo** [comment]
Sending a PM to @shanselman / @anthonychu / @jansche, will report back. :)

**Comment by jansche** [comment]
Thanks everyone! 

Re: Testing
Is there a standard testing procedure or anybody who could outline what testing involves? I'd love to support the project by testing Azure deployment, so this issue could be covered by me if one person is enough. I do have one Azure and two Heroku deployments in my responsibility (call me fortunate) and in production use. I guess basic qualification for the job is given.
=)

It's great to have you all, folks! <3

**Comment by amazaheri** [comment]
@shanselman let me know how can I assist and I am all in.

**Comment by PieterGit** [comment]
@jansche currently testing procedure is successful deployment, initial startup and basic operation (pump and CGM data are shown). As I understand it currently Nightscout won't deploy on Azure at all. Further tests are e.g. if the reports work as expected. If we have somebody that is able to deploy 0.12.x on Azure, we must see if there are problems in day to day operation. I don't think we will hit a lot of Azure specific bugs once we've been able to deploy and startup is successful. Current Nightscout won't work on ancient Node versions, and there is no major difference between Node 
10.15.2 (current Azure version) and Node >= 10.16.0 (used for other deployments).

**Comment by jansche** [comment]
This I can do. Also on a regular and before release cycle. Count me in.

Current 0.12.3 NS deploys to Azure without problems, but only tested on paid tier. Free tier to be tested early next week. Operation is error-free, reports work as expected. So for now, it's a green light. With the paid-tier vs. free-tier issue.

**Comment by jansche** [comment]
And yes, I have it running in a 24/7 production environment (myself).

**Comment by sulkaharo** [comment]
@jansche Yup dev is expected to work using a paid tier in Azure but reports indicate it fails when using the free tier due to CPU resource constraints.

**Comment by PieterGit** [comment]
Postponing this issue to a Nightscout 0.13 release.
@jansche @amazaheri @shanselman @Pogman can you give an update? 
- Will Azure support for free tiers return? 
- Does current 0.12.3 or dev branch work on Azure without issue on a paid tier?
- Please also make sure recent Node without security issues is available on Azure.

**Comment by jansche** [comment]
Im running 0.12.3 without issues on a paid tier in Azure. Only thing to mention is that I don't get the option to show color prediction lines in the menu. It shows up in my other (Heroku-powered) install. So I guess this is related to the Azure base?

**Comment by Pogman** [comment]
I don't actively use Azure but if there are any recent changes that have a chance to make it work there I can try it out again.

**Comment by fromorbonia** [comment]
I do actively use Azure, but it has taken me 12 months just to get back to a NightScout bug I think I might have fixed! I also find it hard to help with deployment issues beyond versioning.
I only spotted this thread today :-(. 
Can we setup a NightScout Azure Gitter thread, which I can look at and see if I can start to help.
I also want to setup some basic automated functional tests with Katalon Studio, which would help with checking deployments.

**Comment by fromorbonia** [comment]
@jansche - I'm trying to get the free service tier running on 0.12.3, but appears to be failing on lack of node-gyp support (which I think is wrong version available of the build tools available on Kudu). As opposed to a problem with CPU.  
Have I just missed the CPU error in the logs, or is there a fix for node-gyp build issue? Thanks

**Comment by jansche** [comment]
@fromorbonia same here. Node-gyp was the problem according to logs. I had to switch to Linux platform on Azure, which is only free the first 30 days.

**Comment by fromorbonia** [comment]
@jansche thanks for the confirmation, i will try some other options around msbuild. Seems bizarre the kudu doesn’t have the build tools preloaded somewhere 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by StevieMac70** [comment]
> Thanks everyone!
> 
> Re: Testing
> Is there a standard testing procedure or anybody who could outline what testing involves? I'd love to support the project by testing Azure deployment, so this issue could be covered by me if one person is enough. I do have one Azure and two Heroku deployments in my responsibility (call me fortunate) and in production use. I guess basic qualification for the job is given.
> =)
> 
> It's great to have you all, folks! <3

I will help with Azure testing as well....  :)  Let me know how I can help.

**Comment by cfaagaard** [comment]
To help out with azure deployment I have made some tests. I have been using "Azure Pipelines" instead of the Kudu engine. I have made two succesful deployments on two separat app services with version 0.12.4-dev. One app services on the free service plan and one on B1:1.

**Comment by cfaagaard** [comment]
To help out with the Azure deployments I have tested an alternative approach.
I have used “Azure Pipelines (preview)” instead of the Kudu Engine.
 
![image](https://user-images.githubusercontent.com/25353502/66824839-62c15800-ef49-11e9-9c36-b56bba905eda.png)

I have tested two deployments; one on a free service plan and one on a B1:1.
Both deployments have succeed multiple times. I have used 0.12.4-dev (I know, not the latest).
It may not be the most user-friendly approach for the average user, but it works.
 
![image](https://user-images.githubusercontent.com/25353502/66824857-681ea280-ef49-11e9-9691-b74e03568a45.png)

**Comment by cfaagaard** [comment]
Just a follow up on my test. I have made two pipelines (one for master and one for dev in github).
Now I have three releases: test-dev, test-master and production-master. I have upgraded to the new version of nightscout 0.12.5 by just PR the master and dev in github. Azure pipeline takes care of the rest.
For my production nightscout (aagaardloop) there is no CI. I want to do this manually. :-)

![image](https://user-images.githubusercontent.com/25353502/66829902-a3729e80-ef54-11e9-9077-c8976951210a.png)

![image](https://user-images.githubusercontent.com/25353502/66829930-aec5ca00-ef54-11e9-9c9a-09c39764af65.png)

**Comment by jansche** [comment]
That looks promising, @cfaagaard. I can't reproduce here. Are you running these on Windows platform, or did you try the free tier on Windows, and the other (B1) on Linux? I have some weird other options (start command e.g.) that you didn't assign.

**Comment by jansche** [comment]
Also, it gives me some line break errors:

```2019-10-15T11:24:24.4687510Z deploy.sh: line 2: $'\r': command not found
2019-10-15T11:24:24.4687739Z deploy.sh: line 7: $'\r': command not found
2019-10-15T11:24:24.4687807Z deploy.sh: line 10: $'\r': command not found
2019-10-15T11:24:24.4688189Z deploy.sh: line 11: syntax error near unexpected token `$'{\r''
2019-10-15T11:24:24.4688538Z deploy.sh: line 11: `exitWithMessageOnError () {```

**Comment by cfaagaard** [comment]
All three are windows.

**Comment by cfaagaard** [comment]
Warning: not related to this issue directly, but more of an Azure perspective for Nightscout.
@jansche on a side note (saw that you work at MS): I am playing around with api management in azure with the nightsout rest api. And it works. Using the swagger.yaml from NS I got an api working and I can now post entries/treatments from ex. postman to NS.
Also just made CosmosDb working as backend for the Nightscout website.
So now I am submitting data via api management to NS website which sends data to a cosmosDB. :-) Sweet!

**Comment by cfaagaard** [comment]
@jansche Tried to make a Linux release, but got the same errors as you describe. I am a novice when it comes to Linux. So google is my friend.... and it turns out it has something to with the deploy.sh has been created in a windows environment and therefor the line endings are not correct.
https://stackoverflow.com/questions/18608380/r-command-not-found
https://stackoverflow.com/questions/54876508/unable-to-execute-shell-script-on-azure-pipelines
like this answer (lol): https://github.com/microsoft/vscode-azureappservice/issues/1016

I am looking into this a bit more.

**Comment by fromorbonia** [comment]
@cfaagaard pipelines do sound interesting, I could not get anywhere with either B1 or the free tier. If you can get a pipeline on the free tier that would be amazing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fromorbonia** [comment]
@cfaagaard sorry I meant that my attempts without Pipeline all failed, which I’m sure are related to no control over the version of msbuild used by node-gyp on Kudu. I haven’t gone back and tried on 0.12.5 code. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cfaagaard** [comment]
@fromorbonia  aaahhh, ok. In the past I sometimes could get the Kudu to work, but I had to try 10-15 times. With the pipeline it works every time. It would be great if you could test the pipeline approach.

**Comment by hgreving** [comment]
> Also, it gives me some line break errors:
> 
> ```
> 2019-10-15T11:24:24.4687739Z deploy.sh: line 7: $'\r': command not found
> 2019-10-15T11:24:24.4687807Z deploy.sh: line 10: $'\r': command not found
> 2019-10-15T11:24:24.4688189Z deploy.sh: line 11: syntax error near unexpected token `$'{\r''
> 2019-10-15T11:24:24.4688538Z deploy.sh: line 11: `exitWithMessageOnError () {```
> ```

How did you fixed it? I've the same errors while deploying from azure pipeline.

**Comment by cfaagaard** [comment]
@hgreving Do you deploy to Linux?

**Comment by shanselman** [comment]
For what it's worth, I recently moved from Azure App Service on Windows to
Azure App Service on Linux via Azure DevOps.

There's an azure-pipelines.yaml file here
https://github.com/shanselman/cgm-remote-monitor/blob/master/azure-pipelines.yml
and it works and deploys reliably.

**Comment by sulkaharo** [comment]
@shanselman great, wanna PR in the file and deploy instructions? Is hosting Nightscout this way free?

**Comment by hgreving** [comment]
@cfaagaard with App type: Linux Web App
I will try the suggestion of Scott Hanselman

**Comment by cfaagaard** [comment]
Just wanted to let you know I just upgraded to version 13.0.1 (master) on Azure via Azure devops(windows). No problems.

**Comment by StevieMac70** [comment]
Did you just upgrade your current version?  I tried it using deployment slots to test the install and it constantly fails.

**Comment by cfaagaard** [comment]
I just pull requested my fork of cgm-remote-monitor on github. (see my setup in previous comments). I have not tested Linux. (see shanselman solution)

**Comment by cfaagaard** [comment]
@StevieMac70 are you using kudu services or azure devops?

**Comment by StevieMac70** [comment]
@cfaagaard I believe Kudo...  :(   Will try devops now.  Thanks

**Comment by pmgiant** [comment]
Hello, I just kinda succeeded with a very simple approach: 
1. git clone (13.0.1), 
2. fix deploy.sh (CRLF-->LF)  
3.VS Code + Azure appService plugin deployment (Linux, NodeJS 10 LTS), 
4. CosmosDB (Mongo API) as database.
It almost works.. The web app displays some data, allows for configuration etc.. but xDrip+ POSTs to /api/v1/entries 95% of times end up with HTTP 500 :(.  
Logs look clear (or I`m looking in the wrong places). May the ns code be missing some try/catch/log?
Is there a better/fixed branch than master (18.09.2019 as of today).

**Comment by pmgiant** [comment]
Hello, I have a few more observations after running nightscout on Azure AppService + CosmosDB for a week and then comparing CosmosDB to MongoDB Atlas. CosmosDB, shame on you...

On CosmosDB:
1. app insights occasionally reports HTTP 500s - once every hour or two.
2. **some treatments are not being uploaded** from xDrip to nightscout, no errors, no time corellation with the 500s above. Looks like the xDrip sync protocol does not check wether all recent treatments have been succesfully reported or not - **this can be harmful and even potentially lethal**..
3. running this app (that effectively reports no more but a single dot once every 5 minutes) have drained my Azure credits in two weeks. The "Free" CosmosDB accout throttled at the minimum of 400 RU/s per collection actually costed me 9 EUR/day. Performance graph were showing 400-700 RU/s for "GetMore" and "Find" operations. 

On the other hand, running the exact same app (+ uploader and web clients) on **MongoDB Atlas** (M0 free tier) is **really free** with reported traffic of 0.3 reads and 0.007 writes/s on average. 
Uploading historical data from xDrip created a few seconds long "peak" of 0.8 writes/s and worked like charm without any interventions.

Fortunately there are some Azure regions that offer both free NodeJS and MongoDB Atlas.

Looks like the "free" CosmosDb traffic reporting and charging algorighm **has bugs that transform into real money** :(

**Comment by kirillg** [comment]
@pmgiant sorry you're having issues with Cosmos DB free tier. Could you share your free account/database name (or what it was if you already deleted it? (email to kirillg @ msft ) . Would love to understand the issue better/fix it.

**Comment by arpyman** [comment]
Latest version 14.0.7 works for me with these steps:
1. Deplyment Center -> Azure Pipeline
2. In Azure DevOps Organization Create new oraganization 
3. In web Application Framework select: NodeJS
4. Continue -> Finish
5. wait approximately 10 min and done

**Comment by sulkaharo** [comment]
@arpyman Does that work with the free tier? Previously the problem was the free tier didn't work and the paid tier easily cost $50 a month per user

**Comment by shanselman** [comment]
This should work, the issue wasn't the Free Tier's compute for *running *it
was that the free tier didn't have the computer to reliably build. This
technique has AzDo do the build.

@arpyman - why not GitHub Actions? Would that be easier for the non
technical?

**Comment by psonnera** [comment]
I apologize for waking up this old thread, but since we'd like to add more vendors to the documentation @arpyman could you contact me to give me more hints on your Azure deployment? You'll find me at https://m.me/patrick.sonnerat , in Discord @psonnera#5277 or in Gitter.

**Comment by Bbasamadel123** [comment]
ebb
dbdn

في الأحد، ٦ يونيو ٢٠٢١ ١٠:٢٥ ص Patrick Sonnerat ***@***.***>
كتب:

**Comment by PieterGit** [comment]
@arpyman are you still using Nightscout with Azure? Can you confirm what Node versions are currently supported with Azure? I would like to update Node support in Nightscout, but can't/will not do any Azure testing. See #7241 for details.

**Comment by arpyman** [comment]
when I tried to update, deployment failed. iam currently on heroku. I gave
it up with azure.
