### ISSUE TITLE
DISPLAY_UNITS should support "mmol/L"

### ISSUE THREAD

**Issue by unsoluble** [nightscout/cgm-remote-monitor#4807]
`DISPLAY_UNITS` needs to allow for "mmol/L" as well as "mmol" — way too many support problems stemming from this, and zero downside to accommodating.

Haven't had a chance to look into where code changes would need to happen, just dropping this here as a placeholder.

**Comment by sulkaharo** [comment]
Merged to dev. Also normalizing wrong casing on mg/dl
