### ISSUE TITLE
Older browser support broken in 0.12.3

### ISSUE THREAD

**Issue by danpowell88** [nightscout/cgm-remote-monitor#4835]
Trying to run NS on an older ipad with safari 9 and it will not get past the loading screen.

I dont think I can easily get the log for what is causing the error but I'm guessing its probably something that just needs to be polyfilled.

Trying to find an emulator online I can run it through to simulate, I know theres been other issues like this with verison upgrades and the consensus was to try and maintain as much browser support as possible as many people out there are using older "spare" devices they have lying around.

**Comment by danpowell88** [comment]
Just confirmed it actually doesnt even appear to work in IE  11

![image](https://user-images.githubusercontent.com/1100397/62169602-f84a4400-b36b-11e9-9eea-978d2bc9a8ad.png)

Seems to be pointing towards this code
```
     Object.keys(profile.data[0].store).forEach(key => {
        if (key !== current && key.indexOf('@@@@@') < 0) profiles.push(key);
      })
```

and the client.js one

```
$(document).on('online', function() {
	console.log('Application got online event, reloading');
	window.location.reload();
});
```

**Comment by danpowell88** [comment]
Confirmed still an issue in 0.12.3

**Comment by unsoluble** [comment]
The minimum supported browsers are listed in the [Readme](https://github.com/nightscout/cgm-remote-monitor#minimum-browser-requirements-for-viewing-the-site).

**Comment by sulkaharo** [comment]
Both of those lines only contain Javascript that's supported by IE 11, so no clear reason why those would break. That $ reference error is also double strange, as that code hasn't changed in the release and worked on both browsers in the 0.11

**Comment by bartsluimer** [comment]
Would it be possible to only make the color clock overview open for older browsers? Have got an IOS 9 ipad ready to display the values next to our bed.

**Comment by unsoluble** [comment]
No, but you can deploy an older version of NS to a second site for use on unsupported devices. Full guide [here](http://www.nightscout.info/wiki/welcome/how-to-deploy-an-older-version-of-nightscout).
