### ISSUE TITLE
Dockerfile does not build with 0.12.3

### ISSUE THREAD

**Issue by m-a-v** [nightscout/cgm-remote-monitor#4852]
To be able to build the Dockerfile with 0.12.3 Python and build tools need to be added.

Here is a possible solution:
https://github.com/nightscout/cgm-remote-monitor/issues/4843#issuecomment-517712085

See also here:
https://github.com/martinachtman/cgm-remote-monitor/commit/81418a2f039ce9b139ef00b4db9c81f9ce4a3c12?_pjax=%23js-repo-pjax-container

With Docker version 17.05 (release date 2017-05-04) onwards, we can use multi-stage builds. See also here:
https://github.com/mhart/alpine-node#example-dockerfile-for-your-own-nodejs-project

I will create a PR.

**Comment by charlenewoollard** [comment]
How can I stop from getting these emails

**Comment by m-a-v** [comment]
https://github.com/m-a-v/cgm-remote-monitor/commit/12e362740f1ce21322a5f3bcc94a1fda132bb0d0 fixes this issue (multi-stage builds is not needed since everything can be done with a sinlge RUN command).

I still have to test it before I will make a PR.

@PieterGit I am not familiar with npm. Is there a way to delete unneeded data? The base image is approximately 81 MB. After the npm commands the image increases to 265 MB. The build dependencies are already cleaned up.

**Comment by sulkaharo** [comment]
Apologies for the long latency - DEV now has working Docker setup, coupled with Github Actions Docker build. More improvements to land soon. https://hub.docker.com/r/nightscout/cgm-remote-monitor/tags?page=1&ordering=last_updated
