### ISSUE TITLE
Unable to submit Temporary Target Cancel - requests valid top and bottom range values

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#4859]
**Describe the bug**
I try to set a Temporary Target Cancel action in the care portal, but when I submit, I am prompted to "Please enter a valid value for both top and bottom target to save a Temporary Target" and the submission is not completed. For the Temporary Target Cancel, there are no top and bottom value fields nor should there be.

**To Reproduce**
1. Go to '+' (top right, with careportal enabled)
2. Select 'Temporary Target Cancel' as the Event Type
3. Click 'Submit Form'
4. See error: 'Please enter a valid value for both top and bottom target to save a Temporary Target'

**Expected behavior**
Select Temporary Target Cancel and submit with no errors.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/46848705/62557728-61c6c880-b82c-11e9-8ec1-bcb1f69e9b12.png)

**Your setup information**
- What version of Nightscout 0.12.3
- What type of CGM, and how do you get your data there? Dexcom G6 using the Dexcom app and Brdige
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No. Replicated on Chrome Desktop and on Android Chrome as well as MS Edge

**Additional context**

**Comment by unsoluble** [comment]
Is looking like this was probably an unintended side-effect of #4812.
