### ISSUE TITLE
Feature Request: Ability to remove predictive blue lines and margin from the right

### ISSUE THREAD

**Issue by iphotostuff** [nightscout/cgm-remote-monitor#486]
This is a request formalized from an online discussion. Users would like the ability to be able to "turn off" the predictive paths that are displayed in blue and reclaim the padded area they occupy on the right for the current BG plot points. 

Justification: Concern that the algorithm of the predictive path interferes with the user's own ability to spot the trajectory of the actual BG plotted points and treat highs or lows accordingly. 
##

**Comment by jimsiff** [comment]
@iphotostuff can you deploy and play with the latest dev release to see if it meets your needs?  @jasoncalabrese has added an adjustable focus range feature which uses more of the screen for 6, 12, and 24 hour time ranges.  See below:

![screen shot 2015-03-17 at 10 10 17 am](https://cloud.githubusercontent.com/assets/6069420/6693139/351c1d5a-cc8e-11e4-8c03-7e2e32a571e8.png)

![screen shot 2015-03-17 at 10 10 32 am](https://cloud.githubusercontent.com/assets/6069420/6693140/35438638-cc8e-11e4-8080-afbfc0ae20d6.png)

![screen shot 2015-03-17 at 10 10 44 am](https://cloud.githubusercontent.com/assets/6069420/6693142/3545a06c-cc8e-11e4-94bc-605fecf628ba.png)

![screen shot 2015-03-17 at 10 11 02 am](https://cloud.githubusercontent.com/assets/6069420/6693141/35444a6e-cc8e-11e4-85e0-78e64fda8657.png)

**Comment by jasoncalabrese** [comment]
After the enchilada release I'm planning to have a way to pick the predictor, the current AR2 cone, iob-cob based,  none, etc

**Comment by francescaneri** [comment]
![screen-shot](https://cloud.githubusercontent.com/assets/9915825/6694065/c2c271e2-ccd7-11e4-8a1d-dedb644ff195.png)
@jasoncalabrese @jimsiff you can not expand the front ?

**Comment by jasoncalabrese** [comment]
@francescaneri, that the iob-cob branch, think we're talking about the mainline here

**Comment by francescaneri** [comment]
@jasoncalabrese ...I thought you could only transfer the part of the vision in the master branch.

**Comment by iphotostuff** [comment]
@jimsiff it sounds like @jasoncalabrese is already planning on doing this? @jasoncalabrese, were you thinking of having that picker in the settings side panel or on the prefs side of azure? Seems like a great solution.

**Comment by Kdisimone** [comment]
The ability to turn off the AR2 forecast is included in most recent NS version.  This could be closed

**Comment by brunoe90** [comment]
Hi could you explain how to delete the blue dots? I don't know where I'd be able to turn off.

**Comment by tweej** [comment]
I have the same question as above. How do I turn this off in Nightscout 14.1.0?

**Comment by Kdisimone** [comment]
@tweej and @brunoe90 tap the three dots near the 24HR pill box in Nightscout. Your prediction lines can be turned off and on there with the checkboxes.

**Comment by tweej** [comment]
There are no boxes checked, yet the blue lines remain.
![Screenshot_2021-01-14_14-08-57](https://user-images.githubusercontent.com/8267265/104655264-50fdc180-5672-11eb-9148-76f275d05152.png)

**Comment by Kdisimone** [comment]
You are looking at the wrong boxes. You need to tap the dots next to the 24HR icon/pill box. Look under the large clock time.

**Comment by tweej** [comment]
That did it, thanks!

**Comment by psonnera** [comment]
@flash-107 try to disable it in your variables https://nightscout.github.io/nightscout/setup_variables/#ar2-ar2-forecasting
