### ISSUE TITLE
blind widget of Nightscout X

### ISSUE THREAD

**Issue by oleg-post** [nightscout/cgm-remote-monitor#4893]
**Describe the bug**
I have Nightscout X installed on Apple iPhone (SE, 6 and 8+). Everywhere the widget  Nightscout Glucose is a blind, i.e. no figures are seen. 

**Screenshots**

**Your setup information**
- The version of Nightscout (e.g. 0.12.3)
- What type of CGM, and how do you get your data there? (e.g. Spike)
- iPhone
![IMG_0409](https://user-images.githubusercontent.com/41417313/62868395-3bb69200-bd1e-11e9-8340-dbe1ef7e8816.jpg)

**Additional context**

**Comment by unsoluble** [comment]
Nightscout X is a third-party wrapper app — best to try to get in touch with its developer (@DaniFernandez95 on Twitter).
