### ISSUE TITLE
How does the Alexa API accept requests?

### ISSUE THREAD

**Issue by iybjc** [nightscout/cgm-remote-monitor#4896]
I am working on a custom Alexa skill, and part of it is a Python 2.7 Lambda function that sends a request to a user defined endpoint. I've been looking for a while, and I can't figure out how exactly the Alexa Skills Kit actually goes about sending a request to the heroku website in order to grab something like NSStatus. I have Alexa enabled for my instance;
![alexa](https://user-images.githubusercontent.com/44852853/62883872-be2d5a80-bcfa-11e9-8b00-85fb1c37652a.png)
but any requests made to http://(mydomain).herokuapp.com/api/v1/alexa give a 404, when in theory that shouldn't be happening. I have cgm-remote-monitor 0.12.3, and Alexa was able to grab my endpoint etc when I set up an Alexa skill by following the tutorial [here](https://github.com/iybjc/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md). I'm really stumped, as either something is wrong with my heroku instance, or I'm really just missing something. Here's the Python script I used to try and get a basic response (not the one I'm using in Lambda), which still gives a 404.

```python
import json
import requests
data ="""
{
    "version": "1.0",
        "session": {
            "new": true,
            "sessionId": "amzn1.echo-api.session.123456789012",
            "application": {
            "applicationId": "amzn1.ask.skill.987654321"
            },
            "user": {
            "userId": "amzn1.ask.account.testUser"
            },
            "attributes": {}
        },
        "context": {
            "AudioPlayer": {
            "playerActivity": "IDLE"
            },
            "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.987654321"
            },
            "user": {
                "userId": "amzn1.ask.account.testUser"
            },
            "device": {
                "supportedInterfaces": {
                "AudioPlayer": {}
                }
            }
            }
        },
        "request": {
            "type": "LaunchRequest",
            "requestId": "amzn1.echo-api.request.1234",
            "timestamp": "2016-10-27T18:21:44Z",
            "locale": "en-US",
            "intent": {
                    "name": "NSStatus",
                    "confirmationStatus": "NONE"
                }
        }
    }
"""
url = 'http:/(mydomain).herokuapp.com/api/v1/alexa'
headers = {'Content-type': 'application/json', 'Accept': 'text/plain',}
r = requests.get(url, data=json.dumps(data), headers=headers)
print(r.status_code)
```

**Comment by unsoluble** [comment]
Just in case: You listed your URL with `http` here — `https` is required for connections as of 0.11 (or somewhere around there).

**Comment by iybjc** [comment]
> You've got your URL with `http` here — `https` is required for connections as of 0.11 (or somewhere around there). Dunno if there's something else getting in your way as well maybe, but start with tweaking that.

I actually tried HTTPS, and got a 400 error instead, I'm assuming that's not much better, plus when I manually navigate to https://(mydomain).herokuapp.com/api/v1/alexa, it says `Cannot GET /api/v1/alexa` , but stuff like status.json works etc

**Comment by iybjc** [comment]
Confirmed with several other people who use Nightscout, going to https://(mydomain).herokuapp.com/api/v1/alexa, says `Cannot GET /api/v1/alexa` , but stuff like status.json works. Tried re-deploying the latest commit of the Nightscout repo, same issue.

**Comment by meenanader** [comment]
Interestingly, When I call /api/v1/alexa I get the same output, but when I set that into Alexa dev url, everything works fine.
I can get the result fine from the dev test on the laptop, but can't get my device to recognize the skill on the echo device or the Alexa mobile app.

**Comment by iybjc** [comment]
@unsoluble semi unrelated but I don't think it is, I can do a normal `requests.get` call with no https and it works perfectly fine.

**Comment by meenanader** [comment]
It simply works fine.
Just dont try to call the api url from browser or postman as that will not work.
Just use the url in Alexa app directly.
I have also changed my own code to make it accept more keywords and also to round the result to 2 decimal places as for example cob can be said as 30.757755457755 which is annoying.

**Comment by robwild** [comment]
Having the same issue as above https://github.com/nightscout/cgm-remote-monitor/issues/4896#issuecomment-521717593, running 0.12.4 on an Heroku instance, followed all the config instructions on https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md, XXX..herokuapp.com/api/v1/status.json works fine and shows that alexa is in the enable state, any help would be much appreciated from those who have got this running

**Comment by meenanader** [comment]
@robwild
Make sure you Alexa app has the same language as on the device you are testing on.
That was my fault.
However it should work from the development environment test tab.

**Comment by robwild** [comment]
@meenanader thanks, but the language for the alexa settings and the app both match, if I hit https://(mydomain).herokuapp.com/api/v1/alexa, says Cannot GET /api/v1/alexa , but stuff like status.json works. I would have expected the /api/v1/alexa to not return a 404 regardless of request origin for any kind of data consumption to work, seems like either the deploy instructions are incorrect or there is an issue in the code, I have debugged the code as little and perhaps its connected with /api/v1/verifyauth returning {"status":200,"message":"UNAUTHORIZED"} ??

**Comment by meenanader** [comment]
For me as well I het 404 error if I call the api link direct, however it works on Alexa app!
There might be some other parameters gets sent from Alexa app which is not visible so when you call it from a browser or postman it fails.

**Comment by meenanader** [comment]
@robwild 
Just checked the NS logs, the /alexa request is a POST request, so it is normal to get an error if you try GET request on it.

**Comment by inventor96** [comment]
@iybjc @robwild As @meenanader brought up, the Alexa API requires a `POST` request, so any `GET` request (such as one made through a web browser) will give you an error.

@iybjc If you don't mind me asking, what are you trying to build with Alexa that requires an intermediary Lambda script? Is there some functionality that could be added to the existing Alexa plugin instead?

**Comment by iybjc** [comment]
@inventor96 I was building basically a dynamic version of the plug-in in which the lambda function references the user who called it's email through the Alexa skill, then queries a database to get their nightscout url, then retrieves the latest BG and trend and returns that to the person who asked it. I figured out another way to do it by just using a bit of regex with a requests.get call to `/API/v1/entries.json`, so the Alexa API would have just been an extra step.

**Comment by inventor96** [comment]
@iybjc Very nice. Once you get that figured out, definitely share it! I'm sure there are others who might be interested in that kind of functionality.

In the meantime, if there's not anything else related to your original post, please close this issue. Thanks!
