### ISSUE TITLE
Request for Eversense integration to Nightscout

### ISSUE THREAD

**Issue by timmy354321** [nightscout/cgm-remote-monitor#4898]
As a prevoius long-time user of nightscout with dexcom, I would love to see my eversense data in nightscout again. Are there any plans to make an eversense-nightscout bridge? Are there any methods of getting my data into nightscout using an iPhone? Thank you.

**Comment by unsoluble** [comment]
Can be done via [this](https://github.com/BernhardRo/Esel).

**Comment by timmy354321** [comment]
I am using iOS. I believe the esel/xdrip route is android only.

**Comment by unsoluble** [comment]
You’re out of luck then; this is the only option currently.

**Comment by nickarmstrong84** [comment]
I’m a recent Eversense patient and a long time nightscout user. Any chance enough interest is being generated to see an iOS solution developed? Thanks
