### ISSUE TITLE
Inconsistent CGM pill state and warning with xdrip-js module

### ISSUE THREAD

**Issue by PieterGit** [nightscout/cgm-remote-monitor#4903]
**Describe the bug**
Nightscout shows inconsistent CGM state to user. It has a warning/alarm (yellow): "Sensor warmup" and a CGM pill status text "Failed start" (orange). This is with xdripjs Lookout. The sensor was started, but gave a 0x16 error (failed start) so it wasn't warming up.

**To Reproduce**
Happens after a CGM Dexcom G6 `0x16` error. The sensor was started with `lookout back-start 1234` 

**Expected behavior**
CGM pill and warnings/alarms should be consistent within Nightscout and be the same as in the CGM application (in this case xdrip-js Lookout)

**Screenshots**
This is the image after the issue (self) resolved. 
![image](https://user-images.githubusercontent.com/6500826/63334929-bf830680-c33c-11e9-9d0a-4bb8efbb82f3.png)
The Nightscout had a alarm/warning `Sensor Warmup` (orange) with a CGM pill state `Failed Start` (yellow). Lookout status was `Sensor Failed Start`

**Your setup information**
- What version of Nightscout (e.g. 0.10.3):  0.12.3-dev
- What type of CGM, and how do you get your data there? G6 (old firmware) and xdrip JS lookout (dev version, https://github.com/xdrip-js/Lookout/commit/69598d7dec7541f351d28b6004b202f9dded90b5 ) 
- Is your issue specific to a browser (Firefox/Safari/Chrome?) no

**Additional context**
See Gitter discussion at:
https://gitter.im/thebookins/xdrip-js?at=5d5b19d20eff7d2dfede5886
https://gitter.im/thebookins/xdrip-js?at=5d5bb74a9507182477146a8f

**Comment by PieterGit** [comment]
@jpcunningh Did a quick code search. I think this is caused somewhere near https://github.com/nightscout/cgm-remote-monitor/blob/48c0f59088f42ff767b401390f8aa857a1376ca1/lib/plugins/xdrip-js.js#L315
But perhaps it's some default Nightscout behaviour based on notifications/alarms on `WARN` level.

I don't understand why the CGM Pill text update  `sbx.pluginBase.updatePillText` won't update/cancle the alarm/notification for the sensor warmup.

**Comment by jpcunningh** [comment]
@PieterGit, the orange `Sensor: Sensor Failed Start` is not tied to the alarm.  It is an Announcement that Nightscout clears after some amount of time.

Lookout both sends the Announcement when the status changes and sends the device status record the CGM Pill uses to display the status.  If the CGM status changes within the time before the Announcement ages out of the NS display, it could be out of sync with the CGM Pill.

Is it possible to pull from the Lookout logs the state changes time line?  Also, when the state changed to Failed Start from Warmup, another announcement should have been sent which I should replace any existing announcement being displayed on Lookout. Perhaps NS doesn't replace old Announcements with new Announcements?

**Comment by efidoman** [comment]
I just experienced this same issue with Logger while testing out a CGM status text update to show tx-expired if tx age > 90 days. I'll look at the Logger logs to see if it is Logger that is putting it out of sync or NS processing. I'm not sure which it is at this time.

**Comment by efidoman** [comment]
![cgm-pill-status-takes-time-to-show-latest](https://user-images.githubusercontent.com/26698840/63426327-87350400-c3e0-11e9-8dff-3f30d5bedf1f.png)

**Comment by efidoman** [comment]
About 5 minutes later, they got in sync. It could be logic in both Lookout/Logger that causes this. Checking now.

**Comment by efidoman** [comment]
Yes, I think it is Logger with the issue ... It processes the announcements if last state is different than this state. See the 5 minute lag ...
08/21 06:42:44 saveLastState, state=Needs Calibration-tx-expired
08/21 06:47:39 readLastState: lastState=Needs Calibration-tx-expired
08/21 06:47:42 process_announcements: state=Needs Calibration lastState=Needs Calibration-tx-expired status=OK lastStatus=OK

**Comment by efidoman** [comment]
I checked the Logger code and the announcement post along with the cgm pill post are side-by-side in the Logger loop. I can't find a reason in Logger for the 5 minute delay.

**Comment by PieterGit** [comment]
@jpcunningh @efidoman thanks for your updates. I postpone this to the 0.13.0 release and I hope somebody has some time to figure this out in that time frame (that might even be me 😄  ). If somebody knows if this is a Lookout or Nightscout issue, and is able to fix this, please help contribute to fix this issue.
