### ISSUE TITLE
Loop Basal Rate Actual Delivery vs Nightscout Day to Day Report

### ISSUE THREAD

**Issue by marionbarker** [nightscout/cgm-remote-monitor#4971]
EDITED: Anything in {} should be disregarded.  Please see my later post (9/7/2019). I did not delete anything.  Just added newline{ and }newline around incorrect assumptions.

Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier? 
The reported basal values in Day-to-Day Report differ significantly for Omnipod Loop from the actual values.
I believe this is an inconsistency in method for estimating basal from rate*time on NS vs Loop (actual insulin delivered).  
{
Significant differences are noted for Omnipod which must cancel TB before initiating the next TB, so the period for the TB is typically just under a minute mark and NS rounds down the minute.
} 
[Sep 12, 2019: EDITED to add examples from database records for "eventType": "Temp Basal",: old Loop code had "duration": 4, new Loop code (after Sep 9, 2019, dev) has "duration": 4.767875816424688, and new field: "amount": 0.1,
END EDIT ]

See discussion here: 
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Nightscout.20daily.20total.20temp.20basal.20delivery/near/174760280

{
I think that Mark Yeager is correct that the primary problem is rounding down the minutes for TB. He said:
"It seems the "revert to programmed basal" that Loop issues between temp basals (as @ps2 explained) results in a 4 minute increment in NS vs the 4min:57sec ? in Loop.."
}

The other part of the problem is something I've noticed before - if you change your profile for scheduled basal, the day-to-day report changes because the intervals between TB are modified to new basal pattern.

Which device / browser version was used to reproduce the bug?
Running dev branch from https://github.com/LoopKit/LoopWorkspace
Using Omnipod, iPhone 7
Running dev on Nightscout (0.12.4-dev)

Does this happen every time you launch Nightscout, or sometimes?
yes

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)

I am attempting to reproduce bug by taking the treatment report and doing rate * time and summing up to match the reported basal.  

{ 
If I use an extra minute of Scheduled Basal between each TB reported by Loop plus the actual scheduled basal, I get close to the overestimate provided by NS. 
}

 I want to clean up the spreadsheet some to make it more understandable before posting it.

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong

I wanted to get this issue reported so people are aware. I will come back with more documentation (or maybe others can chime in).
Loop knows how much basal insulin is delivered.
Pete Schwamb says he is willing to work with NS developers to figure a method to have NS reporting be more accurate.
My daily basal delivery over more than a week showed up as 8 to 13% too large on NS compared to what Loop / Apple Health / Tidepool reports. Several others checked and also found the discrepancy.

**Comment by bartsluimer** [comment]
<img width="999" alt="Schermafbeelding 2019-09-07 om 15 28 13" src="https://user-images.githubusercontent.com/25899216/64475530-3bc27a00-d184-11e9-8eaa-8f7684abf791.png">
<img width="1347" alt="Schermafbeelding 2019-09-07 om 15 28 40" src="https://user-images.githubusercontent.com/25899216/64475531-3bc27a00-d184-11e9-86ff-71e8457d2e9c.png">

**Comment by marionbarker** [comment]
Update.  I redid my spreadsheet where I try to reproduce the NS reported basal total from day-to-day report.  This time I changed the reported 4 or 9 minute duration to 5 or 10, etc, and I was able to reproduce the NS number fairly well.  I don't have time to post spreadsheet - still needs some clean up and explanation added. And I'm also planning to add the actual quantized basal delivery from AH.

Method: 
put NS Temp Basal Treatments for one day into spreadsheet
modify all duration values to be "corrected" number of minutes
multiply rate * correctedDuration and sum
insert times of scheduledBasal and use rate * scheduledBasal

```
For day 9/5/2019
Change NS Duration to next higher 5 min
25.6 : My sum for Rate*Time for TB
 6.5 : My sum for Rate*Time for SchBasal
32.1 : My Total Basal
32.3 : NS Day to Day Report Total Basal
29.0 : AH Total Basal
```
Note - I use a lot of positive TB (instead of bolus)  to handle meals that last longer than Fiasp. This exacerbates the discrepancy.

For completeness, My sum for Rate*Time for TB before increasing the duration was 23.2

**Comment by ps2** [comment]
The current dev version of Loop is now uploading an `amount` field on `Temp Basal` records.  If set, it will reflect the actual amount of insulin delivered to the best of Loop's knowledge, using pulse timing of specific pumps. At the moment, this will only be set for omnipod, I believe. Eventually records from Medtronic pumps will include this field.

**Comment by ps2** [comment]
Also, the records will initially be uploaded w/o this field, as we don't have the final delivery amount until the dose is ended. A later update will set the value, if we have it.

**Comment by ps2** [comment]
Ok, dev is updated so that Medtronic is also including a populated `amount` field on uploaded temp basals. This amount reflects total delivery, *not* relative to basal schedule.

**Comment by bartsluimer** [comment]
Is it best to keep loopworkspace or normal loop dev?

**Comment by ps2** [comment]
Either should work. But for future reference, that kind of question is probably best for Zulip. Comments on this ticket should be saved for discussion around how to fix this issue.

**Comment by bartsluimer** [comment]
Still there is a big difference between Tidepool en Nightscout. Running latest dev of Loop.

![Schermafbeelding 2019-09-10 om 14 01 24](https://user-images.githubusercontent.com/25899216/64612212-8be34b80-d3d3-11e9-8a40-d4f71dd251c9.png)
![Schermafbeelding 2019-09-10 om 14 01 31](https://user-images.githubusercontent.com/25899216/64612213-8c7be200-d3d3-11e9-9c30-ebacb61f3e15.png)

**Comment by ps2** [comment]
I looked into the code for this a bit.  Unfortunately, there are several untrue assumptions in the current daytoday.js math.  The algorithm, for each day, samples the current basal rate every 5 minutes of the day, then does rate based math to calculate positive and negative rates, then adds them together with scheduled basal.

To accurately reflect how much insulin was delivered as basal and temp basal, the algorithm needs a completely different approach, not sampling rates, but adding up volumes from doses.

**Comment by marionbarker** [comment]
Adding one example of "new" after Sept 9, 2019 dev update and "old" versions for the TempBasal format - example is for Omnipod. Note that both Medtronic and Omnipod were updated.  The NS day-to-day report basal total discrepancy is much more obvious for Omnipod because of the basal pulse timing.

Summary of change: 

- "duration" is no longer integer minutes
- "amount" is added

### new TempBasal
{
    "_id": {
        "$oid": "5d792b1f7cc3d56f0c739952"
    },
    "absolute": 1.75,
    "rate": 1.75,
    "temp": "absolute",
    "duration": 4.767875816424688,
    "timestamp": "2019-09-11T17:12:57Z",
    "enteredBy": "loop://Marion iPhone 7+",
    "eventType": "Temp Basal",
    "amount": 0.1,
    "created_at": "2019-09-11T17:12:57.000Z",
    "utcOffset": 0
}

### old TempBasal
{
    "_id": {
        "$oid": "5d53811e7cc3d56f0c3fe930"
    },
    "timestamp": "2019-08-14T03:28:47Z",
    "eventType": "Temp Basal",
    "enteredBy": "loop://Marion iPhone 7+",
    "duration": 4,
    "temp": "absolute",
    "absolute": 2.55,
    "rate": 2.55,
    "created_at": "2019-08-14T03:28:47.000Z",
    "utcOffset": 0
}

**Comment by sethgagnon** [comment]
Just checking to confirm my understanding on this one. So, this means that Loop (Omnipod) users really can't be using Autotune, as the insulin entries in NS do not appear to be correct? Thanks!

**Comment by marionbarker** [comment]
That is correct. It’s approximately ok for Medtronic, but not for Omnipod. With the added information about actual delivery from basal, the statistics could be improved.

**Comment by sulkaharo** [comment]
Nightscout day to day reporting shares 0 lines of code with autotune, so this reporting difference has nothing to do with how autotune calculates IOB. If you’re interested in the autotune calculation, I recommend looking at the oref0 repository.

**Comment by sethgagnon** [comment]
Thanks @sulkaharo! Are Pete's thoughts above not accurate? Just trying to understand exactly where the issue is, as it seems like there are some different perspectives here.

**Comment by sulkaharo** [comment]
Pete is correct about the code in the reporting in the day to day report. The key is, autotune does not use the code Pete is referring to.

**Comment by sethgagnon** [comment]
Ah ok, thanks for clarification.

@scottleibrand should we open up an issue on the oref side to account for this? Thanks!

**Comment by scottleibrand** [comment]
Yes, please open a new issue in https://github.com/openaps/oref0/issues/ - we'll need to determine how much of a discrepancy there is when autotune parses this same data, and look at adding support fo the new fields required to resolve that discrepancy.

**Comment by bewest** [comment]
If I understand:
* For loop/omnipod users, nightscout does not correctly calculate effected temp basal amounts for omnipod
* Loop users as of September 2019 updates have new data in the form of `.amount` contains effected rate 

Impacts nightscout reports for loop/omnipod users and becomes detectable comparing reports or even adding things up manually.
It looks to me like the issue in the daytoday reports traces through to [line 369](https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/profilefunctions.js#L351-L383) in `getTempBasal`.


There are 18 *other* places that similarly use `.absolute` and conceivably some of them will need a similar patch or update to use a method to calculate effected rates.  Thoughts?

```
lib/client/careportal.js:251:      data.absolute = Number(absolute);
lib/client/careportal.js:376:    pushIf('absolute' in data, translate('Basal value') + ': ' + data.absolute);
lib/client/renderer.js:1165:          .text((t.percent ? (t.percent > 0 ? '+' : '') + t.percent + '%' : '') + (isNaN(t.absolute) ? '' : Number(t.absolute).toFixed(2) + 'U') + (t.relative ? 'C: +' + t.relative + 'U' : ''));
lib/plugins/basalprofile.js:86:        !isNaN(basalValue.treatment.absolute) ? basalValue.treatment.absolute + 'U/h' : '';
lib/plugins/bgnow.js:166:      recent.mean - delta.absolute / delta.elapsedMins * 5 : recent.mean - delta.absolute;
lib/plugins/bgnow.js:191:      info.push({label: translate('Absolute Delta'), value: sbx.roundBGToDisplayFormat(sbx.scaleMgdl(delta.absolute)) + ' ' + sbx.unitsLabel});
lib/plugins/treatmentnotify.js:148:      (!isNaN(lastTreatment.absolute) ? '\n' + translate('Value') + ': ' + lastTreatment.absolute + 'U' : '')+
lib/profilefunctions.js:345:    if (treatment && !isNaN(treatment.absolute) && treatment.duration > 0) {
lib/profilefunctions.js:346:      tempbasal = Number(treatment.absolute);
lib/report_plugins/daytoday.js:674:          //            .text((t.percent ? (t.percent > 0 ? '+' : '') + t.percent + '%' : '') + (t.absolute ? Number(t.absolute).toFixed(2) + 'U' : ''));
lib/report_plugins/treatments.js:133:    pushIf(!isNaN(data.absolute), translate('Basal value') + ': ' + data.absolute);
lib/report_plugins/treatments.js:205:            data.absolute = $('#rped_absolute').val();
lib/report_plugins/treatments.js:213:            if (data.absolute === '') {
lib/report_plugins/treatments.js:214:              delete data.absolute;
lib/report_plugins/treatments.js:241:        $('#rped_absolute').val('absolute' in data ? data.absolute : '');
lib/report_plugins/treatments.js:334:        .append($('<td>').attr('align','center').append('absolute' in tr ? tr.absolute.toFixed(2) : ''))
lib/server/treatments.js:169:  obj.absolute = Number(obj.absolute);
lib/server/websocket.js:309:             if (data.data.absolute) {
lib/server/websocket.js:310:              query_similiar.absolute = data.data.absolute;

```
