### ISSUE TITLE
Suspend shows schedule basal rate instead of zero insulin period

### ISSUE THREAD

**Issue by naromero77** [nightscout/cgm-remote-monitor#4982]
**Describe the bug**
This occurs with Loop dev while using the omnipod pump. When a suspend is initiated, the schedule basal rate is still shown. It should be shown as a zero insulin period.

**To Reproduce**
Change a pod or do a suspend in Loop.

**Expected behavior**
NS should be consistent with Loop and show suspends as zero insulin periods.

**Screenshots**
Screen shots provided by Marion Barker.

![](https://loop.zulipchat.com/user_uploads/8196/vtBwGuXFRIoz8ve-_SWc-34d/IMG_1345.PNG)

![](https://loop.zulipchat.com/user_uploads/8196/a2ZzRbzIoLBPXbacnUhWZrkV/IMG_1344.PNG)

**Your setup information**
- Latest NS dev
- G6 ShareBridge

**Additional context**

**Comment by inventor96** [comment]
Check out https://github.com/nightscout/cgm-remote-monitor/issues/5078 for a more in-depth discussion on this topic.
