### ISSUE TITLE
HTTP Basic authentication

### ISSUE THREAD

**Issue by thecubic** [nightscout/cgm-remote-monitor#5002]
**Is your feature request related to a problem? Please describe.**
Default-exposure of the Nightscout base URL shows a live-updated datastream of the associated human being.  By configuration, that human / caretaker should be able to lock down the website such that any visitor must pass basic pre-shared authorization before any app page will load.

My personal problem is I had created a inside-joke cgi-bin page on the same host which runs my nightscout instance, then remembered that the people with which I shared the joke are perfectly capable of nmap-ing that host, and finding my nightscout site, which will let them view my data.

This means the baseline of security is only obscurity, which is a situation that must be addressed.

**Describe the solution you'd like**
Person adds env variable, say:
`HTTP_AUTHS=AzureDiamond:hunter2::anotheruser:hunter7
`
At a base layer, when that variable is set, requests must pass one of the combos, or get 401 ad infinitum (uploaders and other clients like xDrip inclusive, which probably already support basic auth through URL input, e.g. `https://user:password@nightscout.site/`.

**Describe alternatives you've considered**
I thought about HTTPS client certificates, but they are "challenging"

**Additional context**
probably just adapt this:
https://www.codexpedia.com/node-js/node-js-basic-auth-in-express-js/

**Comment by unsoluble** [comment]
Does the AUTH_DEFAULT_ROLES var not solve this for you?

https://github.com/nightscout/cgm-remote-monitor#featureslabs

**Comment by thecubic** [comment]
It does, I was unaware, thanks.  IMHO the default should be `denied`, since any first-time setup is going to require the API secret anyway
