### ISSUE TITLE
Merge SVG and Sensor entries received via MQTT

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#501]
There are some issues getting these to line up so we'll need to be careful, but the merged data is much easier to work with so it needs to be done.

**Comment by bewest** [comment]
I'm not sure this needs to be done.  I've tried lining up hundreds and thousands of records, and they don't line up the way people might be expecting: there are all kinds of gaps in even as few a hundred records.

**Comment by jasoncalabrese** [comment]
Without doing this supporting the current "when there is noise" setting will be hard.  Also need to preserve the results from `/pebble`
