### ISSUE TITLE
Cross on "Color" clock view is not clickable

### ISSUE THREAD

**Issue by PJHNS** [nightscout/cgm-remote-monitor#5014]
In 0.12.4, on the "Color" clock view page, the cross in the top right of the page isn't clickable (whereas the same crosses on the other clock view pages are clickable). On all three clock view pages the space immediately above the cross is clickable, so on the "Color" clock view page I need to use that area to close the page.

**Comment by unsoluble** [comment]
Yep, known CSS bug. Those close buttons are primarily useful on mobile (where navigation isn't as obvious), and the targets work properly there. Something wonky in the desktop rendering of the click target, haven't had a chance to dig into it yet. If you've got any ideas, love to hear 'em.

**Comment by unsoluble** [comment]
Fixed in #5018 (with a z-index on the close button).
