### ISSUE TITLE
AM/PM selection is absent in Careportal using Firefox

### ISSUE THREAD

**Issue by aaronjknox** [nightscout/cgm-remote-monitor#502]
When entering an event in Firefox via careportal and designating the Event Time as "Other" the option to select AM/PM is absent so it requires entry using "military time".  This is seen on the Master branch (version 0.6.4) while using Firefox (version 36).
##

**Comment by jasoncalabrese** [comment]
There are some known issues with the time/data input types on firefox, the only solution is probably going to be replacing those inputs with something else.

**Comment by aaronjknox** [comment]
Thanks. I'm glad the dev's were aware of the bug. If users know about the required event time format it's easy enough to enter the data using 24-hour time.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
