### ISSUE TITLE
Reports Pages +24hours when viewed from non GMT timezone

### ISSUE THREAD

**Issue by haspden** [nightscout/cgm-remote-monitor#5025]
When viewed from a different time zone data appears +24 hours in the reports section.

Whilst it shows correctly in the database, uploads correctly etc, the data pulls to xDrip aaps etc correctly however

Viewed from Spain the data appears on 26/09/19 in the graph not 25/09/19 +24 hours

Viewed from the UK the data appears today in 25/09/19 correctly.

This appears in all 0.12.3 and 0.12.4 sites I've tested

**Comment by haspden** [comment]
Can you refrence if this was fixed @Tornado-Tim ?

**Comment by Tornado-Tim** [comment]
@haspden doing a big cleanup of the repo, and closing all issues that no longer apply or have proven to apply to the current release version.

If you find the issue still exists with the current release, please open up a new issue.

Just trying to help triage issues so we can get appropriate eye balls to look at the issue if needed.

Cheers

**Comment by haspden** [comment]
👍 next time I'm allowed to travel international I will test and re-open if needs be 😅😅

**Comment by herzogmedia** [comment]
it seems to still be the case, see #6773
