### ISSUE TITLE
Bolus correction marker

### ISSUE THREAD

**Issue by sandyavery** [nightscout/cgm-remote-monitor#5069]
Would like to add the ability to add a marker when a Bolus correction is made, would be a useful piece of information to have, perhaps a coloured dot on the graph with actual time and amounts given on another screen?

**Comment by sulkaharo** [comment]
Sounds like the Careportal feature which we already have. Have you enabled the careportal?

**Comment by sandyavery** [comment]
I have no idea, what is it and where do I look?

**Comment by unsoluble** [comment]
Add `careportal` to your `ENABLE` string, then check it off under "Show Plugins" in the main menu of your NS site.
