### ISSUE TITLE
When run with iOS 13, the D3 graph bottom "brush" area registers as a tap target for entire view

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#5074]
**Describe the bug**

When viewing the Nightscout graphs, the bottom area of the D3 graph shows the last 48 hours  of CGM plots and is intended to be tappable so users can move the main view of the graph to show a historic point of time in the graph. The taps to change the graph to show the historic moments are expected to register when tapping the bottom of the graph. When run on iOS 13 Safari, the entire page registers as a tap target for the graphs. The site still behaves as expected on desktop browsers.

**Comment by unsoluble** [comment]
I haven't been able to replicate this, running 13.1.2 on an iPhone X and an 11.

**Comment by sulkaharo** [comment]
Right, looks like this happens inconsistently when the site is being accessed in a browser and quite consistently when accessing the site in full screen mode through having made a home screen web app of Nightscout. So for testing, adding the site to Home might be key

**Comment by unsoluble** [comment]
Can you describe more about what you’re doing to trigger this? Just loading the site in a pinned view, then tapping around the main view? I still can’t get it to happen.
