### ISSUE TITLE
Upgrade D3 to the latest version

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#5075]
Nightscout currently uses the no longer maintained D3 version 3.5.17. The graph renderer should be refactored to be easier to maintain, not leak memory and to use a newer version of D3 that is still maintained.

**Comment by jpcunningh** [comment]
@sulkaharo, I started looking at upgrading D3 last night.  I'm willing to give it a shot this week and see how far I can get.

**Comment by alphacentauri82** [comment]
On it too
