### ISSUE TITLE
API query for first or last dataset

### ISSUE THREAD

**Issue by zreptil** [nightscout/cgm-remote-monitor#5091]
I am not really having trouble setting up nightscout, but i need to know how to use the api properly. I am writing the nightscout reporter and use the query api to request data from nightscout.

It works good for known dateranges, but i wonder if there is a possibility to find the first and the last dataset in a collection.

Lets take entries as example. When i look for a special date i use something like this:

https://xxx.herokuapp.com?find[date][$gte]=1571090400000&find[date][$lte]=1571176799999&count=100000

But with such a query i cannot get the first entry (meaning the entry with the lowest number in field "date") or the last entry (meaning the entry with the highest number in field "date").

Is there a possibility to get these special entries? I would like to extract from the data which daterange is available.

A workaround for the last entry seems to work like this:

https://xxx.herokuapp.com?find[date][$lte]=32503676399000&count=1

But also there the returned entry is only randomly the latest, since the entries seem not to be sorted by time. 

So my question is: what is the best way to find the oldest and the newest entry using the url-query?

best regards
Andi

**Comment by hannesvoss** [comment]
I am also very interested in a suggestion as I'm facing the same issue.

**Comment by zreptil** [comment]
Since there was no answer for a long time, i finally used my own approach to find the oldest dataset:

1 i start at the current date and load datasets for the day 256 days before the current date.
2 when there are datasets, i jump back another 256 days and continue at 1
3 when there are no datasets, i change the direction and take half of the days (128 when it was 256)
4 then i go back to 1, reversing the logic (go ahead as long as there is no data, change direction, cut in half, when there is data)

with this method you can find the first dataset with some iterations. to find the last dataset, just start at the first dataset and jump 256 days in the future using the same method as above. when data found, go on in the same direction, when not, cut the number of days to jump in half and go in the other direction reversing the logic.

The iterations are done, when the number of days to jump is 1.
