### ISSUE TITLE
Fat & Protein Display

### ISSUE THREAD

**Issue by mountrcg** [nightscout/cgm-remote-monitor#5146]
**Is your feature request related to a problem? Please describe.**
Recently the feature to log Protein and Fat intake in g has been added. Great feature and the first step to may be move to an insulination model not purely based on carb or carb equivalent. However events in Nightscout do not display any of those input. Mongo DB has them though.

**Describe the solution you'd like**
Any treatment containing input for those 2 variables should display them on NS.

**Comment by sulkaharo** [comment]
Can you post a screenshot with an annotation showing where you’d expect to see the protein and fat values?

**Comment by mountrcg** [comment]
Display on Web:
![image1](https://user-images.githubusercontent.com/539276/67465484-8ec59300-f645-11e9-8a40-5cee5f106305.jpeg)

corresponding Mongo-Entry in treatments
![image2](https://user-images.githubusercontent.com/539276/67465485-8f5e2980-f645-11e9-9de0-9c64837641ac.jpeg)

**Comment by sulkaharo** [comment]
Can you post the entire JSON object so I can see the treatment type? Looks like this was entered as a Note (which I think the code expects to just have text).

**Comment by mountrcg** [comment]
{
    "_id": {
        "$oid": "5db1564aaece6848c1e0654b"
    },
    "enteredBy": "FPUcalc",
    "fat": 10,
    "protein": 20,
    "created_at": "2019-10-24T07:44:06.000Z",
    "utcOffset": 0
}

Eventype: ???  Is missing?

**Comment by sulkaharo** [comment]
Right - that looks like the data is such that the client doesn't know what to do with it (and another thing we might want to enforce in the API). What is FPUcalc? If that application starts to send the event with a Careportal event type, the values will immediately show up in the UI.

**Comment by mountrcg** [comment]
FPUCalc is an IOS Shortcut from Robert Silvers I adapted heavily to calculate extended Carbs for the health App that feeds Loop.
So eventType= “careportal”
A token with role careportal should be enough in that case.

**Comment by sulkaharo** [comment]
Umm no, Careportal is a system that provides multiple event types. You might want to take a peek here: https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/plugins/careportal.js

**Comment by mountrcg** [comment]
{
    "_id": {
        "$oid": "5db16e35aece6848c10b54dc"
    },
    "enteredBy": "",
    "eventType": "Meal Bolus",
    "reason": "",
    "protein": "60",
    "fat": "40",
    "duration": 0,
    "created_at": "2019-10-24T09:26:13.674Z",
    "utcOffset": 0
}

**Comment by mountrcg** [comment]
![2019-10-24 11_53_34-1 hour ago](https://user-images.githubusercontent.com/539276/67474609-08b14880-f655-11e9-9d83-ec77005ec2b8.png)

**Comment by sulkaharo** [comment]
Which version of Nightscout do you have? If you enter a treatment using the careportal in nightscout itself and enter proteins, do they show up?

**Comment by mountrcg** [comment]
12.6 dev
The screenshot of Meal Bolus is directly from NS.

**Comment by mountrcg** [comment]
changed to 12.3 and input via NS careportal:
{
    "_id": {
        "$oid": "5db1a056aece6848c195429c"
    },
    "enteredBy": "",
    "eventType": "Carb Correction",
    "reason": "",
    "protein": "12",
    "fat": "24",
    "duration": 0,
    "created_at": "2019-10-24T13:00:06.047Z",
    "utcOffset": 0
}

UI display no show
<img width="349" alt="Bildschirmfoto 2019-10-24 um 15 00 56" src="https://user-images.githubusercontent.com/539276/67488223-bc273680-f66f-11e9-8d6c-b111d828414a.png">

**Comment by mountrcg** [comment]
If carb entry is 0, fat and potein will not show up in UI. All in NS 12.3

**Comment by mountrcg** [comment]
Just saw this fix and will test shortly

**Comment by mountrcg** [comment]
works all quite smooth. thx a lot.
