### ISSUE TITLE
Discord link doesn't do anything

### ISSUE THREAD

**Issue by viq** [nightscout/cgm-remote-monitor#5149]
Discord link doesn't do anything, at least if you're not already on the server, and it doesn't give any information how to join the server.

**Comment by unsoluble** [comment]
Which link, where?

**Comment by viq** [comment]
The new "shield" replacing the gitter chat link in the readme

**Comment by viq** [comment]
This commit
https://github.com/nightscout/cgm-remote-monitor/commit/a9f89aa679b979a607e6318db4d7ee76d93d9496

**Comment by unsoluble** [comment]
Ah, yeah, that should be an invite link, not a direct link to the channel. Will amend when I get a chance.

**Comment by unsoluble** [comment]
Fixed in #5126
