### ISSUE TITLE
Graph Render Glitch on Random Time Update

### ISSUE THREAD

**Issue by BradleyPJ** [nightscout/cgm-remote-monitor#5150]
**Describe the bug**

As shown in image, graph details jump to the middle after a random minute update. Version 0.12.6-dev.

The issue has happened a couple times today but don't see a pattern that might be linked.

**To Reproduce**
use version 0.12.6-dev wait 

**Screenshots**
![image](https://user-images.githubusercontent.com/13054604/67511288-762d9b00-f68e-11e9-8ae8-048bfa3a6ee2.png)

**My setup information**
Nightscout: v0.12.6-dev
CGM: Libre 1 with MiaoMiao 1
Browser: Firefox v70.0
Measurements: mmol

**Comment by steffen-AEI** [comment]
Does this also happen with predictions turned off?
