### ISSUE TITLE
Can't add treatment and Profile editor disappear

### ISSUE THREAD

**Issue by Calvinkuo-0801** [nightscout/cgm-remote-monitor#5162]
Dear,

I updated my daughter Nightscout on 26th Oct. I'm not sure whether I made any wrong setting.
Now, I can't add treatment from NS web and I find the profile editor is disappeared.

Many thanks for help.

**Comment by Calvinkuo-0801** [comment]
I find the reason why my daughter's NS "Profile editor" and "Log a treatment" disappear.  The reason is I change "Config Vars" item. I change "ENABLE": "careportal basal" to "cors". Now, I change back to "careportal" and I can use profile editor and log a treatment now^^. Sorry, I'm not a engineering. Could I ask a dumb question?  How can I keep "careportal basal" and "cors" at the same time under ENABLE?    Thank you for the community and great NS and xDrip, it makes my daughter life better.

**Comment by unsoluble** [comment]
You can put as many plugins as you'd like in the `ENABLE` variable — just list them all with a space between each. In your case, this would look like: `cors careportal basal`

(The Profile Editor disappears when the `basal` plugin isn't enabled, on older NS versions. This has been fixed in later versions.)

**Comment by Calvinkuo-0801** [comment]
Hi, thank you so much for your help and instruction. Thank you for this community help to keep my 4 yr daughter life easier.

**Comment by Calvinkuo-0801** [comment]
Hi John,

Thank you so much your help and instruction. I understand it now.

Really thanks for this community help and keep my 4yr daughter life easier and better.

Thank you.

Best,
Calvin
________________________________

**Comment by unsoluble** [comment]
Happy to help! And glad to hear the site is helping with your daughter's care. Take it easy. :)
