### ISSUE TITLE
cgm Color false, when display_units is mmol

### ISSUE THREAD

**Issue by zehnBE** [nightscout/cgm-remote-monitor#5171]
**Describe the bug**
When you have the Display_Units as mmol, the graph is only red (bg_target* is also in mmol).
When you set the bg_targXXXX * 18.8 (mg/dl), then the Color works.

**To Reproduce**
1. Set the Display_Units to mmol and set BG_HIGH, BG_TARGET_TOP, BG_TARGET_BOTTOM, BG_LOW also with mmol
The cgm Lines is always red (out of range).

**Expected behavior**

**Screenshots**

**Your setup information**
- What version of Nightscout:
0.12.6 and earlier
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?
No.

**Additional context**

**Comment by unsoluble** [comment]
This is (currently) expected behaviour, and is described in the [docs](https://github.com/nightscout/cgm-remote-monitor/blob/master/README.md#alarms).
