### ISSUE TITLE
Don't re-raise notifications in Pushover that have been ack'd

### ISSUE THREAD

**Issue by inventor96** [nightscout/cgm-remote-monitor#5180]
**Is your feature request related to a problem? Please describe.**
Nightscout seems to send Pushover alerts quite frequently, even after I've acknowledged them in the app. The time between notifications is greater when I acknowledge them, compared to when I just leave them, so it doesn't seem to be an issue with the Pushover service. In nearly all cases, I don't want the notification to come up again after I've acknowledged it. In the cases I want it to come back, I'll leave the notification alone so it'll come back on it's own, or I can snooze the notification (at least on Android, not sure what iOS has in that regard).

**Describe the solution you'd like**
When Nightscout receives a confirmation from Pushover that the notification has been acknowledged, NS should not re-raise the respective alert until after that alert has been cleared and occurs thereafter.

**Describe alternatives you've considered**
It's possible to use Tasker in combination with Pushover or IFTTT on an Android phone to mimic this functionality based on message titles, but it would either 1) be unnecessarily complex, or 2) prevent further notification based on a time factor (like snooze time from the first occurrence, or minimum time between messages). This solution is probably limited to Android phones, as I'm unaware of a Tasker equivalent for iOS.

**Additional context**
Implementation ideas are welcome. I'm thinking it's probably not worth the effort of storing active alerts in the DB, so it would just be something kept in memory. I'm not sure how easy it would be to watch for alerts being cleared? I'm assuming it'll probably pretty easy to watch for them being raised and recording the alert (maybe based on the title?) with the timestamp.

**Comment by sulkaharo** [comment]
AFAIK acknowledging the push is considered the same in Nightscout as if you'd go into the Nightscout UI and clear the alarm with the shortest presented snooze interval (as in, the pushes are an alternate UI to the alarm system). If you want the snoozing to last longer, you can configure the snooze timers to use a longer time span. The push notification sending is expected to happen at the same time as an alarm being raised in the UI itself; if you're observing more frequent pushes than alarms raised in the UI, that'd be a bug somewhere, but it's unclear from your description if this is happening.

**Comment by inventor96** [comment]
@sulkaharo You're correct (at least based on the documentation); the first snooze value set for the alert in NS is used to snooze it when the Pushover notification is ack'd. The notification pushes are working as expected. My thought is that I don't want to ever see that alert again after I've ack'd it until a new instance of that alert. In the mean time, I'll set my first snooze level to something like 8 hours.

Along with the idea of one notification push per alert instance, I think it might be better to set the Pusover retry duration to the first snooze value for the alarm in NS?

**Comment by jimrandomh** [comment]
This is one of a pretty big pile of problems with Pushover alerts, as implemented. I've fixed them up enough to tolerate for my own usage, mostly by commenting out the bad parts and rewriting hardcoded values, after ~2 years of using OpenAPS+Nightscout with no reliable alerts at all and sometimes having things go offline without noticing. I'm honestly kind of confused about how anyone actually uses these things, at least in the "adult monitoring their own looping rig" use case.

Alarms (including the "high" alarm) resend every 15 minutes regardless of acknowledgement and configuration. The 15 minute duration is hardcoded in `lib/server/pushnotify.js`. There are config settings for snooze duration; maybe they work when you're dismissing alarms on-site, but they do not work if you're only acknowledging the alarms via Pushover.

The alarms have a hardcoded ringtone/sound, which isn't configurable, overrides the setting on the pushover client, and (for some of the alarms), is too obnoxious to use in public.

When mapping Nightscout's internal alarm priorities to Pushover's priority scale, Nightscout's "warn" and higher are mapped to Pushover's "emergency". This means that most alarms will keep being re-raised by Pushover keep re-sending until you acknowledge them through the Pushover app, either every 2 minutes (for "urgent" alarms) or every 15 minutes (for "warn" alarms). These retry times are hardcoded in `lib/server/pushover.js`. This is separate from and cumulative with Nightscout re-sending alarms.

The practical upshot is that if you have an alarm which can't be cleared easily, such as a high that will take some time to drop, or waiting for a new sensor or a sensor restart, you'll get a notification every 15 minutes, plus a re-send every 2 minutes (also hardcoded) if you don't acknowledge it. If this happens at night, you can't go to sleep without turning off Pushover, and there is no way to do that which will turn back on automatically.

**Comment by josziglimp** [comment]
We are pretty happy with the way Pushover alarms work, only using the Pushover app to acknowledge alarms. I customized alarm sounds in the code and reduced the time between resending un-ack'd 'warn' alarms to 5 min. This way if I miss an alarm, it is repeated soon enough. 

My only issue is that it seems that some alarms that are being snoozed are re-raised immediately when the Heroku app is restarted (e.g. when changing a Config Var). For now I haven't been able to figure out which ones are and which ones aren't, or how to stop them from being re-raised.
