### ISSUE TITLE
Unchecking "Predictions" in /report triggers rendering

### ISSUE THREAD

**Issue by steffen-AEI** [nightscout/cgm-remote-monitor#5188]
**Describe the bug**

"Predictions" checkbox behaves like "Show" button.

**To Reproduce**
1. Open Reports page.
2. Click on "Predictions" checkbox. (The other "Display" options are OK.)
3. See error: "Rendering..." shows up.

**Expected behavior**
Only the "Show" button should trigger rendering.

**Your setup information**
- What version of Nightscout? - 0.12.6-dev (git 9c42fed)
- What type of CGM, and how do you get your data there? - N/A
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? - No, seen with Safari, Firefox, derivatives on MacOSX, Linux, Android.

**Comment by steve8x8** [comment]
OK; I found that the last 7 lines of `static/report/js/predictions.js` are somehow responsible for this surprising behaviour. That code seems to trigger a redraw each time the checkbox state is changed. Is this intended? (Shouldn't the state of the checkbox only be obeyed when "Show" is requested?)

**Comment by sulkaharo** [comment]
Sounds like it, yes. Also, as much of the code in /static as possible should be moved to the bundle (so it gets linted and transpiled), so if you’re up for some refactoring, please. :)

**Comment by steve8x8** [comment]
I'm already having a tough job to read the code, let alone understand or modify it :(
