### ISSUE TITLE
No scale if no CGM data, only manual BG measurements

### ISSUE THREAD

**Issue by steve8x8** [nightscout/cgm-remote-monitor#5189]
**Describe the bug**
If there are no CGM data, only BG measurements (e.g. uploaded by xDrip), there's no Y axis scale, and values cannot be read off.

**To Reproduce**
1. Run out of CGM sensors, wait until the graph is "empty" (few days)
2. Use manual BG measurements instead, upload using xDrip.
3. Check display: Red circles are there, but all along a single horizontal line (0.12.5) or two horizontal lines (0.12.6-dev git 9c42fed). No scale (except some blurry stuff in the top-right corner?), no mouse-over. Looks like division by zero?

**Expected behavior**
If there's no CGM value range, either the BG range or a default should be used.

**Screenshots**
https://ns.10be.de:6089

**Your setup information**
- What version of Nightscout - 0.12.6-dev
- What type of CGM, and how do you get your data there? - was using Libre with Glimp, switched to xDrip also for uploading Contour meter data
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? - No

**Additional context**
May be related to issue #3025

**Comment by jpcunningh** [comment]
@steve8x8, can you test #5195 to see if it corrects the issue?

**Comment by jpcunningh** [comment]
I created a separate branch `fix-missing-scale-when-no-entries` so you can deploy it to your server more easily than from the PR.

**Comment by steve8x8** [comment]
I cannot test (as I'm not having admin powers on that server), but the first commit lgtm - in particular as I discovered that in "pure logarithmic scale" the overview graph is OK (but the detailed one has all the values at the left corner so that might be yet another bug?)...
The other two commits are not related to this issue...

**Comment by steve8x8** [comment]
OK, since the server instance has been upgraded to dev 534c443 I can now report...
... that using a logarithmic scale (non-dynamic) places all markers (BG readings, boluses, pump maintenance actions, etc.) at the left border of the main canvas while the overview graph shows the BG measurements of the last days.
... that switching to linear results in everything still in the top left corner (and no useful scale), so basically the behaviour is unchanged.
The URL is still the same.
Apparently also the main graph X axis needs some more attention...
Thanks so far -

**Comment by jpcunningh** [comment]
Thanks! I’ll be able to check it out in a couple of hours when I get to a
computer.

**Comment by jpcunningh** [comment]
Looks like your server is not running 5434c443.  One of the relevant lines in the browser developer tools look like this:
![image](https://user-images.githubusercontent.com/34543464/68726946-a29b4f80-0588-11ea-84f4-94a1cfc8aa0b.png)

They should instead be replaced like this:
![image](https://user-images.githubusercontent.com/34543464/68726979-be065a80-0588-11ea-865b-35d0feec257d.png)

**Comment by steve8x8** [comment]
I've forwarded your request to "run the packaging script" to the server admin. For now, there's nothing I can do (although I'm trying to get some hardware to set up my own server, but this may take a bit longer)...

**Comment by steve8x8** [comment]
Using logarithmic scale for the time being.
