### ISSUE TITLE
"Glucose Distribution" report doesn't finish rendering without data

### ISSUE THREAD

**Issue by steve8x8** [nightscout/cgm-remote-monitor#5190]
**Describe the bug**
With only BG measurements available (CGM temporarily unavailable), rendering the "glucose distribution" view doesn't finish

**To Reproduce**
1. Run out of CGM sensors for a few days.
2. Select a time span short enough in Reports
3. Select "Show" or "Distribution"
4. Wait for "Rendering..." to disappear

**Expected behavior**
There should be a detection whether (enough) data are available at all.

**Screenshots**

**Your setup information**
- What version of Nightscout - 0.12.6-dev
- What type of CGM, and how do you get your data there? - currently none
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? - No.

**Additional context**
Any previously drawn pie diagram isn't erased while (not) "rendering..."

**Comment by jpcunningh** [comment]
@steve8x8, this should also be fixed by #5195. Please let us know if it works for you.

**Comment by steve8x8** [comment]
Unfortunately I cannot test it right away (you're referring to the 2nd of the 3 commits, I presume) - but lgtm. Go ahead...

**Comment by steve8x8** [comment]
Update: although the server claims to be running dev 534c443, I cannot see any change :(

**Comment by sulkaharo** [comment]
@steve8x8 are you self-hosting? If yes, remember to run the packaging script between installs

**Comment by steve8x8** [comment]
I'm not self-hosting (yet) so I must believe what the interface and the server admin tell me...
