### ISSUE TITLE
API query returns non-integer mbg values

### ISSUE THREAD

**Issue by steve8x8** [nightscout/cgm-remote-monitor#5205]
**Describe the bug**
An API query (entries.json) returns mbg values (mg/dl) with extra decimals

**To Reproduce**
1. Use curl (or the web interface) to query entries.json, insert some linebreaks for readability
2. Inspect type:mpg entries
3. Find this:
```
{"_id":"...","device":"Bluetooth Glucose Meter:\nAscensiaDiabetesCare\u0000   ...","type":"mbg","date":15736XXXXX832,"dateString":"...","mbg":106.00000762939453,"sysTime":"...","utcOffset":60},
...
{"_id":"...","device":"Bluetooth Glucose Meter:\nAscensiaDiabetesCare\u0000   ...","type":"mbg","date":15707XXXXX177,"dateString":"...","mbg":110.99999237060547,"sysTime":"...","utcOffset":120},
```

;)

**Expected behavior**
mg/dl values are integer values, and the database should not return values with extra precision which have never been entered this way.

**Screenshots**

**Your setup information**
- What version of Nightscout (e.g. 0.10.3)
0.12.6-dev
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.)
Contour Next One
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?
No

**Additional context**
I presume that internally all values are stored in mg/dl? (If I query an instance that's running on mmol/L I also get values in the mg/dl range.) Supposedly, not only mbg is affected - it's just what I've been providing and checking.

**Comment by sulkaharo** [comment]
Nightscout as it stands doesn’t sanitize the cgm data in any manner, so this means your data source is sending junk data into the system. Which CGM source are you using?

**Comment by steve8x8** [comment]
I'm pretty sure xDrip (which reads my Contour meter) does it right, but at this moment I can't prove nor disprove this claim.
If I dump the internal storage of the meter, I get integers only (being in the mg/dl realm), and I don't see any reason for xDrip to modify these values - which should just be handled as strings, but seem to be stored as floats in the db (? got to fetch a db dump to have a closer look, but with bson involved this will take some extra effort)

**Comment by sulkaharo** [comment]
I checked and the xDrip MBG record upload I have has "59.46005914082527" as the mg/dl value, so looks like an xDrip bug. Nightscout really doesn't do any data conversion on this, so any SGV or MBG value you get is exactly as uploaded.

**Comment by steve8x8** [comment]
OK, I could not reproduce this behaviour with an upload I did myself, using integer values - all of them have been stored as integers.
I wrote before, "I'm pretty sure xDrip (which reads my Contour meter) does it right" but this indeed points many fingers towards xDrip :/ Moving there....
