### ISSUE TITLE
Modify IOB duration

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#521]
I'd like to have possibility to adjust calculation of IOB. 
Current calculation with dia=3 and isf we use in bolus calculator makes iob spent faster in nightscout than our observation.
or should we ajust dia. but i've read somewhere only dia=3 is supported

**Comment by jasoncalabrese** [comment]
We're using the value from the treatment profile now, with a default of 3hr if there isn't a treatment profile

**Comment by MilosKozak** [comment]
so there is no issue  to use different dia value than 3 to adjust duration?

**Comment by jasoncalabrese** [comment]
No issue on dev in iob-cob the /pebble endpoint hasn't been updated yet

**Comment by jimsiff** [comment]
@jasoncalabrese I thought that the /pebble endpoint was updated to use the IOB library and profile DIA with this commit:

https://github.com/nightscout/cgm-remote-monitor/commit/a693304ab2eaac861589d4072b971b20268e3197#diff-5a493a6631e79159204d1905666acac5

**Comment by ELUTE** [comment]
We had a user test today and it was working with a long DIA

**Comment by MilosKozak** [comment]
ok. profile editor support float value of dia .. thx all
