### ISSUE TITLE
BG difference should be divided by missing interval

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#522]
![image](https://cloud.githubusercontent.com/assets/11146458/6800600/45ab2b56-d220-11e4-90c8-004179d0c1b6.png)
BG diff I'd like to see is -0.6 (-2.3/4)  let say for max 30 min in the past
and "Not calculated" if more than 30 min without data

**Comment by jasoncalabrese** [comment]
Think this can be combined with #371, see the comments on that issue

**Comment by jasoncalabrese** [comment]
part of #702 
<img width="536" alt="screen shot 2015-07-11 at 11 46 32 am" src="https://cloud.githubusercontent.com/assets/751143/8635096/40ccd900-27c9-11e5-8520-0c0b10f4a21b.png">

**Comment by MilosKozak** [comment]
thanks
