### ISSUE TITLE
Followed instructions for Alexa Integration perfectly, and multiple times. Still no luck.

### ISSUE THREAD

**Issue by bennettnicholas** [nightscout/cgm-remote-monitor#5220]
I have noticed that the guide is a little outdated and I am not sure if that matters. If you copy and paste the code from
https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md
and try to build, it will error. I tried adding in what it requested, but it still had issues. Same with it wanting two words for the name. I tried all these things and when testing, the only response I get from alexa is that it can not find / understand what I want. Could anyone help on this?

**Comment by bennettnicholas** [comment]
I am using Dexom G6 -> XDRIP+ -> Dexcom Share -> Nightscout (on Heroku). Nightscout has the data there and is working well.

**Comment by bennettnicholas** [comment]
@tanja3981 I saw you have done some things with this.

**Comment by bennettnicholas** [comment]
So found out when testing you can not use "alexa" to start. You must just say "Ask night scout how I am doing"

**Comment by sulkaharo** [comment]
Hey we're doing a big update to Alexa support soon. If you can help test https://github.com/nightscout/cgm-remote-monitor/pull/5137 that'd be great

**Comment by bennettnicholas** [comment]
@sulkaharo, anything specific you want tested?

**Comment by inventor96** [comment]
@bennettnicholas Everything. ;-) The changes made in #5137 affect nearly every interaction. If you're willing to test Google Assistant, that would be much appreciated, too!

**Comment by bennettnicholas** [comment]
@inventor96 I have never used / owned a google assistant :(. Is it like the Alexa developer console? Am I able to test there?

**Comment by inventor96** [comment]
@bennettnicholas If you have an Android phone, you can use it there. However, there is a simulator online as well. If you have other questions, feel free to ask in that PR, that way you can close this one and we can keep everything in one spot.
