### ISSUE TITLE
Temporary Overrides that span 2 days are not visible in Day to Day graph

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#5230]
**Describe the bug**

**To Reproduce**
0. Run or find a temporary override that starts before midnight and extends past midnight.
1. Go to 'Reports > Day to Day' > set date range to cover both days.
2. Press Show
3. See that the override bar is missing on day 2 between midnight and the next override is enabled.

**Expected behavior**
A gray bar should appear from midnight on day 2 until the override is turned off or another is turned on. It should be present for the entire duration that is stored in the treatment.

**Screenshots**
![image](https://user-images.githubusercontent.com/46848705/69375995-57ef9680-0c5e-11ea-830d-e9a3994b881d.png)

**Your setup information**
- What version of Nightscout: 0.12.6-Dev
- What type of CGM, and how do you get your data there? G6 via share
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No

**Additional context**
Using Loop and has temporary overrides enabled.

**Comment by sulkaharo** [comment]
@ps2 Temp overrides > 2 days sounds long? Not sure how to fix, the graphing currently assumes we need items around up to a duration of DIA x 2 to render a day.

**Comment by Nightfoxy** [comment]
@ps2 any ideas on how to show an override that spans across days (midnight)?
