### ISSUE TITLE
Question: How NS calculate the trendarrow!

### ISSUE THREAD

**Issue by st0ber** [nightscout/cgm-remote-monitor#5248]
I need help. For my watchface (SmartWatch) i need the trendarrow. How calculate NS the arrow? I did not find it in the source Code. Can Somebody help me? Thx

**Comment by whooze** [comment]
As far as I know the trendarrow in Nightscout is decided by the data in the database
```
{
    "_id": {
        "$oid": "5de0ff860cb8b0c97b5110d4"
    },
    "sgv": 104,
    "date": 1575026413000,
    "dateString": "2019-11-29T11:20:13.000Z",
    "trend": 4,
    **"direction": "Flat",**
    "device": "share2",
    "type": "sgv",
    "utcOffset": 0,
    "sysTime": "2019-11-29T11:20:13.000Z"
}
```

xDrip+ calculates it's own trendarrow though

**Comment by st0ber** [comment]
Thx. Yes i know that. But there must be a calculation in the source code. The source code from xDrip i know. Thx anyway

**Comment by sulkaharo** [comment]
Hi! This is a not a bug or issue with the software, please visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ to ask this
