### ISSUE TITLE
Local profile suddenly shows faulty times

### ISSUE THREAD

**Issue by Loopi2712** [nightscout/cgm-remote-monitor#5295]
**Describe the bug**
I use AAPS version 2.5.1 on a Samsung S7 and the latest Xdip version. File AAPS preferences on the device is upto date. I can import the correct parameters including the local profile. 

When I toggle to "overview" and back to "local profil" the times in the profile are changed. The annex shows screen shots of the correct and changed (wrong) local profile. 

The profile in the pump (Dana RS) remains ok. 

![Screenshot_20191216-203945_AndroidAPS](https://user-images.githubusercontent.com/11147787/70938072-c4836880-2045-11ea-8cb3-21328e8f7095.jpg)
![Screenshot_20191216-204024_AndroidAPS](https://user-images.githubusercontent.com/11147787/70938071-c4836880-2045-11ea-96df-044ef3ffe8ab.jpg)

**To Reproduce**
1. Import prefferences and restart AAPS 
2. Check local profil -> ok
3. Scroll down to 'overview'
4. Scroll back -> wrong local profil

**Expected behavior**
unchanged local profile

**Screenshots**

**Your setup information**
- What version of Nightscout (e.g. 0.12.5)
- What type of CGM -> G6 , and how do you get your data there? Xdrip 2.18.2.88
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?
unknown
**Additional context**

Thanks for helping. Otherwise the AAPS runs perfect !!

Kirstin & Axel

**Comment by dv1** [comment]
I can confirm this. Exact same problem here. Nightscout 13.0.1, Dexcom G6, xDrip 6d4d283-2019.10.27, AndroidAPS 2.5.1. One ugly workaround I found was to create ISF and IC entries for all 24 hours and fill them all. That way, the hours cannot be corrupted by this bug.

**Comment by sulkaharo** [comment]
Looks like an AndroidAPS bug? Or what am I missing? This is the repository for Nightscout (the web service)
