### ISSUE TITLE
Pump remaining units info pill problem

### ISSUE THREAD

**Issue by pmadhur** [nightscout/cgm-remote-monitor#5296]
I use Loop/Omnipod with Nightscout. I am not sure where the problem is. It could be in Nightscout, Loop or Omnipod. Since I see the info in Nightscout, I thought I would report here first.

In the picture below, you can see around 06:40, Nightscout shows pump remaining units as 39.4 U. From approx. 07:00 to 07:30, it shows +50 U. After 07:30 it shows 36.4 U. The issue is reproducible every 3 day i.e., on the pod changing day. Until the pod is changed, the pump info pill shows +50 U for few hours and real remaining units for few hours.

![ns-pump-rem-units](https://user-images.githubusercontent.com/16571328/71000863-4f16a700-20dc-11ea-8614-33b45747518a.gif)

Is it a Nightscout issue or a Loop/Omnipod issue?

**Your setup information**
- Nightscout installed at my home.
- What version of Nightscout: 0.12.6-dev.
- What type of CGM, and how do you get your data there: G6, ShareBridge.
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.): No.

**Comment by sulkaharo** [comment]
Can you update to latest version and see if this still occurs? We fixed a bug related to pill data handling so it's possible the cause was fixed. Other than that, the data comes from Loop and if the IU left varies like this, it's possible there's a glitch in Loop handling/uploading the data regarding the units left?

**Comment by pmadhur** [comment]
Thanks for info. Just updated to 13.0.2-dev. Changed pod today, so I would see if it is fixed on next pod changing day i.e., in 3 days.

**Comment by pmadhur** [comment]
Problem still exists. I would report the problem to Loop.
