### ISSUE TITLE
Clock / Android Widget UI

### ISSUE THREAD

**Issue by brianhanifin** [nightscout/cgm-remote-monitor#53]
_Update: corrected typo. Changes_ **in bold**.

Create a separate people like **the Pebble Watchface** (at `/basic`?) that omits the chart portion of the full site. This would be perfect for displaying in Android widgets.
##

**Comment by oskarpearson** [comment]
I'm working through old tickets. I'm pretty sure this can be closed. If necessary could you re-open it? Thanks!
