### ISSUE TITLE
Unable to authenticate from the Profile editor, and from the report section

### ISSUE THREAD

**Issue by ghost** [nightscout/cgm-remote-monitor#5306]
When you press the authentication button, the Secret API request window does not appear.

The problem occurs by going to the profile editor, and pressing the authentication button, at this point you would expect to see the authentication window appear. But this is not happening by making it impossible to change the settings. 

The affected Version of Nightscout is the 13.0.0 released today 17 December 2019

**Comment by OpossumGit** [comment]
I had similar problem on my iPhone, fixed it by shutting down the browser and restarting. Then it loaded fresh. By shutting down I mean double clicking the button and throwing the browser up

**Comment by OpossumGit** [comment]
And you are right. If you are unauthenticated in profile, Authenticate option does nothing. You can authenticate from home screen (lock icon)

**Comment by unsoluble** [comment]
Fixed (hopefully) in #5314

**Comment by U47** [comment]
Leaves me with unbridled confidence that the first pull I grab has a show-stopping fatal bug right from the get-go.

**Comment by unsoluble** [comment]
Hardly fatal, just going to be confusing for those who don’t realize that you can auth from the main toolbar as well.

**Comment by U47** [comment]
I can't get to the main toolbar because the root screen immediately throws an alert and redirects you to make a profile if you don't already have one. So, yeah, in a new install, fatal.

**Comment by jpcunningh** [comment]
@u47, the `dev` branch is fixed if you want to deploy that until the `master` is patched.

**Comment by U47** [comment]
@jpcunningh I'll stop griping and go do that. Tks.
