### ISSUE TITLE
"Wrong API secret" after upgrading

### ISSUE THREAD

**Issue by CoreISP** [nightscout/cgm-remote-monitor#5345]
Hi,

After upgrading to Ketchup I'm getting an error "Wrong API secret!" whenever I'm trying to auth. It was working fine before. Even when copy/pasting the API_SECRET value directly from the config: it still responds with the same error and refuses to log me in.

Strangely, my iPhone running Spike and a small MacOS app that shows the glucoselevels in the tray are still perfectly able to auth both for read and write (Spike, using API_SECRET) - so the problem appears to be present solely in the webbrowser. (Tried Safari, Opera and FireFox)

Is this a known bug or have I somehow butched something up with the upgrade?

**Comment by rogue-bryan** [comment]
I had this come up as well. I refreshed the page a couple times to see if it just needed to release some cache, and it still came up. 

I opened the F12 dev tools, and all the sudden it worked when I tried a gain a few minutes later.

**Comment by Alamo04** [comment]
Same here.
But only after update to 13.0.1.

Closing and restart browser fixed it.

**Comment by CoreISP** [comment]
> I had this come up as well. I refreshed the page a couple times to see if it just needed to release some cache, and it still occurred.
> 
> I opened the F12 dev tools, tried it again to see if I saw any console errors/logs, and all the sudden it worked when I tried again a few minutes later.

Still not working here unfortunately, but I opened inspection as well and noticed it's returning:
[Log] Authentication failed. – {status: 200, message: {message: "OK", rolefound: "NOTFOUND"}} (bundle.app.js, line 241)

Guess something's off with the role based authentication in this version.
I've hashed out the AUTH_DEFAULT_ROLES="denied" in my config, which of course causes Nightscout to load now - but it still says the API secret is wrong. :|

**Comment by sulkaharo** [comment]
@CoreISP are you certain your browser has the latest client? I've seen Chrome sometimes absolutely refuse to update the client files, so if on Chrome, please can you confirm the behaviour using some other browser?

**Comment by CoreISP** [comment]
@sulkaharo I've cleared the caches/temporary storage and tried on Safari, Opera (which is Chromium I guess) and Firefox. All have the same problem rejecting the API key. I'm a bit confused as to why it only happens in any browser, whilst apps like Spike, Nightscout Menu Bar and Nightguard happily connect with the API key and seem to have no problems writing/reading.

**Comment by tomiczech** [comment]
Same problem with me. Javascript tells me "wrong api secret" but i'm entering right one. I tried to change it in start script. It is after update to 13.0.1.

Console:
Jan 15 19:57:28 nightscout.mvdstudio.cz start.sh[298786]: GRANTED:  ::ffff:89.239.25.52 no-token api:status:read default
Jan 15 19:57:28 nightscout.mvdstudio.cz start.sh[298786]: WS: Connection from client ID:  kN0R5nIacztUIC47AAAK  IP:  ::ffff:89.239.25.52
Jan 15 19:57:28 nightscout.mvdstudio.cz start.sh[298786]: WS: Authetication ID:  kN0R5nIacztUIC47AAAK  client:  web  history: 48

Javascript console:
hashauth.js:32
status:200, {message: "UNAUTHORIZED", rolefound: "NOTFOUND"}

**Comment by CoreISP** [comment]
@tomiczech I finally ended up downgrading to the previous version today as well. (All hail backing your **** up when going for a major upgrade ;)) Had to modify my profile in Nightscout for Nightscout Reporter to work properly: and that's not available either without API secret. :(  After the downgrade, everything works instantly again. Hope they'll fix it so that we can upgrade in the future. :)

**Comment by RoelStroeve** [comment]
Hey there, 
I've got the same issue with getting glimp to work with nightscout, unfortunately for me it's a fresh install so I've got no backup to go back to...
Is the best way to reduce the security on NS? Any other options like adding another user/role?
Cheers!

**Comment by CoreISP** [comment]
@RoelStroeve No idea, I'm still running the outdated nightscout... Not happy about it, but at least I know its functional. And since it's hosted on a server with no outbound connection I'm not too worried about it, but it is too bad it cannot be upgraded hehe.
