### ISSUE TITLE
Alexa and Authentication Roles

### ISSUE THREAD

**Issue by saund3rs101** [nightscout/cgm-remote-monitor#5347]
Following the set up guide fully, it appears Alexa will not connect to a nightscout site that has authentication roles set up.

She will read out the BG and connect fine when the endpoint is set to 
''https://mynightscoutsite.herokuapp.com/api/v1/alexa'' and no auth roles are active.
 
However, Alexa will not come back with a response if I have authentication roles enabled within nightscout. Even if I add a valid auth role token into the endpoint URL. 

I'd prefer my nightscout site to remain password protected so if this can be adjusted to allow for token access that would be fantastic.

Thanks for all of your development work!

**Comment by PeachOhs** [comment]
I had the same issue with googlehome. With AUTH_DEFAULT_ROLES set to denied, I couldn't get anything through Google, even BG. I changed it to readable and now that works. I don't want to give full access to the default role for publishing data. For now I'll use IFTTT to publish insulin treatments.

**Comment by inventor96** [comment]
I think I've found the solution. There are two situations I worked on, with slightly differing processes for each as outlined below.

- **You've set your `AUTH_DEFAULT_ROLES` config variable to `denied` and would like to setup a separate token for your virtual assistant:** This is by far the easiest and most common scenario.
    1. Add a new subject with the name you desire (e.g. "virtual-assistant") and give it the "readable" role
        - If you **really** would like to be super specific, you could create a new role and set the permissions to `api:*:read`
    2. After the new subject is created, copy the "Access Token" value for the new row in your subject table (don't copy the link, just copy the text)
    3. In the respective configuration screen for your virtual assistant, append `?token=YOUR_TOKEN` to the end of the URL, where `YOUR_TOKEN` is the Access Token you just copied

- **You've set your `AUTH_DEFAULT_ROLES` config variable to `denied` but would like to use only your `API_SECRET` set in your config variables:** This one is a bit trickier, and I was able to get it to work only with Google Assistant because setting a header is required, and Alexa doesn't support that as far as I can tell.
    1. Open a new tab with your Nightscout site
    2. If you haven't already, log in with your API secret
    3. Open the developer tools for your browser (e.g. in Chrome, press F12, or right-click anywhere and click "Inspect")
    4. Look at the console in your browser's developer tools
    5. Find the line that starts with "status isAuthenticated"
    6. Within that line, find `"apisecrethash": "RANDOM_TEXT"`
        - You might have to expand something or click an arrow to display the whole line
    7. Copy the `RANDOM_TEXT`
    8. In the Webhook setting, add a header with the key set to `api-secret` and the value set to your `RANDOM_TEXT` you just copied

**Comment by milenealessi** [comment]
On Heroku, where do I find "AUTH_DEFAULT_ROLES config variable"?

**Comment by inventor96** [comment]
In your app settings.

![Screenshot_20200429-191757](https://user-images.githubusercontent.com/7132744/80662515-a7789080-8a4e-11ea-856e-9e8ffd5e44c5.png)
(See the Settings tab toward right)

**Comment by milenealessi** [comment]
Thank you! :)
