### ISSUE TITLE
ability to deactivate audio alarms

### ISSUE THREAD

**Issue by geekmoto13** [nightscout/cgm-remote-monitor#5349]
**Is your feature request related to a problem? Please describe.**
had an alarm on for <80 and it dang near blew out my hearing it was so loud in my web browser.  there needs to be a way to adjust the audio levels or remove the audio

**Describe the solution you'd like**
an option to adjust the audio levels (volume) or disable the audio entirely

**Describe alternatives you've considered**
Turn all alarms off (bad idea)

**Additional context**
The speaker icon gives no indication if audio is on or not

**Comment by unsoluble** [comment]
You can disable any/all alarms at any time, via the main menu in your site. Or, set your defaults via your Config Vars in Heroku.
