### ISSUE TITLE
Cannot GET /__webpack_hmr

### ISSUE THREAD

**Issue by daveewall** [nightscout/cgm-remote-monitor#5351]
Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier?
I just upgraded from 0.11.1 to 13.0.1 and found this issue.  I haven't tested any other versions.  I'm running my own Docker image, the only other change I made in it was to upgrade from node 8.15 to 10.18, and to checkout the 13.0.1 tag, and rebuilt the image.

Which device / browser version was used to reproduce the bug?
It happened on the iOS Nightscout program, as well as Firefox on Linux.

Does this happen every time you launch Nightscout, or sometimes?
Every time.

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)
I believe the issue lies in the fact that I'm running on a port other than 1337.

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong
The issue manifests itself with the clock and BG number showing, and everything below looking black, and the devtools of the browser showing:  Cannot GET /__webpack_hmr

I was able to fix it myself by going into the docker image, running this:

sed -i s/1337/1234/ webpack.config.js
npm run postinstall

After that, the site started working properly.

I'm guessing that the webpack.config.js just needs to use the PORT environment variable to find the port and update the config.

**Comment by sulkaharo** [comment]
If you want to host a custom docker installation in dev mode for your production site, feel free to PR a change that allows you to do this but given this is very much not supported as a hosting option, I'm closing this ticket as I don't think anyone in the dev team will act on this.
