### ISSUE TITLE
Graph won't display most recent data when Loop/OpenAPS stops reporting

### ISSUE THREAD

**Issue by inventor96** [nightscout/cgm-remote-monitor#5383]
**Describe the bug**
When my OpenAPS rig stops reporting its status (even though it still reports everything else, but that's a different issue), and it's within the time frame that NS allows to report the duration since the last report, the graph won't allow me to scroll all the way to the right in order to see the most recent data. The page doesn't even load to show me the current time. However, once it's past the 6 hours and starts showing the "unknown" value in the pill, the graph will allow me to see everything up to the current time as expected. These same results occur for me on mobile, too.

**To Reproduce**
1. Somehow get your OpenAPS rig to report everything except loop status
2. Go to the NS site

**Expected behavior**
I would expect to have the vertical dashed line in between the two solid lines, and allow me to scroll to the current time.

**Screenshots**
Here's an example where the pill says 6 hours ago, and I can't scroll to the right anymore. You can't see it here, but the vertical dashed line is all the way to the right edge of the window, which I'm assuming is the part that the scrolling position is based on.
![image](https://user-images.githubusercontent.com/7132744/71561112-713eec00-2a2f-11ea-9bbb-46d74ec11cc4.png)

And here's an example of the pill showing "unknown" (past the 6 hour mark) and allowing me to see everything.
![image](https://user-images.githubusercontent.com/7132744/71561161-21145980-2a30-11ea-8b4a-18ec9f2d24a0.png)

**Your setup information**
- NS v13.0.2-dev (the only personal modifications to my instance have been on the virtual assistant APIs, so they shouldn't affect this issue)
- Dexcom G5, collecting via Logger on the OpenAPS rig
- Chrome 79 on MacOS Cataline (10.15.2), as well as Chrome on a Google Pixel 2 XL running Android 10.

**Comment by sulkaharo** [comment]
If I read this correctly, the brush stops scrolling at the last prediction point, if there's an old prediction available. @jpcunningh idea?

**Comment by jpcunningh** [comment]
It's probably in the `chart.createBrushedRange` function, but to figure out why the logic is failing, I'll need to make some time to re-create it on a test NS instance.
