### ISSUE TITLE
Wrong display blood glucose 

### ISSUE THREAD

**Issue by Sarah-B33** [nightscout/cgm-remote-monitor#5384]
**Describe the bug**
Blood glucose note don't display correctly

**To Reproduce**
1. Go to 'Nightscout graph' 
2. Click on previous 'meal bolus' 
3. See error

**Screenshots**

![IMG_20191230_133653](https://user-images.githubusercontent.com/53997360/71582215-66f12080-2b09-11ea-98bf-da7cc66443da.jpg)
![IMG_20191230_133747](https://user-images.githubusercontent.com/53997360/71582216-66f12080-2b09-11ea-8b86-b93cd804f3f7.jpg)

**Your setup information**
- What version of Nightscout (13.0.1)
- What type of CGM, and how do you get your data there? (Miao-miao /Freestyle libre 1/ Sony Xperia F3111 with xdrip+)
- Android with Chrome 

**Additional context**
All 'Meal Bolus' was entry with an Android Phone (Xiaomi redmi note 5 and Web bowser Chrome.)
Bug was discover after Nightscout update 13.0.1

**Comment by Bartlomiejsz** [comment]
@Sarah-B33 this should be fixed by https://github.com/nightscout/cgm-remote-monitor/pull/5381
