### ISSUE TITLE
Brainstorm: Send treatments via virtual assistants

### ISSUE THREAD

**Issue by inventor96** [nightscout/cgm-remote-monitor#5391]
I'm working on developing the ability to send Careportal treatments to Nightscout via virtual assistants (Alexa and Google Assistant), and I'm wanting to get some ideas from the community. Any thoughts on the subjects below, or any others, would be appreciated!

**Security**
Similar to the default configuration, I'm hoping to allow read-only access without authentication (unless otherwise configured) and then require authentication in order to create treatments. From my understanding, this could be accomplished by chaining a few functions in the `express.Router().post()` method:

1. The call to check the `api:*:read` permission
2. A function to check if the received Intent is a reading or a writing one. If it's a reading intent, find the respective handler and call it. If it's a writing Intent, call `next()` to go to the next function
3. The call to check the `api:treatments:write` permission
4. A function to route to the respective handler for the Intent

I think that, technically, the third and fourth functions could be within the second. Not sure if there would be programatic benefits to one way or the other.

**Authentication**
Instead of giving two instructions for API_SECRET and Auth Tokens, I'm thinking I'll write up the instructions to use only Auth Tokens since they always work, and I haven't found a way to get the API_SECRET to work with the Alexa configuration.

**Verification**
With any of the Intents that create treatments, I'm planning on having the virtual assistant repeat back the interpreted data and request a confirmation from the user. Does anyone feel like there are any types that may not require a confirmation? Maybe something like start/stop a CGM transmitter? Or should all of them require a confirmation unconditionally?

**Comment by sulkaharo** [comment]
@inventor96 I made changes to the authentication code in release 13, so the authenticator should accept the Tokens in place of the API_SECRET, so if you have a method for passing the secret to the API, users should be able to pass in a Token using the same method. Please ping me if this doesn't work.

**Comment by inventor96** [comment]
@sulkaharo Accepting tokens isn't an issue as far as I can tell (per the changes made in #5388) unless there's a situation in which tokens aren't enabled? It seems like tokens are always an authentication option, no matter what other configurations are in place. Please correct me if I'm wrong.

**Comment by inventor96** [comment]
@sulkaharo In order to work with multi-step commands such as confirming an action, we'll need to temporarily store a conversation identifier and state. I'm kinda hesitant to add another collection just for this purpose, so I wanted to ask your thoughts on using an existing collection?

**Comment by inventor96** [comment]
@Tornado-Tim Why was this closed? The last question was answered in a discussion on Discord, and I'm still actively working on this feature as I have time.

**Comment by Tornado-Tim** [comment]
Hi @inventor96, can you please open up a Pull request with your fix and WIP in title(so it states it not ready for merge), so the conversation can be carried on there.

I did a massive cleanup for the repo as we had too many issues that were old or had no visible activity for over a year. Having so many open issues which may not apply makes it hard to see what issues actually exist.

I will reopen this issue, then close once PR has been merged.

Thanks

**Comment by inventor96** [comment]
Moved to #6875
