### ISSUE TITLE
Update nightscout

### ISSUE THREAD

**Issue by Sweetea420** [nightscout/cgm-remote-monitor#5413]
Please include the following information with your bug report:

Is this a new bug with the latest release, have you seen this earlier?

Which device / browser version was used to reproduce the bug?

Does this happen every time you launch Nightscout, or sometimes?

Steps how to reproduce (if you can’t reproduce the issue, please don’t report the issue / if we can't reproduce the bug, we can't fix)

Please include 1 or more screenshots of the issue appearing, ideally with an annotation on what's wrong

**Comment by casellir** [comment]
Glycemia arrows disappeared since few days, replaced by a dash"-".

![image](https://user-images.githubusercontent.com/55324736/77250700-f65e2980-6c49-11ea-8157-a9cc57336653.png)
