### ISSUE TITLE
Echo Show enhancement request

### ISSUE THREAD

**Issue by alexmoir1** [nightscout/cgm-remote-monitor#5437]
Hi guys. I have Alexa set up linked to Nightscout, which is great. But it would be really good if we could have a Nightscout 'widget' (BG, graph & trend arrow), showing (day & night) on the Echo Show home screen, just above the time, without having to 'ask' Alexa.

**Comment by adamecker** [comment]
@Tornado-Tim is there any documentation or link to how this was completed? All I see is the main Alexa plugin for voice interactions here: https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md
