### ISSUE TITLE
Make sound button mute / un-mute all sounds

### ISSUE THREAD

**Issue by jakobsandberg** [nightscout/cgm-remote-monitor#5451]
**Is your feature request related to a problem? Please describe.**
I assumed that the sound button (volume icon) would mute all sound. After inspecting the logic, I realized that the purpose of this button is to test the sound on your device (it simulates an alarm for 4 seconds). Once I tested the sound and verified it worked, this button no longer had a use for me. Given that this button takes up valuable real estate (next to primary navigation buttons), it mostly just gets in my way.

I'm concerned that other users are confused by this as well. I'm also worried that new users will find the alarm sounds jarring and intuitively click the volume icon to silence it. This will lead to frustration when the button doesn't silence the alarm. (e.g. see #5349)

**Describe the solution you'd like**
I think it would be very useful to have a mute / un-mute button in a visible place, especially when you are in a quiet environment (e.g. a library). We can include a new icon to make it explicit that the audio is muted, and toggle this icon with the existing one as the sound is muted / unmuted.

I still see merits to a button to test the sound feature, so how about we move that to the settings section next to the alarm settings?

What do y'all think? If there is interest, I'll open a PR for this change

**Comment by unsoluble** [comment]
I think that's a pretty solid argument and rationale.

**Comment by veryfancy** [comment]
I use that button to test the sound every night before I go to bed. This proposed change would turn that (which I assume is a common behavior, given that button has been around for year) from one tap into two, and adds latency. Don't move my cheese!

Also, mute is a function that's generally easily accessible from operating systems and/or devices. Muting your phone or laptop in a quiet place is a more robust solution to the problem described above. And that frees real estate in applications' UIs for app-specific buttons.

**Comment by JonathanFly** [comment]
I found this issue thread after Googling why the mute the mute button didn't work in Nightscout. The icon is a perfect match for a standard volume/mute button combination. Recommend explicitly labeling it as a test button.
