### ISSUE TITLE
Some reports do not show any BG

### ISSUE THREAD

**Issue by engine2isnt** [nightscout/cgm-remote-monitor#5470]
Whereas the home screen graph shows BGs, only Day-to-day/Week-to-week reports use them. The rest of the reports (Daily stats,Distribution.Hourly stats,Percentile chart,Weekly success) do not, reporting "No data"/"0"/"NaN"/"infinity"

1. Go to /report
2. Click on 'Day-to-day' or 'Week-to-week', confirm BGs are there
3. Click on 'Daily stats' and see 'no data available'
4. Click on 'Distribution' and see 'Glucose distribution ( Result is empty )'
5. Click on 'Hourly stats' and see empty graph and 0 readings at all the times - but at least standard deviation is a perfect 0!
And so it goes... It works the same regardless of whether the BGs came from xDrip+ or were put in directly using care portal (did an experiment).

**Expected behavior**
Well... I expected some sort of analysis (percentiles, compounded/average graphs - that sort of thing). I definitely expected to see data that Nightscout already has and has shown that it has.

**Your setup information**
- Nightscout 0.13.0.1
- xDrip+ 20200116 sending info from AccuCheck Aviva Connect, but I don't think it relevant
- Tried on 2 versions of Firefox, Chrome and whatever apple uses, so obviously used Apple, but also 2 PCs, Android phone and IBM H50 (just for shits and giggles)

**Comment by engine2isnt** [comment]
It's been three weeks, so I guess I am the only one seeing this issue. In which case it's the setup question, so I will just have to ask for advice on FB.

**Comment by sulkaharo** [comment]
What’s probably happening is, the reporting only considers CGM data and if you’re sending in data just from the glucometer, the reporting will consider the dataset to be empty

**Comment by engine2isnt** [comment]
Assuming that is the case, and looking for some unneeded conditional (why would one exclude ANY glucose readings, even if they come from the endocrinologist's meter?), in lib.report_plugins/hourlystats.js on line 54 I find:
data = data.filter(function(o) { return !isNaN(o.sgv); });

I may be too old, but having started on FORTRAN IV I expect declaration and definition somewhere, even with classes. So, please, call me dense, but where is o class or structure defined?

**Comment by engine2isnt** [comment]
I guess I am not good enough with sed to look for o!
 ;)}

**Comment by sulkaharo** [comment]
Pull requests to improve the code are welcome! If you want to add support for glucometer data, please do. (Nightscout as such has historically been focused on CGM users and I don’t think we have had any devs who only use a glucometer.)

**Comment by engine2isnt** [comment]
I would love to, but at this point my propeller-hat is hard to hold on to, hence I ask for guidance: obviously SOME reports include the data others exclude. I failed to find any design documentation or mention of this data exclusion anywhere. As all I use are eyes and text editor (plus brain, but no too often!), it's hard for me to have an idea of WHERE to look, so that I do not miss something I shouldn't. Yes, this message is sent from windows, so that I don't mind thrashing the system should something happen, but it is NOT being used for anything other than internet, as it is the only disposable machine around here.
