### ISSUE TITLE
The Alexa plugin fails. "There was a problem with the requested skill's response"

### ISSUE THREAD

**Issue by SimonPhilpott** [nightscout/cgm-remote-monitor#5494]
**Describe the bug**
Using the template JSON file and instructions found within /master/docs on the most current NS version I am unable to get Alexa to respond using the trigger "night scout". This is replicated within the Alexa developer console with an error of "There was a problem with the requested skill's response". I have ensured all setting are correct. 

**To Reproduce**
Set up via, https://github.com/nightscout/cgm-remote-monitor/blob/master/docs/plugins/alexa-plugin.md#adding-alexa-support-to-a-plugin

Testing in https://developer.amazon.com/alexa/console/ask/test/

**Expected behavior**
I should receive a returned response that mimics Alexa. I get the error, There was a problem with the requested skill's response

**Screenshots**
![image](https://user-images.githubusercontent.com/6833057/73441014-3b509880-434a-11ea-898d-4d250aed974d.png)

**Your setup information**
- What version of Nightscout 13.0.1

**Additional context**
I've ensure that my language for pwd is set to English (UK) / AMAZON.GB_FIRST_NAME within the slot type and that my Endpoint is a Subdomain of a domain using a https URL

**Comment by SimonPhilpott** [comment]
The trigger keyphrase cannot be nightscout, it has to be two words or more and therefore "night scout" works.

**Comment by bfelizardo** [comment]
Hello Simon, I have the same problem. How did you fix it? My trigger keyphrase has always been two words "night scout" but still get that problem. Thanks for your response.
