### ISSUE TITLE
Correction Bolus tooltip incorrectly scales BG

### ISSUE THREAD

**Issue by dybs** [nightscout/cgm-remote-monitor#5500]
**Describe the bug**
The Correction Bolus tooltip scales a manually-entered BG value by a factor of 18.

**To Reproduce**
1. Set profile units to mg/dl
2. Set client settings Units to mg/dL
3. In Care Portal, create a Correction Bolus treatment and enter a BG value in mg/dL (e.g. 100).
4. Hover the mouse over the treatment in the graph.
5. The tooltip shows the BG value multiplied by 18 (e.g. 1800).
6. NOTE: The Treatement Report shows the entered value, and the treatement dot does appear at the correct position on the graph.

**Expected behavior**
The treatment tooltip should show the same BG value that was entered.

**Screenshots**
Profile unit settings - mg/dl:
![image](https://user-images.githubusercontent.com/2606788/73586481-7bf80100-4473-11ea-8ff8-9e55a0e006ae.png)

Client unit settings - mg/dL:
![image](https://user-images.githubusercontent.com/2606788/73586486-8adeb380-4473-11ea-9e25-419f85cfcabb.png)

Tooltip:
![image](https://user-images.githubusercontent.com/2606788/73586472-697dc780-4473-11ea-8bc4-8a205b19c457.png)

Treatement report:
![image](https://user-images.githubusercontent.com/2606788/73586583-f7a67d80-4474-11ea-93fd-bbd56e75d5ec.png)

**Your setup information**
- Nightscout 13.0.1
- CGM is Dexcom G5, data uploaded from xDrip+ on Android.
- Have tested on Firefox and Chrome on Windows 10, as well as Firefox on Android.

**Additional context**
I think the issue is lib/client/renderer.js,  appendTreatments.treatmentTooltip() function around line 635 when checking the client units vs the profile units.  I thought there might be a case-sensitivity issue (my settings are mg/dL, but the profile showed mg/dl), but doing a lowercase-only comparison did not fix it on my fork.

**Comment by jakobsandberg** [comment]
This issue was reported back in December (#5384) and a fix was already merged in via #5381. However, that fix has not been released yet (it's currently on the `dev` branch).

It should go out in the next release.

**Comment by dybs** [comment]
Ah, thanks, I didn't think to check dev

**Comment by pbudzon** [comment]
Can confirm this appeared for me today on latest master.
