### ISSUE TITLE
Ypsopump boluses shown in Nightscout

### ISSUE THREAD

**Issue by Arthur86000** [nightscout/cgm-remote-monitor#5536]
Hello everyone !
I've just set up Nightscout on my computer. I was wondering if there is any way to automatically show my boluses from my Ypsopump to Nightscout. I know that it can't be done directly from Nightscout since you can connect the Ypsopump only to the MyLife app. So maybe it is possible to sync MyLife with Nightscout or xDrip ?
Thanks in advance for your answers !

**Comment by unsoluble** [comment]
If you can get your data into xDrip, then it can get from there into Nightscout. I'd reach out to the [xDrip folks](https://gitter.im/jamorham/xDrip-plus) to see if Ypso support is on their radar.
