### ISSUE TITLE
Link to Nightscout API Incorrect in Read.me

### ISSUE THREAD

**Issue by jarothmd** [nightscout/cgm-remote-monitor#5550]
The Nightscout API documentation in the read.me file for cgm-remote monitor indicates that the Nightscout API  docs can be reached at 

https://YOUR-SITE.com/api-docs/

However this URL does not seem to return the docs.  The correct link on my nightscout site seems to be:

https://YOUR-SITE.com/api-docs.html

**Comment by StephenBrown2** [comment]
This is not accurate for my nightscout site (`api-docs/` is correct for me). How are you running yours, and are you up to date with the latest version?

**Comment by jarothmd** [comment]
Yes I am still at Ice Cream 0.11.1 so likely explanation.  Am closing the issue.
