### ISSUE TITLE
Possible to use Nighscout with Guardian Connect sensor without using Guardian CGM app on phone?

### ISSUE THREAD

**Issue by Riveon** [nightscout/cgm-remote-monitor#5551]
Hi,
I'm using (or attempting to use) the Medtronic Guardian Connect with the Guardian Sensor 3 - this is a standalone CGM that doesn't use the pump, just my phone. The official app (Guardian CGM) is incompatible with my Oneplus phone. Is it possible to use Nightscout with this CGM as an alternative? Or is it not possible to use Nightscout with this CGM without also having the official app receiving data on my phone?
Thanks.

**Comment by unsoluble** [comment]
Nightscout is really just an interface for your data; it doesn't deal with device connections directly. Might want to look into xDrip as an alternative receiver app — I'm not sure if it supports the standalone GC system, but it might?

**Comment by szantos** [comment]
It has already been addressed at NightscoutFoundation/xDrip, but nothing really done:
https://github.com/NightscoutFoundation/xDrip/issues/1113

Newer efforts tend to reach the data from the pump (770G/780G):
https://github.com/nightscout/cgm-remote-monitor/issues/6568

IMHO being able to process sensor readings should be a separate (and the first) step.
