### ISSUE TITLE
Reports not visible on Chrome browser

### ISSUE THREAD

**Issue by Propelld** [nightscout/cgm-remote-monitor#5557]
Attempting to see NS reports in chrome results in 'result is empty' message instead of a report. The same attempt in Safari and NS reports are generated normally.

1. Using Chrome browser go to 'reports'
2. Click on any type of report (i.e. 'Day-to-Day')
3. Pick a time range (i.e. 'last 2 weeks')
4. Click on 'Show'

Clicking on any type of report should generate the desired data according to what is selected and the time range.

![image](https://user-images.githubusercontent.com/45499352/75818539-0b404f00-5d67-11ea-870e-3825efd6b320.png)

- Nightscout 13.0.1
- Dexcom G5 and xDrip
- Appears to be specific to Chrome browser on desktop and mobile (tested on Android)

**Comment by unsoluble** [comment]
You have text in your "Notes contain" field, which is filtering your results to zero. (This field is often auto-filled by some browsers for some reason; need to make sure to manually clear it.)

**Comment by Propelld** [comment]
Yup, that solves it! I will look out for that in the future.
