### ISSUE TITLE
How Can I Access Nightscout Data Remotely?

### ISSUE THREAD

**Issue by mistrb01** [nightscout/cgm-remote-monitor#5560]
Nightscout is actually running fine.  I can't find any clear documentation on how to access the data remotely.  I see things for an API but don't understand.  If this is out of scope, please let me know.

What I would like to do is to create visualizations using Tableau Software on a mac.  I don't have access to a windows machine for this effort.  I also have limited programing skills.

Is there a way to connect to the Mongo DB?  Or is there a way to export data to a CSV or Excel file?

I saw some pages regarding exporting a CSV file directly from Dexcom, but I don't see those options on my iPhone.

**Comment by mbtzulu** [comment]
To show the api description take a look at https://meinwebsitename.azurewebsites.net/api-docs.html#/ (replace the domain by your own).

I guess for your idea it would be best to grab the data directly from mongodb. The information to connect you may take the Information of the mongodb connection string as configured in your Nightscout environment.
AFAIK, Tableau does not support mongodb access out of the box, you have to download a seperate driver. 

If you have some experiences with reading python code, maybe this give some ideas on how to access the data: https://kreuzundqwertz.wordpress.com/2019/11/29/python-cgm-dashboard/

I bookmarked these informatin to do the same like you, if there is some time for it in future, so I would be happy if you could share your experiences somehow.

**Comment by mistrb01** [comment]
I am using heroku.  I assume that there is similar documentation for it.

Unfortunately, I am not a programmer.  I can do almost anything else in IT
though.

**Comment by StephenBrown2** [comment]
Yes, the only difference will be if you deployed recently or not, as the path has changed to `/api-docs/`.
Whether your Nightscout is deployed on heroku or azure, you'll go to mynightscout.host.domain/api-docs/ or mynightscout.host.domain/api-docs.html

Unfortunately I don't have any Tableau knowledge myself.
