### ISSUE TITLE
Banner does not collapse when vertical height is too small

### ISSUE THREAD

**Issue by Nightfoxy** [nightscout/cgm-remote-monitor#5561]
**Describe the bug**
The top banner that contains the NS logo and action icons does not collapse when the vertical height shrinks to around 475px or less. This also impacts mobile browsers in horizontal orientation. this leaves a blank space at the top where the screen elements should be.

This issue appears to be unique for version 13. Sites on 12.x collapse properly.

**To Reproduce**
1. Go to 'Any NS site running 13.1+'
2. Shrink the vertical window size to less than 450px.
3. See the empty space on the top and the icons still on the top right.

**Expected behavior**
Like in version 12, the NS logo should disappear and the action buttons should receive a transparent background and allow the rest of the content to slide up to the top of the screen.

**Screenshots**
NS 13 with the issue
![image](https://user-images.githubusercontent.com/46848705/76132544-586f2b80-5fc8-11ea-9080-e5f2b5141cc8.png)

NS 12 working properly
![image](https://user-images.githubusercontent.com/46848705/76132552-60c76680-5fc8-11ea-8737-ba427977a996.png)

**Your setup information**
- What version of Nightscout? **Dev-13.1.0 as of 3/5/2020**
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? **No. Issue replicated on Windows Chrome 80, Windows Edge, and Android 10 Chrome**

**Additional context**
Issue was introduced with version 13.0. I was just hoping it would go away. I've tried clearing cache, temp files, using incognito, and multiple computers. I've also replicated this issue with other user's v.13 sites. 

It also makes v13 sites show up poorly in the new multi-site split view since that top real estate can't be used.
![image](https://user-images.githubusercontent.com/46848705/76132695-10043d80-5fc9-11ea-858f-b9739f11355d.png)

**Comment by sulkaharo** [comment]
Ping @Bartlomiejsz - the toolbar PR caused the conditional height change of the toolbar to break.

**Comment by sulkaharo** [comment]
Can you test https://github.com/nightscout/cgm-remote-monitor/pull/5562 - this should fix the behaviour

**Comment by Nightfoxy** [comment]
5562 fixes this issue but introduces another. If there are more than 3 icons in the top right toolbar, one wraps in the shorter height scenario I've described.
![image](https://user-images.githubusercontent.com/46848705/76157780-7e78f680-60c2-11ea-8520-4cd434b544a5.png)
![image](https://user-images.githubusercontent.com/46848705/76157781-89338b80-60c2-11ea-9067-54828e5f05d5.png)

**Comment by sulkaharo** [comment]
@Nightfoxy this should now be fixed in #5562, thanks!
