### ISSUE TITLE
need someone to help a parent setup nightScout

### ISSUE THREAD

**Issue by aimohaggag** [nightscout/cgm-remote-monitor#5618]
need someone from Canada Alberta to helpba friend of mine setup nightscout i did try helping her but configuration on herku and other it stuff are not easy for here, that's why she is looking for some one to help her in person , she has account here i will share that link with here if any one is intrested .. thank you all for the great work

**Comment by asmaa257** [comment]
Thanks Amr for sharing and for helping me a lot

**Comment by asmaa257** [comment]
Hi there, I tried setting Nightscout up, but stucked in the middle and couldn’t complete it anymore, so I need someone living in Edmonton, Alberta Canada to help me in person, even I have to pay for him. 
I really want to help my diabetic daughter, and will appreciate any help. 
  thanks in advance!

**Comment by JonathanFly** [comment]
I don't think someone in person for this. The heroku stuff can be done by anyone anywhere, and then you might need to use FaceTime or another video chat to help someone setup their physical device so it communicates with nightscout.

**Comment by haspden** [comment]
@asmaa257 you should be able to get help at CGM on the Cloud Facebook group. This should be used for issues and glitch reporting only. Please can you mark this issue as closed.

**Comment by bewest** [comment]
Howdy all, there is https://t1pal.com/ which offers a paid subscription based service for Nightscout.  They will ensure you get started with Nightscout.
