### ISSUE TITLE
ALEXA API - Cannot GET /api/v1/alexa

### ISSUE THREAD

**Issue by haspden** [nightscout/cgm-remote-monitor#5637]
On my site if I try to access my Alex API manually 
https://mynightscoutsite.herokuapp.com/api/v1/alexa 
I get the error
Cannot GET /api/v1/alexa
not in invalid argument, or request but cannot GET, which implies to me that the file/view does not exists or cannot be retreived ?

Is anybody else able to replicate this issue?

Rest of the site and functions work great and have done for several years now. 

Running latest master build of remote-cgm-monitor
Nightscout 13.0.1

Thanks

![Screenshot 2020-04-27 at 21 40 22](https://user-images.githubusercontent.com/4039041/80418807-df0cfe80-88cf-11ea-85f5-d7de7821d4b5.png)

**Comment by jakobsandberg** [comment]
Hi @haspden,

The `/api/v1/alexa` route is only configured to receive POST requests, not GET requests: https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/api/alexa/index.js#L44.

In your case, Chrome's address bar makes a GET request, and thus you get an error.

If you want to manually make a POST request, you can do that via `curl` in your teminal, e.g.

```
curl -d '{POST_DATA_HERE}' https://mynightscoutsite.herokuapp.com/api/v1/alexa
```
If you want to use the above script, be sure to replace `{POST_DATA_HERE}` with the POST data you want to send. You can read more about making these types of requests here: https://ec.haxx.se/http/http-post

**Comment by inventor96** [comment]
@haspden If you don't have any more questions on this issue, make sure to mark it as resolved.

**Comment by haspden** [comment]
Resokved
