### ISSUE TITLE
Wrong username when creating the app 

### ISSUE THREAD

**Issue by jensvandooren** [nightscout/cgm-remote-monitor#5639]
Hello everyone,

A few days ago I created a Nightscout app through the Heroku website. (https://github.com/SpikeApp/Spike/wiki/Spike-Follower-Mode) This is the guide I followed to create the app. I made a mistake when creating the app because I have the wrong username for Dexcom. Is there a way to fix this without having to create a second Nightscout app ?

Thanks in advance !

Jens

**Comment by StephenBrown2** [comment]
Yes, go to the heroku dashboard for your app: https://dashboard.heroku.com/apps/your-app-name-here
Then click the Settings tab:
<img width="578" alt="Screenshot 2020-04-28 at 11 31 47" src="https://user-images.githubusercontent.com/1148665/80518712-14533400-8944-11ea-88f9-1ee746635b3b.png">
Then scroll down to "Reveal Config":
<img width="589" alt="Screenshot 2020-04-28 at 11 31 53" src="https://user-images.githubusercontent.com/1148665/80518731-1cab6f00-8944-11ea-9c35-9bdd08bc735e.png">
Once you click that, you can see all the settings again. Change the appropriate one, then scroll back to the top and in the "More" menu button, click "Restart all Dynos":
<img width="247" alt="Screenshot 2020-04-28 at 11 34 16" src="https://user-images.githubusercontent.com/1148665/80518895-5d0aed00-8944-11ea-9117-0ab0efd4689b.png">
