### ISSUE TITLE
NS Profile on AAPS

### ISSUE THREAD

**Issue by qwerty1203** [nightscout/cgm-remote-monitor#5653]
HI there

Not sure if this is the right place for my question as a beginner? My NS profile online is how I edit my ISF, basal etc...... Today for the first time I noticed when I change my profile online and then go to my phone and AAPS the change isn't reflected on my phone so I can't therefore "activate" my new profile because it hasn't been changed. So there is something interfering with the info from NS getting to my AAPS on my phone. Wifi is all good and Ive allowed info under pref: to come from NS rather than upload only? Any ideas what's wrong? Thank you

**Comment by StephenBrown2** [comment]
From the docs: https://androidaps.readthedocs.io/en/latest/EN/Usage/Profiles.html

> On starting your AndroidAPS and selecting your profile, you will need to do a “Profile switch” event with zero duration (explained later). By doing this AAPS starts tracking history of profiles and every new profile change requires another “Profile switch” even when you change content of the profile in NS. Updated profile is pushed to AAPS immediately, but you need to switch the same profile again (in NS or AAPS) to start using these changes.
> 
> Internally AAPS creates snapshot of profile with start date and duration and is using it within selected period. Duration of zero means infinite. Such profile is valid until new “Profile switch”.

So you will need to "Profile Switch" to the same profile any time you update it in Nightscout to see the changes in AAPS.
