### ISSUE TITLE
I can get plugin values like COB, BWP, CAGE, BASAL, IOB From API?

### ISSUE THREAD

**Issue by madeinnordeste** [nightscout/cgm-remote-monitor#5654]
``
Im putting my Nigthscout values from API in my computer pannel with XFCE. I whould like know if its possible get data form plugins values like COB, BWP, CAGE, BASAL, IOB from API too?

![screenshot](https://i.imgur.com/le0IwDV.png)

I search but don know nothing about.

Thanks

**Comment by jakobsandberg** [comment]
These values are considered "plugins", and they're all exposed on the properties endpoint, e.g. https://mysite.herokuapp.com/api/v2/properties.

You can also make requests for specific plugins by extending the endpoint to include the plugin name(s):
- https://mysite.herokuapp.com/api/v2/properties/iob will return strictly the iob
- https://mysite.herokuapp.com/api/v2/properties/cob,bwp,cage,basal,iob will return strictly the five values you've listed

This will only work if these values are listed in the Heroku Config Var `ENABLE`

<img width="783" alt="Screen Shot 2020-05-10 at 11 54 10 PM" src="https://user-images.githubusercontent.com/15298645/81532639-9155b480-9319-11ea-843d-6752a7691881.png">

To expose the five values you've listed, you'd need at least the following values in your `ENABLE` string: `careportal basal bwp iob cob cage` (note: `careportal` is needed for these plugins to work).

**Comment by madeinnordeste** [comment]
thanks a lot for information!!
I will try use this data now!

**Comment by szantos** [comment]
> 
@jakobsandberg 
Is there a way to get historical data?

**Comment by sulkaharo** [comment]
Historic data for plugins is not available as the data from the v2 API is the real time in-memory state of the plugins

**Comment by szantos** [comment]
@sulkaharo 
Thanks! It must not be v2. Any other API maybe?
(I've already read the documentations and found nothing.)

**Comment by szantos** [comment]
In "api/v1/devicestatus.json" under "openaps" you can find historical IOB and COB

**Comment by sdolenc** [comment]
@madeinnordeste , I'd love to install that XFCE plugin you built

**Comment by madeinnordeste** [comment]
> I'd love to install that XFCE plugin you built. (if it's quick and easy to share)

@sdolenc sorry about time,

yes its easy,

its is a simple php script, bu now i use gnome, but works on two enviroment, iguess.

In gnome i use executor plugin to show script response on taskbar.

No xfce i guess the name is "run command"

using docker my command is like this:

cd ~/Dropbox/Scripts/Nightscout && docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest php monitor-aimi.php --ignore-platform-reqs

the script is shared on:
https://github.com/madeinnordeste/php-nitghtscout-current-data

if you have doubts, you can talk to me, im try help.
