### ISSUE TITLE
413 error [Payload Too Large] when saving profile 

### ISSUE THREAD

**Issue by hartlijn** [nightscout/cgm-remote-monitor#5673]
Using a circadian profile I want to add hourly values not only for basal rates, but for ISF and IC as well. I notice that saving such a profile hits some kind of limit of line that can be saved in a profile.

**To Reproduce**
1. Create a profile with 1 BG target range
2. Add 24 hourly basal rates
3. Add 24 hourly IC ratios
4. Add 24 hourly ISF ratios --> error 413 error Payload Too Large.
When you remove a few; the profile can be saved succesfully.
It turns out that the save command, saves not only the current profile, but gives in the API also all other profiles under the same 'Valid from' record. All together it hits a limit.

> 413 PayloadTooLargeError: too many parameters
   at queryparse (/app/node_modules/body-parser/lib/types/urlencoded.js:151:13)
   at parse (/app/node_modules/body-parser/lib/types/urlencoded.js:75:9)
   at /app/node_modules/body-parser/lib/read.js:121:18
   at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
   at done (/app/node_modules/raw-body/index.js:213:7)
   at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
   at IncomingMessage.emit (events.js:203:15)
   at endReadableNT (_stream_readable.js:1143:12)
   at process._tickCallback (internal/process/next_tick.js:63:19)

**Workaround**
Move unnecessary prolfiles to other databaserecord 'Valid from'

Nightscout version 13.0.1
Added a recording of what I did.
[profile_error.zip](https://github.com/nightscout/cgm-remote-monitor/files/4677119/profile_error.zip)

**Comment by mtfoley** [comment]
My guess would be that this is dealing with PUT request encoding.  I think by default $.ajax serializes javascript objects like this into query string parameters, and sends to the server with content-type of `application/x-www-form-encoded`.  In turn, I think the Express web server limits request bodies of this format to [1000 parameters](https://expressjs.com/en/5x/api.html#express.urlencoded)

One solution here may be to change the content-type on the payload to application/json. I'll submit a PR.

**Comment by mtfoley** [comment]
See PR #5704

**Comment by hartlijn** [comment]
thanks @mtfoley  - i copied your changes into my master and problem is solved.
