### ISSUE TITLE
Old CGM battery data displayed 

### ISSUE THREAD

**Issue by jmarler** [nightscout/cgm-remote-monitor#570]
Issue description: 
When users switch from uploading using the android uploader to using Share2NS bridge, battery data for the CGM is no longer uploaded. However, the NS web site still shows a battery value that uses the last battery value sent before the switch. The manual workaround is to purge all battery data. 

Expected behavior:
The NS web UI should either: 
* Have an environment variable/config option to toggle the display of the battery data and icon
* Recognize that the battery data is older than the last valid data point, and after a certain delta has been reached, either suppress showing the battery icon completely, or indicate that the data is no longer available in some fashion. 

Recreation steps:
* Upload data using NS uploader on Android (including CGM battery data)
* Switch to using Share2NS bridge
* Observe that battery data never changes from last reported value

**Comment by jasoncalabrese** [comment]
There are a couple of tricks to solve this, add a new mongo document with `{uploaderBattery: false}`, delete your `devicestatus` data, and I think newer versions of the bridge even do something with this.

**Comment by jasoncalabrese** [comment]
See https://github.com/bewest/share2nightscout-bridge/issues/10
