### ISSUE TITLE
Add Loop Carbs foodType, absorptionTime to Reports

### ISSUE THREAD

**Issue by kskandispersonal** [nightscout/cgm-remote-monitor#5701]
**Is your feature request related to a problem? Please describe.**
I'd like to view carb food type and absorption time in Reports similar to how Loop displays them on the ICE page.  It helps understand how carbs are absorbed and whether appropriate insulin was injected for the carbs.

**Describe the solution you'd like**
I'd like to see carbs foodType and absorptionTime to DayToDay and Treatments Reports.  These values are entered by Loop users when entering their carbs, and these values are already stored in MLab.  They are also already used in NS on the Home page graph.

**Describe alternatives you've considered**
Alternative is for user to manually re-enter these values in Notes in NS.

**Additional context**
### MLab data:
![image](https://user-images.githubusercontent.com/16564065/84707131-260c8d00-af2c-11ea-80ed-b9d42d9163dd.png)

### Loop ICE page:
![image](https://user-images.githubusercontent.com/16564065/84707233-59e7b280-af2c-11ea-9051-7e82e7b341cb.png)

### NS Main home page graph:
![image](https://user-images.githubusercontent.com/16564065/84707509-d2e70a00-af2c-11ea-9c78-1afd7397987a.png)

### Adding these values to NS Reports could look like the following as implemented in PR #5702

DayToDay:
![image](https://user-images.githubusercontent.com/16564065/84707679-20fc0d80-af2d-11ea-8ced-9a7ab47e2aa9.png)

Treatments:
![image](https://user-images.githubusercontent.com/16564065/84707805-5c96d780-af2d-11ea-93ff-2e7a1ba9615a.png)

![image](https://user-images.githubusercontent.com/16564065/84707724-3a9d5500-af2d-11ea-885b-34d010046ecc.png)

**Comment by sulkaharo** [comment]
PR merged
