### ISSUE TITLE
Heroku mLab shutdown

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/cgm-remote-monitor#5744]
Is any alternative to use with Heroku?

![Screenshot_2020-07-10-19-22-41-48](https://user-images.githubusercontent.com/608650/87186263-1aba4080-c2e3-11ea-83c8-595d5dcaa132.jpg)

**Comment by timmy354321** [comment]
I also received this :(

**Comment by ronrosenbaum** [comment]
Same here.  I can use Azure and have credits there, but would prefer to keep using Heroku.  There is still some time to come up with an alternative, but not much.

**Comment by ronrosenbaum** [comment]
Couldn't we just create a new database in Mongolab (free) and change the settings in Heroku to point to the external database?  We'd lose some old data but it should continue to work ok.

**Comment by Fronix** [comment]
mLab has migrated to Atlas cloud, they have a free tier on the new cloud system which they also created a free migration tool to migrate all your data. Follow the link provided in the email or click [here](https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/) and you can migrate all your data to Altas. 

You will have to manually update the database connections but that is pretty straight forward since you have to do it for nightscout aswell.

**Comment by StephenBrown2** [comment]
I just did the migration and the instructions said that the config var would be deleted, not updated. However, I grabbed the connection string for the new location during the process and updated it, and everything went swimmingly well.
The new DB string for an Atlas DB will look like: `mongodb+srv://{username}:{password}@{instance}.{something}.mongodb.net/{database}`

**Comment by Fronix** [comment]
> I just did the migration and the instructions said that the config var would be deleted, not updated. However, I grabbed the connection string for the new location during the process and updated it, and everything went swimmingly well.
> The new DB string for an Atlas DB will look like: `mongodb+srv://{username}:{password}@{instance}.{something}.mongodb.net/{database}`

Yes this was a very smooth transition, had no problems at all. I don't know how hard it will be for new users tho that haven't got the old database to migrate.

**Comment by sulkaharo** [comment]
The migration instructions are here: https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/

**Comment by UphwbKpqSm47z3qewH9x** [comment]
I wasn't as successful with migration as others. I've triple checked MONGO_CONNECTION config var in Heroku. 

My paper trail has:
`Jul 11 06:34:50 fizburn app/web.1: Setting up new connection to MongoDB
Jul 11 06:34:50 fizburn app/web.1: (node:4) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Jul 11 06:34:50 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 3 sec
Jul 11 06:34:54 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 6 sec
Jul 11 06:35:00 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 9 sec
Jul 11 06:35:09 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 12 sec
Jul 11 06:35:21 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 15 sec
Jul 11 06:35:36 fizburn app/web.1: Error connecting to MongoDB: {"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]} - retrying in 18 sec
Jul 11 06:35:48 fizburn heroku/web.1: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Jul 11 06:35:48 fizburn heroku/web.1: Stopping process with SIGKILL
Jul 11 06:35:48 fizburn heroku/web.1: Process exited with status 137
Jul 11 06:35:48 fizburn heroku/web.1: State changed from starting to crashed`

**Comment by StephenBrown2** [comment]
The var I modified was `MONGODB_URI`. Do you have that one?

**Comment by UphwbKpqSm47z3qewH9x** [comment]
No luck, I added the MONGODB_URI back and getting the same errors in papertrail.

The Atlas instructions said the following, that's why I had added the MONGO_CONNECTION var

> What if I am using Nightscout with an mLab Heroku add-on?
> 
> You only need to perform Step 1 above, and you can skip Steps 2 and 3:
> 
> Copy and paste the value of the existing config var into a brand-new config var called “MONGO_CONNECTION”
> The existing config var that was automatically provisioned should look like “MONGODB_URI” or “MONGOLAB_URI” or “MONGOLAB_<color>_URI”.
> This is because the Nightscout app already looks for a config var called “MONGO_CONNECTION”.

**Comment by sulkaharo** [comment]
https://github.com/nightscout/cgm-remote-monitor/wiki/mLab-discontinuation-FAQ

**Comment by nevenduranec** [comment]
So you need to create a new config var on heroku that will be named `MONGO_CONNECTION` with the value of `mongodb+srv://<username>:<password>@....`. You will get this on the last step of migration.

Replace`<username>` and `<password>` from your old `MONGODB_URI` config var. 

Maybe this will help someone.

**Comment by andrew-dixon** [comment]
Observations from performing the migration that might help others:

1) When you create the Atlas account, it will take you to a page to create a new project, ignore this and don't do it, as when you come to the migration part, it will then try and create another one and will not be able to, as you can only have one free "cluster" on the account and it will already have one.

2) You need to connect your Altas account to your mLab account, which there is a simple way to do in the Atlas interface, however, you need to login to your mLab account, which of course, you have no login details for. So, before you do this step, go to the Heroku interface, go to the "Resources" tab and click on the "mLab MongoDB" link which will open mLab and automatically log you in. You can then proceed with the next step in the Atlas interface and it will not ask you to log in.

3) You need to stop the Nightscout project in Heroku before you perform the migration to ensure no data is written during the migration. It took me a minute to work out how to do this. In the Heroku interface, go to "Resources" and then to the right of "web node server.js" click the pencil icon to edit and then you can click the toggle switch to turn it "off" and then click "Confirm". After you have completed the migration, you do the opposite to turn it back on.

4) The environment variable for the Mongo DB connection has changed from MONGODB_URI to MONGO_CONNECTION, so you need to delete the MONGODB_URI and add a new one called MONGO_CONNECTION, however, before you delete the MONGODB_URI, make a note of its value as you need the username and password from it to use in the new value given to you by Atlas. The username and password is the part after mongodb:// and before the @ and is separated with a colon ( : ).

**Comment by Fronix** [comment]
> 3. You need to stop the Nightscout project in Heroku before you perform the migration to ensure no data is written during the migration. It took me a minute to work out how to do this. In the Heroku interface, go to "Resources" and then to the right of "web node server.js" click the pencil icon to edit and then you can click the toggle switch to turn it "off" and then click "Confirm". After you have completed the migration, you do the opposite to turn it back on.

You can also just put your project in maintenance mode under Settings -> Maintenance Mode, this prevents any data from being written during the migration.

**Comment by bartsluimer** [comment]
Assume a better manual is required for a lot of people. For example I had a . (Dot) inside username. You can not migrate. Needed to change in Mlab first.

Believe the database size option from Nightscout is broken after migration.

**Comment by mboterma670G** [comment]
The manual is doing it job, however it costed me some time to get the uploader working again. For some reason the new mongo url acted strange. Pogman provided me with a better document that provides more details on some cryptic steps. https://docs.google.com/document/d/1gV7dFeipTI3Fas246N10iAxQC8gETV5PIVfL31AYu_c/edit#heading=h.2xm1e0u2gzdc

When all was back up and running again, I've decided to move away from third party vendors, as I don't know what their future steps will be. So I've moved everything to a 5 euro p/m VPS at Strato. With the use of dockers the installation is pretty straight forward and removes all restrictions.  
If there is enough interest i can document all steps needed to get Nightscout running. You need to have some knowledge on plesk to setup the server. But this is documented by Strato.

**Comment by drspike** [comment]
I started the migration and was mostly done and trying to confirm the settings were correct. When going to my nightscout page it asked for my API_SECRET which I put in exactly as it said but it is not working. I also lost my mLab database because I had disconnected from mLab in Heroku during this process. 

I guess the real question is I probably should just rebuild Nightscout fresh but if I were to do that today with Heroku would it not work since mLab is not allowing any new mLab accounts to be created? Should I just wait for the Nightscout build to be update to use MongoDB Atlas?

**Comment by UphwbKpqSm47z3qewH9x** [comment]
Since I couldn't get my migration to work, I just deployed my github
Nightscout branch to a new heroku app and it worked just fine a few weeks
ago. Lost some historical data but that's not a big deal for my use case
(mainly data on my Garmin and occasional reporting).

**Comment by drspike** [comment]
> Since I couldn't get my migration to work, I just deployed my github Nightscout branch to a new heroku app and it worked just fine a few weeks ago. Lost some historical data but that's not a big deal for my use case (mainly data on my Garmin and occasional reporting).
> […](#)

That's probably what I will end up doing but will I have to transition to Atlas again or has Nightscout been updated to use Atlas at this time?

**Comment by UphwbKpqSm47z3qewH9x** [comment]
The master release 13.0.1 from Dec 2019 is what I redeployed, and it still
points to mlab of course.

**Comment by mboterma670G** [comment]
Just make sure that the connection string is correct. It should looklike this.
MONGO_CONNECTION mongodb+srv://<user>:<password>@<user>.nxvlh.mongodb.net/<user>?retryWrites=true&w=majority

so with some fake information:
<user> = heroku_blabla
<password> = whatever
mongodb+srv://heroku_blabla:whatever@heroku_blabla.nxvlh.mongodb.net/heroku_blabla?retryWrites=true&w=majority

You can test your connection string, by downloading [MongoDB Compass:] (https://www.mongodb.com/try/download/compass)

**Comment by drspike** [comment]
> Just make sure that the connection string is correct. It should look like this.
> mongodb+srv://account_name:[password@account_name.nxvlh.mongodb.net](mailto:password@account_name.nxvlh.mongodb.net)/account_name?retryWrites=true&w=majority
> 
> so with some fake information:
> account_name = heroku_blabla
> password = whatever
> mongodb+srv://heroku_blabla:[whatever@heroku_blabla.nxvlh.mongodb.net](mailto:whatever@heroku_blabla.nxvlh.mongodb.net)/heroku_blabla?retryWrites=true&w=majority
> 
> You can test your connection string, by downloading MongoDB Compass: https://www.mongodb.com/try/download/compass
> When you are able to connect, use this string in MONGO_CONNECTION at Heroku.
> Or even use MongoDB to extract the data from the new created DB, so you can import it on your 2nd try.

Thank you, the compass helped but it reports connected refused so I must have the wrong password for the database despite copying the password over.

**Comment by mboterma670G** [comment]
Can you try with this added: ?authMode=scram-sha1

so the string becomes: mongodb+srv://heroku_blabla:whatever@heroku_blabla.nxvlh.mongodb.net/heroku_blabla?retryWrites=true&w=majority?authMode=scram-sha1

**Comment by drspike** [comment]
> Can you try with this added: ?authMode=scram-sha1
> 
> so the string becomes: mongodb+srv://heroku_blabla:[whatever@heroku_blabla.nxvlh.mongodb.net](mailto:whatever@heroku_blabla.nxvlh.mongodb.net)/heroku_blabla?retryWrites=true&w=majority?authMode=scram-sha1
> 
> just make sure this part refer to your installation "nxvlh.mongodb.net"
> 
> even this part alone should do the trick: mongodb+srv://heroku_blabla:[whatever@heroku_blabla.nxvlh.mongodb.net](mailto:whatever@heroku_blabla.nxvlh.mongodb.net).
> So it might me indeed, that you made an error recording the password. Are you still able to logon to the atlas webpage?
> From there you can copy the connection string, via clusters -> connect.
> And via Network Access, set the IP to 0.0.0.0 to rule out any issues. once connected you can setup the security.

Thank you, so I decided to do a clean deployment from Github with Heroku and it allowed a new mLab database. I went through the migration again and everything worked fine. I realized the mLab database that I had a password for was from the first time I started Nightscout 5 years ago but it was not the most recent database, so when I logged into mLab during the early part of the migration it was on an old database and not the most recent one created by Heroku. Hopefully this error might help with the migration guide writeup for Nightscout. Sorry to hijack the thread.

**Comment by mboterma670G** [comment]
Good to hear everything worked out.

**Comment by plmarcelo** [comment]
For me only few entries were migrated. Had to migrate all entries manually. Did it happened to any of you?

**Comment by gitanO0** [comment]
> For me only few entries were migrated. Had to migrate all entries manually. Did it happened to any of you?

I'm only seeing new entries in nightscout and none of the migrated data.  I checked the mongodb and it looks like verything did migrate.  Not sure why nightscout isn't showing that migrated data.

**Comment by plmarcelo** [comment]
I had 600 documents on entries collection in the new instance and more than 124000 in the old one. 

With the help of MongoDB Compass(https://www.mongodb.com/try/download/compass) exported all documents from the old instance and imported them in the new one. Now all data is ok.

**Comment by Menno86** [comment]
> The manual is doing it job, however it costed me some time to get the uploader working again. For some reason the new mongo url acted strange. Pogman provided me with a better document that provides more details on some cryptic steps. https://docs.google.com/document/d/1gV7dFeipTI3Fas246N10iAxQC8gETV5PIVfL31AYu_c/edit#heading=h.2xm1e0u2gzdc
> 
> When all was back up and running again, I've decided to move away from third party vendors, as I don't know what their future steps will be. So I've moved everything to a 5 euro p/m VPS at Strato. With the use of dockers the installation is pretty straight forward and removes all restrictions.
> If there is enough interest i can document all steps needed to get Nightscout running. You need to have some knowledge on plesk to setup the server. But this is documented by Strato.

I would love to run it in Docker,  but I would need a guide for dummies. This way I could run Nightscout on my Synology in an independent environment with unlimited database size. If you would be so kind to write a guide (of film and post on YouTube) I think a lot of people will be grateful.

**Comment by Menno86** [comment]
I messed up and my Nightscout was not working at all. I had no hope anymore so I started over. 

What I did? 

1. I followed the normal install (for my Spike version [click](https://github.com/SpikeApp/Spike/wiki/Spike-Follower-Mode)). So I had a fresh Nightscout. 
2. After that I followed the Youtube migration tutorial ([click](https://www.youtube.com/watch?v=cLh_k1ugoKI)). Now it works again

Perhaps this helps someone

**Comment by akung0324** [comment]
mLab has published a targeted guide at https://docs.mlab.com/how-to-migrate-nightscout-sandbox-heroku-addons-to-atlas/.

There's also a link to a demo video at the top of the guide (and at https://docs.mlab.com/mlab-to-atlas-demo-videos/).

**Comment by mboterma670G** [comment]
> Synology

I am not familiar with Synology's DSM. But it seems docker is already ported for Synlogy.
https://www.synology.com/en-global/dsm/packages/Docker

**Comment by DavidB766** [comment]
I had the same issue as others above. I then downloaded Compass (as per mboterma670G advice) and discovered that when I did the cut and paste of the password it had inserted an extra space. When I deleted the extra space, it all worked brilliantly including my api secret.  I also found this video, by mLab, very helpful!!!

https://drive.google.com/file/d/1N3oDq9UktpiEWWjy3qHhr83qM_60apwz/view

**Comment by parapenT1sta** [comment]
Tutorials
In English: https://drive.google.com/file/d/16okYG3kkSFM1TOqRVsaCibLv4sl3Gxtp/view?usp=sharing
In Portuguese: https://drive.google.com/file/d/1ItJG5JZzNSJ36zVTSpORLp5x9XSk0fl_/view?usp=sharing

**Comment by TheWizardsHub** [comment]
> The migration instructions are here: https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/

Please note that mLab has created a guide specifically for Nightscout users. I tested it myself and it was a very smooth migration.

**Please find the guide here:**
[https://docs.mlab.com/how-to-migrate-nightscout-sandbox-heroku-addons-to-atlas/](url)

**Comment by UberQueiroz** [comment]
> Tutorials
> In English: https://drive.google.com/file/d/16okYG3kkSFM1TOqRVsaCibLv4sl3Gxtp/view?usp=sharing
> In Portuguese: https://drive.google.com/file/d/1ItJG5JZzNSJ36zVTSpORLp5x9XSk0fl_/view?usp=sharing

Obrigado pela versão em português!!

**Comment by akung0324** [comment]
These links are more up-to-date:

* Documentation - https://docs.mlab.com/how-to-migrate-nightscout-sandbox-heroku-addons-to-atlas/
* Demo video - https://docs.mlab.com/mlab-to-atlas-nightscout-demo-video/

**Comment by victoreekhof** [comment]
Is there a tutorial somewhere for new users? I just signed up today and can't continue the "deploy to Heroku" process as I get the error:

`There was an issue setting up your app environment.`
`Couldn't find either the add-on service or the add-on plan of "mongolab:sandbox".`

I'm comfortable in making manual changes in my forked repo if needed :-)

**Comment by veryfancy** [comment]
Just in case it helps someone who, like me, does all this and then sees a bunch of `Error connecting to MongoDB` in their logs... a troubleshooting tip: look at your connection string and verify there's only one `@` in it. 🤦

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by beetusreader** [comment]
Can anyone help me set up nightscout so I can track on my farmin watch. I have no idea what Mongodb is

**Comment by StephenBrown2** [comment]
@victoreekhof @beetusreader Follow the guide here: https://nightscout.github.io/nightscout/new_user/ It has been updated for Atlas.

**Comment by AaronChaimDavid** [comment]
Hi all,
I've just rebuilt my nightscout app using Atlas. All works fine on my PC, laptop and smartphone. I have an issue with the NS on my smartwatch which I use for monitoring while at work. I have a Ticwatch E2, use the 'Free Browser for Wear OS' by Corproxy. I enter the Nightscout URL as the homepage and previously it was fine, showed me the BG level and basic info I needed. After this Atlas change, it doesn't settle. It tries to refresh every few seconds, so all I can see is that Owl face Nighscout logo which always comes up when it is loading, instead of being able to see the BG level numbers.
Can anyone help, please?

**Comment by sulkaharo** [comment]
@AaronChaimDavid Please contact the developer of the watchface.

**Comment by AaronChaimDavid** [comment]
@sulkaharo Thank you. Just to be clear it isn't the watchface causing trouble. It's the browser. My question is, is there anything in the way Atlas works vis a vis the way MongoDB worked, that causes Nightscout to auto refresh (on a Wear OS device) every few seconds, and if there is, is there any way to avoid this problem.

**Comment by andrew-dixon** [comment]
@AaronChaimDavid Atlas is just the name for the hosted version of MongoDB, so there would be nothing in Atlas that would be different to mLab, they are both just hosted versions of MongoDB. As the issue is with the interface, not the DB, it will be related to either a Nightscout update or an update to the Free Browser for Wear OS I would guess.

**Comment by AaronChaimDavid** [comment]
Thanks. So now the question is, is there anything that has changed in the latest version of Nightscout that would cause this reaction?

**Comment by cgeisel** [comment]
Has anyone followed the guide using Loopkit v2.0? In the prerequisites [here](https://docs.mlab.com/how-to-migrate-nightscout-sandbox-heroku-addons-to-atlas/#migration-prereqs) it suggests using the latest released version or a development branch, but the laptop where I do my builds is currently not available, so I'm considering sticking with v2.0.

I'm wondering how risky this is--shouldn't actually affect anything, since v2.0 worked fine with NS in the past, and the datastore isn't something that loop accesses directly AFAIK.

**Comment by cgeisel** [comment]
Update: I decided to risk it and had no issues with my version of Loopkit v2.0. The Guide makes this very, very straightforward.
