### ISSUE TITLE
NightScout Windows 10 App - Changing 'config vars' for BG_TARGET breaks the graph?

### ISSUE THREAD

**Issue by BloodVyper** [nightscout/cgm-remote-monitor#5764]
I am using the NightScout UWP app to monitor my BG levels on my Windows 10 PC.

When changing the 'config vars' in Heroku (eg BG_TARGET_LOW set to 7), I restart dynos, load the app, and the target lines on the graph disappear. [https://imgur.com/a/Jztv0ZX](url)

My DISPLAY_UNITS is set to mmol/L (I thought it may be defaulting to mg/dl, so I chose this as it forces universal mmol/L usage). Still no luck.

Is the UWP app still supported? If not, are there alternatives to have a desktop application for viewing my readings?

**Comment by sulkaharo** [comment]
AFAIK most people just use a browser to view Nightscout while on desktop - there's no need for an app (even on mobile). The UWP app is by some third party dev, I have no idea if that's being actively supported at this point.

**Comment by unsoluble** [comment]
Also the ability to parse target values as mmol was only added in v13 — won't work as expected if your install is older.

**Comment by BloodVyper** [comment]
I think I'll follow your advice and just pin a tab in Chrome.

The desktop app is convenient and all, but it does seem to be outdated.

Thanks again!
