### ISSUE TITLE
Upgrading Helmet to the next major version

### ISSUE THREAD

**Issue by EvanHahn** [nightscout/cgm-remote-monitor#5788]
I'm the maintainer of Helmet. I plan to release the next major version this Sunday, 2020-08-22.

Is there anything I can do to help get this project upgraded to `helmet@4`?

If you'd like to try out the release candidate now, you can install it with `npm install helmet@next`. If you'd rather discuss things outside of this issue, feel free to [reach out to me](https://evanhahn.com/contact) another way.

Hope I can be helpful!

**Comment by sulkaharo** [comment]
Hi! Apologies for the delay. Sure - do you see potential issues in migrating to the next version?

**Comment by EvanHahn** [comment]
The most significant changes are in the [Helmet 4 upgrade guide](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide). Keep an eye out for the fact that there's now a default Content Security Policy.
