### ISSUE TITLE
Current Dev: Dexcom Bridge not working  (NS Dev as of 2020-07-27)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#5795]
**Describe the bug**
Current Dev: Dexcom Bridge not working  (NS Dev as of 2020-07-27).

**To Reproduce**

Loop: CGM upload readings OFF (Dexcom G6)

NS Heroku Config Vars for Dexcom Bridge as specified here: 
http://www.nightscout.info/wiki/welcome/set-up-nightscout-using-heroku

Nightscout Dev as of 2020-07-27  deployed on Heroku.

Result: No CGM data

Deployed reverted NS-Dev repository as of end of June 2020: CGM from G6 loads from Dexcom Share (Bridge).

Possibly some problem with Bridge introduced in recent Dev?

**Comment by unsoluble** [comment]
Reproduced here.

**Comment by bjornoleh** [comment]
Great, thanks. Did you notice this? Seems like @rosseland may have identified the problem?


https://github.com/nightscout/share2nightscout-bridge/commit/7e2309167c3de3472e4607dade99a04d683fdca3#commitcomment-41270370

**Comment by mboterma670G** [comment]
not sure as https://shareous2.dexcom.com/ is now unavailable and https://shareous1.dexcom.com/ (34.95.100.242) is.

**Comment by bjornoleh** [comment]
Yes, that appears to be the issue. NS should point to the latter. Please
note that this is an issue for non-US users only. Which is probably why it
has not been caught until now?

Shareous is probably ShareOutside of US



man. 17. aug. 2020, 13:31 skrev mboterma670G <notifications@github.com>:

**Comment by unsoluble** [comment]
Maybe @bewest could chime in on why he made the change.

**Comment by bjornoleh** [comment]
For the impatient ones ("not waiting" :-) )

Edit line 111 in package.json of your own repository (dev):
Original:   "share2nightscout-bridge": "^0.2.2",	  

Fix:   "share2nightscout-bridge": "0.2.1",

**Comment by bjornoleh** [comment]
Suppose this commit closes the issue

https://github.com/nightscout/cgm-remote-monitor/commit/26ebdbd9a7e13a8ac559f945e07de93dbc6a4610
