### ISSUE TITLE
NS Dev as of today 2020-08-19 is broken

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#5846]
Deploying Dev as of today broke my NS-site, please see picture below. Also the Reports section was affected. I had to revert to a previously functioning Dev build to keep the site operational, but may be able to document better at a later time.

Reverting fixed the issue after doing a [Ctrl]+[F5] to reload (win10/Chrome).

![image](https://user-images.githubusercontent.com/63544115/90624865-efe3d600-e218-11ea-8dc0-aae4cc26aeb7.png)

Please let me know if there are better ways to reference the state of the Dev branch, besides referring to the date and time I encountered this issue. I am aware of commit IDs, but there are more than one commit in the last few hours.

NS Dev as of today 2020-08-19 (approximately 10 UTC).

**Comment by bjornoleh** [comment]
It's related to one of the commits during the last two days, as this issue was not found before these appeared.

![image](https://user-images.githubusercontent.com/63544115/90625846-78af4180-e21a-11ea-8891-8247b3d5d1ab.png)

**Comment by sulkaharo** [comment]
That just simply looks like the loading of CSS failed initially / your browser used old client files until you did a full reload. Chrome is for some reason especially persistent in caching files in some occasions; this doesn't look like a bug.

**Comment by bjornoleh** [comment]
Thanks. That's possible. The previous working versions have been Dev from June and July. 

It was the same on Android Chrome. I had to di cashe clean in settings to get it back to working order after reverting. On PC Chrome ctrl + F5 was enough.

I will try again later. What's the best way to clear cache on pc Chrome? Settings/privacy? Or some other trick?

**Comment by sulkaharo** [comment]
If you figure out how to consistently clear the cache, please let me know! 😅 The Clear Browsing Data menu seems to work most of the time, but not always.

**Comment by bjornoleh** [comment]
Will do :-)

I tried again, same results. I tried all the ways I could think of for deleting cashe and browser history. No luck. I also tried with the Edge browser, same result there as well, also after clearing cache... And I haven't even used this browser with NS, as far as I can remember.

Could I have corrupted the Dev branch in my repository? I pulled the NS Dev changes into my repo as usual, dont think I messed anything up.

**Comment by bjornoleh** [comment]
I tried again, created a new branch in my repo based on Master. Pulled changes from current Dev, and deployed to Heroku. And again, same result.

I also checked NS in Safari on an old iPhone SE. Same result here. I then removed cache from Safari, same result still.

![20200819_170919](https://user-images.githubusercontent.com/63544115/90652853-ce95e080-e23e-11ea-9c7a-a01e783775c9.jpg)

Reverting to the previously working Dev was ok after clearing cache.

I will have to give up on this for now. If no-one can reproduce this, I would be happy if someone can tell me what I am doing wrong.

Thanks!

**Comment by sulkaharo** [comment]
Can you check the JavaScript console on an affected browser / web dev tools to see what's going on? This basically looks like the CSS is not loading (or is wrong).

**Comment by bjornoleh** [comment]
Ok, I will try later. Do I find this console in Chrome? I havent looked into this before, so appreciate any hints about what to look for.

**Comment by bjornoleh** [comment]
Ok, I have poked around in the developer tools in Chrome a bit. Is this the JS console you were suggesting?

Here is a screenshot from our two NS-sites, side by side. The one on the left is the broken one. On the right is a previous Dev build.

There are some error messages on the broken site, do they convey anything meaningful?

And please let me know if I am revealing anything from our NS-sites here that should not be in the public domain.

Thanks!


![image](https://user-images.githubusercontent.com/63544115/90685666-71178900-e26a-11ea-9df4-72d162d219a2.png)

**Comment by vytux-com** [comment]
I have the same issue and would have to guess it's to do with helmet upgrade as one of its functions is setting the CSP header options

**Comment by sulkaharo** [comment]
Right, checking! Wonder why this is working for me. 🤔

**Comment by vytux-com** [comment]
Try CTRL-F5 on your browser.... 
Mine was working too until I tried reports (had not tried those for a while and notice they were broken) then did the above on my site and it broke too...

**Comment by sulkaharo** [comment]
We've always defined our custom CSP and this was unchanged with the Helmet upgrade, so the CSP changes in Helmet should not affect Nightscout. I re-deployed DEV and got a strange result, where Chrome initially loaded the site as per screenshots above and reported CSP violation, but on reloading the site the CSP violations disappeared and the site now loads fine (with the expected CSP). However on Safari, the web socket opening is now blocked. Investigating.

**Comment by cascer1** [comment]
I am experiencing this issue on the following browsers, even after clearing their caches.

* Chrome 84.0.4147.125
* Brave 1.12.114 (Chromium: 84.0.4147.135)
* Firefox 79.0
* Edge 44.18362.449.0

**Comment by sulkaharo** [comment]
Can you update to latest dev and re-test. I suspect what's going on in your browsers is, the service worker is not updating, causing issues. I made a few small changes to the service worker and CSP setup and DEV works for me on Chrome and Safari.

**Comment by sulkaharo** [comment]
Ah, found the underlying issue with CSP, this is now also in DEV.

**Comment by bjornoleh** [comment]
Thanks, glad to help! Its working for me.

Now, if I could get the split view to work again... :-) Could you check please if there is something missing for this to work?

Mousing over the two halves give slightly different error messages

Rough translation: 

Left: Requests to the server have been blocked by an extension

Right: xxxx.herokuapp.com rejected the attempt to connect

![image](https://user-images.githubusercontent.com/63544115/90798904-d6bf5000-e312-11ea-8f21-eaff06879b22.png)

![image](https://user-images.githubusercontent.com/63544115/90800023-5b5e9e00-e314-11ea-91ed-f3e5f516c3ea.png)

**Comment by bjornoleh** [comment]
The Split screen referat to custom clock URLs of two NS sites. I havent checked yet if these work without the split screen.

The urls are 
NS config variable: FRAME_URL_1 https://xxxx.herokuapp.com/clock/by10-tm20-nl-sg30-dt20-nl-ag15

Same for FRAME_URL_2, just different NS site.

**Comment by bjornoleh** [comment]
Ok, I just checked the custom clock views, they work just fine with the current Dev, but the split screen do not.

**Comment by sulkaharo** [comment]
Ok I know what needs to happen to support the split view, will implement today

**Comment by sulkaharo** [comment]
And it's done, latest dev should now support the split view again. Note you might need to reload the site once to ensure you have the right CSP to support the view.
