### ISSUE TITLE
Google Home plugin installation process has changed

### ISSUE THREAD

**Issue by LTHeaven** [nightscout/cgm-remote-monitor#5852]
**Describe the bug**
It seems the steps to configure the google home plugin have changed. Starting at point 6. there is no "conversational" option. Also when it asks to go to "actions" there is no such option in the google actions console

**To Reproduce**
1. try to follow the google plugin guide.
2. Fail at step 6

**Expected behavior**
Being able to follow the guide

**Screenshots**
![image](https://user-images.githubusercontent.com/18329749/90703184-64585c80-e28d-11ea-9ffd-46dea19ef6e1.png)

**Your setup information**

**Comment by mrspouse** [comment]
When you get the screen with the tiles **don't click one**. Instead, click Actions Console at the top left corner. The Develop tab has the **Build your first Action** option which gets you to the Custom Intent in Dialogflow.

**Comment by inventor96** [comment]
@LTHeaven @mrspouse I've updated the instructions to reflect the Actions Console as I saw it when setting up a new Action. Could you double check these updated steps are the same for you? You can create a new action, and then delete it after you're done double-checking. Thanks!

You can find the changes here: https://github.com/inventor96/cgm-remote-monitor/commit/b34a8fc94719a0c7d1d07988a348a0154b69c1bb

**Comment by mrspouse** [comment]
@inventor96 @LTHeaven Yes, that looks ok to me.
