### ISSUE TITLE
dbsize plugin issue post ATLAS migration

### ISSUE THREAD

**Issue by Ashley112885** [nightscout/cgm-remote-monitor#5884]
**Describe the bug**
dbsize plugin no longer appearing after migrating to ATLAS

**Screenshots**
dbsize plugin is enabled but not showing up as a pill within NS display
![Capture](https://user-images.githubusercontent.com/38409940/91116798-2d05f900-e65b-11ea-9d13-cc118b439cff.JPG)

**Your setup information**
- Version of Nightscout is 13.1.0 dev
- Tried various browsers and devices

**Comment by PieterGit** [comment]
Is there anything in the logs that can point to an error?

**Comment by Ashley112885** [comment]
I don't actually know how to check the logs 😬

**Comment by sulkaharo** [comment]
Now fixed in dev
