### ISSUE TITLE
Disallow '/' in robots.txt to prevent search engines from crawling your nightscout

### ISSUE THREAD

**Issue by stijnbrouwers** [nightscout/cgm-remote-monitor#5905]
Currently, the 'Disallow' directive in robots.txt is empty. Wouldn't it be better to set the value to '/'?
This prevents the nightscout site from being crawled by search engines.
I don't think it's wanted in any case to have your nightscout appear in search results.

**Comment by sulkaharo** [comment]
Great idea! Added to dev in 6613e76.
