### ISSUE TITLE
Mongo Performance issues (reported by Mongolab)

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#593]
I got this as an email from Chris at Mongolab

> Date queries
>
> I was talking with one of our DBAs and he mentioned that there might be a query of the following form: 
>
>    `db.<collection>.find({}).sort({"date" : -1} )`
>
> From our last exchange, indexes are now automatically created, which is great. However, y'all might want to consider implementing some kind of date filter into the query. If a user has been using Dexcom for several months, the data will continue to grow and the queries will be doing collection scans. 
>
> If you only need to display data for the past two weeks for example, then a filter will really improve performance. 
>    
>    `db.<collection>.find( { "date" : { $gt : <value> } } ).sort( { "date" : -1 } )`
>
> Leaking connections
>
> We've also noticed that Nightscout databases are causing connection leaks. Connections are being opened but not closing so over time, a server, particularly one that may have a greater number of Nightscout DBs than others, may start to trigger available connection warnings.
>
> Restarting a server will close these connections, but is not ideal as it causes downtime for all the users on the server. Happy to brainstorm with you and the team on this.
>
> Rackspace
> 
> Heads up- we will no longer be supporting Rackspace in the future, only Amazon, Azure, and Google. Noticed that Rackspace is mentioned here: http://www.nightscout.info/wiki/labs/how-to-migrate-from-an-azure-hosted-mongo-database.
>
> Let me know if you have any questions or if I can help!

**Comment by jimsiff** [comment]
@jasoncalabrese, any idea whether the orphaned connections are from c-r-m, or failed uploads?  Uploader connections would be my initial suspicion because there's far more connectivity variability between the uploader and Mongo db than between c-r-m and the db.  I wonder if Mongo can provide any log data that includes the connection source IP.  It might be easy to correlate whether the source iP of the stalled connection is from Heroku/Azure vs a random IP used by an uploader.

**Comment by jasoncalabrese** [comment]
Based on some analysis done by mongolab, the hanging connection seem to be coming from old uploaders.  Still need to fix the `find({}).sort({date: 1})` pattern used all over the place

**Comment by jasoncalabrese** [comment]
Fixed as part of #694, all loading from mongo is now bounded and the pebble endpoint uses the data already stored in the `ctx` instead of hitting mongo again
