### ISSUE TITLE
(dev) reload loop in firefox

### ISSUE THREAD

**Issue by viq** [nightscout/cgm-remote-monitor#5943]
**Describe the bug**
Page keeps reloading in firefox.

**To Reproduce**
1. Open nightscout (dev) in firefox
2. Watch it reload. And reload. And reload. And reload. And reload. And... you get the picture.

**Expected behavior**
Tested, and in chromium after opening one reload happens, and then it stays there. In firefox, it just keeps reloading.

**Your setup information**
```
$ git describe ; node --version ; npm --version
0.10.3-783-g6613e761
v12.16.1
6.13.4
```
Same behaviour is shown on both desktop (linux) and mobile (android) firefox. It *does not* happen on:
- chromium (linux desktop) and chrome (android)
- mobile: firefox beta and firefox focus

**Comment by sulkaharo** [comment]
In the name of full transparency, we're not developing/testing against Firefox at the moment at all given the extremely few people who are contributing to Nightscout development. If you want to get this fixed, please advocate some more developers to join the team so we have time to look at browser specific issues. Related: #5920

**Comment by tycho40** [comment]
I can confirm the same issue as well, with Firefox 80.0.1 under macOS 10.15.6 (19G2021). I've tried clearing the Firefox cache, as well as disabling all add-ons as well. What's strange is that the issue doesn't happen when I load the site under Firefox Private Window. @viq Does the reload loop happen for you using Firefox Private Browsing? Just curious.

I wish I could do more to help, but alas, I am not a dev by any definition. Thanks!
