### ISSUE TITLE
Implement caching for database communication

### ISSUE THREAD

**Issue by cascer1** [nightscout/cgm-remote-monitor#5944]
I self-host my mongo database in Google Cloud Platform and noticed that the monthly price is higher than expected. After inspecting some of my bills, it appears that almost 50% of the bill is made up of network egress from the database to nightscout.

![image](https://user-images.githubusercontent.com/7243299/92101346-489c9c80-eddd-11ea-9fea-957458e39193.png)

I believe that caching can potentially drastically decrease the amount of network traffic to the database and as such might reduce running costs of the database.

**Comment by bewest** [comment]
We've noticed similar.  Are you also using Loop?  @sulkaharo has done some good analysis on this issue.  Stay tuned.

**Comment by sulkaharo** [comment]
Yup, working on a change for the next release, which should drop this dramatically.

**Comment by sulkaharo** [comment]
See #5947. On my Mongo instance, this drops the database network traffic to slightly under 10% of last week's average.

**Comment by sulkaharo** [comment]
Can you please test the branch in the PR listed above? I added more optimisations over the weekend and this has dropped the DB traffic to almost a hundredth of what it used to be. I don't have known bugs on the PR anymore, so testing would be great.

**Comment by cascer1** [comment]
@sulkaharo thanks, I'll test it tomorrow or otherwise wednesday.

**Comment by cascer1** [comment]
@sulkaharo I have now deployed your `optimize_polling` branch to my nightscout instance. Unfortunately I can't test the actual interface since I'm still experiencing some weird constant refreshing bug. I'll keep an eye on the mongo network usage and report back.

**Comment by sulkaharo** [comment]
The Firefox issues should be fixed shortly, but if you want to test in the meantime, there's other browsers available. ;)

**Comment by sulkaharo** [comment]
Now implemented in dev
