### ISSUE TITLE
Missing variable for Render Bolus Amount: [All (without leading zero and U)]?

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#5975]
It seems there is a missing variable for **Render Bolus Amount**: [_All (without leading zero and U)_], at least I could not find it.

It would be nice being able to set this as the default bolus rendering in Heroku config variables.

The variable may exist, but at least I can't find it documented in README.md

![image](https://user-images.githubusercontent.com/63544115/92902988-03eab400-f422-11ea-8e17-6153df79718c.png)

**Comment by tycho40** [comment]
I'm having this same issue as well. How do I set All (without leading zero and U) as the default? I tried setting BOLUS_RENDER to all-remove-zero-u in 14.0.7, but that didn't work. Any thoughts?

**Comment by bjornoleh** [comment]
@sulkaharo Hi, would you happen to know if this is possible, or what it would take to enable "Render Bolus Amount: [All (without leading zero and U)" as the default?

**Comment by bjornoleh** [comment]
It seems current Dev is addressing this. Just tested, works for me. Thanks!

From readme.md (Dev)
https://github.com/nightscout/cgm-remote-monitor/tree/dev#bolus-bolus-rendering

bolus (Bolus Rendering)
Settings to configure Bolus rendering

BOLUS_RENDER_OVER (0) - U value over which the bolus labels use the format defined in BOLUS_RENDER_FORMAT. This value can be an integer or a float, e.g. 0.3, 1.5, 2, etc.
BOLUS_RENDER_FORMAT (default) - Possible values are hidden, default (with leading zero and U), concise (with U, without leading zero), and minimal (without leading zero and U).
BOLUS_RENDER_FORMAT_SMALL (default) - Possible values are hidden, default (with leading zero and U), concise (with U, without leading zero), and minimal (without leading zero and U).
