### ISSUE TITLE
NS Dev 14.0.2 Day to day reports: Previous days are missing both rendering and counting of temporary basal and boluses

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6006]
**NS Dev 14.0.2 Day to day reports:** 
Previous days are missing both rendering and counting of temporary basal and boluses. 

Apparently, this only affects the first half of the day. The current day seems ok, but possibly it is just the timing of the screenshot that makes it look this way.

NS Dev 13.1.0 as of Aug 22 show the basal and bolus correctly, and seems to also count the insulin correctly.

![image](https://user-images.githubusercontent.com/63544115/93301888-61537c00-f7f9-11ea-8698-2f669a74c0de.png)

**Your setup information**
NS 14.0.02
Dexcom Share / Bridge
Loop (FreeAPS 172)

Possibly related to the issue of rendering temporary overrides in https://github.com/nightscout/cgm-remote-monitor/issues/5992 ?

**Comment by bjornoleh** [comment]
The timing of the first correctly rendered/counted temp basals and boluses varies from day to day:

All boluses are affected, not only microboluses.

This is with Dev 14.0.2 of today:
![image](https://user-images.githubusercontent.com/63544115/93306624-6bc54400-f800-11ea-9575-5b5c065e4aef.png)

**Comment by sulkaharo** [comment]
This is related to Loop storing around 20x more Profiles to Nightscout than what the system has been designed for. Can you try latest DEV to see if this fixes the issue? I found and fixed a bug in the REST query in the reports.

**Comment by bjornoleh** [comment]
@sulkaharo Thanks, but unfortunately 14.0.3 made no difference here.

In my case, I'm not sure if the profile collection is to blame. I have applied John Fawcetts patch to stop Loop from uploading profile entries unless there are actual profile changes (eliminating the profile uploads from activating temporary overrides). I have also purged the collection to one entry per day from the period prior to the patch, and it is now at around 110 entries. I would expect that to be manageable for NS.

**Comment by sulkaharo** [comment]
Ok reproduced locally and submitted another fix to DEV, this should work now

**Comment by bjornoleh** [comment]
@sulkaharo Confirmed! 

Thanks!

**Comment by sulkaharo** [comment]
Well, thank you for testing and reporting these! ❤️
