### ISSUE TITLE
Version 0.7.0 not deploying in Azure or Vagrant using existing instructions

### ISSUE THREAD

**Issue by alexpop** [nightscout/cgm-remote-monitor#606]
Amazing job dear contributors. Hope to contribute as time allows.
I managed to hook everything up, but it took a few days of work. Here are some notes based on my experience:

1) I had hard time with Azure payments until I used Internet Explorer

2) I deployed version 0.7.0(sha: c11d4c7fa08d122a29064b5881e51506b2dbbe65) to Azure and this is the result:
https://glucomon.azurewebsites.net

It's not loading properly due to a few .js and .css 404s

3) To troubleshoot further, I deployed it locally in virtualbox.

In order to make 'vagrant up' work I changed in Vagrantfile:
config.vm.box = "precise64"
  to
config.vm.box = "hashicorp/precise64"

4) Once logged into the Ubuntu 12.04 instance, I had to run these commands to make the site function:

```bash
sudo -i
apt-get update -y
apt-get upgrade -y
# git needed here in order to clone the repo containing setup.sh
apt-get install curl git -y
#apt-get install mongodb-clients -y
git clone https://github.com/alexpop/cgm-remote-monitor

cd cgm-remote-monitor
./setup.sh
# npm install in setup.sh throws an error. a second run required for success
npm install

npm install -g graceful-fs
npm install -g ambi
npm install -g csextends
npm install -g zeparser
# without these bower commands I get the same 404s as in Azure
npm install -g bower
bower install tipsy-jmalonzo --allow-root

# without NODE_PATH I get errors like: Error: Cannot find module 'graceful-fs'
echo 'NODE_PATH=/usr/lib/node_modules/' > my.env
echo 'MONGO_CONNECTION=mongodb://RRRRRREEEEEEMMMMMOOOOOOVVVVVVVVEEEEEEDDDDDDD' >> my.env
echo 'MONGO_COLLECTION=entries' >> my.env
echo 'PORT=80' >> my.env
nohup env $(cat my.env) node server.js&
```

**Comment by jasoncalabrese** [comment]
Sounds like npm install failed, it should run bower install after the npm modules are installed.  I've seen people have to redeploy on azure, but I've never used azure myself.

**Comment by alexpop** [comment]
Thank you Jason. Redeploying a second time worked. Closing
