### ISSUE TITLE
Mongo adds on not exists

### ISSUE THREAD

**Issue by saraelmoghazy** [nightscout/cgm-remote-monitor#6069]
when connect project to herouk , mongo adds on not exists and this cause an error with app because invalid connection to mongo

**Comment by sulkaharo** [comment]
This has been fixed in the latest release, so sounds like you're trying to deploy an old version

**Comment by saraelmoghazy** [comment]
i steup atlas mongoBD manually then put Url in Mongo_Url , site is working now but throw BG check to treatments table not entries

**Comment by sulkaharo** [comment]
Sounds like you've configured the MONGO_COLLECTION variable to point to treatments?

**Comment by saraelmoghazy** [comment]
no i entered CG check manually not through sensors
