### ISSUE TITLE
Render Basal no longer showing after version 14.0.3 update

### ISSUE THREAD

**Issue by human911** [nightscout/cgm-remote-monitor#6084]
Unable to see the basal rates. I switched Render Basal in the menu from None, Default and Icicle without success.

![image](https://user-images.githubusercontent.com/10080856/93922835-57cd8680-fcc7-11ea-8bf7-6a7efec73527.png)

Heroku/Altas Environment

Was working on 13.0.1 prior to update.

I can provide any logging or access to url if needed.

**Comment by sulkaharo** [comment]
Are you still experiencing this? This is the only report so far of the issue, so either this was a temporary fluke or you have some extremely rare piece of data in your system that breaks this

**Comment by human911** [comment]
@sulkaharo Yes, I haven't had a chance to do any troubleshooting. I'll send you a pm with more information to my site.

**Comment by Britt2004** [comment]
I have th same problem. Updated to day...

**Comment by sulkaharo** [comment]
Right - can you try adding "basal" to the ENABLE setting in Heroku? Also I'd recommend updating to the latest .6 point release while at it.

**Comment by human911** [comment]
Resolved. Thank you.
