### ISSUE TITLE
Nightscout first time - deploy Heroku not working

### ISSUE THREAD

**Issue by kjeaxelsson** [nightscout/cgm-remote-monitor#6126]
I am trying to set up Nightscout for the first time, when i press deploy on Heroku I get a message saying:

 "A valid GitHub directory could not be found.

The given URL (https://github.com/) is not a valid GitHub repository."

Any thoughts on what I should do?

Regards,
Johan

![Skärmavbild 2020-09-26 kl  18 27 57](https://user-images.githubusercontent.com/71938180/94345434-06562c00-0026-11eb-9080-b1b910b578eb.png)

**Comment by sulkaharo** [comment]
Hi! For support, please visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

This looks like a temporary issue with Heroku, can you try again?

**Comment by kjeaxelsson** [comment]
> Hi! For support, please visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ
> 
> This looks like a temporary issue with Heroku, can you try again?

![Skärmavbild 2020-09-28 kl  07 52 54](https://user-images.githubusercontent.com/71938180/94395331-bc716100-015f-11eb-94e8-ef192b9cac77.png)

Hi again,
Thank you for your reply. I get the same message when I try today. I have attached an overview image, please reply if I should provide additional information.

Kind Regards,
Johan

**Comment by octavioCibrian** [comment]
Try it in firefox new version. i had the same problem with google chrome
