### ISSUE TITLE
Backfill data not visible on main screen (regression 14.0.3)

### ISSUE THREAD

**Issue by Pogman** [nightscout/cgm-remote-monitor#6134]
This was reported by a user of 600 series uploader. Whenever there is a period away from the internet and they return online the uploader will backfill the missing data. There is a gap for this period visible on the main screen but the data exists and can be seen in the reports.

Section A and B are for the same period.

![ns-14 0 3-backfill-regression-main-A](https://user-images.githubusercontent.com/7413594/94367722-60afc500-00d8-11eb-9dd0-b93f88939230.jpg)

![ns-14 0 3-backfill-regression-reports-B](https://user-images.githubusercontent.com/7413594/94367724-64434c00-00d8-11eb-9805-b393afedf275.jpg)

Notes:

Refreshing the web page or clearing the cache will not show the missing backfill period.

Nightscout version 14.0.3

**Comment by sulkaharo** [comment]
Just about to release 14.0.5, which should fix this

**Comment by sulkaharo** [comment]
Ok, please instruct the user to update to latest master (14.0.5) to see if this is fixed

**Comment by Pogman** [comment]
@sulkaharo great, thanks!
