### ISSUE TITLE
Problem parsing config URL from IMPORT_CONFIG failed

### ISSUE THREAD

**Issue by octavioCibrian** [nightscout/cgm-remote-monitor#6169]
Hi, i don't know what can i do with that problem, some ideas?

**Comment by sulkaharo** [comment]
Are you self-hosting or are you in T1Pal?

**Comment by octavioCibrian** [comment]
-hi sulkaharo, i resolved the problem, the problem was that in mongodb i needed to put ip 0.0.0.0 to see from wherever. =)
