### ISSUE TITLE
Deploy To Heroku

### ISSUE THREAD

**Issue by michellemullis1** [nightscout/cgm-remote-monitor#6179]
Deploy to Heroku Button takes me to the following site:  A valid GitHub directory could not be found.
I'm on step 4 of the install.  I'm using Chrome, and I'm trying to setup a follow link for a Libre CGM.

![image](https://user-images.githubusercontent.com/72204608/94815441-897dd600-03c8-11eb-9210-191a4be105d1.png)

**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your setup information**
- What version of Nightscout (e.g. 0.10.3)
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)?

**Additional context**

**Comment by sulkaharo** [comment]
This is a Heroku bug and should be resolved - please use some other browser than Chrome if you still have the issue
