### ISSUE TITLE
BAGE info reset after 31 days in use

### ISSUE THREAD

**Issue by sarunia** [nightscout/cgm-remote-monitor#6192]
As always, the BAGE pump battery age is reset after 31 days regardless of the nightscout version. When will it finally be corrected?
![bage](https://user-images.githubusercontent.com/12498738/95014497-a6740c80-0647-11eb-9c26-b3b6fb4472d5.jpg)

**Comment by sulkaharo** [comment]
You're the first person ever to report this is not working correctly - issues that are not reported cannot be fixed. :) I'm curious what pump / batteries are you using to have the battery last for over 31 days?

**Comment by sarunia** [comment]
I secretly hoped that with each new version of nightscout it would be taken into account. I don't know what kind of weak batteries you use in your pumps, but it is quite normal to work for 60 days on the lithium battery with AC Combo pump, such is a natural curiosity. :)

**Comment by vytux-com** [comment]
Would this also fix SAGE not showing correctly if over 31 days?

**Comment by sulkaharo** [comment]
14.0.7 now changes BAGE and SAGE pills to load two months of data
