### ISSUE TITLE
Inconsistent delta values in NS and clock view (mmol/L)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6244]
Inconsistent delta values in NS and clock view (mmol/L).

**To Reproduce**
Compare delta values of NS and the color clock (or custom clock view).
(xxxxx.herokuapp.com/clock/clock-color)

Quite often, a +/- 0,1 mmol/L incnsistency is seen.

Captured at the exact same time:
![image](https://user-images.githubusercontent.com/63544115/95989723-ef3b7a80-0e2a-11eb-98e5-a6ba7aa7b0f5.png)
![image](https://user-images.githubusercontent.com/63544115/95989761-f9f60f80-0e2a-11eb-9538-c5b46d78c1e8.png)

Another observation:
![image](https://user-images.githubusercontent.com/63544115/95989855-172ade00-0e2b-11eb-84ab-b693f27bc71c.png)
![image](https://user-images.githubusercontent.com/63544115/95989878-1eea8280-0e2b-11eb-9f81-bd3f3e188a45.png)

Please also note that the age of the SGVs are different between NS and clock view. The clock views are also updated quite delayed compared to the main NS view, perhaps 20-30 seconds (haven't checked this accurately).

**Expected behavior**
I would expect consistent delta values.

Your setup information

Nightscout 14.0.7 dev
Heroku, recently migrated from mLab to Atlas
Loop/FreeAPS (upload data = ON)
Dexcom G6 --> Loop
Tested in PC/Chrome, iPad/Safari and Android/Chrome

**Comment by bjornoleh** [comment]
Hi, I tested your fix_batch branch to check the delta fix. In a NS testing instance fed with Dexcom data only, the differences in delta between main NS view and custom clock was still there. And for some reason, the delta value was no longer displayed in "clock-color". The update of the clock data is also delayed, 20-30 seconds.

![image](https://user-images.githubusercontent.com/63544115/96241935-27fe5f80-0fa3-11eb-92da-b294a5d3f327.png)

Compare diff in the Heroku Activity log (compared to current Dev), to make sure I deployed the correct branch:
![image](https://user-images.githubusercontent.com/63544115/96243069-8546e080-0fa4-11eb-9af8-806e1b041fe3.png)

**Comment by bjornoleh** [comment]
With the Loop-fed NS instance, it looks better, so possibly different behavior between SGVs from Dexcom (Bridge) and other sources? Also the delta in "clock-color" is present :

![image](https://user-images.githubusercontent.com/63544115/96251021-166f8480-0fb0-11eb-9c96-0d10ca4ef94f.png)

**Comment by sulkaharo** [comment]
Right, the precalculated delta wasn't actually applied correctly. The clock now has no BG conversion between the units whatsoever and fully relies on the backend configuration for display. The clock has historically updated the data only once a minute, so the delay between a reading in the main view and the clock has been anything from near instant to 59 seconds, depending on how the clock load time has aligned to the moment the CGM was started. I made the clock now request the data every 20 seconds, so the max delay is now much shorter. Also - I unified the color and black clock views, which historically haven't shared the layouts, so different view between the two has been the expected behavior.

**Comment by bjornoleh** [comment]
@sulkaharo Thanks, looking good now, although I havent had time to check the deltas yet (I'm sure tis good now).

But suddenly the Loop Follow app started crashing a couple of seconds after starting the app. This was replicated on two phones, and the app was working again after deploying current Dev again.

We could ping John Fawcett if you need help spotting the problem, in case it's not obvious.

**Comment by sulkaharo** [comment]
@bjornoleh Oops the cause for that crash should now be fixed.

**Comment by bjornoleh** [comment]
@sulkaharo Thanks, working now!
