### ISSUE TITLE
App crashed on heroku after deplay new build 14.0.6

### ISSUE THREAD

**Issue by mstaegemann** [nightscout/cgm-remote-monitor#6260]
**Describe the bug**
I've run nightscout on heroku with mLab. But I'm not sure which version I've got before. After updating to the latest version and deploy it to heroku the app crashed with the following message in the log:
`nightscout at=error code=h10 desc="app crashed" method=get path="/socket.io/?eio=3`

After restarting the app on heroku I've got the following message:
`error: helmet no longer supports `true` as a middleware option.`

**Your setup information**
- What version of Nightscout 14.0.6
- AndroidAPS
- xDrip
- This issue is not specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)

**Additional context**
As a workaround I switch the config var SECURE_HSTS_HEADER from
true
to 
false.

After that is works.

Sorry that i cannot give more information as I do not have save the logs. Perhaps you can instruct me how to get them from heroku.

**Comment by sulkaharo** [comment]
Found the issue, looking for a fix. Looks like you need to have both SECURE_HSTS_HEADER and SECURE_CSP turned on to cause the breakage.

**Comment by mstaegemann** [comment]
yes, your right. SECURE_CSP was also turned on. Thanks for fixing.
