### ISSUE TITLE
Providing a hosted option

### ISSUE THREAD

**Issue by robertherber** [nightscout/cgm-remote-monitor#6272]
I just set up Nightscout for myself after getting a Miaomiao and it's great for me. But in Facebook groups I've noticed a lot of non-technical folks have issues setting up and maintaining Nightscout (which is perfectly understandable). I also understand some features/plugins of Nightscout could potentially be complicated to host from a legal standpoint.

But looking at HealthKit which is just acting as a data container to facilitate the sharing of Health-related data between apps - it can hardly be considered a "medical device" and I have a hard time seeing Apple getting in trouble for data put into HealthKit from third-party apps.

I'd argue the main use case for Nightscout is sharing diabetes-related data between apps - similar to HealthKit - where third-party apps can provide alarms, bolus calculators, medical advice with legal implications.

Wouldn't it be great if we could break out the parts of Nightscout that could be "safely" co-hosted - for easier access for the general public? Thoughts on this?

**Comment by bewest** [comment]
Howdy, feel free to get in touch with us at mikem@betterlivingtech.net and bewest@medicaldatanetworks.com.  We built https://t1pal.com/ to make these benefits more widely accessible. Your thoughts here are definitely interesting, I've had similar ideas and would love to hear more.
