### ISSUE TITLE
Browser tab BG / delta does not update in the background

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6378]
Browser tab BG / delta does not update in the background. Others have reported the same.

Tested with Chrome on Win 10

![image](https://user-images.githubusercontent.com/63544115/98451935-f49a9500-214a-11eb-8ee6-c7a33db1005b.png)

**To Reproduce**
Leave a NS tab in the background, the BG and delta values no longer updates, like it used to.

**Your setup information**
NS 14.0.7 (fix_batch)
Loop Upload readings = ON
Chrome / Win 10

**Comment by sulkaharo** [comment]
This is a likely change in how browsers issue re-paints and run JS when app is not in the front. With web apps, the app has 0 control over background execution and it's likely this is a Chrome change to reduce the memory usage and battery consumption by throttling CPU use in pages that are not visible. There has been no change in the app itself on how it often it updates the views.
