### ISSUE TITLE
Deploy nightscout

### ISSUE THREAD

**Issue by vera-aleixo** [nightscout/cgm-remote-monitor#6464]
I´m trying to deploy nightscout, but i get this error:

"Couldn't find either the add-on service or the add-on plan of "mongolab:sandbox"."

How should i deploy it now with atlas DB.

It will be a new install.

**Comment by psonnera** [comment]
https://nightscout.github.io/nightscout/new_user/

**Comment by jsmith5484** [comment]
@psonnera Your response does not address this specific error. I am experiencing the same issue as @vera-aleixo

**Comment by sulkaharo** [comment]
This error only appears if you have an old Nightscout version in your fork in Github. Please update to the latest as described in the instructions.
