### ISSUE TITLE
Breakage due to automatic MongoLab mongo version upgrades

### ISSUE THREAD

**Issue by dduugg** [nightscout/cgm-remote-monitor#657]
My nightscout server broke abruptly when MongoLab upgraded the mongo version of my db to 3.0.x. The response I received from their support indicates they are planning to automatically, irreversibly upgrade all sandbox accounts in the coming weeks:

>Hello,

>Sorry for the delayed reply. Unfortunately, there is not a way to roll back the version of an Experimental Sandbox database.

>For a guide on migrating data between the two databases, please refer to the "Migrating Data into MongoLab" section of our documentation, linked below: http://docs.mongolab.com/migrating/#dump-and-restore

>Note that you must dump the data using 3.0.X version of mongodump and restore using a 2.6.x version of mongorestore.

>Also, please keep in mind that our normal Sandboxes will be upgraded to MongoDB 3.0 in the coming weeks, but that we will be informing users to this change prior to the update.

>Regards,

>Samson

**Comment by jasoncalabrese** [comment]
What was the actual error, was data lost?  Any ideas for a way we could prevent problems for others?

**Comment by dduugg** [comment]
No data lost, just can't connect to MongoLab. There are others on SO having what I believe is the same problem: 

http://stackoverflow.com/q/30659213/2193416
http://stackoverflow.com/q/30924859/2193416

To fix, it may be sufficient to upgrade the mongodb package to v1.4.29: http://docs.mongodb.org/manual/release-notes/3.0-scram/#upgrade-drivers

**Comment by jasoncalabrese** [comment]
the version on dev is current, if that works we should be able to to a hot fix

**Comment by dduugg** [comment]
Just opened https://github.com/nightscout/cgm-remote-monitor/pull/658. Haven't tested on dev, but I committed directly to master on my fork, and it seems to be up and running with the mongo 3 collection. (The page errored out for the first minute or so, something about a type error in calling `.extent` on undefined, but it should be unrelated.)

**Comment by jasoncalabrese** [comment]
Guess we can close this one too, as mentioned on #658 the solution is to redeploy so the newer mongo module is picked up
