### ISSUE TITLE
BWP plugin should show more data in tooltip

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#666]
The current configured target levels should be shown. The math for why a suggestion was generated should be shown.
##

**Comment by jasoncalabrese** [comment]
@sulkaharo is there anything else that you wanted to do with this issue?  Think most of it is there now.

**Comment by jasoncalabrese** [comment]
So far feedback has been that current tooltip has been good, removing milestone label, but leaving open.

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
