### ISSUE TITLE
Access Token not used when exiting Reports, Profile editor or Admin tools

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6671]
I use Access Tokens for authentication, with AUTH_DEFAULT_ROLES = denied. When exiting Reports, Profile editor or Admin tools using the X in upper right hand corner, I am redirected to https://xxxxxx.herokuapp.com/, without the token in the url. Hence, I am prompted to enter API secret or token. Perhaps I could just close the tab instead (a new one is created when entering  Reports, Profile editor or Admin tools )? But the current behaviour does not seem to be as intended.

NS 14.1.0 (Dev)
Chrome/Win 10

![image](https://user-images.githubusercontent.com/63544115/102714867-ec00b700-42d1-11eb-9881-2c769323f5a2.png)

![image](https://user-images.githubusercontent.com/63544115/102714986-98429d80-42d2-11eb-87ac-e1793051d876.png)

**Comment by sulkaharo** [comment]
With dev, users are now expected to use the login UI for the tokens, rather than GET parameters. If you're on a recent dev, can you try that for the auth?

**Comment by bjornoleh** [comment]
Ok, I'll try yr, but haven't heard about that. Is there any documentation, how do I use this? 

I am using the urls that are available in Admin Tools.

**Comment by bjornoleh** [comment]
I suppose you mean putting the token into the login UI in the screenshot in the first post?

**Comment by sulkaharo** [comment]
Yup, as indicated in the dialog text. 😉

**Comment by bjornoleh** [comment]
Yes, I eventually got it :)

Seems to work now! 

How will this work with various other apps which use token based authentication? I am using the urls now. 

And I found a missing translation key:
(Remove stored token)

**Comment by bjornoleh** [comment]
@sulkaharo I have recently been kicked out repeatedly when having logged in via an access token url ( e.g. https://xxxxx.herokuapp.com/?token=name-123abc456qwerty). A simple refresh of the page have been enough to resume the session, since the authentication is in the url, whether on the phone (Android/Chrome) or Win10/Chrome. I have been thinking about reporting this, but don't know if it is a known issue.

I was hoping it would improve now that I logged in with the token like you suggested, but unfortunately it is the same. Checking the "Remember this device" box does not help.

Is this a known issue? Do you need more details, or is there already a solution?

I am on current Dev.

**Comment by sulkaharo** [comment]
What do you mean by kicked out? I haven't got any other reports of this and the authentication works for me, so I don't know what the symptoms are that you're referring to.

**Comment by bjornoleh** [comment]
@sulkaharo Kicked out as in getting the login dialogue 


![_20201221_162637](https://user-images.githubusercontent.com/63544115/102792976-7ec05500-43a9-11eb-8209-17c7add3971d.JPG)

**Comment by sulkaharo** [comment]
Does this happen on it's own, or when you do something like submit a care portal entry? This is curious in that after the client has loaded, there should not be anything that triggers reauthentication. The data is transmitted through the authorized web socket. The only thing I can imagine that'd trigger this is either the server crashing and rebooting and this causing some kind of a client error, or maybe Internet connection being interrupted between the client and the server and this somehow triggering the client to go into a state where it thinks it's not authorized, although even in these cases it's curious the client looks like that, as there is no implementation in the client for degrading the permissions after a successful authentication without a page load, so the only situation where you should see that dialog is after a page reload where the client is not authenticated. Basically, there's no place in the client logic that'd be the obvious spot to look at that might be the culprit.

**Comment by bjornoleh** [comment]
It happens on its own after some time of inactivity

**Comment by bjornoleh** [comment]
@sulkaharo Let me know if there is something I can test. Clearing cache?

At what commit or release was the current behaviour introduced? I might roll back to a previous version, as it currently is a little annoying.  But will help troubleshooting if there is something to test.

**Comment by sulkaharo** [comment]
Using Tokens to authenticate in the web was introduced in release 13 a year ago, but there was a refactor to the code recently that's still in dev. What you could do is open up the Javascript console for the site and see if you can see any JS errors throw on the site after the dialog appears.

**Comment by sulkaharo** [comment]
Actually - how soon after a page load has this happened to you? Wondering how hard it'd be to replicate this. I'm unable to reproduce this on our instance, but wonder what behaviour to describe to others. Also note we're close to releasing as many others have said DEV works for them, so wondering if your instance is somehow special or if this is more wide spread.

**Comment by bjornoleh** [comment]
I will check the JS console. I guess there is no way to do that on a phone? But I am having the same issue on the PC, so will have a look.

As for replicating this, I can't give a very specific description. But it happens several times a day, sometimes it seems it is every time I look at the site after a significant time away. I don't know if that is half an hour or one hour, but probably less than tw

**Comment by bjornoleh** [comment]
It happens real quick on the phone, less than 30 minutes. Actually, I can refresh Chrome to bypass the login dialogue, although I did not use the url with token.

This was with Chrome on Android. It should not matter, but I have made a shortcut to the home screen, and in this latest case i also had a separate tab open in Chrome

**Comment by sulkaharo** [comment]
I think I maybe found the cause. Can you update to latest DEV to see if this fixes it for you?

**Comment by bjornoleh** [comment]
Thanks, deploying now, let's see how it goes

**Comment by bjornoleh** [comment]
Well, it hasn't failed on me yet, looking very promising! I'll report back if that changes. No news is good news!

@sulkaharo  Did you notice my comment about a missing translation key I found?:
_(Remove stored token)_

**Comment by sulkaharo** [comment]
Yup it's likely this works for you now, great you caught this! The missing key should be waiting for you in Crowdin. :)
