### ISSUE TITLE
TypeError: Cannot call method 'toString' of undefined in Heroku upon app start

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#668]
Browserify-express is throwing errors in production in Heroku.

Jul 02 01:52:51 eero-cgm app/web.1:  TypeError: Cannot call method 'toString' of undefined 
Jul 02 01:52:51 eero-cgm app/web.1:      at /app/node_modules/browserify-express/index.js:84:46 
Jul 02 01:52:51 eero-cgm app/web.1:      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) 
Jul 02 01:52:51 eero-cgm app/web.1:      at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13) 
Jul 02 01:52:51 eero-cgm app/web.1:      at /app/node_modules/express/lib/router/index.js:280:7 
Jul 02 01:52:51 eero-cgm app/web.1:      at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12) 
Jul 02 01:52:51 eero-cgm app/web.1:      at next (/app/node_modules/express/lib/router/index.js:271:10) 
Jul 02 01:52:51 eero-cgm app/web.1:      at SendStream.error (/app/node_modules/express/node_modules/serve-static/index.js:120:7) 
Jul 02 01:52:51 eero-cgm app/web.1:      at SendStream.emit (events.js:95:17) 
Jul 02 01:52:51 eero-cgm app/web.1:      at SendStream.error (/app/node_modules/express/node_modules/send/index.js:245:17) 
Jul 02 01:52:51 eero-cgm app/web.1:      at SendStream.onStatError (/app/node_modules/express/node_modules/send/index.js:356:12) 
Jul 02 01:52:51 eero-cgm app/web.1:      at onstat (/app/node_modules/express/node_modules/send/index.js:621:26) 
Jul 02 01:52:51 eero-cgm app/web.1:      at Object.oncomplete (fs.js:108:15)

**Comment by sulkaharo** [comment]
Ok I'm pretty sure this only happens if you try to load the site while Browserify is still bundling.

**Comment by jasoncalabrese** [comment]
and if you do that does it correct or do you need to re-deploy?  Maybe this is 1 more reason to do the browserify as part of the install script like bower.

**Comment by sulkaharo** [comment]
This is non-destructive and doesn't cause a need to re-deploy. No need to fix.
