### ISSUE TITLE
Reload loop on Chromium 65

### ISSUE THREAD

**Issue by t1dpanic** [nightscout/cgm-remote-monitor#6683]
**Describe the bug**
Nightscout reloads/redirects continuously on Chromium 65.0.3325.181/Raspbian 9.4. I will briefly see my chart, then "Connecting to server", then the chart again, then "Connecting to server" over and over. This was not an issue prior to updating to 14.0.7, but I don't know what my previous install version was. My 14.0.7 install is stable when running from Chrome or Edge on PC.

**To Reproduce**
1. Load Nightscout
2. Page reloads continuously 

**Your setup information**
- Nightscout: 14.0.7
- OS: Raspian 9.4
- Browser: Chromium 65.0.3325.181
- CGM: Libre -> MiaoMiao -> Spike -> Nightscout

**Comment by nspitwo** [comment]
Looks like an error in views/server-worker.js due to promise.allSettled() call. 

![5413D573-4E49-4362-BFB1-EA73207D9E10](https://user-images.githubusercontent.com/31219158/104829074-9dddc580-5835-11eb-9a04-b979a83da637.jpeg)

**Comment by nspitwo** [comment]
If you comment out line # 726 in cg-remote-monitor/views/index.html and replace it with an 'if (false) {', this will prevent the looping.  It just disables the service worker capability.   Should look like this:

...
 <script>
    // if ('serviceWorker' in navigator) {
    if (false) {
      window.addEventListener('load', () => {
...

**Comment by sulkaharo** [comment]
This seems to only affect you? From the OS - do you mean the browser is running on Raspbian?

**Comment by t1dpanic** [comment]
Thank you @nspitwo, I implemented the workaround in my repo and it is now running properly on my pi!

@sulkaharo I can't confirm if this is affecting others, but in my case where it is failing is Chromium on Raspbian. I have not tried Chromium on any other OS. Not sure where @nspitwo is running it. 

After commenting the service worker per the above suggestion my site loads fully without the reload loop.
