### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by EmilyK-S** [nightscout/cgm-remote-monitor#6685]
My region changed to a new timezone in November. The timezone settings within nightscout are correct, but the time on nightscout is stuck in the old timezone on all Windows devices. The time shows up correctly on iOS devices though. - Devices and nightscout all have the latest updates.
Thank you for your help.

**Comment by bewest** [comment]
Are you referring to the main display or to the reports?

**Comment by EmilyK-S** [comment]
The main display. It looks like the problem was resolved. (Sorry I should close the issue). - Microsoft issued an update to their timezone mapping which seemed to have resolved the problem.

Thanks for responding.
Anett

P.S. I issued another problem for which I have not found a solution: #6686 I believe. - I can’t add food from the database. Unfortunately, it’s an intermittent problem - and I can’t figure out what triggers it.

Sent from my iPhone

On Apr 16, 2021, at 2:32 PM, Ben West ***@***.***> wrote:

﻿

Are you referring to the main display or to the reports?

**Comment by bewest** [comment]
Thanks, closing this one for now.

**Comment by bewest** [comment]
Sorry, Anett, I wasn't able to see the issue you referenced.  Please let me know if you find it and leave a note for `@bewest` in it to help me find it.

**Comment by EmilyK-S** [comment]
I tried to tag you, but was not able to figure out how. (Sorry)

It’s issue #6684

„Bolus wizard/ bolus calc not working intermittently „

Thanks,
Anett

Sent from my iPhone

On Apr 16, 2021, at 2:49 PM, Ben West ***@***.***> wrote:

﻿

Sorry, Anett, I wasn't able to see the issue you referenced. Please let me know if you find it and leave a note for @bewest in it to help me find it.
