### ISSUE TITLE
Remember selections in Day to day report (IOB, COB etc)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6701]
I look at the Day to day report a lot, and always want to see IOB and COB. I wish selecting these would be remembered the next time. Alternatively they could be on as default. It would save a few clicks, and when viewing the report on a phone, I also have to zoom in a bit to manage to select IOB and COB. 

Thanks for considering this!

**Comment by bjornoleh** [comment]
Thanks @sulkaharo and @mg80 , the current dev seems to work as I was hoping! At least for Day to day, havent checked other reports yet.

The Day to day graph size doesn't seem to save though. I believe it did before?

**Comment by mg80** [comment]
@bjornoleh my change only saves these preferences:
![image](https://user-images.githubusercontent.com/6451350/106675019-1dbf9b80-6569-11eb-8b2a-1e21b66ea0fd.png)
@sulkaharo let me know your thoughts on saving other report preferences and I can include them.

**Comment by sulkaharo** [comment]
"The Day to day graph size doesn't seem to save though. I believe it did before?" AFAIK this has not ever persisted, so if it has, that's probably been some behaviour of your browser, not Nightscout itself.

**Comment by bjornoleh** [comment]
That is possible, in that case it is with Chrome (Win/Android). But I am unsure about this.
