### ISSUE TITLE
Multi-plugin (pillbox) display on mobile browser (portrait mode)

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#671]
With multiple plugins enabled, the display in portrait mode (Safari/iOS) ends up stacked. (This stacking also makes it impossible to touch a pillbox, like BWP and see the popup toolbox info.)

![f_portrait](https://cloud.githubusercontent.com/assets/9641700/8500686/406192c0-2153-11e5-9517-3652401b78ce.png)

[For comparison: This display issue does NOT occur when the Nightscout iOS app pulls up the same set of enabled pillboxes.]

In landscape mode, with all of them enabled, the final one may force a horizontal scroll.

![f-display2](https://cloud.githubusercontent.com/assets/9641700/8500698/586a8af2-2153-11e5-8dd2-fcd04ea85907.png)

**Comment by sulkaharo** [comment]
Which iPhone model were you testing on? The stacking works as expected on iPhone 6, but I can see how it could break on older devices.

**Comment by oamyoamy** [comment]
iPhone 5
(But since the app is cascading the pillboxes appropriately... the same handling of the containers probably can work in standard browser display.)

**Comment by oamyoamy** [comment]
A stale data alert (yellow warning box) also stacks atop all of them... not a huge deal since, in theory, you need to clear that when you see it anyway. But it hints at another level of stacking currently showing up.

**Comment by jasoncalabrese** [comment]
I can reproduce when using the iphone 4 device setting in the chrome dev tools.  Probably just needs some css adjusts for another break point.

I'm not sure what to do when there are too many plugin shown, there will be a many more, too many to display at once.  Maybe we make them wrap and let the chart keep getting smaller?

<img width="412" alt="screen shot 2015-07-03 at 9 42 23 am" src="https://cloud.githubusercontent.com/assets/751143/8502657/ee59f3e0-2167-11e5-9fd7-e0b66853ba13.png">

**Comment by sulkaharo** [comment]
Looks like there's plenty of space if you overlap the chart a little? Related - can we make the chart position not absolute?



—

**Comment by jasoncalabrese** [comment]
I was thinking that we can set the top in the resize code, based on the bottom of the header.  If we do that we can wrap pills to insane levels.

**Comment by francescaneri** [comment]
![img_0018](https://cloud.githubusercontent.com/assets/9915825/9331959/86c2eb86-45c2-11e5-940e-e2b5a9a822bc.PNG)

you could activate a plugin at a time , otherwise it is difficult with the small size of the screen ( iPhone 3GS )

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9332064/22a1f2fe-45c3-11e5-898e-ce5da54c6265.png)

congratulations , cleaning the code has made ​​it much more fluid on the devices of the older generation .
there is still room to raise the screen a few pixels.

**Comment by francescaneri** [comment]
![screenshot_2015-08-18-18-06-18](https://cloud.githubusercontent.com/assets/9915825/9335584/258ac920-45d5-11e5-8314-79c1c3bd131c.png)
 
As regards to screen size of 4.65 inch 720x1280 , if you could order pills.

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9336080/ea5dd25e-45d7-11e5-97b8-62fdec3ce427.png)
hypothetical arrangement . I do not know if you can

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9336233/ca1fa296-45d8-11e5-88ef-2495e1ee634f.png)
or so

**Comment by francescaneri** [comment]
![screenshot_2015-08-18-18-49-07](https://cloud.githubusercontent.com/assets/9915825/9336504/37555ee0-45da-11e5-8ca8-48f292313a64.png)
horizontally pills are cut

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9336845/064a5c68-45dc-11e5-874b-081c5f761457.png)
 proposal

**Comment by jasoncalabrese** [comment]
I'm working on a solution that will dynamically position the chart right below the pills.  That will allow the pills to wrap.  I thinking the left side will be used for other types of pills such as stats.

**Comment by jasoncalabrese** [comment]
@oamyoamy and @francescaneri, if you get a chance give #825 (`wip/chart-dynamicsize`) a try, I think it will resolve most if not all these issues.

**Comment by francescaneri** [comment]
@jasoncalabrese give a look

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9355403/40fbbde6-4679-11e5-9f96-9d849a956ea6.png)
 you can move down ?

**Comment by francescaneri** [comment]
![img_0504](https://cloud.githubusercontent.com/assets/9915825/9355672/7c254aca-467b-11e5-9127-eadc93478656.PNG)
 Ipad2 (ok)

**Comment by francescaneri** [comment]
![img_0019](https://cloud.githubusercontent.com/assets/9915825/9355702/c65b2222-467b-11e5-8294-11346b732390.PNG)
iphone 3gs (ok)

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9356023/383a92cc-467e-11e5-83ba-cf91f4e982e7.png)
you can fix it?

**Comment by francescaneri** [comment]
![image](https://cloud.githubusercontent.com/assets/9915825/9356361/9e634024-4680-11e5-8f68-f90c99e77f73.png)
would increase the space for the graph

**Comment by jasoncalabrese** [comment]
@francescaneri I'm not able to reproduce any of that, are you sure you'r running `wip/chart-dynamicsize`?  What browser is that?  The pills are out of order also?

**Comment by francescaneri** [comment]
@jasoncalabrese the pictures that I have put proposals the pictures that I have put proposals to free up space.

**Comment by jasoncalabrese** [comment]
Each of the plugin pills are handled the same, I don't want to treat them differently if possible.  There will be plenty more, and no one will ever use them all at once.

**Comment by francescaneri** [comment]
ok, si può spostare verso il basso? see first photo.

**Comment by jasoncalabrese** [comment]
Fixes for this are on dev now
