### ISSUE TITLE
Unburdening diabetes care: (mean) daily manual interventions

### ISSUE THREAD

**Issue by petervanrijt** [nightscout/cgm-remote-monitor#6714]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sulkaharo** [comment]
Hi! Please fill in the descriptions in the request template if you want someone to pick things up. We have almost no resources to develop features and it's impossible to evaluate adding things if people who read the ticket don't have a clear idea of what's being asked.

**Comment by petervanrijt** [comment]
Sorry @sulkaharo, accidentally updated this too soon earlier this afternoon. I'll create a new feature request.
