### ISSUE TITLE
MongoDB Upgrade

### ISSUE THREAD

**Issue by inventor96** [nightscout/cgm-remote-monitor#6736]
Looks like it's time for another part of the system to be upgraded... MongoDB.com is sending out email notifications Ike the following to Nightscout users:

![Screenshot_20210111-142528](https://user-images.githubusercontent.com/7132744/104240414-42689d80-5419-11eb-9d81-b55baf09d729.png)

I haven't looked into the technical implications yet, but figured I'd start the discussion here for whoever is able to start the research and/or development.

**Comment by sulkaharo** [comment]
We run unit tests against 4.4 already and looks like at least everyone on 14.1 should be fine. Highly likely everyone who updated during the summer can just ignore Thai.

**Comment by inventor96** [comment]
Looks like they don't let you upgrade manually...

![image](https://user-images.githubusercontent.com/7132744/104242855-fb7ca700-541c-11eb-8e88-e85154108fc6.png)

Maybe worth an announcement in the Facebook group so people aren't worried about the email? @sulkaharo Do you have permissions to do that there?
