### ISSUE TITLE
calendar plugin

### ISSUE THREAD

**Issue by intelli-perl** [nightscout/cgm-remote-monitor#6759]
many apple / iWatch users and also android or carplay users struggle to
find a way to display bg values on their devices.
often sugarmate is suggested which somehow creates a so called calendar complication, so that the bg can be displayed.
it would be very nice to have a plugin which can be configured to create such a calendar event
can anybody help with this?

**Comment by sulkaharo** [comment]
Nightscout is a web application and doesn't run on the phone in a manner that it could change the data on the calendar to show the recent BG values. You'll have to find an iOS application that syncs data from Nightscout that can change the calendar data to do this.

**Comment by marekmand** [comment]
I would like to reopen the calendar plugin idea... 
The plugin could be similar to the Pushover plugin but instead of sending notifications it would create calendar events via Google API [https://developers.google.com/calendar/api/guides/create-events].

**Comment by EasternPA** [comment]
I've been thinking about whether iCal integration would work. It seems like this would be cleaner than allowing Nightscout to access my Google Account and make changes. You could then separate out normal vs abnormal readings to avoid getting a calendar event notification every five minutes for normal readings. As much as I like the thought of my watch buzzing every five minutes when I'm inside my normal range, I would like my watch to buzz whenever I am outside the normal range.

I also don't want my calendar littered with readings every five minutes, so every five minutes, my theoretical plugin would delete the prior reading and create a new one on either the "normal" or "not normal" calendar feed.
