### ISSUE TITLE
Inconsistent mmol conversion in sandbox

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#676]
Looks like displaySGV in buildBGNowLine is sometimes already converted to mmol and sometimes in mg/dl format. When in mmol mode, LOW notifications from simplealarms reports the current SGV in mmol but AR2 reports the current SGV in mg/dl. Didn't find cause immediately, something different in the execution path?

Following logging happening with the same configuration:

emitted notification: { level: 2,
  title: 'Urgent LOW',
  message: 'BG Now: 4.1 +0.2 ↗ mmol/L\nBWP: -0.57U\nIOB: 0.46U\nCOB: 0g',
  eventName: 'low',
  plugin: 
   { [Function: simplealarms]
     label: 'Simple Alarms',
     pluginType: 'notification',
     checkNotifications: [Function: checkNotifications],
     enabled: true },
  pushoverSound: 'persistent',
  debug: 
   { lastSGV: 4.1,
     thresholds: 
      { bg_high: 260,
        bg_target_top: 180,
        bg_target_bottom: 179,
        bg_low: 178 } },
  key: 'simplealarms_2' }

emitted notification: { level: 1,
  title: 'Warning, LOW',
  message: 'BG Now: 66 +0.5 ↗ mmol/L\nBG 15m: 3.8 mmol/L\nBWP: -0.77U\nIOB: 0.62U\nCOB: 6.8g',
  eventName: 'low',
  pushoverSound: 'persistent',
  plugin: 
   { [Function: ar2]
     label: 'AR2',
     pluginType: 'forecast',
     checkNotifications: [Function: checkNotifications],
     forcastAndCheck: [Function: forcastAndCheck],
     forecast: [Function: forecast],
     enabled: true },
  debug: 
   { forecast: { predicted: '3.7, 3.7, 3.8, 3.8, 3.9, 3.9, 4, 4.1, 4.1' },
     thresholds: 
      { bg_high: 260,
        bg_target_top: 180,
        bg_target_bottom: 80,
        bg_low: 55 } },
  key: 'ar2_1' }

**Comment by jasoncalabrese** [comment]
we probably shouldn't be passing `displaySGV` the sandbox methods, I'll try doing that in the `wip/bwp-with-ar2` branch since there are some other change in the same area

**Comment by jasoncalabrese** [comment]
I think think is fixed now in #678
