### ISSUE TITLE
Master/wip/rawbg-  units testing

### ISSUE THREAD

**Issue by DunePlodder** [nightscout/cgm-remote-monitor#680]
I have 2 Nightscout websites using commits c11d4c7fa0 & 1cfdc03dbf, the master & wip/rawbg-units branches. (Hoping I'm using the terminology correctly). I'm testing with mmol/l.
I have an xDrip box & use the xDrip app independently of, & to upload to Nightscout.

So far I've seen little difference in the output. The exception being small differences in Insulin on Board, e.g. earlier this morning the main site showed 0.62u, rawbg site was 0.55. Each was on the same upload time. I love the extra info "bubbles" when you hover over/tap BWP, IOB & COB by the way.

I made the suggestion in the Nightscout survey recently that the Care Portal becomes rather congested on a small screen especially when the soft keyboard takes up a lot of space. I have worked on data logging for land surveying & we concluded it was best to split the input into several screens, each with just 1 or 2 items/tick boxes. This allows larger text & buttons, useful for people with less than perfect eyesight as well as those with large fingers & in bad weather.
The screens would vary depending on which Treatment Event Type was selected in the first screen.

Most of my testing has been done with the Nightscout screens running on my PC browser so I was surprised by a message on "CGM in the Cloud" yesterday which pointed out that web based alerts won't happen if your mobile phone screen is switched off - obvious really of course.I know that you are working with Push & a method of Tweeting warnings but wouldn't it make sense to also do this from an app, like NightWatch. Perhaps collaborating with the xDrip team to add a Care Portal to NightWatch? 
Hope these suggestions are useful. Happy 4th July!
Regards
Robert

**Comment by sulkaharo** [comment]
Work to make it easier to integrate this to the watchfaces and other software is underway.

You should check the combo of enabling the predictive alarms (note bwp threshold config) and get a pushover license, which is $5 for lifetime. Pushover does push notifications to mobile regardless of whether the app is running. 

Sulka

**Comment by DunePlodder** [comment]
Thank you Sulka, I will sign up for Pushover.
Currently bidding for Pebble Watches on eBay - fingers crossed!
Robert

**Comment by jasoncalabrese** [comment]
I'm going to close this, if you have any issues while testing pushover and the dev branch, just open a new issue
