### ISSUE TITLE
Tokens reset in current Dev

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6838]
@sulkaharo 

Current Dev 14.2.0 seems to cause all predefined tokens/access keys to change. The names are the same, but the part after the dash was changed after updating from 14.1.0 (e.g. name-123wer34dg43ff).

This can cause quite a few issues for people using tokens, so if this is the case, it would be fair to give a warning (also for Dev).  We had to update quite a few devices and apps after this unexpected change.

Thanks

**Comment by bjornoleh** [comment]
Sorry, this is probably caused by a change in API_SECRET, I did not realise this would alter the tokens.

**Comment by sulkaharo** [comment]
I just pushed a fix to DEV that should revert the tokens to how they were before the recent security PR was merged in, please update and test.

**Comment by bjornoleh** [comment]
Ok, so now I learned that the tokens are altered if changing the API_SECTET, but also by updating from NS 14.1.0 to Dev 14.2.0. So this is a real issue to be aware of.

**Comment by bjornoleh** [comment]
> I just pushed a fix to DEV that should revert the tokens to how they were before the recent security PR was merged in, please update and test.

Ok, thanks, there you go!

**Comment by bjornoleh** [comment]
Thanks, the change in Dev now generates the same tokens as before in 14.1.0.

Now i will just have to reset all the tokens again, ugh! :-)

**Comment by isabel2149** [comment]
Unsubscribe.

I want to unsubscribe from all github emails, can I do that through replying to you?

Isabel

**Comment by sulkaharo** [comment]
@isabel2149 Practically 100% of Internet services put the unsubscribe link to the bottom of every email they send you - as does Github. Just scroll to the bottom of the email to see the link that allows you to unsubscribe.
