### ISSUE TITLE
Administration messages: Last recorded time at picosecond precision

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6839]
Administration messages give "Last recorded time" at something like picosecond precision:

![image](https://user-images.githubusercontent.com/63544115/106732722-51560080-6611-11eb-912f-fe14092afee0.png)

Current Dev 14.2.0.

**Comment by sulkaharo** [comment]
Everyone needs picosecond time precision, no? 😅

**Comment by bjornoleh** [comment]
I want everything down to the nearest femtosecond, thank you very much!

**Comment by sulkaharo** [comment]
I checked and I could use decimal.js to give you any of digits of precision, just tell me how many you want!

**Comment by sulkaharo** [comment]
Should be fixed in dev now

**Comment by bjornoleh** [comment]
Hm

Every other minute it looks ok, then it's like this:
![_20210204_235810](https://user-images.githubusercontent.com/63544115/106966327-659b1a00-6745-11eb-81a6-8c9f95cf0ee0.JPG)

**Comment by bjornoleh** [comment]
The reports of failed auth for >1h ago are okay at 1/100th hour precision, but I suppose 1\10th of an hour (6 min) would suffice.

**Comment by bjornoleh** [comment]
@sulkaharo

OK, the buggy time reports are for faulty auths that are less than 1 minute old. So you should have a look at times that are reported in seconds.

![_20210205_090726](https://user-images.githubusercontent.com/63544115/107007287-9b1a2480-6792-11eb-89b3-84edc04144a0.JPG)

![_20210205_090651](https://user-images.githubusercontent.com/63544115/107007317-a79e7d00-6792-11eb-9e5e-ad63ca4bd257.JPG)

**Comment by bjornoleh** [comment]
Looks fine now
