### ISSUE TITLE
Temporary overrides for Loop does not work from NS Careportal in current Dev 14.2.0

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#6841]
Temporary overrides for **Loop** does not seem to work from NS Careportal in current Dev 14.2.0.

Same result with Safari iOS, and Chrme in windows or Android.

Have tried deleting cashe from browser (Win Chrome), no effect.

Tested authentication both with api secret and with token (read and write permission)

![image](https://user-images.githubusercontent.com/63544115/106748552-b156a200-6625-11eb-826a-0832300acc93.png)

Error message:
-
![image](https://user-images.githubusercontent.com/63544115/106748742-ee229900-6625-11eb-8f4d-03879cc6adb1.png)
-

@sulkaharo, perhaps something was broken for Loop remote overrides recently? Is it working for AAPS? NS master 14.1.0 is working with Loop.

**Comment by sulkaharo** [comment]
That error dialog doesn't look like it's from Nightscout? Where is the error from?

**Comment by bjornoleh** [comment]
@sulkaharo Sure, it's from NS in Chrome on Win10

**Comment by bjornoleh** [comment]
![image](https://user-images.githubusercontent.com/63544115/106754221-fdf1ab80-662c-11eb-848a-485d9f097608.png)




![image](https://user-images.githubusercontent.com/63544115/106754118-dd295600-662c-11eb-8a61-49b271efa152.png)

**Comment by sulkaharo** [comment]
Ping @ps2 - I have no means to debug this myself as I'm not on Loop and don't have this setup

**Comment by bjornoleh** [comment]
@sulkaharo if you have an idea about which commit might have caused this, I could always see if reverting it will make a difference. I will roll back to 14.1.0 for now.

**Comment by sulkaharo** [comment]
What could help is, can you capture the server-side log when you use the feature, so we can see if something is logged in that end. There's multiple commits that have touched the server, so when someone fixes this, I'll ask for a unit test that'd have caught this...

**Comment by bjornoleh** [comment]
@sulkaharo 

remote override to LoopHere is a snippet from the logs that are related to sending the O

```
2021-02-03T19:08:00.584179+00:00 heroku[router]: at=info method=POST path="/api/v2/notifications/loop" host=xxxxxxx.herokuapp.com request_id=833df9ec-fabf-4f0c-a360-79835a56278f fwd="158.xxx.xx.75" dyno=web.1 connect=1ms service=19ms status=500 bytes=759 protocol=https
2021-02-03T19:08:00.575985+00:00 app[web.1]: error sending notification to Loop:  Loop notification failed: Unhandled event type:
```

**Comment by sulkaharo** [comment]
Right - I checked on this last night and I can't find find anything that'd have change that would cause this. The error you're seeing is from the server reporting it the event type that can be seen the confirmation dialog wasn't actually received by the server, which is odd. Ping @josep1972 and @altaired - I'd love to make a release soon so confirming DEV works for you and/or detecting the issue asap would be great.

**Comment by bjornoleh** [comment]
@sulkaharo I just checked if anything would show up in the debug mode while the Loop phone was plugged into Xcode. But no, nothing there. Perhaps it was already clear that no communication is going to Loop.

I'm back to Master now, where remote overrides are working as usual.

**Comment by sulkaharo** [comment]
@bjornoleh This should now be fixed in DEV

**Comment by bjornoleh** [comment]
@sulkaharo Confirmed, thanks!

**Comment by bjornoleh** [comment]
@sulkaharo 

Other careportal entries are also failing now, I don't know if that was the case before the latest fix or not.

Both BG Check and Notes give the error "Saving failed. Status 400" (or Status 500) 

![Screenshot_20210209-031551~2](https://user-images.githubusercontent.com/63544115/107307208-8c7b8800-6a86-11eb-9e0a-2d0d8433c20c.png)

**Comment by sulkaharo** [comment]
Fixed in dev. So many use cases to add to the unit tests.... 😬

**Comment by bjornoleh** [comment]
Thanks, the careportal entries I have tried so far is working fine now.

Better put those robots at work! :-)
