### ISSUE TITLE
Invalid request causes crash of nightscout (potencial DoS)

### ISSUE THREAD

**Issue by maskac** [nightscout/cgm-remote-monitor#6843]
version of socketio client 2.3.0, nightscout 14.1.0

Sample code:
const io = require("socket.io-client");
const socket = io.connect('ws://url-of-nightscout/');
socket.emit("authorize");

Log of NS:
/opt/app/lib/server/websocket.js:87
    ctx.authorization.resolve({ api_secret: message.secret, token: message.token, ip: ip }, function resolved (err, result) {
                                                    ^

TypeError: Cannot read property 'secret' of undefined
    at verifyAuthorization (/opt/app/lib/server/websocket.js:87:53)
    at Socket.authorize (/opt/app/lib/server/websocket.js:503:9)
    at Socket.emit (events.js:315:20)
    at /opt/app/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by sulkaharo** [comment]
Should be fixed in DEV now

**Comment by sulkaharo** [comment]
@maskac can you verify if you can replicate in dev?

**Comment by maskac** [comment]
The dev version is not crashing anymore.Dev #6862
