### ISSUE TITLE
Português translation is unavailable on Drop Menu on the lastest DEV.

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/cgm-remote-monitor#6854]
I can be wrong but this commit https://github.com/nightscout/cgm-remote-monitor/commit/157eddfe263824f82fc51098f8487b6c5846eb35 should do it, but when I deploy the latest DEV. I am unable to choose Portuguese from Drop Menu.

![image](https://user-images.githubusercontent.com/608650/107300243-09036c00-6a71-11eb-9203-92491aca6193.png)

**Comment by sulkaharo** [comment]
Double check you deployed the latest and/or that your client is not caching some old version of the client. (I can see it in our install.)

**Comment by parapenT1sta** [comment]
@sulkaharo The auto deploy wasn't working properly, I just had force it with a manually deploy and it's working. Thank you for remembering about the deploy in Heroku.

![image](https://user-images.githubusercontent.com/608650/107497986-20367c80-6b8b-11eb-82a0-a557954708a1.png)

**Comment by miguelpruivo** [comment]
It looks like I can't see it again both on master/dev at 14.2.2.
