### ISSUE TITLE
versionNum not correctly generated and transmitted to AAPS

### ISSUE THREAD

**Issue by guydavies** [nightscout/cgm-remote-monitor#6861]
The change in commit 4a9f492e causes AAPS to raise an INFO message "Unsupported Version of Nightscout" because versionNum is not being correctly created and/or transmitted to AAPS following this commit.

I tried with the latest dev build based on commit c24d0f9b and the latest AAPS dev build.  This shows the issue.  Having traced through the AAPS code, it was clear that versionNum was the source of the problem.  I looked into the AAPS logs and found this.

10:57:24.653 [NSClientServiceHandler] D/NSCLIENT: [NSSettingsStatus.handleNewData():137]: Received status: {"status":"ok","name":"nightscout","version":"14.2.0","versionNum":null,"serverTime":"2021-02-11T09:57:24.520Z"

note the "versionNum": null.

I searched back through the changes in NS since I last updated and found the commit 4a9f492e, which changes the mechanism through which versionNum is derived.  I believe this has broken the mechanism.

I reverted just that single commit in my own dev build and found that AAPS no longer raises the alert on restarting.  The logs now show this.

16:05:39.548 [NSClientServiceHandler] D/NSCLIENT: [NSSettingsStatus.handleNewData():137]: Received status: {"status":"ok","name":"nightscout","version":"14.2.0","versionNum":140200,"serverTime":"2021-02-11T15:05:39.400Z"

Here, you can see "versionNum": 140200

I discussed some of my thinking in the Nightscout_developers channel on Discord.  I'm not a very good coder in any language but I have next to zero experience in JS, so I'd rather not mess around with the code too much.

**Comment by sulkaharo** [comment]
Should be fixed in dev

**Comment by guydavies** [comment]
Confirmed fixed in dev
