### ISSUE TITLE
Gaps in reading. How much data can nightscout retrieve?

### ISSUE THREAD

**Issue by Vukasin90** [nightscout/cgm-remote-monitor#6866]
Hi, everyone. 

I'm wondering if this is a bug, or it's just the way it works. But, it seems that nightscout can only retrieve only a small portion of data (I'd say about 20 minutes), and if I don't scan for some time, it simple doesn't show the data, even though, sensor can store up to 8 hours of data.

So, is there a way to fix this? 

Thanks :)

**Comment by sulkaharo** [comment]
Hi! This respository is about the Nightscout cloud service, which doesn't directly interface with any devices. Sounds like you need to get in touch with the developer of the mobile app you're using to scan your sensor (sounds like you're on Libre?).

**Comment by Vukasin90** [comment]
> Hi! This repository is about the Nightscout cloud service, which doesn't directly interface with any devices. Sounds like you need to get in touch with the developer of the mobile app you're using to scan your sensor (sounds like you're on Libre?).

Yes, libre. And I'm using Glimp to scan it, but on glimp, I'm getting a 8 hours of data, or in other words, I can wait 8 hourse to scan, and I'll get the data for past 8 hours. But, for some reason, I'm not getting that on Nightscout app. 

So, where's the problem? Is it the Glimp app that is not sending everything, or does the Nightscout have some limitations?

**Comment by sulkaharo** [comment]
That sounds like Glimp is not sending everything. The Nightscout API has no restrictions that'd prevent uploading a full history, even dating back years.

**Comment by Vukasin90** [comment]
> That sounds like Glimp is not sending everything. The Nightscout API has no restrictions that'd prevent uploading a full history, even dating back years.

Ok, thank you. I just wanted to see if I need to setup anything from Nightscout side. But, I guess not. :)
