### ISSUE TITLE
Docker-Image Tag:latest_dev crashes

### ISSUE THREAD

**Issue by swissalpine** [nightscout/cgm-remote-monitor#6872]
I use the official docker image https://registry.hub.docker.com/r/nightscout/cgm-remote-monitor/
Unfortunately the image on my Synology Nas crashes lately, at least the version with the tag "latest_dev", and that with all versions since about 10 days. The version with the tag "latest" (14.1.0) runs fine.
Here is the error message that repeats in a circle after each reboot:

```
Error: Cannot find module '/opt/app/server.js'
 
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
 
 at Function.Module._load (internal/modules/cjs/loader.js:725:27)
 
 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
 
 at internal/main/run_main_module.js:17:47 {
 
 code: 'MODULE_NOT_FOUND',
 
 requireStack: []
 
}
 
internal/modules/cjs/loader.js:883
 throw err;
 ```
I appreciate any help or a bug fix.

**Comment by sulkaharo** [comment]
Do you have the latest latest_dev installed or did you just pull it at one point? The file was broken for a while, but should work now

**Comment by swissalpine** [comment]
Thanks for coming back!
Just to be sure, I just deleted the container completely again, re-downloaded the file with the tag "latest_dev" and started it: Same error message.

**Comment by pazaan** [comment]
Hi @swissalpine. My own environment is running the latest from `nightscout/cgm-remote-monitor:latest_dev`, and I don't get this message at all.
The current `nightscout/cgm-remote-monitor:latest_dev` image doesn't have a file called `/opt/app/server.js`. Is it possible that you have a wrapper (perhaps a docker-compose setup) to launch the image, which is overriding the Docker COMMAND? If so, you:
1) Either don't need to override it; or
2) Need to change the command to `lib/server/server.js`, to match [the contents of the `dev` `Dockerfile`](https://github.com/nightscout/cgm-remote-monitor/blob/dev/Dockerfile#L18).

**Comment by swissalpine** [comment]
@pazaan 
Thanks a lot! This was the hint!
In my settings I found the variable `"cmd" : "node server.js"`. I deleted this setting in my json-file and: "Here we go!"
