### ISSUE TITLE
Dexcom share problems EU

### ISSUE THREAD

**Issue by xxbyxx** [nightscout/cgm-remote-monitor#6895]
Hi folks, 

I tried to set up NS at heroku for the first time but get no cgm values from dexcom. 
BRIDGE_PASSWORD and BRIDGE_USER_NAME are correct as i am able to login at https://clarity.dexcom.eu 
BRIDGE_SERVER is set to "EU"

It seems that there is not any request to the dexcom server. I tried to set wrong username to provocate a failure log at Heroku application logs, but nothing changed. 

Du you have some hints for me? 

BR

**Comment by psonnera** [comment]
Did you follow this? https://nightscout.github.io/troubleshoot/troublehoot/#dexcom-data-not-showing

**Comment by xxbyxx** [comment]
Thanks for reply. Yes i followed this guide. 
Dexcom share is active and i can see cgm data on any iphone/android device with the dexcom follow app. 

The problem seems to be at the interface with NS

Does it help if i copy application logs?

**Comment by bewest** [comment]
Howdy @xxbyxx, I am the maintainer for the dexcom share plugin.  Can you help me understand if it may be possible that other apps besides the Dexcom mobile app and Nightscout are signed into Dexcom Share?  Common apps include Loop, Glance, Sentinel, Happy Bob, SugarMate, etc...

From your description, it sounds like it's possible that the plugin is not yet fully enabled.  In addition to the things you mention, please ensure that the keyword `bridge` is included in your `ENABLE` list.

**Comment by xxbyxx** [comment]
Hi bewest, glad to hearing from you. 

Let me explain my setting briefly: 
Dexcom G6 app is running on my wifes iPhone. I am using Dexom follow app on my Android Device and also an my iPad. I can receive cgm values on my devices and the system is running stable since month. 
As the alerts and notifications in the Dexcom follow app are not working reliable, i wanted to forward cgm data from my wifes iPhone, over Dexcom share servers to a Nighscout interface with the plugin. I do not want to integrate her pump in the first step. 

I just copied my heroku config vars:

BRIDGE_PASSWORD: "Dexcom passwort" (works fine with Dexcom login)
BRIDGE_SERVER: EU
BRIDGE_USER_NAME: "Dexcom username" (works fine with Dexcom login)
ENABLE: "careportal basal dbsize rawbg iob maker **bridge** cob bwp cage iage sage boluscalc pushover treatmentnotify mmconnect loop pump profile food openaps bage alexa override speech cors"


I hope my explanation helps you

**Comment by psonnera** [comment]
Can you confirm your Clarity user name only has letters as mentioned here https://nightscout.github.io/troubleshoot/troublehoot/#dexcom-username-issue ?

**Comment by xxbyxx** [comment]
Sorry for my late response. It seems that the GitHub notification was catched by my spam filter. 

@psonnera  I have double checked and unfortunately the user name looks like "firstname.lastname". As described in the guide this could be the reason for my problems. 

I am not able to change the username atm. It is connected to the system of my wife's doctor and she has to arrange with him in order to not loose any values.

Is there any possibility to fix the bug without changing the username? 

BR

**Comment by psonnera** [comment]
Not that I know... maybe you could use xDrip+ on your phone as a Dexcom share follower and have your phone upload to Nightscout?

**Comment by bewest** [comment]
@xxbyxx are you able to sign in using Dexcom Clarity on the web (sounds like yes, from your comment earlier)?
* https://clarity.dexcom.com/
* https://clarity.dexcom.eu/

While not ideal, it is possible to create a new account and share that one with the doctor as well.
It is possible to fix this issue given some more details and documentation from Dexcom.
The proper place for this discussion would be https://github.com/nightscout/share2nightscout-bridge/issues/37, so let's head over there and close the issue here.
