### ISSUE TITLE
Add BGI (blood glucose impact) pill

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#690]
Maybe part of a new iob-cob plugin
##

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3
