### ISSUE TITLE
Extract data loading from client.js and align data model with server

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#691]
Get rid of the `x` and `y` fields, use milliseconds for in-memory date/timestamp values
##

**Comment by jasoncalabrese** [comment]
my comments from gitter :point_up: [July 8, 2015 10:55 PM](https://gitter.im/nightscout/public?at=559e0cbc9399a9015e9b528c):

>
  think I'm going to stick with the new .mills field for now, nice to have a new name so it's easier to verify all code was updated
  next up is finding a common field name for `.y`, `.sgv`, `.mbg`, `.glucose`, and `.displayBG`
  I want a single field name that is used for the glucose level on the y axis

>
  thinking about calling it `.dgl` (display glucose level)
  that would be the prescaled value in the display units

>
  there would be 2 other fields for actual values, with a different name based on the source units
  something like `.mgdl` and `.mmol`
  you'd have 1 or the other, never both
  value from the dex would be in `.mgdl`, but care portal entries when display is in mmol mode would be in `.mmol`

>
  this is in memory only, using the current mongo/api/pebble schemas

**Comment by jasoncalabrese** [comment]
@sulkaharo, @bewest, any thoughts on these changes to the in memory data model?

**Comment by sulkaharo** [comment]
I guess my question is, how do we reduce the load on programming against the in-memory model to as little as possible? What space do we do the math in? Whatever we do, I'd love it if most of the time any code would not need to do any unit checking to function correctly. And please tell me if that's not effectively possible. :)

**Comment by sulkaharo** [comment]
Regarding naming, I'm a fan of descriptive variable names. So .milliseconds would possibly be better. ;) For glucose, using the units in variables that guarantee the units is obviously good. .dgl feels a bit arbitrary?

**Comment by jasoncalabrese** [comment]
`.mills` is already all over the place but could be replaced `.milliseconds` feels too long, is `.ms` any better?

I'm not a fan of `.dgl`either, but I want something that could be used for anything we want to put on the timeline.  So it's not bg, sgv, egv, mbg, since those seem to be more specific.

To use the `.mgdl` and `.mmol` fields I think you'd use a function like:

```javascript
function toDisplay (entry) {

}
```

**Comment by jasoncalabrese** [comment]
`.x` => `.mills` was completed in #694

`.y` => `.mdgl`, `.mmol`, `.scaled` is being worked on in #702
