### ISSUE TITLE
Official Docker image for Nightscout on linux/arm64

### ISSUE THREAD

**Issue by ireneusz-ptak** [nightscout/cgm-remote-monitor#6932]
I would like to use an official NS docker image on my RPI 4, but there is none so I can't and I don't like it.
Please add automated CI build for linux/arm64 (and maybe others as well?).

How do I assign it to @pazaan ? ;)

**Comment by sulkaharo** [comment]
Looks like there's no recent MongoDB available for the ARM64? If so, that basically means you can't run a full Nightscout stack on the RPI.

**Comment by ireneusz-ptak** [comment]
There is an official one (at least for v8):
https://hub.docker.com/layers/mongo/library/mongo/bionic/images/sha256-cdf3e3a8fca1c8eebd9cfbca2966b1e03123febbcf6e93e2c88d043594d186a8?context=explore

**Comment by walczakkamil** [comment]
I`m using Nightscout stack on RPI 4 with 4GB RAM:
https://github.com/walczakkamil/Nightscout_for_RPI4
But this not official release. 
One problem i see now is that Docker Hub will not build automaticaly images for ARM.

**Comment by pazaan** [comment]
@sulkaharo The only other challenge I can see is that GA has no direct support for arm64 agents. We could spin up "self-hosted runners". Not sure if we want to go into that? I feel that if we wanted to build an official arm64 image, that we'd also want to have the capability to test it.

**Comment by pazaan** [comment]
Oooh. Just came across [this guy](https://github.com/uraimo/run-on-arch-action).

**Comment by Kywalh** [comment]
I'm trying to make it run on a router in France called Freebox that can run VM but it is a ARM64 architecture so +1 to the issue.

**Comment by lightswitch2159** [comment]
Why not [this PR](https://github.com/nightscout/cgm-remote-monitor/pull/7043)?
