### ISSUE TITLE
mini report for doctor

### ISSUE THREAD

**Issue by mo211073bkp** [nightscout/cgm-remote-monitor#6956]
Hello,
How do I make a report for the selected period in the form of a table in which the data will be summarized as in the picture or or similar?
![table](https://user-images.githubusercontent.com/46835974/111217672-dfe17880-85e6-11eb-841e-2eecc8dd9af5.png)

**Comment by psonnera** [comment]
I think you can get most of this data from here https://nightscout.github.io/nightscout/reports/

**Comment by mo211073bkp** [comment]
Thanks for the advice. I found another option to create reports: 
[Setting-up-NightScout-Reporter.pdf](https://github.com/nightscout/cgm-remote-monitor/files/6151224/Setting-up-NightScout-Reporter.pdf)
 https://nightscout-reporter.zreptil.de/

This topic is closed.
