### ISSUE TITLE
Requesting data via the v1 API using the "count" parameter and token-based auth returns a 401 error. 

### ISSUE THREAD

**Issue by jauntySerpent** [nightscout/cgm-remote-monitor#7042]
**Describe the bug**
After enabling token-based authentication on my Nightscout site, my OpenAPS rig is able to publish treatments and devicestatus, but it is unable to retrieve glucose entries. Troubleshooting revealed requesting data via the v1 API using a URL that contains the "count" parameter and token-based auth returns a 401 error. 

**To Reproduce**
1. Enable token-based auth and set AUTH_DEFAULT_ROLES to "denied"
2. Attempt to get data from Nighscout's API using a browser. For example, https://NIGHTSCOUT_URL/api/v1/entries/sgv.json?count=10?token=SOME_TOKEN
2. Nightscout returns a 401 Unauthorized error. 
3. Remove the "?count=10" from the URL
4. The API returns data

A URL containing the "count" parameter functions as expected if token-based authentication is disabled.
1. Disable token based auth
2. Navigate to the same URL as before: https://NIGHTSCOUT_URL.herokuapp.com/api/v1/entries/sgv.json?count=10?token=SOME_TOKEN
3. The API request is successful and data is returned.

**Expected behavior**
API calls with parameters such as "count" should function when using token-based auth. 

**Screenshots**
Attempt to access https://NIGHTSCOUT_URL/api/v1/entries/sgv.json?count=10?token=SOME_TOKEN without AUTH_DEFAULT_ROLES set:
![auth_default_roles_permitted](https://user-images.githubusercontent.com/15910886/120565655-916c9a80-c3db-11eb-9e71-9ac84abc99b6.jpg)

Attempt to access https://NIGHTSCOUT_URL/api/v1/entries/sgv.json?count=10?token=SOME_TOKEN with AUTH_DEFAULT_ROLES set to denied:
![auth_default_roles_denied_401_error](https://user-images.githubusercontent.com/15910886/120565665-9598b800-c3db-11eb-8dba-e729f9184baf.jpg)

Access attempt is successful when AUTH_DEFAULT_ROLES is set to denied if the count parameter is removed.
![auth_default_roles_success](https://user-images.githubusercontent.com/15910886/120565719-afd29600-c3db-11eb-8a1f-6cad1a774b85.PNG)

**Your setup information**
- Nightscout version 14.2.2
- Dexcom G6, xDrip+, OpenAPS
- Issue replicated on both Chrome and Firefox

**Additional context**
Tested tokens include several with "admin" role and the OpenAPS role with the following permissions (listed below):
api:devicestatus:create,
api:devicestatus:read,
api:entries:create,
api:entries:read,
api:profile:create,
api:profile:read,
api:treatments:create,
api:treatments:read

I am unsure if this is the root cause of my issues with OpenAPS, but it did not appear to be expected behavior.

**Comment by Aiden-Xi** [comment]
yes, I encountered the same problem! !   

I ask for help again.

**Comment by miklosz** [comment]
Same here, upvoting!

**Comment by sulkaharo** [comment]
This should work. Note the URLs in the original description are broken and don't follow the URL encoding, so one of the GET parameters is ignored. The correct way to include GET parameters is to separate the GET section from the URL with a question mark (?) and then separate the subsequent parameters using the ampersand (&). Also note the parameter names and data has to be URL encoded in case they include any reserved characters like ? and &. So the correct URL format is

https://NIGHTSCOUT_URL/api/v1/entries/sgv.json?count=10&token=SOME_TOKEN

Note the second ? has been replaced by an &.

Please reopen if this does not work.
