### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/cgm-remote-monitor#7129]
**Describe the bug**
NS stops displaying treatments. This includes OpenAPS insulin, temp basal rates. Visually this propagates to NSClient also.

ns-looplog on OpenAPS shows the following error - probably a HTML page being served up by the NS API when it shouldn't be...

```
Refreshed carbhistory; COB: 0
{"batteryVoltage":3647,"battery":45}
{"BG":92,"IOB":0.442,"rate":null,"duration":null,"units":null}
Latest NS treatment: 2021-10-12T06:08:32.000Z
<html>
  <head>
    <meta charset='utf-8'>
    <title>PayloadTooLargeError: request entity too large</title>
```

Looking at Atlas DB, all writes cease, as if NS has locked up. Dropping the treatments collection temporarily fixes things, but the lock up returns.

I have 4 clients. This happens on Master and Dev NS.

- 2 x OpenAPS edison rigs
- xDrip (uploading BG)
- NSClient for monitoring / care portal.

**Comment by old-square-eyes** [comment]
@bewest am I in the right dir?

```
root@apsgreen:~/myopenaps# ls -alh upload
total 228K
drwxr-xr-x  2 root root 4.0K Oct 13 17:55 .
drwxr-xr-x 11 root root 4.0K Oct 10 13:40 ..
-rw-r--r--  1 root root 215K Oct 13 17:55 latest-treatments.json
-rw-r--r--  1 root root 1.3K Oct 12 22:18 recent-pumphistory.json
root@markapsgreen:~/myopenaps#
```

and

```
root@apspiw:~/myopenaps# ls -alh upload
total 12K
drwxr-xr-x  2 root root 4.0K Oct 13 16:57 .
drwxr-xr-x 11 root root 4.0K Sep 12 17:25 ..
-rw-r--r--  1 root root    0 Oct 13 17:56 latest-treatments.json
-rw-r--r--  1 root root 1.4K Oct 12 18:48 recent-pumphistory.json
```

**Comment by bewest** [comment]
Yes, perfect, @old-square-eyes.  Thanks for the information.  Your file is 215K, which is more than the 100K limit being enacted currently.  I'm currently testing with a similar file, which contains 30k records in it.  My `wip/bewest/request-body-limit` feature branch should help address this issue: https://github.com/nightscout/cgm-remote-monitor/pull/7131

**Comment by old-square-eyes** [comment]
@bewest is this ready for me to test? Or is it a work in progress (as wip might suggest)

**Comment by old-square-eyes** [comment]
@bewest I tried your feature branch and it's been working for 6 hours so far. Thank you my friend! This was a great source of distress and it means a lot for you to have jumped on this. Frankly I have no idea why I seem to be one of only a few with the issue. I have no idea why I had a large upload. The rig in question is a daily driver so shouldn't have gone offline for any length of time necessitating a big upload when returning online.

**Comment by old-square-eyes** [comment]
Autotune is working again per https://github.com/openaps/oref0/pull/1410
