### ISSUE TITLE
Use of "upsert" to insert/update records

### ISSUE THREAD

**Issue by ochenmiller** [nightscout/cgm-remote-monitor#721]
When inserting sgv records into mongo I've been using the "upsert" option - I create a unique key from the date string (date/300000). This has been very useful as I can insert records from several devices and don't have to worry about cluttering up the db with duplicate records. Also, it's made the creation of calibration records from share data much easier. I'd be happy to coordinate.
##

**Comment by savek-cc** [comment]
Planing to use a network of multiple wixels around house and work to catch my G4 signal. Each node would be capable of uploading the current reading to NS - but the same reading might be captured and thus uploaded by multiple nodes.
Having a reading de-duplication would be essential for this scenario.

**Comment by PieterGit** [comment]
Isn't using https://github.com/jamorham/python-usb-wixel-xdrip a much better solution for this?

**Comment by savek-cc** [comment]
That only works if you can assign static IPs to the collectors/nodes - and still requires a phone with xDrip+ to be on the same network. I want the nodes to directly upload in order to not have an xDrip+ dependency and also work on networks I don't control (workplace, hotel-wifi etc).

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3

(Also - I believe are already upserting the data now, please re-file if not.)
