### ISSUE TITLE
Basal Profile - School day different to weekend

### ISSUE THREAD

**Issue by StuArnold** [nightscout/cgm-remote-monitor#722]
Just discussing with Kate Groves she has different basal rates on a schoolday versus the weekend. Is it possible to have different profiles on different days or to hold multiple profiles that can be switched on and off easily?. Can see that it would make a very complex profile if we had to have a profile per day.

I have just copied my profile to a TXT file to see if I can keep multiple copies that I can just copy and paste as required into Mongolab.

Thanks
##

**Comment by StuArnold** [comment]
Another comment in UK Nightscout FB page about using multiple profiles for Basal rates. Is this possible? or is there an easy workaround? Thanks

![image](https://cloud.githubusercontent.com/assets/10799221/9681366/719784fc-52f5-11e5-87bb-bc8ffa988aeb.png)

**Comment by jasoncalabrese** [comment]
Would be nice to be able to pick a profile, we have multiple profiles now but I don't think it's understood, and mostly for historical information

**Comment by sulkaharo** [comment]
Hi! In process of cleaning up the project Github and closing old issues. If you still care about the this issue, please install the latest version of Nightscout (as of right now, the Habanero release) and report based on how the software has changed compared to what Nightscout was compared to the point in time when you created the ticket. Thank you for caring about Nightscout to the point of having reported a ticket - hope the software has been useful for you. <3

**Comment by StuArnold** [comment]
Hi Think this was resolved when multiple profiles was introduced. Love Nightscout and thanks for all you do
Stuart
