### ISSUE TITLE
BG delta calculated wrong on current dev

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#724]
Probably rounding somewhere
left enchilada - right dev
![image](https://cloud.githubusercontent.com/assets/11146458/8794092/cea9ec00-2f7f-11e5-9725-ad58da5ccb0e.png)

**Comment by MilosKozak** [comment]
enchilada is correct

**Comment by jasoncalabrese** [comment]
Is this still a problem, of so think we need to get a fix in really soon

**Comment by MilosKozak** [comment]
![image](https://cloud.githubusercontent.com/assets/11146458/9568303/e4b1d3ba-4f45-11e5-9146-b30a6718668c.png)

**Comment by MilosKozak** [comment]
dev still wrong

**Comment by jasoncalabrese** [comment]
Maybe the conversions are happening before calculating the deltas, would be more accurate, but would look wrong

**Comment by jasoncalabrese** [comment]
Yup, thats whats happening: https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/delta.js#L55

**Comment by MilosKozak** [comment]
it looks strange whe you see BGs 4.7 .... 4.7 .... and diff -0.1

**Comment by jasoncalabrese** [comment]
I'll change it to do the conversions before doing the calculation
