### ISSUE TITLE
Nightscout crashing

### ISSUE THREAD

**Issue by etaiaps** [nightscout/cgm-remote-monitor#7349]
**Describe the bug**
Today I was testing some basic API - only GET (devicestatus, status, ...) in a browser, shortly after that I noticed my nightscout site is down. 
"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command"

I see this in the heroku log (repeating every few seconds):
`2022-02-25T16:52:41.047300+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/socket.io/?EIO=3&transport=polling" host=NIGHTSCOUT_URL request_id=cfe6a152-5cf1-477e-b6f4-8fd8aefd00a0 fwd="IPADDRESS" dyno= connect= service= status=503 bytes= protocol=https`

Also time to time these messages:
`2022-02-25T17:04:19.854987+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=NIGHTSCOUT_URL request_id=3f732a75-9b1f-419a-8216-aeb32b74964d fwd="IPADDRESS" dyno= connect= service= status=503 bytes= protocol=https`
`2022-02-25T17:04:22.342875+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/sw.js" host=NIGHTSCOUT_URL request_id=7914d53d-749e-43fe-bd8f-65b5cc7b48a3 fwd="IPADDRESS" dyno= connect= service= status=503 bytes= protocol=https`

Tried restarting dynos, deploying from github, creating new application in heroku from scratch, nothing helped.

**Setup information**
- Nightscout 14.2.5
- Dexcom G6 (xDrip as collector)
- AndroidAPS
- NOT specific to a browser or a device

Any ideas what could be the problem and how to fix it?

Thank you guys!

**Comment by etaiaps** [comment]
Started working by itself after a few hours. Still I would be interested in what caused it.

**Comment by reijoahola-nightscout** [comment]
Check could it be this problem. https://github.com/nightscout/AndroidAPS/issues/1279
