### ISSUE TITLE
how can i run multiple night scout users?

### ISSUE THREAD

**Issue by Fiark** [nightscout/cgm-remote-monitor#7374]
how can i run multiple night scout users?

**Comment by psonnera** [comment]
https://nightscout.github.io/nightscout/multiadmin/

**Comment by Fiark** [comment]
i neeed this for local server with local db and local proxy
i have vps server and 1 working nightscout
i need 2 nightscout in 1 vps with docker

**Comment by viq** [comment]
1. Get Nightscout running in Docker
2. Might be useful to get MongoDB running in Docker
3. Either create another database in same MongoDB, or run another instance of MongoDB
4. Run another instance of Nightscout
5. Run nginx (or caddy) in front, proxying traffic to Nightscout instance depending on hostname used.

**Comment by bewest** [comment]
Right, at a minimum you will need different database for two Nightscout sites.  See https://nightscout.github.io/.  For what its worth, one subscription at T1Pal allows managing up to 5 Nightscout sites; this might be a great option if you are not comfortable with the server technology.
