### ISSUE TITLE
Build of current dev is failing on Heroku

### ISSUE THREAD

**Issue by yeagerm** [nightscout/cgm-remote-monitor#7475]
**Describe the bug**
From log of build attempt:
```
-----> Installing dependencies
       Installing node modules
       npm ERR! code EBADPLATFORM
       npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
       npm ERR! notsup Valid OS:    darwin
       npm ERR! notsup Valid Arch:  undefined
       npm ERR! notsup Actual OS:   linux
       npm ERR! notsup Actual Arch: x64
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.mWHMw/_logs/2022-07-07T17_23_13_488Z-debug-0.log
-----> Build failed
```

**Comment by psonnera** [comment]
Same here, [cgm-remote-monitor](https://github.com/nightscout/cgm-remote-monitor/tree/dev)/package-lock.json specifies darwin as the OS and that's not what's Heroku wants...

**Comment by sulkaharo** [comment]
As discussed with Ben in private, the issue seems to be the lock file in the repo has been generated with a newer version of npm than the npm version in package.json. Heroku honors the defined node and npm versions, which then fail to interpret the file in the repo

**Comment by bewest** [comment]
```
  "engines": {
    "node": "^16.x || ^14.x || ^10.22.0 || ^12.18.4",
    "npm": "^8.x || ^6.14.6"
  },
```
I've removed the `npm` requirements line and regenerated `package-lock.json` using node 10.x via `n 10`.  This lets the build succeed assuming the lowest common denominator is chosen.
https://github.com/nightscout/cgm-remote-monitor/pull/7487

**Comment by sulkaharo** [comment]
We should be able to remove Node 10 and 12 from the officially supported versions, as these are not maintained anymore. OpenJS lists Node 14 as the Maintenance LTS version: https://nodejs.org/en/about/releases/

**Comment by bewest** [comment]
Node 10, 12, and 14 produce identical package-lock.json files using npm 6.

**Comment by bewest** [comment]
Should be resolved.
