### ISSUE TITLE
NPM error on dev

### ISSUE THREAD

**Issue by bartsluimer** [nightscout/cgm-remote-monitor#7490]
When building latest dev we have the following error;

-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  ^16.x || ^14.x || ^10.22.0 || ^12.18.4
       engines.npm (package.json):   ^8.x || ^6.14.6
       
       Resolving node version ^16.x || ^14.x || ^10.22.0 || ^12.18.4...
       Downloading and installing node 16.16.0...
       Bootstrapping npm ^8.x || ^6.14.6 (replacing 8.11.0)...
       npm 8.14.0 installed
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules
       npm ERR! code EBADPLATFORM
       npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
       npm ERR! notsup Valid OS:    darwin
       npm ERR! notsup Valid Arch:  undefined
       npm ERR! notsup Actual OS:   linux
       npm ERR! notsup Actual Arch: x64
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.6l6Cn/_logs/2022-07-19T06_45_43_856Z-debug-0.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by psonnera** [comment]
https://github.com/nightscout/cgm-remote-monitor/pull/7487

**Comment by bewest** [comment]
Believe this is fixed, closing.
