### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by jossellr** [nightscout/cgm-remote-monitor#7545]
Dear developers.
I miss some method for exporting raw data. E.g. CSV format. Currently, I am interested in diabetes related research, but people using this tool cannot easily provide me with such data.

Thank you very much.
Jose Luis.

**Comment by bewest** [comment]
We have an API that should assist in exporting csv, tab separated, and json records.

EG: `/api/v1/entries.txt` and `/api/v1/entries.csv?....`.  There is also a rich query string syntax for selecting records by date, and changing the `count` number of records in the result set.  It should be possible to use functions in modern spreadsheet applications to import these values.  See the `/api-docs/` of your Nightscout site for more information.

https://gist.github.com/bewest/dbe590ab131edfdddd4d988d58c25930
