### ISSUE TITLE
mongo_url_parser is super old and doesn't line up with the mongo driver, and rejects MaxIdleTimeMS when it shouldn't

### ISSUE THREAD

**Issue by shanselman** [nightscout/cgm-remote-monitor#7598]
**Describe the bug**

mongo_url_parser is super old and doesn't line up with the mongo driver, and rejects MaxIdleTimeMS when it shouldn't

**To Reproduce**

use a connection string that includes MaxIdleTimeMS. NS will fail to start. Y'all need to update mongo url parser to MATCH the mongo driver.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/2892/194633419-f6177772-3fd4-48a5-8260-306519190f40.png">

**Comment by sulkaharo** [comment]
@bewest see linked PR that bumps the URL parser version to include the version that supports the parameter Scott is having issues with

**Comment by bjornoleh** [comment]
I can confirm https://github.com/nightscout/cgm-remote-monitor/pull/7606 works for me when testing with maxIdleTimeMS=120000, instead of socketTimeoutMS=120000 as suggested by Scott as a workaround  in his Azure setup video:
https://www.youtube.com/watch?v=EDADrteGBnY&ab_channel=ScottHanselman

**Comment by sulkaharo** [comment]
Dev should finally have the updated version (and a lock file that deploys to Heroku)
