### ISSUE TITLE
Release 0.3.x Issues

### ISSUE THREAD

**Issue by brianhanifin** [nightscout/cgm-remote-monitor#76]
If you are having difficulty with one of the v0.3.x website releases here are some things to try:

1. The previous version of the site was too aggressive with caching the files used by the site. Important changes may not be downloaded to your browser, which would cause problems. Try viewing the site in Private Browsing or Incognito Mode. (Thanks Josh Corwin for sharing this.)
2. The new settings feature requires cookies, so please enable cookies. Version 0.3.4 handles this error so the data can display despite disabled cookies. (Thanks Ben West for discovering this.)
3. If you only see a chart, and are using Dolphin browser, upgrade your site to at least version 0.3.3 for the layout fix.
4. If you only see a chart, and are using a "Stock Android Browser" of some variety, please switch to Google Chrome. I do not have access to those browsers for testing. So until a developer with access to those browsers can edit the code to help us, Chrome is your best bet.

If after trying the above suggestions you still have a problem, please either post about it below. Be sure to include:
* Browser name (e.g. Chrome, Safari, Firefox, Internet Explorer, Dolphin).
* Platform (e.g. Windows, Mac, iPhone, Android, etc.).

Thank you everyone for your patience. This just proves how experimental all of this is, and how important it is to have as many people try out the new site as possible. The more quickly someone reports a problem, the quicker we can discover a solution.

**Comment by jasoncalabrese** [comment]
old
