### ISSUE TITLE
[dev: language.js] inconsitent translations

### ISSUE THREAD

**Issue by AdrianLxM** [nightscout/cgm-remote-monitor#760]
I'm starting this to keep track of possible mistakes in translations (for the following review process / clarification discussions /...):
- "Record: " in Spanish translates to a verb like "to record a song". In French it translates to something like "record of data".
##

**Comment by jasoncalabrese** [comment]
I'd like to add Language to the setting drawer and then get a test site up that people can review

**Comment by Fokko** [comment]
Great idea. Sometimes it is hard to come up with the correct translation without having the context.

**Comment by jasoncalabrese** [comment]
Just merged in #793, and will do a beta1 release this weekend, hoping to get lots of translation updates

<img width="296" alt="screen shot 2015-08-15 at 6 32 53 pm" src="https://cloud.githubusercontent.com/assets/751143/9291578/40b6060a-437e-11e5-9dc3-1322d5ccf6a0.png">

**Comment by jasoncalabrese** [comment]
I'm going to remove the funnel cake milestone from this issue and leave it open.

Planning on releasing on Saturday.  Any last minute translations updates would be great, but I don't think they should hold up the release.
