### ISSUE TITLE
Alternatives to heroku since it will no longer be a free services

### ISSUE THREAD

**Issue by bckelley** [nightscout/cgm-remote-monitor#7692]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Is your feature request related to a problem? Please describe.**

as of Nov 28 Heroku is eliminating it's free plan and forcing everyone to pay monthly for the service any alternatives planned to replace as an option as other alternatives exist? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

having looked [https://alternativeto.net/software/heroku/](here) other alternatives exist paid and unpaid

**Additional context**

**Comment by psonnera** [comment]
Yes they do https://nightscout.github.io/vendors/heroku/migrate/

**Comment by bckelley** [comment]
> Yes they do https://nightscout.github.io/vendors/heroku/migrate/

ok thanks
