### ISSUE TITLE
How to update NS for Fly.io?

### ISSUE THREAD

**Issue by JLChamberlain** [nightscout/cgm-remote-monitor#7695]
I currently have my NS deployed on Fly.io and it runs without issue. Since running NS on Fly.io I can see there have been a few newer releases but currently see no info on the [update page](https://nightscout.github.io/update/update/) on how to update via this host. Is this in the works to add that to the docs or does anyone know how you go about updating it via this host?

**Comment by psonnera** [comment]
You need to follow this https://nightscout.github.io/troubleshoot/fly.io/#make-your-migrated-app-maintainable

**Comment by JLChamberlain** [comment]
> You need to follow this https://nightscout.github.io/troubleshoot/fly.io/#make-your-migrated-app-maintainable

So how do I ensure that the app secrets I currently have are copied across upon update? I see nothing regarding this, all I see is an outline of how to get a new fly.toml file or to export the current config if you still have NS running of Heroku.

**Comment by JLChamberlain** [comment]
> You need to follow this https://nightscout.github.io/troubleshoot/fly.io/#make-your-migrated-app-maintainable

Followed the instructions and have updated to the latest release of NS, do I have to clone and follow these steps every time I need to update?

**Comment by psonnera** [comment]
No, now that you've got a .toml you just need to flyctl deploy after you update your cgm-remote-monitor repo and clone it locally. I need to add instructions in the documentation.
