### ISSUE TITLE
MongoDB instructions doesn't parse password correctly

### ISSUE THREAD

**Issue by mylesamoran** [nightscout/cgm-remote-monitor#7717]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**
When following the monboDB instructions, a > is left after the password when generating the MONGODB_URI string.  This causes a new deploy to not connect to the DB and error out.

**To Reproduce**
1. Go to https://nightscout.github.io/vendors/mongodb/atlas/
2. Follow the steps of entering a DB username, DB password, atlas connection string, and database name.
3. Click Generate
4. Note in the resulting connection string, the > at the end of <password> remains.

**Expected behavior**
The entire <password> field should be replaced when generating the string.

**Screenshots**
N/A

**Your setup information**
Chrome 106.0.5249.103  No other browsers tested.

**Additional context**
N/A

**Comment by psonnera** [comment]
Hello, this is for the documentation https://github.com/nightscout/nightscout.github.io
Let me fix this ASAP

**Comment by psonnera** [comment]
@mylesamoran please check and close this issue. If you need further help open another one in https://github.com/nightscout/nightscout.github.io/issues

**Comment by mylesamoran** [comment]
Excellent, its working now.  Thanks!
