### ISSUE TITLE
Fly requesting payment information

### ISSUE THREAD

**Issue by robster7674** [nightscout/cgm-remote-monitor#7811]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**
Following https://nightscout.github.io/vendors/fly.io/new_user/, after "fly launch", eventually I get this error, after selecting the region (Amsterdam):

`Error We need your payment information to continue! Add a credit card or buy credit: https://fly.io/dashboard/robgadget-omnimail-nl/billing
`
I did "fly auth login" prior to launch, and selected "Try for free" at the screen that follows login.

**To Reproduce**
1. Follow https://nightscout.github.io/vendors/fly.io/new_user/
2. Type "fly launch" after logging in and setting up the config

**Expected behavior**
To be able to launch the fly app.

**Screenshots**
n/a

**Your setup information**
- What version of Nightscout (e.g. 0.10.3) - latest
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.) - FSL2
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? - n/a

**Additional context**

**Comment by robster7674** [comment]
Ok, after adding a card (and unlocking my account due to high risk?), I end up with this error:
```
Rob@Gadget cgm-remote-monitor % fly deploy
Update available 0.0.437 -> 0.0.442.
Run "fly version update" to upgrade.
==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-patient-sun-2533 ready
==> Creating build context
--> Creating build context done
Error failed to fetch an image or build from source: error fetching docker server info: Get "http://[fdaa:1:1b1d:a7b:c207:b0e9:338e:2]:2375/v1.41/info": context deadline exceeded
```

**Comment by psonnera** [comment]
Might find its place in https://github.com/nightscout/nightscout.github.io/issues as it's not a cgm-remote-monitor issue.

**Comment by sulkaharo** [comment]
Yup there's nobody here who can help deploy the app to Fly. If the documentation needs improvements, please poke an issue to Patrick's link, or post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Comment by robster7674** [comment]
Looks like this was caused by my vpn connection. I got this clue from https://community.fly.io/t/error-when-deploying-context-deadline-exceeded/7188/2. Disconnecting vpn and relaunching worked.
```
 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total]
--> v0 deployed successfully
```
