### ISSUE TITLE
NS 14.2.6 no longer shows Temp Targets

### ISSUE THREAD

**Issue by Foxy7** [nightscout/cgm-remote-monitor#7822]
**Describe the bug**
following update to NS 14.2.6 (from 14.2.5) our NS pages no longer show Temp Targets rendered.

**Expected Behaviou**
NSClient version of AAPS does show the Temp Target as active, between ~ 8am - 10am today:
![Screenshot_20230109-120448_NSClient](https://user-images.githubusercontent.com/37312469/211304748-9aa6b90e-fb9e-4c5e-9801-ae1dceb6704f.jpg)

**Screenshots**
NS does not show the grey Temp Target line:

![image](https://user-images.githubusercontent.com/37312469/211280397-1fbf4aec-cd63-4799-8139-01ad5e0c1f09.png)

Treatments report shows the correct data existing in the db:
![image](https://user-images.githubusercontent.com/37312469/211280577-ea149a8e-0a5a-4af7-80ae-8ec37161753b.png)

**Your setup information**
Nightscout 14.2.6
All browsers have the same issue.
AAPS loading to Heroku.

thanks.

**Comment by Foxy7** [comment]
Can't remember where the database is, will confirm tonight when at home.

Note, i did see the Temp Target grey line on my work pc first thing this morning, but it disappeared immediately when the page refreshed. Suggests to me it's 14.2.6 rather than a database issue. Also, doesn't explain why NSClient works correctly, since the data must be getting to the database.

What i will try tonight is to roll back to 14.2.5 and see if that works, without touching the database.

**Comment by Foxy7** [comment]
This is strange and i didn't notice it this morning, but i can see the Temp Target at the bottom of the screen, it must be a conversion issue as the grey line should be in the top graph. Note, this doesn't correct even if i change the units in the burger bar settings menu.

Just looking through the release notes [releases](https://github.com/nightscout/cgm-remote-monitor/releases), my feeling it's related to this change:

#7273

![image](https://user-images.githubusercontent.com/37312469/211429074-24295350-0cae-416b-bfe3-01813b17e4d3.png)

**Comment by Foxy7** [comment]
Having reversed this commit #7273 and reloaded i see the Temp Target correctly rendered now:

fwiw my change https://github.com/Foxy7/cgm-remote-monitor/commit/b90598554c993ed8bd6c3a6d44dfaa6efa327a21

from my wife's NS

Before:

![image](https://user-images.githubusercontent.com/37312469/211433034-b5f55ca2-a514-42a9-a216-d1c7c68b73e3.png)


and After changing the line back

![image](https://user-images.githubusercontent.com/37312469/211433119-8ac6ee0f-ba55-413f-8427-6e17df4099ad.png)

**Comment by Foxy7** [comment]
and same change worked for my kid's page:
![image](https://user-images.githubusercontent.com/37312469/211433821-635b7c26-59ba-4db3-9e29-393cc02ca4e4.png)

after:
![image](https://user-images.githubusercontent.com/37312469/211434019-24a00312-d1cc-4f36-beb5-60bb92685ff8.png)

**Comment by emmatovar27** [comment]
@Foxy7  I'm using AAPS dev-f and my temp target looks like yours! 

The first one was at 120 mg/dl the second one at 85 mg/dl


![image](https://user-images.githubusercontent.com/39507448/211469919-b1b733b4-f251-4e2c-86cb-6880d2b1c7f6.png)

**Comment by sulkaharo** [comment]
Right - which version of AAPS are you using? What are the unit settings across your systems? Nightscout uses mg/dl by default, so nothing should be converted to mmol.

**Comment by sulkaharo** [comment]
Can you load a piece of sample data from /api/v1/treatments.json on your Nightscout that includes a temp basal that's affected?

**Comment by Foxy7** [comment]
@sulkaharo thanks for looking at this.

I'm using two different AAPS set ups using the AIMI plugin, this TT issue has only appeared since Saturday when updating to 14.2.6 and using that new change to NS. Have previously used openaps and multiple versions of AAPS with no issues.

My kid is running off a base of AAPS Master and my wife is runing off AAPS Dev at commit https://github.com/nightscout/AndroidAPS/commit/82fb85c9e09ed1fe81be2133bd88e732296d9502.

Using mmol/l across all NS and AAPS set ups.

This is today's morning temp target for my kid (Master AAPS), which is the same as the one from yday that didn't render correctly:

```ruby
  {
    "_id": "63bd1a73496fb00004d1ba19",
    "eventType": "Temporary Target",
    "duration": 150,
    "durationInMilliseconds": 9000000,
    "isValid": true,
    "created_at": "2023-01-10T07:57:14.000Z",
    "timestamp": 1673337434000,
    "enteredBy": "AndroidAPS",
    "reason": "Activity",
    "targetBottom": 9.509509509499999,
    "targetTop": 9.509509509499999,
    "units": "mmol",
    "mills": 1673337434000,
    "carbs": null,
    "insulin": null
  },
```


Today's NS view looks good:

![image](https://user-images.githubusercontent.com/37312469/211516252-78e3f86f-db7a-4d8c-a8f1-a18273cda070.png)

**Comment by olorinmaia** [comment]
Experiencing same issue on my Nightscout both in browser on my PC and android phone. Caretakers at school use temp-targets alot and they are really missing the possibility to easily see if there is a temp target or not in Nightscout. Attaching screenshot. Im using ns.10be.de. Is there something I can do or those hosting my Nightscout to fix this? Using latest AAPS master version and latest Nightscout master version.

![image](https://user-images.githubusercontent.com/114103483/211680664-b9f21e69-9e37-435f-9f46-63b25f1dda27.png)

**Comment by Foxy7** [comment]
@olorinmaia for the time being you can sync off my version, which is 14.2.6 except for the one change that is causing me the issue.

https://github.com/Foxy7/cgm-remote-monitor


for info, this is the change https://github.com/Foxy7/cgm-remote-monitor/commit/b90598554c993ed8bd6c3a6d44dfaa6efa327a21 so you could just copy that to your NS repo if you prefer/easier.

**Comment by olorinmaia** [comment]
> @olorinmaia for the time being you can sync off my version, which is 14.2.6 except for the one change that is causing me the issue.
> 
> https://github.com/Foxy7/cgm-remote-monitor
> 
> for info, this is the change [Foxy7@b905985](https://github.com/Foxy7/cgm-remote-monitor/commit/b90598554c993ed8bd6c3a6d44dfaa6efa327a21) so you could just copy that to your NS repo if you prefer/easier.

Thank you very much, thanks to this codechange it is now working for us and all other customers @ ns.10be.de :)

**Comment by sulkaharo** [comment]
Ah right, read the full code and there's a clear bug in that merge the people reviewing the code should have spotted. PR for the fix here: #7825

**Comment by Foxy7** [comment]
> Ah right, read the full code and there's a clear bug in that merge the people reviewing the code should have spotted. PR for the fix here: #7825

This fix looks good, works for me. Thanks.

**Comment by zehnBE** [comment]
It makes a Problem on aaps nsclient-Followers.
If the patch in and some do a BG-Check in nsclient it is uploaded as mmol, but the follower reupload it as mg/dl.
If the patch out, the reupload comes fine in mmol.

**Comment by olorinmaia** [comment]
Experiencing an issue @ 10be.de after this fix was applied. Maybe a long shot but could it be to the code in this fix? It's causing BG check registered in AAPS in mmol/L to show in NS and NSclient with wrong values.
![image](https://user-images.githubusercontent.com/114103483/215037557-1c793c2b-0077-4024-91c9-1a16a4d569c1.png)
