### ISSUE TITLE
NSv3 : Strange NS web page behaviour if upload on charge set on phone (AAPS) / API v3

### ISSUE THREAD

**Issue by robertrub** [nightscout/cgm-remote-monitor#7838]
We are several people having the same issue. AAPS Dev started using API v3 and this bug started with v3. If AAPS set to use API v1, the problem doesn't happen.

Setting: AAPS last Dev, use NS v3, NS tab, settings, do not upload if on battery, NS and Mongo db both running in containers on my QNAP NAS.

While AAPS is not uploading to NS, my NS web page is missing data. Normal behaviour. When phone is charging, the data is uploaded and it is no more "missing" in the Mongo db but there are holes in the NS graph.

On NSv3, once the data is uploaded, actualising my NS web page does NOT fill the holes in the graph. I need to restart the containers to have the graph filled (which proves that the data is in the Mongo db). But, the last connection data is still missing on the upper part.

Till now, when using v1, I didn't have the "holes" in the graph. But, I had not tested as thoroughly.

Graph after data update ans actualising.

![Screenshot_20230117_084425_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/212863040-a78a58af-924c-4b67-b984-ce9261b0c2a3.jpg)

Graph after restart of containers.

![Screenshot_20230117_084842_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/212863081-022a65a4-d63f-4b23-a7a6-055b2507baf8.jpg)

**Comment by sulkaharo** [comment]
I have a hunch I know what's causing this. Will take a look.

**Comment by sulkaharo** [comment]
Right - can you deploy Nightscout from this branch and send me a snapshot of the logs that includes lines with  "Mongo collection requesting cache update event" https://github.com/nightscout/cgm-remote-monitor/tree/debug_log_cache_updates

**Comment by vanelsberg** [comment]
Interesting. Actually I can not confirm this issue?
Running my own deployment for NS v14.2.6 (prebuild Docker image release).

So I's say it could have something to do with the way NS is deployed?
My site is service through an Nginx portal server in my network, I think you are using a local Traefic instance?
And how about the access token: does it have "admin" rights?

**Comment by robertrub** [comment]
@vanelsberg I'm using the certificate of QNAP, the containers are really basic. AAPS's token has admin rights. The data is in the Mongo db, thus it is not a data upload problem.

@sulkaharo  Will try to test. I'm not very _fluent_ in this kind of manipulation. Will see what the commands are in the yaml file.

**Comment by robertrub** [comment]
@sulkaharo  I tried to change the image in the yaml but it looks like that restarting the container used the last Image I had (14.2.6). Any ideas how I can change the image used in the container ? I'm not sure how to get the logs either (but I have an idea...). Sorry, really a noob on these subjects. 

![ns_debug](https://user-images.githubusercontent.com/76626474/213175613-62529b14-ad4c-4f72-99bf-bc0237ca9d28.png)

**Comment by sulkaharo** [comment]
I have no idea how the installation process in QNAP works, sorry

**Comment by robertrub** [comment]
Is there an update to 14.2.6 ? With your link, I get version 14.2.6 shown but if I ask, I get the message that an update to NS is available... I'm not sure if I have your debug version running or not. I'll try to find the logs if I can...

**Comment by sulkaharo** [comment]
Ah right, if you're deploying docker images, no there's no new image available for branches, just dev and master.

**Comment by vanelsberg** [comment]
Correct. Apart from image pull_policy (https://docs.docker.com/compose/compose-file/#pull_policy) version 14.2.6 is "latest".
If want to deploy a newer version based on dev you'd need to build your own docker image.

**Comment by psonnera** [comment]
@vanelsberg this one https://hub.docker.com/layers/nightscout/cgm-remote-monitor/latest_dev/images/sha256-70729b993a7ee41640a12d96306b25e0df625fe54f74e74ce9b3be7662e1d70a?context=explore ?

**Comment by vanelsberg** [comment]
Actually can not think of anything in NSv3 that might cause your problems.
I'd look for the problem on the frontend: are you all are Traefik?

**Comment by vanelsberg** [comment]
@psonnera Ok? Yes, you are right. Was assuming (falsely) that latest was "latest release" :-|

**Comment by sulkaharo** [comment]
Architecturally the only thing that can cause the gaps is either the Nightscout instance not getting the REST uploads directly or there being a bug in the REST API implementation. The gaps are an expected feature if you have multiple Nightscout instances running using the same database, where only the instance that gets the REST uploads will update the data correctly.

**Comment by vanelsberg** [comment]
@robertrub You can try force-reloading the image on startup by adding "imagePullPolicy: Always" (under containers:)

**Comment by robertrub** [comment]
Ok, strarted testing with latest_dev v15.0.0... Will keep you updated.

**Comment by vanelsberg** [comment]
@robertrub 
> ...Nice try but it didn't like it ;)
My bad. Working mostly with Kubernetes, which is much alike - but not the same ;-)
I think, for docker compose it is "pull_policy"

See https://docs.docker.com/compose/compose-file/#pull_policy
Example:
```
nightscout:
    image: 'nightscout/cgm-remote-monitor:14.2.6'
    pull_policy: always
```

**Comment by robertrub** [comment]
Thanks. That one was accepted👍 Will test v15.0.0 beta for the moment.

**Comment by robertrub** [comment]
_Victory_ (but **I** didn't do anything 🤣 )
The problem seems to solved in v15.0.0 beta. 

I'm closing this issue. Thanks for your help 🙂

**Comment by vanelsberg** [comment]
>Who is supposed to send the "reread db data" command ?
Don't know the details but I'd expect a database change triggers NS to refresh.

Again, using NS 14.2.6 in a similar deployment as yours with AAPS configured for NSv3. And I am not experiencing any problems with refreshing as you describe.

Settings:
![Screenshot_20230118_172837_AAPS](https://user-images.githubusercontent.com/45144129/213237682-d4ca6956-d059-431d-9642-8fcaaf2017b1.jpg)

![Screenshot_20230118_172901_AAPS](https://user-images.githubusercontent.com/45144129/213237496-7565cf78-a805-4e72-896d-4adf9feebaf6.jpg)

**Comment by vanelsberg** [comment]
> The problem seems to solved in v15.0.0 beta.
Nice!

Nut know I have a problem: why does this work for me with v14.2.6 ? 8-|
;-)

**Comment by robertrub** [comment]
Sorry folks. I tested again and, the problem is not solved in latest_dev v15.0.0

3h without charging and started charging. The holr is there, un filled 😭

![Screenshot_20230118_215438_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/213293084-508944fd-3f20-4d0a-b6f3-07100565ac02.jpg)

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/213860124-5217f396-b2fd-4547-85db-7c509974d3f5.png)
It's enough to keep nsclient off and start after some time. it starts upload all missed data
[nightscout.log](https://github.com/nightscout/cgm-remote-monitor/files/10471825/nightscout.log)

**Comment by sulkaharo** [comment]
@MilosKozak damn, the logger you're using doesn't store timestamps, so it's very hard to deduct how the uploads are working. Based on the log you have restarted the server just before generating this? What's curious is the data loader that loads the full dump of last 50 hours from the database finds 315 SGV entries, which should mean there's no gaps in the timeline (as per 288 entries / day).

**Comment by robertrub** [comment]
@MilosKozak  Your comment _after server restart NS displays all data_ is correct. The data have been uploaded to the server.

The problem is that the NS page is "not informed" that it needs to reread the data from the db. As you said, only a server restart will populate the missing data.

The best option would be tell NS that there has been data upload that needs rereading the db. 

The second best option would be to reread the data if the page is actualised.

**Comment by sulkaharo** [comment]
Ah, I'm pretty sure I know what the bug is. Will probably take until tomorrow to implement a fix.

(Note the app explicitly doesn't do full database reads repeatedly as this doesn't work for anyone using the free cloud databases that have strict usage limits, so we can't change the app to just reload all data.)

**Comment by robertrub** [comment]
@sulkaharo You said, _app explicitly do full database reads repeatedly_ 

You only need to read the amount of data shown on the screen.

If you can keep track of the _last_ and _one before last_ date stamps, it will be easy to solve. If _one before last_ is "stale", read data since _one before last till _last_ ;)

**Comment by sulkaharo** [comment]
Sorry unclear wording - meant to say even reading the last 48 hours is too much for free Atlas. We already have the mechanisms in place to minimize these reads, the bug is in the data uploaded through the REST api not being recognized correctly.

**Comment by sulkaharo** [comment]
Also maybe worth noting, loading one before last is not enough as clients can upload changes to any record in the database, so changes can occur to records with an arbitrary timestamp.

**Comment by MilosKozak** [comment]
> @MilosKozak damn, the logger you're using doesn't store timestamps, so it's very hard to deduct how the uploads are working. Based on the log you have restarted the server just before generating this? What's curious is the data loader that loads the full dump of last 50 hours from the database finds 315 SGV entries, which should mean there's no gaps in the timeline (as per 288 entries / day).

I stopped server, removed log, started server, did upload of historic data resulting in the issue. So the log is from server start to final state with this issue

**Comment by sulkaharo** [comment]
#7853 should fix the gaps, can someone test? :)

**Comment by sulkaharo** [comment]
Fixed in dev

**Comment by robertrub** [comment]
Thanks @sulkaharo . I updated my container tonight with the latest-des. Will test tomorrow morning after a couple of hours od paused ocnnection.

**Comment by sulkaharo** [comment]
@robertrub you can repro the test with a short pause, anything longer than 15 minutes pause will cause CGM entries to go missing with v3 uploads without this fix.

**Comment by robertrub** [comment]
> @robertrub you can repro the test with a short pause, anything longer than 15 minutes pause will cause CGM entries to go missing with v3 uploads without this fix.

Great job :) Tested 2 times. Worked both times but only 2 data is "missing" or late.

![Screenshot_20230125_054349_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/214504149-b039e6cd-d1c4-42f8-83d0-88097c622a47.jpg)

![Screenshot_20230125_082341_DuckDuckGo.jpg](https://user-images.githubusercontent.com/76626474/214504352-f4d55291-347b-4e8a-ac5f-c9a2e47a9a22.jpg)

**Comment by sulkaharo** [comment]
The bug causing data go missing applies to device statuses as well. Based on the log Milos uploaded, almost no device status data is uploaded after the uploads have been paused. @MilosKozak how do the uploads work after a pause in regards to device status records? Are those retained and uploaded similarly to treatments and CGM entries?
