### ISSUE TITLE
No connection from AAPS since socket.io Update

### ISSUE THREAD

**Issue by philipgo** [nightscout/cgm-remote-monitor#7874]
**Describe the bug**
Since commit [https://github.com/nightscout/cgm-remote-monitor/commit/6ad4ef18140d33936bf8795c628c698b90ced02c](url) AndroidAPS (dev built Jan 31) cannot connect to my Nightscout instance. In the NSCL tab AndroidAPS shows `Error: io.socket.engineio.client.EngineIOException xhr poll error`

**To Reproduce**
1. Run AndroidAPS dev
2. Connect to a Nightscout instance running dev including the above mentioned commit
3. Try syncing your treatments etc with your Nightscout instance

**Expected behavior**
Connection without error

**Your setup information**
- What version of Nightscout (dev including commit [https://github.com/nightscout/cgm-remote-monitor/commit/6ad4ef18140d33936bf8795c628c698b90ced02c](url)
- Dexcom -> Xdrip -> Nightscout (works)
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? Specific to AndroidAPS

**Additional context**
My nightscout setup is a self hosted docker installation. But that probably does not play a role in this context.

**Comment by viq** [comment]
Just out of curiousity, are you using the official docker image, or did you build your own with a newer node version?

I'm seeing the same issue on a self hosted version, but I blamed the fact that where I'm running it I have only node 18 available.

**Comment by philipgo** [comment]
@viq I use this docker image: https://hub.docker.com/r/nightscout/cgm-remote-monitor

If I interpret it correctly, it uses node version 14.15.3

**Comment by viq** [comment]
So the official one. Yeah, it is 14.15.3. Thank you.

**Comment by MilosKozak** [comment]
AAPS master + dev needs NS master
AAPS ns15 branch needs NS dev

**Comment by viq** [comment]
Thank you for that information.
Skimming through https://github.com/nightscout/AndroidAPS/pull/2364 it seems like most changes touch only the nightscout and xdrip communications, and otherwise running this version should be not too different from running `master` (i.e. `3.1.0.3`), do I understand it correctly?

**Comment by philipgo** [comment]
> AAPS master + dev needs NS master AAPS ns15 branch needs NS dev

Thank you, now it works.
