### ISSUE TITLE
Mydiabby french platform for Omnipod

### ISSUE THREAD

**Issue by vincedejonx** [nightscout/cgm-remote-monitor#7896]
One question regarding Mydiabby , a french platform linked to Omnipod. It stores data from Libreview and pump, so that my medical team can share reports with me. Do You know if someone is working on exporting ns data to Mydiabby?  AsIs we can only post on Mydiabby ns-reporter pdf-reports, which is quite different and not aligned with all Medical teams requests.

**Comment by KikiManjaro** [comment]
Unfortunately, myDiabby does not have any API, so it is not possible to integrate a possible way of communication with Nightscout for the moment

**Comment by vincedejonx** [comment]
Really 2 bad. Cheers!
