### ISSUE TITLE
Improve ENABLE parsing to only accept spaces

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#790]
Store as an array, update util functions, etc

**Comment by bewest** [comment]
How about something like this: https://github.com/bewest/drywall-rev-proxy/blob/wip/subscriptions/public/views/account/sites/index.js#L156-L175

```
  function env_config (env) {
    var enabled = [null].concat((env.ENABLE || 'delta direction ar2 errorcodes').split(' '));
    var config = { };
    var known = [
        'careportal' , 'rawbg' , 'iob' , 'cob'
      , 'bwp' , 'cage' , 'delta'
      , 'direction' , 'upbat' , 'ar2'
      , 'simplealarms' , 'errorcodes' , 'treatmentnotify'
      , 'basal' , 'pushover' , 'maker'
      ];
    var field;
    for (var i in known) {
      field = known[i];
      if (enabled.indexOf(field) > 0) {
        config[field] = true;
      }
    }
    return config;
  }

```

**Comment by jasoncalabrese** [comment]
the split is exactly what I was thinking, but I don't want a list of known plugins, will become a hotspot, make hacking harder

**Comment by jasoncalabrese** [comment]
I'd rather have an api to list available options that can be enabled, that plugins could hook into

**Comment by bewest** [comment]
If above is in standalone module, which is then used to simply trigger hooks/plugins which are then the main agents, it might be fine.  There's already a hotspot with listing all the modules, this small module could also expose the lists of known/defaults, etc, isolating everything.  Ammended with blacklist, untested.

**Comment by jasoncalabrese** [comment]
The current list in https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/plugins/index.js is needed for `browserify-express` to do it's static analysis.  Replacing `browserify-express` would be nice, but might take me some time to get right.

**Comment by bewest** [comment]
Nice, that'll work nicely, actually...
