### ISSUE TITLE
Issue with api v1 returning stale data

### ISSUE THREAD

**Issue by adamd9** [nightscout/cgm-remote-monitor#7910]
I have a Mac OS X app that I made that pulls the latest CGM values from Nightscout using v1/entries - a user recently reported that their values are all showing as stale / old. When I looked into it, I can see that he's on the DEV branch of cgm-remote-monitor, and when I hit his v1/entries endpoint and compare to v2/properties it's clear that the v1 endpoint is no longer reporting up-to-date values. 

I have since upgraded my own instance and I can see the same behaviour.

**To Reproduce**
1. Go to api/v1/entries on a NS instance running 15.0
2. Look at the timestamps / epoc times and you will see they are multiple hours old versus the latest bgnow readings at api/v2/properties

**Expected behavior**
api/v1/entries should be up to date.

- NS version 15.0
- My data comes from loop://iPhone but the other user's data comes from xDrip-DexcomG5 G6 Native
- Not specific to a browser or device

**Comment by adamd9** [comment]
With further testing, I notice when I request the specific entry type of 'sgv' I get the right values. I see now in the swagger def that the spec is actually a required value, and maybe it was just my good luck all this time that the basic /entries was still returning valid results!

<img width="822" alt="image" src="https://user-images.githubusercontent.com/4033496/221300681-088b5dce-12f2-4644-aa3d-5380210116b8.png">

Will close.

**Comment by sulkaharo** [comment]
This is a

**Comment by sulkaharo** [comment]
Fixed in #7911

**Comment by sulkaharo** [comment]
Oh thanks for the report - when adding a unit test to cover the bug, found another serious bug with the API. Both issues are now fixed in the fix PR.

**Comment by adamd9** [comment]
Nice one, thanks @sulkaharo !
