### ISSUE TITLE
sgvs are shown in grey

### ISSUE THREAD

**Issue by KiLLuuuhh** [nightscout/cgm-remote-monitor#7994]
**Describe the bug**
uploaded sgv data via API are shown in grey instead of green

**To Reproduce**
1. setup nightscout docker container as described in https://nightscout.github.io/nightscout/docker/
2. Post data: `curl -X POST -H 'api-secret: *********' -H 'accept:  */*' -H 'Content-Type: application/json' -i 'https://nightscout.******.**/api/v1/entries.json --data '[{"type": "sgv", "date": 1681974546000, "sgv": 117}]'`
3. Get data: `curl -X GET -H 'api-secret: *********' -H 'accept:  */*' -H 'Content-Type: application/json' -i 'https://nightscout.******.**/api/v1/entries.json'` result:
`{"_id":"6440e528df3f7b408de4f62c","type":"sgv","date":1681974546000,"sgv":117,"utcOffset":120,"sysTime":"2023-04-20T07:09:28.208Z","mills":1681974568208}`

**Expected behavior**
A green dot is shown in nightscout web view

**Screenshots**
![Screenshot from 2023-04-20 09-20-47](https://user-images.githubusercontent.com/74672908/233290580-6bd757f6-835a-4181-b4bc-5a32770befc6.png)

**Your setup information**
- What version of Nightscout (e.g. 0.10.3) 14.2.6
- What type of CGM, and how do you get your data there? (e.g. G4 and ShareBridge, or wired receiver, etc.) via API from Medtronic
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? No

If you need additonal information, please let me know, thanks!

**Comment by psonnera** [comment]
And you are in color mode? https://nightscout.github.io/nightscout/setup_variables/#theme-colors

**Comment by KiLLuuuhh** [comment]
> And you are in color mode? https://nightscout.github.io/nightscout/setup_variables/#theme-colors

Thank you very much, I must have missed this!
