### ISSUE TITLE
Latest dev doesn't work in container

### ISSUE THREAD

**Issue by robertrub** [nightscout/cgm-remote-monitor#8038]
I run NS on my QNAP NAS (containers). Latest main 14.2.6 was working ok. I tried dev 15.0.0 and it was working ok too. The last working dev image I used was 1 month ago.

The latest_dev image I have downloaded today isn't working. It starts then stops then is restarted by the container and stops again etc.

I went to the last master 14.2.6 and it is working ok.

Don't know what more information I can give to help you more.

**Comment by parapenT1sta** [comment]
I have same error with container in Azure and I can find this error in Logs:
`Container didn't respond to HTTP pings on port: 1337`

The latest dev version working from me is
`nightscout/cgm-remote-monitor:dev_5f953df881f7878547738e3e1f400aa4ed000ea7`

From https://hub.docker.com/r/nightscout/cgm-remote-monitor/tags

Can you try and check if the version is working?

**Comment by parapenT1sta** [comment]
I have same error with container in Azure and I can find this error in Logs:
`Container didn't respond to HTTP pings on port: 1337`

The latest dev version working from me is
`nightscout/cgm-remote-monitor:dev_63544948dbb32bb193cdd7f33a28fd67a1538ecd`

From https://hub.docker.com/r/nightscout/cgm-remote-monitor/tags

Can you try and check if the version is working?

**Comment by robertrub** [comment]
I confirm, the version indicated by @parapenT1sta works OK in a container on my QNAP NAS. 
Something broke after that version.

**Comment by parapenT1sta** [comment]
This release is broken: `nightscout/cgm-remote-monitor:dev_9d55ea513d5d1b91cdfe84202d4629742ed44fbe`

https://hub.docker.com/layers/nightscout/cgm-remote-monitor/dev_9d55ea513d5d1b91cdfe84202d4629742ed44fbe/images/sha256-e53bd2f242ffb84e55cea5a62542e52844904da74f9c48d00544933fa40802db?context=explore

**Comment by sspt** [comment]
Same here, adding the log from a clean install (docker compose up) with a new mongodb+nightscout instance
[20230616.log](https://github.com/nightscout/cgm-remote-monitor/files/11771082/20230616.log)

**Comment by adamecker** [comment]
Another azure user here hitting the same error: 
```
2023-06-17T03:29:56.787884358Z /opt/app/node_modules/mongodb/lib/utils.js:113
2023-06-17T03:29:56.788058660Z throw err;
2023-06-17T03:29:56.788084660Z ^
2023-06-17T03:29:56.788092460Z
2023-06-17T03:29:56.788098160Z Error: Cannot find module 'node:url'
```

**Comment by sulkaharo** [comment]
The error implies your QNAP is running an old version of Nodejs. Can you update Node on the device?

**Comment by parapenT1sta** [comment]
> The error implies your QNAP is running an old version of Nodejs. Can you update Node on the device?

Is any tutorial available to update Node in Azure + MongoDB environment?

**Comment by robertrub** [comment]
I don't know how to update and don't know if it's updatable.

The NAS is new and the FW is the latest.

Did anything change about the nodejs between the last and before last Dev versions ?

**Comment by sulkaharo** [comment]
I don't think anyone in the dev team uses Azure, so I don't think we have any up to date troubleshooting instructions. I checked and seems our Dockerfile has been using an older release as the Node docker image base. I just bumped that to the version required elsewhere, which might fix this in the next build.

**Comment by parapenT1sta** [comment]
> I don't think anyone in the dev team uses Azure, so I don't think we have any up to date troubleshooting instructions. I checked and seems our Dockerfile has been using an older release as the Node docker image base. I just bumped that to the version required elsewhere, which might fix this in the next build.

Thank you for your reply. I had follow this tutorial: https://nightscout.github.io/vendors/azure/new_user/ but it seems there is no info about the Node version. I am searching for some info online but is not clear if I really can change it.

**Comment by psonnera** [comment]
@parapenT1sta this deploys the community maintained container image but if you want to modify it you need to build your own from the main repository https://docs.docker.com/get-started/02_our_app/ I don't think you can do that from our free Azure environment (but I'm not knowledgeable enough to be relied on).

**Comment by parapenT1sta** [comment]
> @parapenT1sta this deploys the community maintained container image but if you want to modify it you need to build your own from the main repository https://docs.docker.com/get-started/02_our_app/ I don't think you can do that from our free Azure environment (but I'm not knowledgeable enough to be relied on).

Thanks @psonnera !!

**Comment by sspt** [comment]
> I don't think anyone in the dev team uses Azure, so I don't think we have any up to date troubleshooting instructions. I checked and seems our Dockerfile has been using an older release as the Node docker image base. I just bumped that to the version required elsewhere, which might fix this in the next build.

Seems fixed, at least on my end the latest_dev is now working fine :)

**Comment by parapenT1sta** [comment]
> I don't think anyone in the dev team uses Azure, so I don't think we have any up to date troubleshooting instructions. I checked and seems our Dockerfile has been using an older release as the Node docker image base. I just bumped that to the version required elsewhere, which might fix this in the next build.

Issue is fixed with the new commit! Many thanks!
Now is working with the latest_dev `nightscout/cgm-remote-monitor:latest_dev`

**Comment by robertrub** [comment]
I'll try this afternoon on my QNAP NAS.

This seems the latest nodejs version on QNAP (but the info dates from 2022..)

![Screenshot_20230617_163245_Firefox.jpg](https://github.com/nightscout/cgm-remote-monitor/assets/76626474/f020dc46-a363-4909-938b-df4f960b2105)

**Comment by robertrub** [comment]
> Issue is fixed with the new commit! Many thanks!
> Now is working with the latest_dev `nightscout/cgm-remote-monitor:latest_dev`

I confirm, the problem is solved with the latest_dev 3h old ;)

I'm closing this issue.
