### ISSUE TITLE
 apple watch os 9.5.2: no automatic update of the values ​​on the watchfaceand what do i have to do to get alarms on the watch?

### ISSUE THREAD

**Issue by bernienightscout** [nightscout/cgm-remote-monitor#8051]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

hi, 

i dont get auto update of the values on the watchface. what i have to do that this work? its on my iphone the same… i always have to open the app to get the value update

and i want to get alarms on my watch but i dont know how to setup this… im using 10be as server and nightguard on my watch

**Comment by sulkaharo** [comment]
These tickets go to the people developing the cloud Nightscout software and we can't really help with issues in hosting the software or issues with software that is not the Nightscout cloud service. So for problems in 10be, you should contact people at 10be. For Nightguard, you should get in touch with the Nightguard developer.
