### ISSUE TITLE
Missing selection box on Smartphone

### ISSUE THREAD

**Issue by robertrub** [nightscout/cgm-remote-monitor#8059]
Using latest NS Dev 15.

On smartphone Samsung S21FE, on 2 different navigators (FF and DuckDuckGo), the box for the selection of the profile appears for a fraction of a second and disappears.

https://github.com/nightscout/cgm-remote-monitor/assets/76626474/61418930-cbe6-4554-925f-8a947e7bb480

https://github.com/nightscout/cgm-remote-monitor/assets/76626474/69bb3f94-d7c0-4a62-9057-34597ba86f91

**Comment by psonnera** [comment]
https://github.com/nightscout/cgm-remote-monitor#recommended-minimum-browser-versions-for-using-nightscout might be an answer?

**Comment by robertrub** [comment]
That's why I tested with both and had the same reaction. The fact that it is shown
and probably overwritten seems like a bug to me.

**Comment by zehnBE** [comment]
yes, its a bug:
https://github.com/nightscout/cgm-remote-monitor/issues/7947#issuecomment-1644163822
