### ISSUE TITLE
Weekly stats by email

### ISSUE THREAD

**Issue by matthiasvdpoel** [nightscout/cgm-remote-monitor#8061]
I bevielve it would be helpfull to have a feature to enable receiving weekly updates about your current bg stats. 
Before I made the switch to NightScout, I used Dexcom G5 with Dexcom Clarity. Every sunday I would receive an email stating my time in range and other usefull data. This helped me keep track on how good/bad my readings actually where and made me be more aware if was doing a good job or not. 

I know that there are reports in nightscout and xdrip and they are really usefull. I suggest making a feature that would send the 'distribution' report by email once per week. 

The user can enable this feature by adding his own credentials to a SMTP server which is used to send the email to an emailaddres. 

A user can host it's own smtp server (advanced) or can use free alternatives like MailChimp

**Comment by bewest** [comment]
I think this is a great idea but I believe the scope falls outside of Nightscout.  I've been assembling groups of people that are interested in developing and promoting additional ecosystem components like this.  Please let me know if you are interested; in particular I think chatcgm and health replica would be interesting sources for reports.
