### ISSUE TITLE
/entries/history does not return all the available items

### ISSUE THREAD

**Issue by justmara** [nightscout/cgm-remote-monitor#8090]
**Describe the bug**
I'm currently testing AAPS dev-l and encountered strange behaviour with NS API v3 client - it fails to backfill BG data from NS.
As I can see from logs NS client queries `/entries/history?from={}&limit={}` endpoint with limit 0f 500 items and on whenever it receives will 500-items long recordset it believes that there is more data and makes new query, setting last received item's timestamp for `from` value. But for some reason NS not always returns all the 500 records even when there are much more available in database.

**To Reproduce**
Clean install AAPS 3.2 dev-i, setup NSClientV3, enable BG backfill from NS and press 'Full synchronization' in NSclientv3.
I've started full sync in AAPS dev-i build and sow this in log
--> GET https://[my ns here]/api/v3/entries/history/1694366629182?limit=500
--> GET https://[my ns here]/api/v3/entries/history/1694366929102?limit=500

and this in NSClient log.
![image](https://github.com/nightscout/cgm-remote-monitor/assets/4157587/12390bf4-95e9-4a81-b4aa-66b1a1550052)

So on second iteration it received only 497 items of requested 500 and thought that the data is over.

But I've modified AAPS code a bit so it would stop only if received array size is smaller than *0.95 of requested. And got this log

![image](https://github.com/nightscout/cgm-remote-monitor/assets/4157587/5e9bdc93-6185-4c02-9e07-ad1e51e451fe)

So there was much more data in NS, but many times NS refused to return full 500-records long response.

Looks like if limit were applied on db read, but then some records were removed from response.

**Expected behavior**

Request with `limit=500` option should always return 500 records, if there are more 500 or more available in database for that query.

**Your setup information**
- Checked with NS 14.2.6 and 15.0.0 (from docker image `nightscout/cgm-remote-monitor:latest_dev@sha256:eead357dc7e30dee8c380a1b310d5cc5716bddf460dfb51de0336e0355fc5170`)
- Android APS 3.2 dev-i build

**Comment by sulkaharo** [comment]
The entries also contains glucometer readings (type = mbg) so if you're storing these and want to download just cgm records, you should ask for just type=sgv records.

**Comment by justmara** [comment]
Hmmm, sounds reasonable. Thats why I've asked this in AAPS channel first :) But there I was said that this issue must be created here :)
And now I see, where those records are filtered-out in nsclientv3.
Thank you. Going back to AAPS channel...

**Comment by sulkaharo** [comment]
Btw does NSClientV3 use the rest api or the websockets? We'll probably remove a lot of the websocket support in the next release so at least old NSClient versions will stop being working.

**Comment by justmara** [comment]
It seems to be able to use both, but I've only got rest mode to work at acceptable level.
