### ISSUE TITLE
Sensor Change Treatments disappear when older than 4 days on api/v1

### ISSUE THREAD

**Issue by Joerg-Schoemer** [nightscout/cgm-remote-monitor#8094]
When using REST API v1 to query sensor changes they disappear after approximately 4 days.

**To Reproduce**
Query with type filter on v1/treatments…

**Expected behavior**
Get all Sensor Change Treatments when query on api/v1 even when the treatment was entered more than 4 days ago.

**setup information**
- What version of Nightscout 14.2.6
- G7 Bridge

**Comment by sulkaharo** [comment]
The API only returns recent data, unless you query it with a date filter or a count parameter.

**Comment by Joerg-Schoemer** [comment]
I'm currently using the following request:
/api/v1/treatments.json?token=\(token)&find[eventType]=Site%20Change&count=1

**Comment by bewest** [comment]
Add a query component to filter the `find[created_at][$gte]=0`, or a more relevant timestring like the ISO8601 date from four days ago.  If the query parameter is absent, only a limited amount of data is queried by default.

**Comment by Joerg-Schoemer** [comment]
I‘ll give it a try 😀

**Comment by Joerg-Schoemer** [comment]
it works 😄

**Comment by Joerg-Schoemer** [comment]
> The API only returns recent data, unless you query it with a date filter or a count parameter.

only count parameter doesn't work
