### ISSUE TITLE
Error with V15 Profile Editor and v1 API

### ISSUE THREAD

**Issue by AndyLow91** [nightscout/cgm-remote-monitor#8114]
**Describe the bug**
A bug has been found where the user cannot save or edit any profile data in the database, either via the NS profile editor, or via the v1 API.

**To Reproduce**
Deploy NS using V15.0.0 master, or V15.0.0 dev from between October 12th and October 18th. Head over to the profile editor and try to save any change, you will see error and the profile data is not saved to the database.

**Additional context**
From looking through the history, it seems this bug was introduced on October 12th, since dev images from before then work just fine, but no longer work from that point onwards. I haven't pinpointed the exact cause just yet, but I have a hunch that it is to do with the new MongoDB method of updating data. e.g. db.collectionName.update turns into db.collectionName.updateOne().

I haven't fully verified that this is the cause, as there was more than one commit on the same day. It may have something to do with the new Node.js version?

I have confirmed this is the case for DIY users also, tested on Heroku with MongoDB Atlas also.

**Comment by bewest** [comment]
Suspect this is similar to https://github.com/nightscout/cgm-remote-monitor/pull/8111.

**Comment by bewest** [comment]
Howdy all, can you please verify if this branch/PR fixes things? https://github.com/nightscout/cgm-remote-monitor/pull/8115

**Comment by bewest** [comment]
Updated hotfix: 15.0.2.  Duplicate: https://github.com/nightscout/cgm-remote-monitor/issues/8117

**Comment by bewest** [comment]
Believe this is fixed, closing for now.
