### ISSUE TITLE
Deleting treatment records in reports fails with 500 error

### ISSUE THREAD

**Issue by oddst** [nightscout/cgm-remote-monitor#8117]
**If you need support for Nightscout, PLEASE DO NOT FILE A TICKET HERE**
For support, please post a question to the "CGM in The Cloud" group in Facebook
(https://www.facebook.com/groups/cgminthecloud) or visit the WeAreNotWaiting Discord at https://discord.gg/zg7CvCQ

**Describe the bug**
Trying to delete announcement records using Reports>Treatments fail with a 500 error message.
**To Reproduce**
1. Go to Reports
2. Click on Treatments and select Today and change to date till tomorrow, since I an in Norway and the site is in the US. 
3. Scroll down to announcements, and press the delete button in from of each announcement (X)
4. See 500 error message after confirming that the deletion info is correct

**Expected behavior**
The announcement should have been deleted. Checking it to see if it had been deleted, shows that the error message was correct in that the deletion failed.

**Screenshots**

**Your setup information**
- What version of Nightscout 15.0.0 Master
- What type of CGM, and how do you get your data there? The announcement was done manually in the NS15 Master Careportal, with the announcement function.
- Is your issue specific to a browser (Firefox/Safari/Chrome?) Tried the latest Chrome Beta and the latest Safari on an update Mac

**Additional context**

**Comment by oddst** [comment]
This seems to have been solved in NS15 DEV. Closing this issue...!

NS15 Master still needs to be updated similarly to NS15 DEV...!

**Comment by bewest** [comment]
Thank you! This is the feedback I needed.
