### ISSUE TITLE
NS15 fail after adding record fron AAPS 3.2 RC2 

### ISSUE THREAD

**Issue by maskac** [nightscout/cgm-remote-monitor#8121]
NS15 final fail when AAPS 3.2 RC2 adding record with this error, on dev version from 2/2023 no problem reported.

WS: dbAdd client ID:  w7jYJGptCRHhdvb4AAAG  data:  {
  collection: 'treatments',
  data: {
    created_at: '2023-10-20T09:23:53.000Z',
    enteredBy: 'openaps://AndroidAPS',
    eventType: 'Temp Basal',
    isValid: true,
    duration: 4,
    durationInMilliseconds: 298000,
    type: 'NORMAL',
    rate: 0.55,
    percent: 10,
    pumpId: 3395587667197,
    endId: 3395588263198,
    pumpType: 'DANA_I',
    pumpSerial: 'WKJ00066FI'
  }
}
DEDUPE: Adding new record
/opt/app/lib/server/websocket.js:406
              ctx.store.collection(collection).insert(data.data, function insertResult (err, doc) {
                                               ^

TypeError: ctx.store.collection(...).insert is not a function
    at findSimiliarResult (/opt/app/lib/server/websocket.js:406:48)
    at /opt/app/node_modules/mongodb-legacy/src/utils.js:18:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

NS15 final version in docker, MongoDB 3.6

**Comment by bewest** [comment]
Duplicate? https://github.com/nightscout/cgm-remote-monitor/issues/8114

**Comment by maskac** [comment]
This proble with uploading treaments / cgm from AAPS 3.2RC2 not profile editor. similarly may be, duplicate no.

**Comment by maskac** [comment]
It's look that 15.0.1 solved the problem. Thanks.
