### ISSUE TITLE
MongoDB driver version for Atlas

### ISSUE THREAD

**Issue by ninelore** [nightscout/cgm-remote-monitor#8143]
MongoDB Atlas announced via Email that they will upgrade M0-M5 clusters to MongoDB 7.0 in February 2024. 

Since this is our preferred/recommended Database service we need to bump the nodejs driver to at least 5.7

As time of writing the package.json lists 3.6, the package-lock.json 3.7.3.

Sources: 
https://www.mongodb.com/docs/drivers/node/current/compatibility/
![image](https://github.com/nightscout/cgm-remote-monitor/assets/21343557/0a9f7e92-62e0-4a71-9f91-3853fa347d25)

(Side note: Personal information in the screenshot is already public record in my GH profile)

**Comment by psonnera** [comment]
Just tried with Northflank 14.2.6 and 7.0.2, no problem.
Disclaimer: an anonymous person I know is running a Nightscout service on Mongo 7 and told me no problem.

**Comment by ninelore** [comment]
Aight thx for the info
