### ISSUE TITLE
The last GitHub Release is still 15.0.0, which is missing hotfixes

### ISSUE THREAD

**Issue by thedewi** [nightscout/cgm-remote-monitor#8208]
The last GitHub Release is still 15.0.0, which is missing hotfixes.

**Additional context**
I upgraded to 15.0.0 thinking it was current, and got crashes that were fixed back in October. The latest tag (15.0.2) commit message mentions "dev branch for next release" which added to my impression that it was not the release.

I am all fixed up now, but just wanted to suggest creating a GitHub release so the next person doesn't hit this.

**Comment by dhermanns** [comment]
To bad - just ran into crashes too with 15.0.0. So after 3 Month this issue is open, a release would really be helpful. Is there a reason for this?

I'm using the official docker image. Looks like there is a current release missing, too.

**Comment by thedewi** [comment]
The latest release is still broken 😟

**Comment by bewest** [comment]
I found the "publish as release button" inside the tag.  Hopefully that fixes.  Thanks for the reminders.
