### ISSUE TITLE
SAGE: Allow defining max sensor age

### ISSUE THREAD

**Issue by ecrist** [nightscout/cgm-remote-monitor#8214]
The SAGE item begins to show red as 10 days approaches.  The Libre sensors are 14 days sensors, so this reduces the usefulness of the pill for quick reference on sensor age.  It would be nice if this could be set to either a dropdown of 10 and 14 or an arbitrary number, since there are implants now that can be several months or a year long.

**Comment by psonnera** [comment]
Just change the variables https://nightscout.github.io/nightscout/setup_variables/#sage-sensor-age
SAGE_INFO="336"
SAGE_URGENT="348"
SAGE_WARN="342"

**Comment by ecrist** [comment]
Thanks, this told me what I needed.
