### ISSUE TITLE
Profile Editor uses server-side clock format settings

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#822]
The CGM visualization component allows user to set between 12 and 24 hour clocks on the client side, but the profile editor only uses the server-side setting to change between 12 and 24 hour clocks. Should probably refactor the editor to use the client setting (which in turn uses the server side as the default).

**Comment by jasoncalabrese** [comment]
think the code just needs to get the value from `client.settings` should already be loaded from local storage.  Just need to replace all the `serverSettings.settings`'s with `client.settings`'s
