### ISSUE TITLE
Authentication via https://ACCESS_TOKEN@HOST/api/v1/entries.json seems to no longer work

### ISSUE THREAD

**Issue by 15characterlimi** [nightscout/cgm-remote-monitor#8228]
**Describe the bug**

Authentication by specifying the access token in the Nightscout URL through HTTP authentication (putting it in front of the hostname separated by "@") no longer works.

**To Reproduce**

Below, replace ACCESS_TOKEN with an access token with role `device-readwrite` set up in Nightscout, and replace HOST with the hostname of a Nightscout instance (ends with ".code.run"). Then:

- (a) If I open the URL `https://HOST/api/v1/entries.json?token=ACCESS_TOKEN` in a browser (i.e. via HTTP GET), it lists a array of my latest glucose values, in JSON format.
- (b) If I instead open the URL`https://ACCESS_TOKEN@HOST/api/v1/entries.json` in a web browser then I get redirected to the same URL without ACCESS_TOKEN@, and with page body `{"status":401,"message":"Unauthorized","description":"Invalid/Missing"}`

This broke after I synced my fork of https://github.com/nightscout/cgm-remote-monitor to the latest commit 21e0591d49235845acba58cf8b3cc7339921185b today.

Unfortunately the previous version that I know to have worked was from around May 20, 2021, so I don't know when in the last 33 months or so this broke.

**Expected behavior**

Both methods should produce a list of my latest glucose values, in JSON format.

**Your setup information**
- Nightscout built today from the latest commit 21e0591d49235845acba58cf8b3cc7339921185b
- Trying to upload via Xdrip. Due to bugs in Xdrip, the access token needs to either be specified in the manner I noted above, when one can't reuse the Xdrip webserver's API secret. Concretely, the code in Xdrip incorrectly treats the uploader base URL as a String  and appends stuff to it, instead of parsing it as a Uri and then mutating just the path component; this breaks when the URL has query parameters.
- See https://github.com/NightscoutFoundation/xDrip/issues/1035#issuecomment-845475389 for an old comment of mine elaborating how the authentication used to be able to get to work in combination with Xdrip.

**Additional context**

Note that the documentation at https://nightscout.github.io/uploader/setup/#xdrip documents the format that no longer works (that page is very old so it still refers to API_SECRET rather than ACCESS_TOKEN, but the gist is the same).

**Comment by akadaoui** [comment]
Hi all. I'm encountering the same issue...
@15characterlimi have you found any clue or workaround this issue?

**Comment by 15characterlimi** [comment]
@akadaoui no I didn't, my personal workaround is that I fixed the bug in the xdrip sourec ode where it doesn't correctly put the access token into a query parameter like in my example (a). I didn't contribute that fix back to xdrip because I've found the xdrip maintainers to be very unwelcoming towards fixes for even very obvious bugs in the past (the xdrip source is a huge bug fest, but that's a different matter).

Anyway, that's my personal workaround but it will only work for those who are comfortable editing and compiling the xdrip source code themselves.

**Comment by fitzsim** [comment]
This worked fine for me when I entered `https://ACCESS_TOKEN@HOST/api/v1/` in `Settings -> Cloud Upload -> Nightscout Sync (REST-API) -> Base URL` in [Nightscout xDrip+ version e18eef0-2024.08.26](https://github.com/NightscoutFoundation/xDrip/releases/tag/2024.08.26).

If I paste the same URL into a web browser (Firefox) it first warns me about the URL format, then returns:
```
Cannot GET /api/v1/
```
so I do not think pasting the URL into a web browser is a valid test.

I looked at the `Nightscout xDrip+` code (commit `e18eef09cfc9224defb32e1bfba6aa601d09fe49`) and it extracts the secret (in this case, the token) from the URL string with `uri.getUserInfo()`, hashes it with `SHA1`, then uses the hash separately from the rest of the URL.

For my test, the token belonged to a subject with the `admin` role.

**Comment by akadaoui** [comment]
One extra info that helped my specific case (not being able to upload to Nightscout via Xdrip): the database was full, and no error message was displayed (which led me to (wrongly) believe I was affected by this Issue.

In case somebody stumbles upon this thread and happens to have the same problem as me: 

I fixed it by deleting old entries (this is irreversible: Authenticate, then Menu -> Admin Tools -> Delete old treatments / documents / entries under "Clean Mongo * Database". As I'm using herokuapp as a host, I was able to make a backup of my mongodb via herokuapp-cli, but I don't know of a generic solution for all hosts. If you don't care too much about your past data and just want it to work again, it's worth a try.)

**Comment by fitzsim** [comment]
@15characterlimi Do you think we can close this issue report as not-a-bug?

**Comment by 15characterlimi** [comment]
I don't know, I haven't looked into this in a long time, since I worked around the issue by locally changing the xdrip source code instead. I observe that this bug has remained unadressed in a long time so realistically the chance of this changing are probably low, so in that sense there's probably no real incremental harm in closing it. I will try to reproduce this again some time, but it will likely take weeks for me to get around to it and I can't promise that it'll happen.

**Comment by adamlounds** [comment]
I cannot see any historical support for basic auth - even going back to when the [Authorization header parsing was first introduced](https://github.com/nightscout/cgm-remote-monitor/commit/3d88bd33a6aa34975f6ee34ca657ad6f2d73e4f7#diff-5f5605b92de173ba05a96a0df0b842e5db02b8cd41c888c45677510dd371e315R65) there's no mention of anything other than Bearer authn.

There was a big refactor in [December 2020](https://github.com/nightscout/cgm-remote-monitor/commit/7fe8e32152a150235bfb68858a9a0be1133401fe) but still no obvious signs of basic auth (eg I'd expect a match on `git grep -i "'Basic'" $(git rev-list --all)` or `git grep -i "parts.*basic" $(git rev-list --all)`)

I guess it could have been using a middleware, but no matches for `basicAuth` or `basic-auth` either.

Could it be that the reporter had local patches to support basic auth that were not shared upstream?

**Comment by adamlounds** [comment]
OK, I think I understand now. The xDrip+ Base URL is [configured using this url style](https://nightscout.github.io/uploader/setup/#xdrip), but nightscout itself has never supported it. xDrip+ [extracts](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/utilitymodels/NightscoutUploader.java#L379) the secret from the configured Base URL (via `uri.getUserInfo`) & actually uses the standard v1 `api-secret` header authn when it [makes calls to nightscout](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/utilitymodels/NightscoutUploader.java#L127).

```java
String baseURL;
String secret = uri.getUserInfo();
if ((secret == null || secret.isEmpty()) && apiVersion == 0) {
    baseURL = baseURI;
} else if ((secret == null || secret.isEmpty())) {
    throw new Exception("Starting with API v1, a pass phase is required");
} else if (apiVersion > 0) {
    baseURL = baseURI.replaceFirst("//[^@]+@", "//");
} else {
    throw new Exception("Unexpected baseURI: " + baseURI);
}
```

So if there's a bug here it's in xDrip+, not nightscout

**Comment by 15characterlimi** [comment]
I just updated my configuration and I can confirm that the steps that @fitzsim noted in comment https://github.com/nightscout/cgm-remote-monitor/issues/8228#issuecomment-2316359361 work for me. Thanks!

I'm closing this issue, since it appears to be resolved / a workaround found.
