### ISSUE TITLE
JS error: bower_components

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#849]
Seeing an error with /bower_components/d3/d3.min.js in Chrome. (Not seeing the same error logged in Firefox.) Not seeing any noticeable affect of this error.

Chrome JS panel showing this sometimes as a GET error and other times as a 404 for the specified file:

Failed to load resource: the server responded with a status of 404 (Not Found) {SITE}/bower_components/d3/d3.min.js

(Running up-to-date dev branch; redeployed again to confirm error.)

**Comment by jasoncalabrese** [comment]
Think we can remove this from index.html, since d3 is in the bundle, I'll take a look.

**Comment by jasoncalabrese** [comment]
Resolved by #863
