### ISSUE TITLE
Treatments popup messages

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#878]
Seeing a new issue (worked properly until newest dev/beta3). CP entries are not showing the proper message text. Looks like the most recent two entries both show the text of the newest entry, and the ones before that are then "off" by one.

Hard to get screenshot to show the issue with the popups. After seeing issue, I removed my existing treatments collection and set up a new one. Only brand new testing entries are in place. Each new CP entry becomes the message text for the current new entry and the one before it.

**Comment by jasoncalabrese** [comment]
Thats very strange, did a quick test and could see anything going on there.  What does the data look like in mongo?  Does restarting the site change anything.

**Comment by oamyoamy** [comment]
Can't reproduce today. Using a simulated site with manual entries to test. Testing this morning with a set of treatments is working.

**Comment by jasoncalabrese** [comment]
That's good, but I still wonder what might have caused that.  Maybe something related to not have current CGM data?

**Comment by mrfoley** [comment]
Most everything seems to be working very well for me.  I do have a question / offer if it's not too ambitious for this build.   I would like to see ketone checks (blood & urine) in the treatment drawer.  I'm willing to attempt coding.  How can I verify that I've updated everywhere needed.  It looks like only in lib: careportal.js and treatments.js should be updated.  In static: treatments.html and index.html.  Here's a picture of what I was thinking.  


![ns ketone](https://cloud.githubusercontent.com/assets/12192704/9616240/00e39fa6-50cb-11e5-966c-5ecfa64a6719.JPG)

**Comment by jasoncalabrese** [comment]
@mrfoley, maybe for later, but I don't think we should add new features like that to the 0.8.0 release.  Probably best to open a new issue for this.

side note: I think we've tested keytones maybe 5 times in the last 5 years, so wouldn't want to take up all that space by default, so it would need to be optional
