### ISSUE TITLE
Azure deploy issues

### ISSUE THREAD

**Issue by jasoncalabrese** [nightscout/cgm-remote-monitor#882]
An error has occurred during web site deployment. D:\Program Files (x86)\Git\bin\cat.exe: **\* Couldn't reserve space for cygwin's heap (0x68570000 <0xBA0000>) in child, Win32 error 0 getting node version failed

@bewest any ideas?
##

**Comment by bewest** [comment]
Couldn't reserve memory to run `cat`?  Would just run it again?

**Comment by jasoncalabrese** [comment]
Sounds like after several redeploys is worked, just wondering if there's anything we can do differently to help with this.  Seen it come up several times.
