### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#888]
Checking intended functionality (compared to screenshots I've seen). When sending an "announcement":

1) pushover notification is working (message text comes through)
2) IFTTT notification is working (message text comes through)
3) site status bar (top) changes to "Urgent Announcement" (red) or "Announcement" (yellow) (depending on level of BG entered) -- but text of announcement is NOT shown in browser. (I saw testing images from Jason with a "juicebox" announcement... which seemed to suggest announcement text would go to the status bar area.)

SOLVED:
If you do NOT enter a BG, the announcement status goes to the status bar properly. (Orange text.)

FUNCTIONALITY:
IF entering a BG and selecting TYPE of CP entry as announcement, shouldn't you see the level (Urgent Announcement or Announcement) with the "message" of the announcement appended to the end of it: Announcement: Juice Box Needed!

**Comment by jasoncalabrese** [comment]
Think this is a bug, I'd like the message to be displayed always.  With the Urgent/Warning prefix if a BG is entered.

**Comment by oamyoamy** [comment]
Yes. That is what I would expect, too, from the feature.
