### ISSUE TITLE
Localize month name in timeline

### ISSUE THREAD

**Issue by sulkaharo** [nightscout/cgm-remote-monitor#897]
The timeline uses English for month names regardless of the language.

**Comment by MilosKozak** [comment]
where?

**Comment by sulkaharo** [comment]
The timeline at the bottom of the site.

<img width="466" alt="screen shot 2015-09-02 at 16 05 12" src="https://cloud.githubusercontent.com/assets/1001330/9631878/7fe013b8-518c-11e5-8ba1-1c9f480f6002.png">

**Comment by sulkaharo** [comment]
Do we use moment.js for that? AFAIK Moment comes with pre-localized month names AND uses same format for the locale, so we could just pass the language ID to moment and get local names out.

**Comment by MilosKozak** [comment]
we had an issue with moment locales. they must be loaded from a localization file. currently we don't know how to make it with browserify
so far we use pure js .toLocaleString() to get localized strings

**Comment by MilosKozak** [comment]
new Date().toLocaleString('cs', { month: "long" });
this works
but we should localize  whole timeline not only months

**Comment by jasoncalabrese** [comment]
think that is all done with d3, but there's a way to override it like like we do with the time format

**Comment by jasoncalabrese** [comment]
here: https://github.com/nightscout/cgm-remote-monitor/blob/dev/lib/client/chart.js#L43

**Comment by MilosKozak** [comment]
solved by https://github.com/nightscout/cgm-remote-monitor/pull/1097
