### ISSUE TITLE
Announcements not clearing (alarm-level ones)

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#913]
*I reported this same problem earlier this week. Jason, you couldn't reproduce it.

In testing announcements again tonight, same issue.

I was testing, specifically, to see how clearing the announcements works.

First test: A regular announcement, no BG. Announcement pops up in orange on all three open browsers. No way to acknowledge it.

Second test: An announcement with a BG in an alarm range (60). Announcement pops up in yellow on all three open browsers. I had someone else clear the alarm in a browser on another computer (simulating a nurse doing so). "Warning" announcement disappeared -- snooze.

In one minute, the yellow warning announcement returned (with alarm playing). He tried repeatedly to snooze the alarm. It replays every minute. I then tried to snooze it. It continues to replay every one minute.

Upshot... no way to clear the announcement... no way to snooze or stop it.

The treatment entry:

{
    "_id": {
        "$oid": "55e8f42c2b01c20b006858aa"
    },
    "enteredBy": "AMC",
    "eventType": "Announcement",
    "glucose": 60,
    "glucoseType": "Finger",
    "notes": "Double-dropping 2! Please test!",
    "units": "mg/dl",
    "created_at": "2015-09-04T01:30:20.827Z",
    "isAnnouncement": true
}

**Comment by oamyoamy** [comment]
Appears that after x amount of time, the announcement DOES go away on its own. (Trying to confirm it's 15 minutes. But that means that with an announcement paired with an alarm-triggering BG, the alarm seems to replay every 1 minute... doesn't respond to snooze.)

**Comment by oamyoamy** [comment]
Auto-stopped after 11 minutes.

**Comment by oamyoamy** [comment]
Had another support team user run this same test. mmol user, and a bg at an mmol threshold wasn't triggering an alarm status-level announcement... she is filing a separate bug. Testing again now with a mg/dl user....

**Comment by oamyoamy** [comment]
Confirmed with another support team member testing. She sees same every 1-minute alert, despite snoozing via browser.

**Comment by audiefile** [comment]
I saw exactly what @oamyoamy described. If I enter an announcement with "urgent low" bg I can clear the alarm announcement but it doesn't actually snooze, it re-alarms every minute for 10-15 minutes.

**Comment by jasoncalabrese** [comment]
Think I have a fix for this if anyone wants to test it #944(wip/announcement-ack)

Only downside to this fix is a new announcement at the same level or less won't get sent if another announcement was ack'd recently.  But Announcements will still be independent of normal alarms.

The real solution for this is to store the notification/alarms/announcements in mongo, and then ack by id, but thats a much bigger change than we have time for now.
