### ISSUE TITLE
Announcements / Orange

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#921]
Related to #913  but separate issue.

No way to clear a regular announcement from site. ORANGE-level announcement persists indefinitely?

If you send an announcement so that a nurse sees it, for example, it would be nice if there was a way to clear it? (That way you would know the announcement was seen?)

Appears to auto-clear eventually... somewhere around 20 minutes?
##

**Comment by jasoncalabrese** [comment]
Yeah, right now it's auto clearing, if you set the BG to a warning/urgent level it becomes an alarm that can be clear.  Wasn't a good way to clear info level messages.  What I'd really like is a way to respond.

**Comment by oamyoamy** [comment]
(Bug 913 is about the fact that the "alarm" ones urgent/warning do not currently clear properly.)

**Comment by jasoncalabrese** [comment]
Don't know if I'll be able to do anything about this for the patch release
