### ISSUE TITLE
Tooltips near edge of timeline go off screen 

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#922]
Tooltips that are near the right edge are run off screen. 
![tooltip-rightedge](https://cloud.githubusercontent.com/assets/9641700/9690780/4b4c539c-52f3-11e5-8139-8b80d039ddd6.png)

![popup-offedge](https://cloud.githubusercontent.com/assets/9641700/9690787/51b1832e-52f3-11e5-848f-7560cdf4232c.png)

**Comment by jasoncalabrese** [comment]
this has bugged me too, need to set min width and make sure we don't go off the screen
