### ISSUE TITLE
When no CGM data insulin and carbs treatments are not displayed

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#923]
![image](https://cloud.githubusercontent.com/assets/11146458/9691539/470d3846-5343-11e5-8a96-253a9df7e154.png)
##

**Comment by jasoncalabrese** [comment]
Related to this, we should use recent treatments and MBGs for BWP if cgm data isn't available

**Comment by MilosKozak** [comment]
we started new sonsor now and raw data are not displaying too

**Comment by jasoncalabrese** [comment]
any browser/server console errors? /api/v1/entries.json looks right?

**Comment by MilosKozak** [comment]
no errors, my primary site with enchilada is displaying it

**Comment by MilosKozak** [comment]
![image](https://cloud.githubusercontent.com/assets/11146458/9692896/a1bd09f2-534c-11e5-83d4-663ad60b51bf.png)
![image](https://cloud.githubusercontent.com/assets/11146458/9692905/b004449e-534c-11e5-987b-ffc573c1bc14.png)
enchilada vs fc

**Comment by Kdisimone** [comment]
This issue appears to be resolved now.  I regularly am able to see treatments when BGs are not displayed.
