### ISSUE TITLE
Unify mg/dl & mg/dL

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/cgm-remote-monitor#925]
##

**Comment by jasoncalabrese** [comment]
Moved to 0.8.X+1, might be easy to break things doing this so I don't want to rush it

**Comment by oskarpearson** [comment]
I've confirmed that a mix still exists in 0.9.3-dev-20161212b. Most tests and translations refer to "mg/dl", while some of the comments and UI code refers to "mg/dL". It seems like it may be reasonably easy to standardise.
