### ISSUE TITLE
Clock.Html website view only showing in mg/dl

### ISSUE THREAD

**Issue by GrantKY** [nightscout/cgm-remote-monitor#938]
Mmol users that use clock display option are seeing bg levels in mg/dl units.  Mmol has been set as display units in azure.

**Comment by jasoncalabrese** [comment]
@GrantKY I was able to reproduce and fix this, you could try #942 (wip/clock-mmol) that would be great

**Comment by SargentChris** [comment]
I've updated to latest repo but I still get this issue.

**Comment by acron0** [comment]
I still get this issue on version 0.11.1

**Comment by sulkaharo** [comment]
@acron0 The latest release is 0.12 series, which should work. Please upgrade :)

**Comment by acron0** [comment]
Upgraded to 0.12.5 and issue persists. In `status.js`:
```
this.serverSettings = {"status":"ok","name":"nightscout","version":"0.12.5","serverTime":"2019-10-21T14:15:14.052Z","serverTimeEpoch":1571667314052,"apiEnabled":true,"careportalEnabled":true,"boluscalcEnabled":true,"settings":{"units":"mg/dL","timeFormat ...
```

**Comment by sulkaharo** [comment]
Have you set DISPLAY_UNITS in the server to "mmol"? That's basically the only required variable that must be set in addition to Mongo URL

**Comment by acron0** [comment]
@sulkaharo Thanks, I was setting it in the NS settings menu and would expect that same value to persist into the clock. I've set the `DISPLAY_UNITS` correctly now though, thanks for the heads up (it was unset).
