### ISSUE TITLE
Deployment Fails on Azure

### ISSUE THREAD

**Issue by JulieCGM** [nightscout/cgm-remote-monitor#95]
Hi,

Thanks so much for what you guys are doing with this project. 

I'm having an issue trying to get this to deploy on Azure. Could you please review the error below. Thanks.

Command: bash deploy.sh
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Using start-up script server.js from package.json.
Generated web.config.
Node.js versions available on the platform are: 0.6.17, 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29.
Selected node.js version 0.10.29. Use package.json file to choose a different version.
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/errorhandler
npm http GET https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/express-extension-to-accept
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/sgvdata
npm http GET https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/errorhandler
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/express-extension-to-accept
An error has occurred during web site deployment.
npm http 304 https://registry.npmjs.org/bower
npm failed
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/sgvdata
npm http 304 https://registry.npmjs.org/mongodb
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/express/-/express-4.8.3.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.8.3.tgz
npm ERR! Error: shasum check failed for C:\DWASFiles\Sites\juliecgm\Temp\npm-6984-W8igQesr\1407737516346-0.7824546734336764\tmp.tgz
npm ERR! Expected: a2c95b9079cda0473a04448f6b6c1e7fc20bf200
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/express/-/express-4.8.3.tgz
npm ERR!     at D:\Program Files (x86)\npm\1.4.10\node_modules\npm\node_modules\sha\index.js:38:8
npm ERR!     at ReadStream.<anonymous> (D:\Program Files (x86)\npm\1.4.10\node_modules\npm\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\\Program Files (x86)\\nodejs\\0.10.29\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.10\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd d:\home\site\wwwroot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.10
npm

**Comment by jasoncalabrese** [comment]
Closing this old issue
