### ISSUE TITLE
Stale Data Warning / Snooze

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#958]
Testing with:

ALARM_TIMEAGO_WARN  on
ALARM_TIMEAGO_WARN_MINS 6    (artificially low for testing)

When the warning triggers, 30 minutes is the snooze time in the box, but it isn't snoozing. It continues to warn until the data comes in.

**Comment by jasoncalabrese** [comment]
Did the client settings refresh, maybe do "reset and use defaults".  I didn't change anything with the client side time ago, but I do want to turn that into a plug that can be used on the server for pushover.

**Comment by jasoncalabrese** [comment]
Just reproduced it, guess I broke something, good catch
