### ISSUE TITLE
Reports/Treatments dates on mobile

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#981]
Treatments screen works fine on a desktop browser. But on mobile, the dates of the treatments are all showing as undefined January 1 1970. See below. Screenshots shows the start of 3 days of treatment notes, all with a bogus date.

I tried both the default date range and specifying one of the shortcuts (today, last 2 days, etc.). Same behavior on iOS/Safari.

![reports-dates](https://cloud.githubusercontent.com/assets/9641700/9742648/76d45ffc-5616-11e5-81ec-c1234e1ffd2f.png)

**Comment by oamyoamy** [comment]
For comparison - same date range on a desktop. (Treatments collection is fine.)

![reports-dates-desktop](https://cloud.githubusercontent.com/assets/9641700/9742957/7cd64a30-5618-11e5-984f-32808bfcaafa.png)

**Comment by oamyoamy** [comment]
(I saw discussion at gitter that no one has seen this same effect. Tested again tonight, iOS/Safari... same issue. I caught a screenshot to show you that when it is loading up/processing the data, it is reflecting the proper date as it cycles through them... But still showing 1970 in the table.)

![reports-cycledates](https://cloud.githubusercontent.com/assets/9641700/9835069/e022b3aa-598b-11e5-8a85-9afb86d4f38e.jpg)

**Comment by jasoncalabrese** [comment]
Think this was fixed by #998
