### ISSUE TITLE
BWP Phrasing 2

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#991]
Confusing phrasing.

When the amount over high target is slight (as in both of the examples shown below), sometimes a 30min temp is shown, but a 1hr temp suggestion is not available. 

Looking at the first screenshot below, if the projected bg (expected outcome) is only 8 over the target (and a .10 amount needed), it doesn't make sense (to me) that the change needed is "too large" for a 1 hour temp and a bolus is recommended instead. 

Is this a phrasing issue in this case (only slightly out of range)? Or is there a logic issue/bug happening?

It seems like the 1hr recommendation would be negligible, but that it certainly wouldn't be "too large." 

Even if this is working the way it is intended, the phrasing is confusing and feels misleading - and I think will confuse others.

---

![n-bwp-temp](https://cloud.githubusercontent.com/assets/9641700/9816492/3a901e12-5852-11e5-8e4c-e57aa8caaaa2.png)

![fc-bwp-toolargeadjustment](https://cloud.githubusercontent.com/assets/9641700/9816501/3f0d0220-5852-11e5-8e90-de2a7d1d20d2.png)
##

**Comment by jasoncalabrese** [comment]
Not sure why that's displayed that way, seem like the 1 hour temp adjustment should be `Math.round((1.00 + 0.08) / 1.00 * 100)` = 108

@sulkaharo any ideas?  Maybe something with rounding that I'm not seeing?

**Comment by sulkaharo** [comment]
The 1 hour basal suggestion being missing is a bug. I've tried to replicate this to understand where it fails but can't find what's causing this. Probably something really silly. Rounding? MG/DL specific?

**Comment by cjo20** [comment]
This is a problem because in this calculation
```
      var thirtyMinAdjustment = Math.round((basal/2 + results.bolusEstimate) / (basal / 2) * 100);
      var oneHourAdjustment = Math.round((basal + results.bolusEstimate) / basal * 100);
```

`basal + results.bolusEstimate` gives (0.7 + 0.213) = 0.70.213, (because `basal` is a string, I assume). Changing
`      var basal = sbx.data.profile.getBasal(sbx.time);`
to
`      var basal = parseFloat(sbx.data.profile.getBasal(sbx.time));`
seems to do the right thing

**Comment by jasoncalabrese** [comment]
nice catch, probably should fix getBasal to return a number, surprised that isn't the case

**Comment by cjo20** [comment]
So I guess the easiest way is to change

```

**Comment by sulkaharo** [comment]
Yay thanks! Fixing :)

**Comment by sulkaharo** [comment]
@cjo20 Can you pull  #1122 and see if this fixes this for you? I made the fix generic for all numeric values returned by the profile object.

**Comment by cjo20** [comment]
@sulkaharo That pull request looks like it solves this issue for me. :+1: (apart from the typos, `basal adjustment our of range` should be `basal adjustment out of range`)

**Comment by sulkaharo** [comment]
Thank you Apple and your infinite wisdom to add spell checking to OS X without supporting users actively engaging with multiple languages. Fixing the typo...

**Comment by PieterGit** [comment]
Issue seems resolved. Closing this issue.
